### ISSUE TITLE
Replace %s with string format {} across all str functions of models

### ISSUE THREAD

**Issue by TroJan** [Cloud-CV/EvalAI#1000]
This is a pretty simple task. Some part of the code base contains `%s` function(used for string formatting). It involves replacing all the occurrences of such `%s` with string format function `{}` everywhere in models of each app.

For example one such case can be found in `challenges/models.py`, __LeaderBoard__ model.
The function right now looks like 
```
def __unicode__(self):
        return "%s" % (self.id)
```

After replacing `%s` with string format function, the above function will looks something like

```
def __unicode__(self):
    return '{}'.format(self.id)
```

Note: Only replace in models of each app, not across the whole project as of now.

**Comment by isht3** [comment]
I would be happy to help! Is anyone working on this?

**Comment by deshraj** [comment]
No, I don't think so. Please go ahead. :)

**Comment by isht3** [comment]
Okay, on it. Why are we doing it? Is the latter method more efficient than the other?

**Comment by deshraj** [comment]
For more reference, please see this http://stackoverflow.com/questions/5082452/python-string-formatting-vs-format

**Comment by isht3** [comment]
Understood. Thanks. :+1:
