### ISSUE TITLE
Remove unused images from frontend directory

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1004]
There are a lot of images that are not being used at all and are there in the repository. Can we please get rid of those images?

**Comment by aka-jain** [comment]
Sure @deshraj, will do it.

**Comment by the-dagger** [comment]
@deshraj @aka-jain mind if I take this up?

**Comment by deshraj** [comment]
Sure @the-dagger.

**Comment by xamfy** [comment]
Can I take this up?

**Comment by deshraj** [comment]
@xamfy sure. :)

**Comment by xamfy** [comment]
@deshraj  following are the images that should be removed:
```
challenge-preview.png
cloud-4.gif
cloud3.png
dash-challenge.png
owl.png
plane.png
rock.png
rocket.png
sat.png
sate.png
star.gif
```
Am I right?
