### ISSUE TITLE
Write integration tests for submission worker

### ISSUE THREAD

**Issue by taranjeet** [Cloud-CV/EvalAI#1005]
Submission worker: Runs as a individual python process, has dependency on RabbitMQ and the main app server.

### How ??

I was thinking of starting submission worker via subprocess and then killing it later on via `process.kill`. This way the worker will start listening on queue and then we can publish a message which will be acted upon by the worker.

Also the only way to check if the submission has passed through the worker flow is to check its status in db. It should be either SUCCESS or FAILURE and nothing else.

@deshraj @dexter1691 : your thought here please

**Comment by TroJan** [comment]
@deshraj : let me know if you have any development here ?

**Comment by deshraj** [comment]
@TroJan sorry I have been busy with working on other stuff and hence didn't get time to work on this one. I am afraid that I won't be able to work on this for next 3 days. I will let you know once I have something.

**Comment by TroJan** [comment]
@deshraj @dexter1691 : let me know your thoughts please :)

**Comment by deshraj** [comment]
I am not sure how this should be done exactly. I need some more time. Also, @RishabhJain2018 @TroJan please suggest if you have other thoughts about how to do this?

**Comment by isht3** [comment]
@deshraj Is this issue still active?

**Comment by RishabhJain2018** [comment]
@isht3 Yes, but can you please discuss the strategy here before implementing it.

**Comment by isht3** [comment]
@RishabhJain2018 I've specified two methods of implementation in #1457, could you give me feedback?

**Comment by taranjeet** [comment]
@deshraj @RishabhJain2018 : Can we close if not required?

**Comment by deshraj** [comment]
Thanks @taranjeet for pointing it out. Closing it.
