### ISSUE TITLE
Change path of storage of Evaluation Scripts

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1009]
## Current behaviour

Currently, the evaluation scripts are stored in the `submission_files` directory which should not happen ideally.

## Solution
Modify the `RandomFile()` method such that the evaluation scripts should be uploaded in the `evaluation_scripts` directory instead of the `submission_files` directory.

**Comment by TroJan** [comment]
@deshraj : Why is this required ?

**Comment by deshraj** [comment]
The `RandomFile()` definition sets the path of the uploaded file to be `submission_files/blah` and hence the evaluation scripts being uploaded are also stored in the submission_files. I hope I am clear now.
