### ISSUE TITLE
Notification toasts misplaced on the auth pages

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1010]
On the new Signup and login page, the notification toast is misaligned and is not shown at the correct position.

**Comment by vedantrathore** [comment]
@deshraj I would like to work on this, could you please explain a bit more on what the issue is?

**Comment by deshraj** [comment]
@vedantrathore it seems like this has already been fixed by @aka-jain. Please feel free to take up any other issue. :)
