### ISSUE TITLE
Auth form input field sizes are contracted.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#1011]
Auth pages like login, signup etc have contracted input field. Need to expand them.

**Comment by anirudhvenu** [comment]
Hey @aka-jain has this been resolved? I'd love to take it if it hasn't yet.

**Comment by deshraj** [comment]
I think this is already resolved. Isn't it @aka-jain ?

**Comment by RishabhJain2018** [comment]
@aka-jain @deshraj Is this still an issue ?

**Comment by deshraj** [comment]
I am not sure. @aka-jain can you please reply to this thread?

**Comment by aka-jain** [comment]
This issue is resolved. Closing this.
