### ISSUE TITLE
RandomFileName class returns incorrect path when id is not provided.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1041]
**Bug:** The `RandomFileName` class in [base.utils](https://github.com/Cloud-CV/EvalAI/blob/master/apps/base/utils.py#L22) returns incorrect path when `id` is not provided in the path.

**Fix:** The condition on the [line 28](https://github.com/Cloud-CV/EvalAI/blob/master/apps/base/utils.py#L28) needs to be changed to `or` from `and` as `instance.pk` will always be available for upon saving a model.

**Comment by taranjeet** [comment]
Can you please explain this in more detail along with an example of where it is failing? 

As per my understanding `and` perfectly makes sense as the string should be substituted with the value of `instance.id` if it exists. Still I want to know where am I missing?

**Comment by RishabhJain2018** [comment]
@taranjeet Yes you are correct `and` makes sense here.I understood it incorrectly.Moreover, it is failing when we are calling the class like `RandonFileName("evaluation_script")` without giving the `id` & hence due to hard-coded [path](https://github.com/Cloud-CV/EvalAI/blob/master/apps/base/utils.py#L31) all the files are getting saved in `submission_files/something`.
I think we should simply check for `id` parameter in the path, if it is present then we should append it else  save the files on the given path. What do you say?
