### ISSUE TITLE
Change color schemes for popup notifications

### ISSUE THREAD

**Issue by spyshiv** [Cloud-CV/EvalAI#1044]
Default colors for popup notification doesn't looks good and also not matching with our theme colors. We need different colors for popup notification.
@aka-jain : Assigning this to you. You have to share color codes only. Please choose colors according to notification category that's are given below
1. Success
2. Warning
3. Error
4. Info
also provide need four icons for the same.

**Comment by aka-jain** [comment]
Yeap, we have to redesign the whole notification system. I'm on it 👍

**Comment by spyshiv** [comment]
cool. Let me know if you need helping hands. :grin:

**Comment by the-dagger** [comment]
@aka-jain I think using materialized toast would be a better idea as compared to the current toast we are using.

https://material.angularjs.org/latest/demo/toast

The current toast is quite buggy and lacks a lot of customization.

**Comment by deshraj** [comment]
I think we wanted to shift to the materializecss toasts. @aka-jain can you please confirm this?

**Comment by Bala1718** [comment]
@deshraj can I work on this?

**Comment by anuj-rathore** [comment]
If nobody is working on this, Can I take this issue @RishabhJain2018 @spyshiv

**Comment by deshraj** [comment]
@anuj-rathore sure, go ahead. :)

**Comment by deshraj** [comment]
This issue is still open. If someone is interested, feel free to take this up.

**Comment by gautamjajoo** [comment]
@deshraj Fixed in #1472 .

**Comment by gautamjajoo** [comment]
@aka-jain @spyshiv It was fixed in #1472 I think so, Can we close this issue?

**Comment by spyshiv** [comment]
Thanks @gautamjajoo for the update.
Closing this issue
