### ISSUE TITLE
Change the email verified template.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1046]
**Issue:**: The current `email verified` template is according to the old theme.
**Fix**: We need to modify it according to the new theme that we are using it now.
Old Template 
![shot](https://user-images.githubusercontent.com/12206047/30498958-53c6c5d0-9a76-11e7-9bc6-d17d289fbc3e.png)

**Comment by xamfy** [comment]
I want to take this issue please guide

**Comment by xamfy** [comment]
Can I take this?

**Comment by RishabhJain2018** [comment]
@xamfy Sure go ahead!

**Comment by 16116073** [comment]
@RishabhJain2018 is anybody working on this.If not I would like to take this issue

**Comment by RishabhJain2018** [comment]
Since @xamfy seems to be inactive from a long time, @16116073 you can take this task up. Also, feel free to ask your doubts.

**Comment by 16116073** [comment]
the email-verified page is already according to the new-theme. 
![1](https://user-images.githubusercontent.com/25207205/34242983-8f4bcf28-e644-11e7-8f8b-ebcc78c0383d.png)

**Comment by Obtin** [comment]
@RishabhJain2018, since the issue has already been resolved, please close it. Thank you

**Comment by deshraj** [comment]
Thanks for noticing @obtin. Closing this.
