### ISSUE TITLE
Change the pagination limit in leaderboard

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1070]
Currently, in the VQA challenge, only 10 entries are visible on the leaderboard and there is no pagination on the client side. To show all the entries of the leaderboard, there are two ways to do that:
1. Add a pagination on the client side
2. Show all the entries on a single page (involves adding a new Pagination Class)

The second approach is a better way since then others will be able to compare their results with everyone else in the team.

**Comment by RishabhJain2018** [comment]
@deshraj Can we add the support for filtering the results on the basis of `participant team` as it will help the participants to be more specific and the overhead of searching team members manually will get reduced. Moreover, for showing all the results we can use pagination. What are your views about it ?

**Comment by deshraj** [comment]
@RishabhJain2018 we can surely do that but this issue addresses a different problem. Please feel free to open a new issue.
