### ISSUE TITLE
Add the functionality to disable the Challenge

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1080]
### Objective

A challenge host should be able to delete the challenge using the UI. At the backend, set the flag `is_disabled` whenever a challenge host submits a request to delete the challenge.

**Comment by rishabhja** [comment]
Can i contribute to this?

**Comment by RishabhJain2018** [comment]
@rishabhja yes sure. Go ahead.

**Comment by rishabhja** [comment]
Can you assign the issue to me?

**Comment by taranjeet** [comment]
@deshraj: I would prefer that you call this issue as "Add functionality to disable a Challenge" since at the backend you are disabling the challenge. It does not make sense to introduce an inconsistency in actions at backend and frontend.

**Comment by rishabhja** [comment]
Where is the disable button to be shown?

**Comment by deshraj** [comment]
The disable button should be shown right below the challenge description in a card where if the challenge host clicks on that button then a dialog box opens that asks the challenge host to enter the challenge name and then press submit in that dialog box. Does that sound good @rishabhja ?

**Comment by rishabhja** [comment]
Why do i need to ask for the challenge name if he is pressing the disable button on a specific challenge?

**Comment by deshraj** [comment]
We are doing this to make sure that the challenge host is not pressing the button by mistake.

**Comment by rishabhja** [comment]
M

**Comment by deshraj** [comment]
We have thought about both the approaches earlier and we wanted to go with this approach similar to what Github follows. :)

**Comment by rishabhja** [comment]
okay, sure

**Comment by deshraj** [comment]
Cool. @rishabhja please let us know if you have other doubts about this.

**Comment by rishabhja** [comment]
Disabling the challenge doesnt hide it. Is it expected?

**Comment by rishabhja** [comment]
Can you give me access to push?

**Comment by RishabhJain2018** [comment]
@rishabhja yes, disabling a challenge must hide it from the list of all challenges.
Moreover, please create a pull request with the changes that you have done.

**Comment by rishabhja** [comment]
I am not able to push my branch. So, how will i create a PR?

**Comment by RishabhJain2018** [comment]
For creating a PR, please fork the repository then you can push your local branch to your origin and then create a PR from there. Please ask if something is not clear. Please refer here for more details https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by RishabhJain2018** [comment]
@rishabhja Any update on this ?

**Comment by anuj-rathore** [comment]
@RishabhJain2018 If nobody is working on this, can I work on this?

**Comment by aka-jain** [comment]
Sure @anuj-rathore please go ahead. Assigning this to you.

**Comment by isht3** [comment]
@anuj-rathore Are you working on this?

**Comment by aka-jain** [comment]
I think @anuj-rathore is inactive. You can work on this @isht3

**Comment by anuj-rathore** [comment]
I am up for this...

**Comment by aka-jain** [comment]
@isht3 you have started working on this?

**Comment by isht3** [comment]
@aka-jain Nope!

**Comment by deshraj** [comment]
Wow, lot of comments. I think the final conclusion is that @anuj-rathore you can start working on this. :) Feel free to ask questions if you have any.

**Comment by anuj-rathore** [comment]
I am really sorry, as I am quite busy these days! It would be really good if you could assign this to someone else @deshraj @aka-jain

**Comment by codervivek** [comment]
Can I claim this assignment?

**Comment by deshraj** [comment]
Sure @codervivek. :)
