### ISSUE TITLE
Add APIs for challenge creation using UI.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1087]
The API's include:
1. API for creating challenge.
2. API for creating leader board.
3. API for creating challenge phase.
4. API for creating dataset split.
5. API for creating challenge phase split.

Please add tests for the same.

**Comment by isht3** [comment]
@RishabhJain2018 How is this coming through? Can I help?

**Comment by RishabhJain2018** [comment]
@isht3 I am working on this feature. Please feel free to take up any other unassigned issue. :)

**Comment by isht3** [comment]
@RishabhJain2018 Okay, cool! :D
