### ISSUE TITLE
Improve the check for if the user is a host of a challenge

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1107]
Currently, at https://github.com/Cloud-CV/EvalAI/blob/master/apps/hosts/utils.py#L12 we only check if the user has created the challegne and based on that we allow the challenge host to see all the submissions (for example, see this https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/views.py#L703). We would want to change it so that anyone who is a part of the challenge host team is allowed to access information such as 'View all submissions' etc.

**Comment by RishabhJain2018** [comment]
@deshraj What if we have an API that takes user and challenge_pk as input and gives the result  as true or false stating whether the user is challenge  host or not. What do you say?

**Comment by taranjeet** [comment]
@RishabhJain2018 : Even if we create api, this does not solve our purpose here. At the end, for this issue, you will be calling a function only and not making an internal request to check if user is challenge host or not.
