### ISSUE TITLE
Not able to click on any button in Chrome 

### ISSUE THREAD

**Issue by aayusharora** [Cloud-CV/EvalAI#1112]
- This issue is related to a specific version of Chrome.

## Steps to Reproduce
-  Setup project in Chrome ( Mac OS X )
- Chrome Version 59.0.3071.115 (Official Build) (64-bit)
- Buttons are non-clickable.

**Note: The website works correctly in Safari**

**Comment by aka-jain** [comment]
@aayusharora Can you capture a short video for this please ?

**Comment by aayusharora** [comment]
Yes @aka-jain, please check https://drive.google.com/file/d/0BylUgB3l8Lc6VlhBWUNFMXlGQ3M/view?usp=sharing

**Comment by spyshiv** [comment]
@aayusharora: Any error in console while clicking on a button??

**Comment by aayusharora** [comment]
@spyshiv Hi, the buttons are working fine now. But I can see the error.
![main](https://user-images.githubusercontent.com/12194719/28985861-2e2b5350-7982-11e7-9535-b97232625c80.png)

**Comment by deshraj** [comment]
@aayusharora: also please check the cache issues on your browser.

**Comment by the-dagger** [comment]
Can confirm this.
Happens when you open the console and try to click anything on the page.
I believe this is issue related to the responsiveness of the website.

Please check the screen record linked below.
[https://youtu.be/hzQtf68QDfw](https://youtu.be/hzQtf68QDfw)

**Comment by deshraj** [comment]
Yeah, I tried on my latest chrome and it seems to be not working on my mobile phone.

**Comment by aayusharora** [comment]
I have tried and figure out some points 
 - The issue is related to `animations`
 - The CSS3 animations introduce a `painting` layer on the screen which does not allow any clicks.
 - On mobile, as the page is not responsive, this `painting` layer go above the buttons which seems to be the major cause.
- To check this, remove all animations from CSS and run the project again.
 - Still, I am not able to figure out why it is not working on `iPhone6` while it works on `iPhone6 plus`. The reason for this seems the size of the button on a screen of 313 px ( iPhone 6 ), we can try to set the initial-scale=2 in the viewport to get this fixed ( not sure on this ).

Please suggest your viewpoint @aka-jain @spyshiv @deshraj

**Comment by RishabhJain2018** [comment]
@aayusharora Does this error still exists ? Can you please check once.

**Comment by RishabhJain2018** [comment]
@aayusharora Any update on this ?

**Comment by spyshiv** [comment]
FYI: using `initial-scale=2` will zoom content of viewport by 200% which is not a solution for this issue.
@aayusharora : IDK if this is fixed but I am closing this issue. Please feel free to reopen this if this issue is not fixed.
