### ISSUE TITLE
Add documentation for preparing the evaluation script 

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1114]
Currently, the documentation for preparing evaluation script for different kind of challenges (X number of phases and y number of dataset splits) is missing. 

## Deliverables

1. Write documentation about creating simple evaluation script from scratch for a simple challenge of string comparison (see https://github.com/Cloud-CV/EvalAI/blob/master/examples/example1/string_matching.zip for more details)
2. Write documentation for a challenge with 2 challenge phases and 2 dataset splits
3. Add a section with heading `How to make the evaluation faster for my challenge?` giving tips about making the evaluation faster. 

Let me know if there are issues/concerns.

**Comment by gautamjajoo** [comment]
@deshraj Can we close this issue since it is fixed in #1526 ?

**Comment by deshraj** [comment]
Thanks @gautamjajoo for pointing out. Closing this now.
