### ISSUE TITLE
Separate Configuration file for API Endpoints

### ISSUE THREAD

**Issue by aayusharora** [Cloud-CV/EvalAI#1116]
All the endpoints used in the project are written inside the files. 
### Problems
- This addresses two major issues
    - Code quality is affected due to the redundancy of same API endpoints
    - Code Readability 
### Proposed Approach 
 - Make a single config.js file containing all End points
 - Call All Endpoints from this Config file.

@spyshiv @deshraj @aka-jain Please suggest if you have some better approaches.

**Comment by deshraj** [comment]
Closing this since we are planning to rewrite most of the part in CloudCV/EvalAI-ngx repository. Feel free to contribute to that repository. :)
