### ISSUE TITLE
Syntax error while compiling scss

### ISSUE THREAD

**Issue by the-dagger** [Cloud-CV/EvalAI#1117]
<img width="1437" alt="screen shot 2017-08-05 at 2 15 40 am" src="https://user-images.githubusercontent.com/6565270/28986325-1c4fd37a-7984-11e7-826b-e96152e8069a.png">

**Comment by aayusharora** [comment]
Welcome @the-dagger. I think this happens after the last merge.
Do you want to work on this ?

**Comment by the-dagger** [comment]
Sure, would love to 🙂

**Comment by RishabhJain2018** [comment]
@the-dagger Please take help from this commit https://github.com/Cloud-CV/EvalAI/pull/1110/commits/3fab1a8ca96f2e6a4dd4ed9a53d8ca23d91566aa.
