### ISSUE TITLE
Sending Email locally

### ISSUE THREAD

**Issue by aayusharora** [Cloud-CV/EvalAI#1131]
- While Creating a challenge locally, I get notified as `Please Verify your email` while the email has not been sent.

## What is expected?
 
- Email configurations changes for `dev.py` should be mentioned in Readme.md.
- Also, `RESEND EMAIL` feature should be there, in case the user does not get an email.

**Comment by xamfy** [comment]
also when signing up the text "Setting up your details" shows up in white color which is not visible

**Comment by deshraj** [comment]
> also when signing up the text "Setting up your details" shows up in white color which is not visible
@xamfy can you please open an issue for this?

**Comment by deshraj** [comment]
@aayusharora: please see your terminal console to see the email content. It gets printed there instead of sending a real email that will need a smtp server.
