### ISSUE TITLE
EVALAI Performance Metrics

### ISSUE THREAD

**Issue by aayusharora** [Cloud-CV/EvalAI#1134]
As the client code base is increasing, we need to focus more on Performance Issues along with additional features, each animation, each `div span` adds to the performance of the page. Hence, to drive more users and to provide the app functionalities on slower connections, we should `measure` the performance and improve it time to time.

I have generated only Homepage Metrics, will add more when we are done with this.
### Lighthouse Report 
[Lighthouse Report.pdf](https://github.com/Cloud-CV/EvalAI/files/1205702/Lighthouse.Report.pdf)

### Google Page Insights Performance Metrics

![evalai](https://user-images.githubusercontent.com/12194719/29040338-399647ee-7bcc-11e7-9a47-af3cab2a300f.png)

 
Some initial Pointers to work upon

- [ ]  Improving the Critical Rendering Path

- [ ]  Following RAIL model to load the animations, instead of loading them on the first load.

- [ ]  Serve images that are appropriately-sized to save cellular data.

- [ ]  Enabling text-compression.

- [ ]  Removing render-blocking stylesheets

- [ ]  Serve WebP images for better compression.

- [ ]  Loading resources asynchronously and deferring the download of unnecessary resources.

- [ ] Improving Accessibility of the app
           - [ ]  Using `alt` tag in images.
           - [ ]  Adding `lang` attribute to `html`
           - [ ]  Using proper color contrast Ratio for text visibility ( UX )

@spyshiv @deshraj Please guide.

**Comment by deshraj** [comment]
Thanks @aayusharora. @aka-jain and I had a discussion about some of the points sometime back but we didn't take any action on this since this wasn't the priority. This looks like an exhaustive list of bugs that we definitely want to fix. :) Feel free to take lead on this if you are interested in solving this.

**Comment by aayusharora** [comment]
Thanks. Will try to do my best @deshraj

**Comment by Obtin** [comment]
@deshraj, I would like to work on this. Can I proceed?

**Comment by deshraj** [comment]
Closing this issue for now as we are working on @Cloud-CV/evalai-ngx . @live-wire can you please take care of this in ngx?
