### ISSUE TITLE
Indefinite progress bar on logging out

### ISSUE THREAD

**Issue by the-dagger** [Cloud-CV/EvalAI#1135]
Once you log out, the progressbar is displayed indefinitely and the user is unable to click anywhere on the screen.

Video Capture : 

https://drive.google.com/open?id=0B6OtIpAL6oa6ZWNoTTY0M0NocVU

Browsers : Safari and Chrome

**Comment by aayusharora** [comment]
I have seen this but forgot to report. Do you like to work on this @the-dagger ?

**Comment by the-dagger** [comment]
Sure. 👍

**Comment by RishabhJain2018** [comment]
@the-dagger Any update on this ?

**Comment by the-dagger** [comment]
@RishabhJain2018 Wasn't able to work on it, will take a look tonight.

**Comment by RishabhJain2018** [comment]
Okay sure, no problem. :+1:

**Comment by xamfy** [comment]
I want to try please guide.

**Comment by aka-jain** [comment]
Need update, anyone working on this? @RishabhJain2018

**Comment by xamfy** [comment]
I want to

**Comment by aka-jain** [comment]
Sure @xamfy, please go ahead and let me know if you find any difficulty.

**Comment by xamfy** [comment]
Sorry, couldn't work, you can assign this to someone else.

**Comment by RishabhJain2018** [comment]
Ok sure. :+1:

**Comment by isht3** [comment]
@RishabhJain2018 Since I'm not able to work on the submission issues due to a migration error, can I look into this meanwhile?

**Comment by isht3** [comment]
@RishabhJain2018 The progress bar is controlled through angular right? Is `startLoader` the command to start the loader?

**Comment by anuj-rathore** [comment]
@RishabhJain2018 If nobody is working on this, can I take this issue?

**Comment by deshraj** [comment]
@anuj-rathore: please work on the other issues assigned to you before working on this one. :)

**Comment by RishabhJain2018** [comment]
@deshraj @aka-jain @spyshiv I think this is resolved. Can you please verify it?

**Comment by deshraj** [comment]
Yeah, I just checked and it seems to be fixed. Thanks for pointing this out.
