### ISSUE TITLE
Disable the Challenge Phase buttons which are inactive while making submissions

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1139]
## Observed Behaviour
Currently, if a challenge phase is inactive then also a participant can select the phase to make submissions. 

See screenshot for example:
<img width="1440" alt="screen shot 2017-08-08 at 7 21 16 pm" src="https://user-images.githubusercontent.com/2945708/29098709-ca4c67a8-7c6e-11e7-8729-73122eb9982e.png">

## Expected Behaviour

The challenge phases that are not active now should be ideally disabled and the user shouldn't be allowed to select those challenge phases.

**Comment by Ram81** [comment]
@deshraj can I take this up?

**Comment by RishabhJain2018** [comment]
@Ram81 Yes sure. go ahead!
