### ISSUE TITLE
Add support for filtering challenges on the basis of challenge phase for host.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1141]
**Current Behaviour**: The filtering of submissions under the `View All Submissions` tab for a challenge host is on the basis of `challenge_pk` only. The results are same even if challenge host selects any `challenge_phase`.
**Expected Behaviour**: We want to filter the submissions on the basis of the both `challenge_pk` and `challenge_phase` corresponding to that challenge, so that the result set will only contain the submissions corresponding to the `challenge_phase` that the challenge host selects.

Please let me know in case of further queries.

**Comment by the-dagger** [comment]
@RishabhJain2018 Could you outline a bit more on what is needed in this issue?

**Comment by isht3** [comment]
Can I take this up? :)

**Comment by deshraj** [comment]
@isht3: yeah sure. Assigning it to you.

**Comment by deshraj** [comment]
@isht3: please accept the invitation as a contributor to CloudCV so that I can assign this issue.

**Comment by isht3** [comment]
@deshraj Thank you very much!

**Comment by isht3** [comment]
@RishabhJain2018 Hi, could you provide a small description about this issue?

**Comment by RishabhJain2018** [comment]
@isht3 I have updated the description of the issue. Please take a look and let me know if you have further queries!

**Comment by isht3** [comment]
@RishabhJain2018 Thank for the clear-cut description, got it done in a giffy!

**Comment by isht3** [comment]
@RishabhJain2018 Thanks for the clear-cut description, got it done in a giffy!
