### ISSUE TITLE
Add approved by admin check in seed script

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1143]
## Observed Behaviour

Currently, when the seed script is ran, then the challenges are created but they are not shown on the client side since the `approved_by_admin` atribute for those challenges is False by default.

## Objective

Set `approved_by_admin=True` for the dummy challenges in the seed script so that they can be viewed on the client side.

**Comment by the-dagger** [comment]
@deshraj can I work on this?

**Comment by deshraj** [comment]
Sure, go ahead.
