### ISSUE TITLE
Add link for challenge creation using zip file examples in read the docs. 

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1146]
Add the link for https://github.com/Cloud-CV/EvalAI-Examples repository in evalai docs under the section https://evalai.readthedocs.io/en/latest/challenge_creation.html#challenge-creation-using-zip-configuration

**Comment by HargovindArora** [comment]
@RishabhJain2018 can i proceed for this?

**Comment by RishabhJain2018** [comment]
Go ahead :)

**Comment by HargovindArora** [comment]
@RishabhJain2018 Working on it!
