### ISSUE TITLE
Mention the version of python used in the project in the README file.

### ISSUE THREAD

**Issue by HargovindArora** [Cloud-CV/EvalAI#1147]
Mention the version of python used in the project in the README file.

**Comment by RishabhJain2018** [comment]
Good catch @HargovindArora :+1: .If you are interested in working on this issue then let me know, I will assign it to you. :)
Moreover, the instructions above are for opening the issue, you can remove them after reading and then open a issue by following these instructions.

**Comment by HargovindArora** [comment]
@RishabhJain2018 Yes please, I would like to do it.

**Comment by RishabhJain2018** [comment]
@HargovindArora Go ahead :)
