### ISSUE TITLE
Remove pagination from challenge phase split list API

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1155]
## Observed behavior

The Challenge Phase Split list API endpoint currently returns the challenge phase splits in a paginated manner. But while showing the leaderboard, we need the list of all the challenge phase splits requesting once. 

## Objective

Remove the pagination from this API (https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/views.py#L357).

**Comment by taranjeet** [comment]
@deshraj : Can we instead of removing pagination, take a query parameter like noPage or some better name, which if presents, causes the api to return complete result set instead of pagination?
