### ISSUE TITLE
Change the email confirmation template according to current UI.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1157]
## Current Behaviour
![email](https://user-images.githubusercontent.com/12206047/29171837-7cab1c2c-7dfb-11e7-9778-93876e6ae87b.jpg)
The Email confirmation template is according to old UI.

## Expected Behaviour
The email confirmation template should be according to the current UI.

**Comment by xamfy** [comment]
I want to work on this.

**Comment by the-dagger** [comment]
Sure, go ahead!

**Comment by xamfy** [comment]
Where can I refer the current UI.

**Comment by the-dagger** [comment]
Try signing up and clicking the email you receive in your inbox.
That should take you to the UI.

**Comment by RishabhJain2018** [comment]
Also please set up these values in your dev.py file
`EMAIL_HOST`
`EMAIL_HOST_PASSWORD`
`EMAIL_HOST_USER`
`EMAIL_PORT`
`EMAIL_USE_TLS`

**Comment by aayusharora** [comment]
@RishabhJain2018 can you help with this https://github.com/Cloud-CV/EvalAI/issues/1131

**Comment by RishabhJain2018** [comment]
@aayusharora Yes sure. I will fix that by tonight. :+1:

**Comment by xamfy** [comment]
python -m smtpd -n -c DebuggingServer localhost:1025
this can be used

**Comment by Ram81** [comment]
@deshraj can I take this ?

**Comment by deshraj** [comment]
@Ram81: looks like no one is working on this. Feel free to work on this.
