### ISSUE TITLE
Provided samples not working

### ISSUE THREAD

**Issue by the-dagger** [Cloud-CV/EvalAI#1164]
On creating a challenge using the provided [test_zip_file.zip](https://github.com/Cloud-CV/EvalAI/blob/master/examples/example1/test_zip_file.zip) , the following error is thrown.

<img width="344" alt="screen shot 2017-08-11 at 12 45 16 pm" src="https://user-images.githubusercontent.com/6565270/29204149-f7399332-7e92-11e7-8e9b-1099f020ca48.png">

Looks like the samples are outdated and need to be updated.

**Comment by RishabhJain2018** [comment]
@the-dagger Thanks for pointing this issue. 
If you want to test this feature then you can use https://github.com/Cloud-CV/EvalAI-Examples repository.

**Comment by the-dagger** [comment]
Sure, thanks! 
So should we link this repo in our Readme and delete the existing samples from the project folder?

**Comment by RishabhJain2018** [comment]
Yes, Please refer to issue #1146 and I am creating a new issue for deleting the outdated samples.

**Comment by the-dagger** [comment]
👍
