### ISSUE TITLE
Remove unnecessary files from examples folder.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1165]
Remove the folder `test_zip_file` and `test_zip_file.zip` from the `EvalAI/examples/example1` folder.

**Comment by HargovindArora** [comment]
@RishabhJain2018 I would like to work on it.

**Comment by RishabhJain2018** [comment]
@HargovindArora sure. assigning it to you.

**Comment by RishabhJain2018** [comment]
closed #1165 via #1169 .
