### ISSUE TITLE
Add feature to update submission metadata.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1176]
**Current Behaviour:** There is no feature to update the submission meta once a submission is done by the participant.
**Expected Behaviour:**
The Participant should be able to update:

- [x] Method Name

- [x] Method Description

- [x] Project Url

- [x] Publication Url

**Comment by johnwlambert** [comment]
@RishabhJain2018 is it possible to add submission metadata that is viewable to the public? For example, if I make a submission to the Argoverse 3d Tracking leaderboard, can I add a reference to our corresponding publication?

The [KITTI leaderboard](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d) has this functionality, for example, and also the [nuScenes object detection leaderboard](https://www.nuscenes.org/object-detection?externalData=all&mapData=all&modalities=Any).

**Comment by johnwlambert** [comment]
Ideally there would be an "Expand" button and then more metadata about the publication would be visible.
