### ISSUE TITLE
Add Forgot password feature

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#118]
Need to add a Password Change (forgotten password) feature. Refer API docs for change password endpoints

**Comment by gauthamzz** [comment]
Can I try?

**Comment by aka-jain** [comment]
@gauthamzz Sure, go ahead. Let me know if you get any problem.

**Comment by aka-jain** [comment]
@gauthamzz just to make you hands on, can you try issue #140? This is just to make you familiar with the client side code

**Comment by aka-jain** [comment]
@gauthamzz : Let me know if you are still working on it?

**Comment by gauthamzz** [comment]
sorry i had a quick hectic week in college. i wont be able to do anything for next four days

**Comment by aka-jain** [comment]
Sure, no problem.

**Comment by anweshknayak** [comment]
is anybody doing this ?

**Comment by aka-jain** [comment]
@anweshknayak I don't think so. You go ahead and try it.

**Comment by anweshknayak** [comment]
can you provide some hint ?

**Comment by aka-jain** [comment]
@anweshknayak : you have to make a nested view for Forgotten Password in auth view (like we have login and signup). Refer http://localhost:8000/docs/ on your local machine for API endpoints. Use design same as of Login page. Steps are:
1. Make an email input field to send password reset link.
2. After confirmation reset password with new password, confirm password, token, and Unique ID.

@deshraj : do yo want to add something?

**Comment by aka-jain** [comment]
@anweshknayak : Please don't try this issue, we have an urgent requirement of this feature that's why I'm assigning this to myself.

**Comment by anweshknayak** [comment]
@aka-jain sure. anyway I have semester exams going on too :P

**Comment by aka-jain** [comment]
@deshraj : You can work on this, let me know if you need any help :)

**Comment by deshraj** [comment]
Sure, will do.

**Comment by aka-jain** [comment]
@spyshiv : assigning this to you.

**Comment by spyshiv** [comment]
@aka-jain : Cool. I am working on it.

**Comment by deshraj** [comment]
Fixed in #446. Closing it.
