### ISSUE TITLE
Update when made public timestamp.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1180]
**Current behaviour:** Currently we are not updating `when_made_public` timestamp when a user makes his submission public.
**Expected behaviour:** When a user makes his submission public then update this timestamp.
The timestamp must be in` UTC`.

**Dependency:** Dependent on the PR #1179

**Comment by RishabhJain2018** [comment]
@deshraj I think we should update `when_made_public` field only when `is_public` field in `Submissions` model is true. OR should we update it every time when a user toggles the `is_public` field. What do you say?

**Comment by deshraj** [comment]
Yeah every  time, when the participant makes it true, we should update the datetime. Does that make sense?

**Comment by RishabhJain2018** [comment]
yes, it does.
