### ISSUE TITLE
Evaluation Script extraction not working properly for Zip Challenge Creation

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1189]
## Current Behaviour

When someone tries to upload a challenge on EvalAI, the evaluation script extraction code is buggy and whenever someone tries to make submission, then it shows the following error for each of the submission:

```
Traceback (most recent call last):
  File "scripts/workers/submission_worker.py", line 296, in run_submission
    submission_output = EVALUATION_SCRIPTS[challenge_id].evaluate(annotation_file_path,
AttributeError: 'module' object has no attribute 'evaluate'
```

## What is the error??

From what I experimented, it seems like when the `evaluation_script.zip` extraction is done at the backend, then while unzipping, there is a directory created `evaluation_script` and then while making submissions, the submission worker looks for `evaluate()` method which it cannot find and hence throws the error.

## How to fix

Ideally, one might want to extract the contents of the `evaluation_script` directory and not the directory itself. It should fix the error.

**Comment by taranjeet** [comment]
I think you are uploading a zip file which has no `__init__.py` file (it is not a valid python module).

Can you check ?

@deshraj

**Comment by deshraj** [comment]
@taranjeet: I checked and verified that it is not the case. I checked the `/tmp` directory created and it is unzipping the `evaluation_script` in the directory which it should not do ideally.

**Comment by isht3** [comment]
@deshraj Can I look into this?

**Comment by RishabhJain2018** [comment]
@isht3 Yes sure. Go ahead!

**Comment by isht3** [comment]
@deshraj @RishabhJain2018 Hi! Was this fixed? I tried to reproduce the error, but everything seemed to work cool. Bottom right window.
![img](https://image.prntscr.com/image/kaatkH62SmqpVugLrrmcRw.png)

**Comment by RishabhJain2018** [comment]
@isht3 No, this isn't fixed. Let me check once.

**Comment by isht3** [comment]
@RishabhJain2018 Thanks!

**Comment by isht3** [comment]
@RishabhJain2018 Any updates?

**Comment by RishabhJain2018** [comment]
@isht3 ohh..It got slipped from my mind. I will update soon :)

**Comment by isht3** [comment]
@RishabhJain2018 Cool! :+1:

**Comment by isht3** [comment]
@RishabhJain2018 Should I start working on this? :smile:

**Comment by deshraj** [comment]
Just checked and this is working properly. Sorry for bothering. :)
