### ISSUE TITLE
Add support for different versions of same packages for different Challenges

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1190]
## Problem 

The current challenges on EvalAI use the same version of the libraries like `numpy`, `scipy`, `matplotlib` etc. But this needs to be changed since different challenges will want different version of the same libraries. 

Possible solutions that I can think of are:

- Different submission workers for each challenge
- Run the submission worker in different docker containers

Discussion/suggestions are welcome!

**Comment by isht3** [comment]
@deshraj, Whenever we make a new challenge, the versions of the software required are given in the `requirements.txt` inside `evaluation_script`, right?

**Comment by isht3** [comment]
@RishabhJain2018 I'd like to work on this. :smile:

**Comment by deshraj** [comment]
@isht3: do you suggest a way to implement this? We have been brainstorming about this. Let us know if you have some ideas about how to do this.

**Comment by isht3** [comment]
@RishabhJain2018 I will definitely look into this issue and get back to you with few days.

**Comment by isht3** [comment]
@deshraj Since the functions of the major libraries like `numpy`, `scipy` and `matplotlib` won't change much across versions, how about maintaining one submission worker and then importing the libraries in the `submission_worker` according to the challenge we are running.

**Comment by isht3** [comment]
@deshraj I think splitting the submission_worker would be the best way to go. What do you think?

**Comment by deshraj** [comment]
@isht3: correct. If you want to work on it and would like to propose the workflow, feel free to do it.

**Comment by party98** [comment]
Hey, I'd like to work on this. I was thinking that instead of creating a docker container or running a different worker, I was thinking that while a submission is being evaluated, the `cwd` of the worker can be changed and the required packages can be locally installed in the submission directory using `pip install numpy -t .` command which will cause the version specified to be installed in the submission directory. These should then get used instead of the global packages.

**Comment by vkartik97** [comment]
> We will go with the challenge based worker approach where for each challenge, there will be dedicated workers so that if one goes down for some reason, it doesn't affect the other challenges.

@deshraj 
One solution can be using multiple workers, for all challenges. If one worker goes down, any challenge won't be affected.

**Comment by RishabhJain2018** [comment]
Closing this since we now support challenge based worker.
