### ISSUE TITLE
No email recieved on forget password

### ISSUE THREAD

**Issue by aayusharora** [Cloud-CV/EvalAI#1212]
After clicking forget password button, no email is received to reset the password.

**Comment by xamfy** [comment]
It's working

**Comment by Bala1718** [comment]
Can I work on it?

**Comment by aayusharora** [comment]
Yes sure :)

**Comment by RishabhJain2018** [comment]
@aayusharora During the `Debug=True` mode in django, the email is printed on console. Hence, the feature is working in production.
So, I am closing this. :)
