### ISSUE TITLE
Writing Proper SCSS files

### ISSUE THREAD

**Issue by aayusharora** [Cloud-CV/EvalAI#1214]
The current ` .SCSS ` is not modular, and contain a lot of redundant code.
We can remove all the redundancy by designing some mixins

- Mixins for 
     - Margin, padding, position, display, keyframes
- Gradients for Extending the classes
- Breaking the code in different files to introduce Modularity

**Comment by aka-jain** [comment]
@aayusharora we are already breaking the files into modular files, do you want it to be more modular or something else?
