### ISSUE TITLE
Add ^ & $ in regex of urls for proper matching

### ISSUE THREAD

**Issue by HargovindArora** [Cloud-CV/EvalAI#1216]
' `^` ' sign should be introduced in the regular expressions of the url's, mentioned in the url files so that our search is always matched up correctly.

For example:  
If we have not added the initial caret character (i.e., 'hello/$'), Django would match any URL that ends with hello/, such as /my/site/hello/.
Also it will be more syntactically correct.

**Comment by isht3** [comment]
@HargovindArora Can I take this up?

**Comment by HargovindArora** [comment]
Hey, @isht3 I was interested to do this on my own and also it will give me some experience of the code base. Would you mind if I take this? :)

**Comment by isht3** [comment]
@HargovindArora Shoot, I just did a PR on this. Wait, Let's split this, I'll do this for the urls in `analytics`, `accounts` and `challenges`. You do this for the other apps, cool?

**Comment by isht3** [comment]
@HargovindArora Haha, cool! I'll close my PR. :)
