### ISSUE TITLE
Add new requirements for AI challenges

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1225]
We would like to add some of the new requirements for the upcoming challenges in the requirements/common.txt

```
pickleshare==0.7.4
proc==0.10.1
rstr==2.2.5
```

**Comment by xamfy** [comment]
Please assign me

**Comment by RishabhJain2018** [comment]
@xamfy I think this has already been assigned to @deshraj . Please take up any other issue!

**Comment by lenixlobo** [comment]
Can i contribute to this?

**Comment by RishabhJain2018** [comment]
@lenixlobo I have opened the PR for the same. Please feel free to take up any other issue which is not assigned. :)

**Comment by lenixlobo** [comment]
I have made a pull request ,please check it out . @RishabhJain2018

**Comment by RishabhJain2018** [comment]
@lenixlobo Okay no problem . I will close mine :)
