### ISSUE TITLE
Change the font everywhere to Roboto

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1227]
We are planning to switch the font to Roboto for the whole web application. Please let me know if there are concerns/issues.

**Comment by xamfy** [comment]
Please assign me

**Comment by RishabhJain2018** [comment]
@xamfy Yes sure. Go ahead.

**Comment by RishabhJain2018** [comment]
@xamfy Any update on this? Please let me know if you need any help.

**Comment by xamfy** [comment]
Couldn't get time, will do today.

**Comment by xamfy** [comment]
@RishabhJain2018 I have sent a message please see.

**Comment by RishabhJain2018** [comment]
@xamfy Please discuss here as it will be available for everyone. :)

**Comment by xamfy** [comment]
I have the changed the base.scss file to use Roboto should I remove the font-faces, also should I make new class for roboto and include that in all the templates to replace the current font classes. What about the boldness?

**Comment by xamfy** [comment]
Changes are working fine locally

**Comment by xamfy** [comment]
Done

**Comment by xamfy** [comment]
Please review
