### ISSUE TITLE
"Setting up your details" shows up in white color 

### ISSUE THREAD

**Issue by xamfy** [Cloud-CV/EvalAI#1231]
While signing up the text "Setting up your details" shows up in white color which is not visible.

**Comment by anuj-rathore** [comment]
I think nobody is on this, can I take this issue @RishabhJain2018

**Comment by gautamjajoo** [comment]
@deshraj @RishabhJain2018 The text is visible while signing up, Can we close this issue??

**Comment by RishabhJain2018** [comment]
@gautamjajoo Thanks for pointing this. Yes, I am closing it as it is already fixed.
