### ISSUE TITLE
Add `^` symbol before url paths in url.py files.

### ISSUE THREAD

**Issue by modestlearner** [Cloud-CV/EvalAI#1237]

**Comment by modestlearner** [comment]
Hey , I was just reading the documentation and code of EvalAI and found missing '^' on urls.py files

**Comment by modestlearner** [comment]
I want to fix this can I do that???
I am new to GitHub so please help me :D

**Comment by xamfy** [comment]
It has been raised earlier, see https://github.com/Cloud-CV/EvalAI/issues/1216

**Comment by modestlearner** [comment]
But I think the changes are still not accepted.

**Comment by modestlearner** [comment]
Because they are still missing from some files.

**Comment by xamfy** [comment]
It's currently being worked upon so look for a different issue.

**Comment by modestlearner** [comment]
Can you help me with that because I am new to GitHub.

**Comment by xamfy** [comment]
Join the gitter channel

**Comment by RishabhJain2018** [comment]
@modestlearner Please join https://gitter.im/Cloud-CV/EvalAI for more details and discussion about the project.
I am closing this issue as #1223 already points to it.

**Comment by modestlearner** [comment]
@RishabhJain2018 Cool!!!! Thanks!!!
