### ISSUE TITLE
Unnecessary r' ' in the regular expressions in urls.py file

### ISSUE THREAD

**Issue by modestlearner** [Cloud-CV/EvalAI#1240]
I am not too sure about the issue but I think there's unnecessary r ' ' in the regular expression in urls.py file in analytics..

If this is a valid issue I will be glad to fix this.

**Comment by RishabhJain2018** [comment]
@modestlearner No, since we are following pep8 guidelines for writing the code. Please refer https://stackoverflow.com/questions/22775697/how-to-specify-long-url-patterns-using-regex-so-that-they-follow-pep8-guidelines for more details.
Also let me know if you have further doubts.

**Comment by modestlearner** [comment]
Okay thanks!!!!
