### ISSUE TITLE
Update Facebook's logo on home page

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1243]
We would like to change the Facebook's logo with the one uploaded here. 
![facebook-logo-preview](https://user-images.githubusercontent.com/2945708/30350572-41840eac-97e5-11e7-90a3-bc9808d0057d.png)

**Comment by xamfy** [comment]
Please assign me

**Comment by deshraj** [comment]
Sure @xamfy, go ahead. :)

**Comment by xamfy** [comment]
![image](https://user-images.githubusercontent.com/19357995/30377600-f71fc8d2-98ad-11e7-8583-c1f51dff2c7c.png)
Should I change the size?

**Comment by xamfy** [comment]
![image](https://user-images.githubusercontent.com/19357995/30378743-db3deb0e-98b1-11e7-91d5-1b6096d86915.png)
How about this?

**Comment by deshraj** [comment]
@xamfy it would be nice if you can crop the facebook logo from top and bottom so that it's of similar size as others.

**Comment by xamfy** [comment]
Sure, I'll do that. Alternatively we can get a fb wordmark logo from https://en.facebookbrand.com/ of the same quality.

**Comment by xamfy** [comment]
https://en.facebookbrand.com/assets has the required assets

**Comment by xamfy** [comment]
![image](https://user-images.githubusercontent.com/19357995/30385773-c62d4fd4-98c5-11e7-8d74-fbf07d97340a.png)
Is it ok?

**Comment by xamfy** [comment]
![image](https://user-images.githubusercontent.com/19357995/30386676-16f9bd1a-98c8-11e7-9a13-8f694e549f08.png)
Is this ok?

**Comment by dhruvbatra** [comment]
Can we please use the colored logo for VT?

**Comment by xamfy** [comment]
Sir, it is already colored, while taking screenshot I hovered over it.

**Comment by dhruvbatra** [comment]
Ah, I see. Thanks!

**Comment by xamfy** [comment]
![image](https://user-images.githubusercontent.com/19357995/30389554-c924b38e-98d0-11e7-8c43-b22511fd11b5.png)
@deshraj Is it ok?
