### ISSUE TITLE
Remove debugging statements from auth controller

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1259]
**Expected Output** : Remove `console.log` statements from `authCtrl.js` so that the lint warnings are removed.

**Comment by Marlysson** [comment]
@RishabhJain2018 the ```console.log``` are in a context to show some error when occours a exception, just remove them or put something in place..

**Comment by xamfy** [comment]
Can I take this?

**Comment by RishabhJain2018** [comment]
@Marlysson Yes, You need to remove them & you can send the same error to the user using `$rootScope.notify`. Please let me know if you are interested in working on this.

@xamfy If @Marlysson doesn't take this up, then you can. :)

**Comment by Marlysson** [comment]
@RishabhJain2018 Yes, I do.

I will send a pull request soon..

**Comment by RishabhJain2018** [comment]
Great ! Assigning this to you.
@xamfy Please feel free to take up any other issue.

**Comment by Marlysson** [comment]
@RishabhJain2018 I'm searching from where came the ```notify``` method in $rootScope.. But don't found..

I too search in file and nothin..

Can you explain ..?
