### ISSUE TITLE
Github and Twitter links are not working in dashboard footer

### ISSUE THREAD

**Issue by Ayukha** [Cloud-CV/EvalAI#1266]
The Hyperlink to Github and Twitter Page is not working in Footer area of the Dashboard Page.
 
Expected Behaviour: Clicking on the Github and Twitter logo should open their respective cloudcv profile               

Observed Behaviour: Clicking on the Hyperlink does nothing.

Adding the URL in the href tag can solve the problem.

**Comment by xamfy** [comment]
Are you working on this?

**Comment by RishabhJain2018** [comment]
Good catch @Ayukha . Please let me know if you are interested in working on this.

**Comment by Ayukha** [comment]
Yes i would like to work on this . @RishabhJain2018

**Comment by RishabhJain2018** [comment]
**Issue** : The `github` and `twitter` link in dashboard footer aren't working. Please refer [here](https://github.com/Cloud-CV/EvalAI/blob/master/frontend/src/views/web/partials/dashboard-footer.html#L8)
**Solution**: We need to create a hyperlink to them.
**Hint**: Take reference from [here](https://github.com/Cloud-CV/EvalAI/blob/master/frontend/src/views/web/partials/footer.html#L8)

**Comment by RishabhJain2018** [comment]
Great @Ayukha . Assigning this to you. 
@xamfy Please feel free to take up any other issue from the list.

**Comment by Ayukha** [comment]
Done with the changes . Please review @RishabhJain2018
