### ISSUE TITLE
RuntimeWarning: DateTimeField received a naive datetime

### ISSUE THREAD

**Issue by xamfy** [Cloud-CV/EvalAI#1277]
This error occurs while running the tests.
See https://stackoverflow.com/questions/18622007/runtimewarning-datetimefield-received-a-naive-datetime
![image](https://user-images.githubusercontent.com/19357995/30781069-271fd94c-a136-11e7-8f19-c1997be6cd11.png)
Partial solution: change
```
when_made_public=datetime.datetime.now()
```
in tests/unit/jobs/test_views.py to 
```
when_made_public=timezone.now()
```

**Comment by xamfy** [comment]
@RishabhJain2018  Should I fix this?

**Comment by RishabhJain2018** [comment]
Go ahead ! Assigning this to you.
