### ISSUE TITLE
Customising Django Admin according to EvalAI Project

### ISSUE THREAD

**Issue by HargovindArora** [Cloud-CV/EvalAI#1284]
For a big project like this, the Django administration should be customised according to the project itself.
Like when we open the admin it states there "Django administration". 
Insetad "EvalAi Administration" seems better. 
Also, we can customize various apps admin and add a search bar and filters so that it may be easy for the administrator to query the admin panel of an app.
If you agree on this, I would like to take up this issue :smile:

**Comment by RishabhJain2018** [comment]
@HargovindArora Yes, we can customise the Django Administration.
Can you please list down all the points what exactly you want to achieve like
- Changing Django Administration to EvalAI Administration.

Please come up with a detailed plan and then we are good to go!

**Comment by HargovindArora** [comment]
@RishabhJain2018 Changes like the following can be introduced in the Admin:

- Changing the name from "Django Administration" to "EvalAI Administration".

- We can edit some required fields of an attribute of a model in the list view itself and need not go in detail view.

- While in the list view of a model's value we can decide or arrange as to which column should be placed first according to your preference like in "Challenge Phases" the name of the challenge column should be displayed first then the name of the challenge phase.

- We can add a filter in "Challenge Phases" so that its challenge can be filtered through challenge name and we can do this in many other models as and where required.

Any suggestion and change you can add will be helpful! :smile:

**Comment by sehgalayush1** [comment]
@RishabhJain2018 Since it is a big task containing a lot of changes, I would like to help @HargovindArora with this issue.

**Comment by RishabhJain2018** [comment]
@HargovindArora :
1. I agree with your first point. We can add it.
2. For the second point can you please give the list of fields that you want to edit in the list view.
3. For the third point , I think we are good to go with the current view. @deshraj What do you say?
4. For the fourth point , the filter for challenge is already there in challenge phase model. Can you please specifically list down the other models you are talking about. 

@sehgalayush1 I think this is a trivial task and @HargovindArora can do it alone. I would suggest you to take up any other issue from the list. 
Please let me know if something is unclear.

**Comment by HargovindArora** [comment]
@RishabhJain2018 I have these list of changes which i think should be done in admin according to me:

1.

**Comment by deshraj** [comment]
@HargovindArora I agree that these will be helpful but these are not the primary concerns as of now. I am closing this PR and will reopen whenever such requirement comes in.
