### ISSUE TITLE
Fix team page content placement and modify hyperlinks

### ISSUE THREAD

**Issue by geekayush** [Cloud-CV/EvalAI#1287]
- Observed behavior

1) The heading 'Core Team' is hiding behind the navigation-bar.

![laptop](https://user-images.githubusercontent.com/22499864/30984609-67c2b564-a4ab-11e7-8831-5720caa9e1d0.jpg)

![phone](https://user-images.githubusercontent.com/22499864/30984639-7b7a8f00-a4ab-11e7-92bc-e852f1ec801d.jpg)

2) All the hyperlinks in team-cards open up in the same tab which is hindering the user-experience.

- Expected behavior 

1) The content of team page should be placed a little lower. (Adding margin-top to the content will work)

2) Hyperlinks should open up in another tab. (Adding target attribute to the anchor tag will solve this)

**Comment by RishabhJain2018** [comment]
Good catch @geekayush .  Let me know if you are interested in working on this. :)

**Comment by gabru-md** [comment]
@RishabhJain2018 can i do this ?

**Comment by RishabhJain2018** [comment]
@gabru-md Let's wait for @geekayush . If he doesn't take this up, then you are good to go :)

**Comment by geekayush** [comment]
@RishabhJain2018 I would like to solve this :)

**Comment by RishabhJain2018** [comment]
Go ahead! @geekayush 
@gabru-md Feel free to take up any other issue from the list. :)
