### ISSUE TITLE
Add support editing a challenge details on UI

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1288]
## Current Status

Currently, we have all the APIs required for editing the challenge. UI needs to be implemented so that the challenge hosts can edit the challenge on their own. 

## Deliverables

Note: There is a constraint that only challenge host should be able to edit the details on the frontend and hence the edit buttons should be avilable to the challenge hosts only.

1. Challenge host should be able to  edit the following fields:
- [x] Challenge name
- [x]  Challenge short description
- [x]  Challenge long description
- [x]  Terms and conditions
- [x]  submission guidelines
- [ ]  start date
- [ ]  end date
- [x]  evaluation script

2. For a challenge phase, following fields should be editable:
- [ ] phase name 
- [ ] phase description
- [ ] start date
- [ ] end date
- [ ] test_annotation file (Open a dialog box showing warning "Do you really want to do this? " Also, ask the host to enter the phase name here to make sure that he/she is not drunk while doing this)
- [ ] max submisasions per day
- [ ] max submissions

Note that this is a big issue and can be submitted as two different pull requests: one for editing the challenge details and the other for changing the challenge phase details. We want to add support for editing more meta details of the challenge and we would like to do that once we have these features in place.

**Comment by RishabhJain2018** [comment]
@deshraj I would like to take lead on this.

**Comment by deshraj** [comment]
Sure. Assigning it to you.

**Comment by RishabhJain2018** [comment]
@deshraj Please take a look at the UI.
![cancel1](https://user-images.githubusercontent.com/12206047/31058004-333bc70c-a70a-11e7-8277-eec6c129d6c8.jpg)

**Comment by deshraj** [comment]
Challenge description will be really long so it would be nice if you can increase the width and height of the dialog box. Rest this looks good to me.

**Comment by RishabhJain2018** [comment]
Currently, I am doing the First part(`Editing Challenge`) of the issue, **the second part is still open to everyone**, as we will have two PR's for the same issue.
Please make the UI as shown in the above comment.
Let me know if there is any problem.
