### ISSUE TITLE
Show a loader when a challenge zip configuration is submitted

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1289]
## Current Status

When a host tries to upload a challenge zip configuration and the zip config is huge file, then he has no clue that what is happening at the backend: whether the file is being uploaded or not. 

## Deliverables

We would want to show a loader till the request is completed.

**Comment by HargovindArora** [comment]
@deshraj  I'm working on it.

**Comment by 16116073** [comment]
@deshraj is anybody is working on it. If not, I would like to take this issue.

**Comment by Obtin** [comment]
@aka-jain @RishabhJain2018 @deshraj , can i take this issue if nobody is working on this.
Thank You.

**Comment by anuj-rathore** [comment]
If nobody is working on this issue can I work on this?

**Comment by adamstafa** [comment]
@deshraj Fixed it.
https://github.com/Cloud-CV/EvalAI/pull/1432

**Comment by deshraj** [comment]
Sorry guys for not being responsive. Seems like this is already fixed. Thanks @adamstafa
