### ISSUE TITLE
Add a boolean field to challenge to make it featured challenge

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1290]
## Current behavior

Currently, the first challenge is considered as the featured challenge on EvalAI. We would like to change this and the admin should have the functionality to choose which challenge should be featured challenge. 

## Deliverables

- [x] Add a new field in the challenge model which makes a challenge featured
- [x] Don't forget to name the migration

**Comment by sehgalayush1** [comment]
Hi sir, can I take up this issue?

**Comment by deshraj** [comment]
@sehgalayush1 sure, go ahead. :)

**Comment by sehgalayush1** [comment]
@deshraj Please clear something for me, You want the default value of the featured field to be false right?

**Comment by sehgalayush1** [comment]
Also, should i just push the new code in the master of my fork and create a PR or should I create a new branch?

**Comment by xamfy** [comment]
@sehgalayush1 Please make a new branch for that

**Comment by deshraj** [comment]
Reopening this issue since one part of this issue is still not resolved.

**Comment by RishabhJain2018** [comment]
@deshraj Which part is still left?

**Comment by deshraj** [comment]
Sorry, this one is done. Closing again.
