### ISSUE TITLE
Change the logic to show featured challenge

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1291]
## Current behavior

Currently, the challenge whose primary key is 1 is shown as the featured challenge on EvalAI. We would like to change it and show the challenge which has the featured challenge flag set as True in the database.

## Deliverables

- [ ] Update the get challenges API to add support for the filtering the featured challenges as a query parameter "featured=True"
- [ ] Update the controller to fetch the featured challenge instead of fetching the first challenge
- [ ] Write unit tests for the updated API endpoint

**Comment by deshraj** [comment]
Also, this depends on #1290

**Comment by xamfy** [comment]
@deshraj I'm done with #1277. Can I work on this?

**Comment by sehgalayush1** [comment]
@deshraj @xamfy Actually since this issue was related to #1290 I already started working on this as I am finished with #1290 . So should I go through with this?

**Comment by RishabhJain2018** [comment]
@sehgalayush1 @xamfy Since this issue requires both front-end and backend changes, we will break it into two PR's.
1. For updating the API and writing its tests.
2. For updating the controller and the view.
Since both of you are interested in working on this. Please let us know which part you are working on. :)

**Comment by xamfy** [comment]
@RishabhJain2018 first one

**Comment by sehgalayush1** [comment]
@RishabhJain2018 I'll work on the second one.
@xamfy Please add a /challenge/featured route in the get_all_challenges API, so that only challenges that have featured=True can be fetched and I'll modify the controller to fetch challenges from that url and display them.

**Comment by RishabhJain2018** [comment]
Awesome!

**Comment by Rahuliamthebest** [comment]
I see!!

**Comment by codervivek** [comment]
Can I work on this?

**Comment by deshraj** [comment]
@codervivek sure, go ahead.
