### ISSUE TITLE
'Dataset split with that codename already exists' error 

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1294]
## Current Scenario

When a user creates a challenge using a zip configuration that has some dataset split codename, then the challenge is created successfully. If he tries to create a similar challenge with similar dataset split name then he gets an error that `Dataset split with that codename already exists` which should not happen since different challenges can have same dataset split codename. 

## Deliverables

- [ ] Remove `unique=True` from DatasetSplit's codename field
- [ ] Set unique_together `pk` and `dataset_split` in Challenge phase model
- [ ] Don't forget to name migrations

**Comment by Himanshi-Khandelwal** [comment]
@deshraj can you explain the second point of Deliverables

**Comment by isht3** [comment]
@deshraj I'm quite familiar with this error, can I look into it? :smile:

**Comment by deshraj** [comment]
Sure @isht3. :)

**Comment by isht3** [comment]
@deshraj Hi, Since `('codename', 'challenge')` exists, is `('pk', 'codename')` is needed?

**Comment by RishabhJain2018** [comment]
I think we @isht3 have already completed this. Hence, closing this.
