### ISSUE TITLE
Increase the data upload limit.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1295]
## Current Behaviour
By default django supports only 2.5 MB of the data to be uploaded on the web app. Refer [here](https://docs.djangoproject.com/en/1.10/ref/settings/#data-upload-max-memory-size) for more info.

## Effects
Due to the low upload limit the file in challenge creation using zip isn't being uploaded on the app as the size exceeds.

## Expected Behaviour
The upload limit must be increased to 10MB.

**Comment by memclutter** [comment]
Hello! I took the task

**Comment by RishabhJain2018** [comment]
@memclutter Go ahead! :)

**Comment by deshraj** [comment]
Edit: there are challenges where the challenge configuration file is of more than 100MB. We would like to update the size to 500MB

**Comment by cwiggs** [comment]
My PR #1310 increases the max file upload size to 500MB.
