### ISSUE TITLE
Add challenge filtering using featured parameter.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1304]
We need to add filtering in challenge model on the basis of `featured` parameter.

**Comment by pohzipohzi** [comment]
@RishabhJain2018  this sounds interesting. Can you provide more details?

**Comment by RishabhJain2018** [comment]
@pohzipohzi Currently the challenges are filtered in django admin using [these](https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/admin.py#L18) fields. We need to add `featured` field to it.
Please let me know if you need more help.

**Comment by pohzipohzi** [comment]
@RishabhJain2018 I made a PR based on my understanding of what you posted
