### ISSUE TITLE
Add instructions to update settings.dev.py in Docker Installation section

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1308]
## Deliverables

- [ ] Add a section to add instructions about renaming `dev.sample.py` to `dev.py` in the docker installation section in docs. See https://github.com/Cloud-CV/EvalAI/blob/master/README.md (4th point of installation instructions) for the text to add.

**Comment by deshraj** [comment]
Pointed out in #1286

**Comment by cwiggs** [comment]
I can work on this.
