### ISSUE TITLE
Remove models from Accounts app

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1312]
**Expected Behaviour** : Remove the `Affiliation` and `UserAffiliation` model from the `Accounts` app.
**Deliverables:**
- [ ] Remove the `Affiliation` and `UserAffiliation` model from accounts app.
- [ ] Create and name the migration.

**Comment by markslingerland** [comment]
I'll pick this one up

**Comment by RishabhJain2018** [comment]
@markslingerland sure. Assigning this to you!

**Comment by HargovindArora** [comment]
@RishabhJain2018 can I look into this?

**Comment by RishabhJain2018** [comment]
@markslingerland is working on it. @HargovindArora Please take up any other issue from the list. :)

**Comment by HargovindArora** [comment]
Sure @RishabhJain2018 .

**Comment by HargovindArora** [comment]
@deshraj @RishabhJain2018 Working on it!
