### ISSUE TITLE
Adding respective organizations links to the images and footer improvements.

### ISSUE THREAD

**Issue by HargovindArora** [Cloud-CV/EvalAI#1319]
![screenshot from 2017-10-10 02-18-30](https://user-images.githubusercontent.com/22341493/31400054-e7163dc2-ae0b-11e7-9b2d-bbdacbbe1c7a.png)

On the homepage of EvalAI, the section containing the list of Organizations that use EvalAI should have clickable links to their respective website pages so that any user can see what that organization does and that organization's particular information.

![screenshot from 2017-10-10 02-22-16](https://user-images.githubusercontent.com/22341493/31400081-fba5b268-ae0b-11e7-8473-974805cba712.png)

The EvalAI and CloudCV logos should also be links to the respective website page so that a user can navigate to the website from any particular page of the website through footer too.

![screenshot from 2017-10-10 02-22-39](https://user-images.githubusercontent.com/22341493/31400184-4cad2880-ae0c-11e7-94da-14a8f228ab13.png)

The Dashboard footer does not contain the CloudCV logo on it. I think the logo must be present there.

**Comment by HargovindArora** [comment]
Hey anyone please review it. Should it be done? :smile:

**Comment by RishabhJain2018** [comment]
@HargovindArora I missed it . I will do it by tonight.

**Comment by deshraj** [comment]
@HargovindArora closing this issue since we don't want to have the link to images of different organizations. I removed it intentionally in my previous pull request.

**Comment by HargovindArora** [comment]
Ohkay . Got it @deshraj :smile:
