### ISSUE TITLE
Stop showing success message for unregistered E-mails while resetting password.

### ISSUE THREAD

**Issue by isht3** [Cloud-CV/EvalAI#1321]
## Problem
When we try to reset password, it asks us for our Email to send the link. Now after we click submit, even if the email is not registered, it still says reset link sent.

![](https://image.prntscr.com/image/-xQ-2t8VRWSUocZt0exp9Q.png)

![](https://image.prntscr.com/image/uSew-wojRB6GoRY9HziKVQ.png)

What I noticed from other sites were that, It should be actually be saying the email is not registered if it is not present, so that the user knows whether they typed in correct email and avoids hassles.

I'd like to hear your views. :smile:

**Comment by deshraj** [comment]
This is being handled by Django allauth so that the email id of registered users shouldn't get exposed. Hence, we don't need this feature.

**Comment by isht3** [comment]
@deshraj Okay, cool. :smile:
