### ISSUE TITLE
Unable to configure project to work properly on virtualenv with Python-3 default. 

### ISSUE THREAD

**Issue by isht3** [Cloud-CV/EvalAI#1325]
- ## Observed Behaviour

While installing the project on a `virtualenv`, if the `virtualenv` was installed through Python-3 then the environment's default will be Python-3 if not specified otherwise. The problem is that if the project is installed on a `virtualenv` with default Python 3 it will lead to very unexpected errors, which are very hard to solve and the submission and challenge system won't run properly. 

- ## How to solve it?
In the long term, the project should be updated to work in Python 3 but now we should clearly specify in the installation instructions that the `virtualenv`'s default python version is supposed to be Python2.7, and also add the commands to help with the installation.

**Comment by RishabhJain2018** [comment]
@isht3 Please check the `Readme.md`, the python version with commands for installation are already mentioned there.

**Comment by isht3** [comment]
@RishabhJain2018 `virtualenv --python=/usr/bin/python2.7 venv` Adding this command will make the `virtualenv` be installed with Python2.7 default otherwise in the new versions it'll be Python3.

**Comment by deshraj** [comment]
@isht3: instead of changing the command, can we just add in the README somewhere which says that EvalAI supports Python2.x for now?

**Comment by isht3** [comment]
@deshraj Yes, that would be nice. :+1:
