### ISSUE TITLE
Typo Fix in Documentation

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1333]
**Current Documentation** : In `Architecture Decision` the operations are described as `CURD`.
**Related Links** : https://github.com/Cloud-CV/EvalAI/blob/master/docs/source/architecture_decisions.md#url-patterns
**Solution** : The operations must be described as `CRUD` according to the convention.

**Comment by jakecarr** [comment]
Hey, I can pick this one up for you if you like.

**Comment by RishabhJain2018** [comment]
@jakecarr Yes sure. Go ahead!
