### ISSUE TITLE
Setup "Deploy to Heroku" option for EvalAI

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1339]
Follow the instructions given here: https://devcenter.heroku.com/articles/heroku-button

**Comment by isht3** [comment]
@deshraj I'm quite familiar with heroku, I've deployed a few apps onto it. Can I try solving this?

**Comment by RishabhJain2018** [comment]
@isht3 Please take up one issue at a time so that it won't be a bottleneck for the overall development of the project. I think you are solving #1342 . Please complete that first then you can take this up, till then it is open to all :)

**Comment by isht3** [comment]
@RishabhJain2018 Okay, cool!

**Comment by anweshknayak** [comment]
Can I work on this?

**Comment by DakshMiglani** [comment]
This wouldn't work as there's two servers, one is the backend and the other is frontend. if they're served together, I can work this out.

**Comment by gurraunaqsingh** [comment]
I was thinking the same, but can't we just integrate both into a single django project?

**Comment by aka-jain** [comment]
#1449 Will do after this.

**Comment by deshraj** [comment]
Not required now. We will get back to it once we have ported the frontend to angular 5.
