### ISSUE TITLE
Down Chevron button not working on Mobile Phones

### ISSUE THREAD

**Issue by HargovindArora** [Cloud-CV/EvalAI#1340]
![screenshot_20171027-011942](https://user-images.githubusercontent.com/22341493/32104752-6620aee2-bb43-11e7-9b97-3ca989ddd5b5.png)

The Down Chevron button linked with "See More" is not working on mobile phones. 
Browser: Chrome

**Comment by RishabhJain2018** [comment]
@HargovindArora can you please tell for which screen size it is not working ?

**Comment by HargovindArora** [comment]
@RishabhJain2018 It's 5.5-inch screen and 720 x 1280 pixels.

**Comment by anweshknayak** [comment]
@HargovindArora are you on this ?

**Comment by anweshknayak** [comment]
It is working fine for 720 x 1280 pixels  I just checked.

**Comment by HargovindArora** [comment]
@anweshknayak I tested this on my device, it wasn't working. If you want to work on this feel free to make a PR. I just reported the issue here :smile:

**Comment by aka-jain** [comment]
It's working now, so closing this issue. @HargovindArora @anweshknayak
