### ISSUE TITLE
Increase the width of edit details dialog box

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1341]
**Observed Behaviour :**
![dialog_box](https://user-images.githubusercontent.com/12206047/32119513-22efbffc-bb73-11e7-8e69-4f9ba7e78a34.jpg)
The dialog box looks small in the screenshot.

**Expected Behaviour:** Increase the width of the dialog box suitably and paste the screenshot in the PR.

**Comment by vikneshwar** [comment]
Hi , i would like to take this up.

**Comment by RishabhJain2018** [comment]
@vikneshwar Go ahead!

**Comment by Ayukha** [comment]
@RishabhJain2018  Can i take this up if @vikneshwar  is not working on it ?

**Comment by RishabhJain2018** [comment]
@vikneshwar Any update on this ?
@Ayukha Let's wait for him, if he is not working on it then you can take this up :-)

**Comment by vikneshwar** [comment]
Hi, I had difficult time setting up the dependencies for this project, so couldn't continue. @Ayukha you can take this up. I will try meanwhile if I get time. Thanks

**Comment by RishabhJain2018** [comment]
@vikneshwar If you need some help in setting up the project, I will be glad to help you. You can also join the gitter channel https://gitter.im/Cloud-CV/EvalAI for your queries.

**Comment by vikneshwar** [comment]
Hi @RishabhJain2018 got this error, when i started the server https://gist.github.com/vikneshwar/adbeb25e96a077c33d23ad77d9cd3063

**Comment by RishabhJain2018** [comment]
@vikneshwar It looks like the SSL package you have installed isn't new enough for Twisted. I suggest you to upgrade it. Moreover, can you tell me which OS are you using ?

**Comment by kunalvishnoi** [comment]
@RishabhJain2018  i would like to work on this.

**Comment by deshraj** [comment]
@kunalvishnoi Sure, go ahead. :)

**Comment by S2606** [comment]
Is somebody working on this?? Can i claim it??

**Comment by 16116073** [comment]
Is anybody working on this issue?  If not I am interested to work on it. 
@RishabhJain2018 @deshraj

**Comment by RishabhJain2018** [comment]
@16116073 Please take up any other issue as @S2606 had asked for it earlier than you. :smile:

**Comment by anuj-rathore** [comment]
@RishabhJain2018 I think nobody is working on it, can I take this issue?

**Comment by S2606** [comment]
@anuj-rathore i am working on this..

**Comment by Obtin** [comment]
@RishabhJain2018, Is this resolved? If not I would like to work on this.

**Comment by RishabhJain2018** [comment]
@Obtin Yes sure!

**Comment by ParthS007** [comment]
@Obtin  Are you still working on this or I can take this up ? Please let me know :+1:

**Comment by Obtin** [comment]
@ParthS007, Yes :-)
