### ISSUE TITLE
Installation requirements/dependencies issues

### ISSUE THREAD

**Issue by AmosHason** [Cloud-CV/EvalAI#1343]
# System

**OS**: Ubuntu 16.04
**Python**: 2.7.12
**pip**: 9.0.1
**git**: 2.7.4
**PostgreSQL**: 10.0
**RabbitMQ**: 3.6.12
**virtualenv**: 15.1.0

# Expected Behavior

Following the steps in the repository README, you should not encounter any issues.

# Actual Behavior

## 1. While executing "pip install -r requirements/dev.txt" (step 3)

Collecting psycopg2==2.6.2 (from -r requirements/common.txt (line 15))
  Using cached psycopg2-2.6.2.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.
txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    Error: You need to install postgresql-server-dev-X.Y for building a server-s
ide extension or libpq-dev for building a client-side application.

## 2. While executing "pip install -r requirements/dev.txt" (step 3)

Collecting psycopg2==2.6.2 (from -r requirements/common.txt (line 15))
  Using cached psycopg2-2.6.2.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.
txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    Error: could not determine PostgreSQL version from '10.0'

## 3. While trying to execute "bower install" (step 8)

bash: bower: command not found

## 4. While trying to execute "gulp dev:runserver" (step 9)

bash: gulp: command not found

## 5. While executing "gulp dev:runserver" (step 9)

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Gem sass is not installed.

### Suggested fix: add a preceding step in the repository README to execute "gem install sass".

**Comment by deshraj** [comment]
@AmosHason closing this since you mentioned on the gitter channel that you were able to solve this by installing sass on your machine.

**Comment by AmosHason** [comment]
@deshraj it only solves the fifth issue. The README should include a step for installing sass.

However, all of the other issues are due to requirements/dependencies gaps, and can be solve by editing those files.

**Comment by deshraj** [comment]
I see. @AmosHason please feel free to go ahead and open a PR adding instructions to install sass in the README.

**Comment by AmosHason** [comment]
Regarding the first issue: it's currently impossible to install libpq-dev using pip (see https://github.com/ncbi/python-libpq-dev/issues/1).

**Comment by NSDCars5** [comment]
@AmosHason libpq-dev can be installed using apt.

**Comment by rupeshcode** [comment]
While installing dependencies for the project got the following error.
`Collecting psycopg2==2.6.2 (from -r requirements/common.txt (line 15))
  Downloading psycopg2-2.6.2.tar.gz (376kB)
    100% |████████████████████████████████| 378kB 334kB/s
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    Error: could not determine PostgreSQL version from '10.1'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/42/54d9118s4xx7qnjygmsbx7th0000gn/T/pip-build-1e_DjJ/psycopg2/`

After changing "psycopg2==2.6.2" to "psycopg2==2.7.1" in requirements/common.txt the dependencies installed correctly. 

should I make a PR for this issue?

**Comment by deshraj** [comment]
Thanks, @mlandry22 for pointing this out. Please feel free to create a pull request for the Postgres dependency updates.

**Comment by Obtin** [comment]
@deshraj , I guess this must be included in #1359

**Comment by deshraj** [comment]
@Obtin: yeah that is a great idea. Please feel free to comment on the thread or create a pull request. :)

**Comment by gautamjajoo** [comment]
@deshraj Added the common error in my the PR :- #1455

**Comment by deshraj** [comment]
Already fixed. Closing this.
