### ISSUE TITLE
Write documentation for preparing evaluation script

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1345]
## Deliverables

We already have the documentation for creating a challenge. We still don't have the documentation which tells the challenge hosts "How to prepare the evaluation script?" for their challenge. 

This issue requires proper understanding of how the evaluation script is executed when a submission is made. You should also know how the submission worker is evaluating the submissions at the backend ( a good thing here is that if you know this, then you know most important part of EvalAI).

See https://github.com/Cloud-CV/EvalAI-Examples to find an example of challenge evaluation script.

**Comment by deshraj** [comment]
Fixed in #1526

**Comment by gautamjajoo** [comment]
@deshraj Since, it is fixed in #1526 , we cna close this issue and #1114 this also.

**Comment by deshraj** [comment]
Thanks @gautamjajoo for pointing out. Closing this now.
