### ISSUE TITLE
Broken link in readme.md

### ISSUE THREAD

**Issue by neeraj12121** [Cloud-CV/EvalAI#135]
There is a link in [readme.md](https://github.com/Cloud-CV/EvalAI/blob/master/README.md)  line 84 to https://github.com/Cloud-CV/EvalAI/blob/development/CONTRIBUTING.md

**Comment by deshraj** [comment]
Thanks @neeraj12121 for reporting this. Actually, the correct link is https://github.com/Cloud-CV/EvalAI/blob/master/CONTRIBUTING.md

If you want to fix it, then go ahead. :-)

**Comment by neeraj12121** [comment]
@deshraj yeah sure
