### ISSUE TITLE
Remove unused code from ChallengeCreate Controller.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1350]
**Expected Behaviour:** Remove the commented code after line `84` from controller `ChallengeCreate.js`.
**Hint:** https://github.com/Cloud-CV/EvalAI/blob/master/frontend/src/js/controllers/challengeCreate.js#L84

**Comment by Ayukha** [comment]
Can i take this up?

**Comment by RishabhJain2018** [comment]
Sure go ahead!

**Comment by prajwalgatti** [comment]
I would like to try this. This would be my very first contribution. Please allow me to

**Comment by RishabhJain2018** [comment]
@prajwalgatti Go Ahead !

**Comment by prajwalgatti** [comment]
I made a pull request. Please review
