### ISSUE TITLE
Add comments in the codebase for analytics controller.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1357]

**Comment by HargovindArora** [comment]
@RishabhJain2018 I would like to work on this. Would you guide me how to proceed? :)

**Comment by RishabhJain2018** [comment]
@HargovindArora The issues labelled with `dev-sprint` are for developers participating in Pycon India 2017 dev-sprints. I will open it to everyone once it gets over.
Till then please take up any other issue from the list. :-)

**Comment by HargovindArora** [comment]
@RishabhJain2018 Sure :)

**Comment by Ayukha** [comment]
@RishabhJain2018  I want to work on this issue, May I?

**Comment by deshraj** [comment]
Fixed to some extent. Hence closing it.
