### ISSUE TITLE
Add comments in the codebase for auth controller

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1358]

**Comment by HargovindArora** [comment]
@RishabhJain2018 Since this is similar to #1357 . Can I take this up?

**Comment by RishabhJain2018** [comment]
@HargovindArora The issues labelled with `dev-sprint` are for developers participating in Pycon India 2017 dev-sprints. I will open it to everyone once it gets over.
Till then please take up any other issue from the list. :-)

**Comment by HargovindArora** [comment]
@RishabhJain2018 Sure. Got it :)

**Comment by DhruvThakker** [comment]
Is this issue open? Can I start working on it?

**Comment by RishabhJain2018** [comment]
@DhruvThakker Yes sure. This is open you can take this up.

**Comment by sachinmukherjee** [comment]
@RishabhJain2018 anyone working on this issue?

**Comment by deshraj** [comment]
This is a very vague issue. Also, we don't need it now since we are moving towards Cloud-CV/EvalAI-ngx (new frontend of EvalAI). Hence, closing it.
