### ISSUE TITLE
Research and suggest Frequently Asked Questions.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1359]

**Comment by nitinprakash96** [comment]
Hi, I'm new here and would like to contribute to this project. Can I start with this issue?

**Comment by gautamjajoo** [comment]
@RishabhJain2018 Here's some of the Frequently Asked Questions 
[Frequently Asked Questions.docx](https://github.com/Cloud-CV/EvalAI/files/1576129/Frequently.Asked.Questions.docx)

**Comment by RishabhJain2018** [comment]
@gautamjajoo The doc looks ok to me but you can add certain questions the common problems in setting up the project with solutions (Check EvalAI channel for the problems and solutions).

**Comment by deshraj** [comment]
Sorry but I think @RishabhJain2018 and @gautamjajoo misunderstood the requirement. The FAQ here is for the end users and not for EvalAI developers. So, there have to be questions such as:

1. What is EvalAI?
2. What kind of challenges does EvalAI support?
3. Can I run EvalAI on my private server?
4. How to host a challenge on EvalAI?
5. How to participate in a challenge in EvalAI?
6. What is the best way to contact EvalAI team?
7. I am interested in contributing. Where should I start from?

There are a lot more FAQs that we can think of. 

Sorry @gautamjajoo, it looks like you did a lot of work for this Pull Request but I am afraid that you would have to modify the questions and answers. We will make sure that this doesn't happen in future.

**Comment by gautamjajoo** [comment]
@deshraj It's ok. But can we add this file as "Common Error during installation"??

**Comment by deshraj** [comment]
As I mentioned that the FAQ that we want is for the end users and not the EvalAI Developers, so I don't think we can include it. Please feel free to suggest some other questions that you have in mind.

**Comment by deshraj** [comment]
Closing this issue since we are going to release the new frontend of EvalAI soon. (Cloud-CV/EvalAI-ngx)
