### ISSUE TITLE
Tutorial to participate in a challenge.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1360]
**Description:** Write a tutorial showing how to participate in a challenge on EvalAI. Stepwise instructions are expected.

**Hint:** Go to [https://evalai.cloudcv.org](https://evalai.cloudcv.org) and participate in a challenge.

**Comment by HargovindArora** [comment]
@RishabhJain2018 Can I take this up? :)

**Comment by RishabhJain2018** [comment]
@HargovindArora The issues labelled with `dev-sprint` are for developers participating in Pycon India 2017 dev-sprints. I will open it to everyone once it gets over.
Till then please take up any other issue from the list. :-)

**Comment by HargovindArora** [comment]
@RishabhJain2018 Sure. :)

**Comment by ayushsuhane** [comment]
@RishabhJain2018 Hi, Can I start with it?

**Comment by gautamjajoo** [comment]
@RishabhJain2018 Here's the document.
[Tutorial to participate in a challenge in.docx](https://github.com/Cloud-CV/EvalAI/files/1579239/Tutorial.to.participate.in.a.challenge.in.docx)

**Comment by deshraj** [comment]
@gautamjajoo this looks great. Can you please add this to the docs and create a pull request for this? There might be really minor changes that I can suggest once you have the pull request ready.
