### ISSUE TITLE
Try and suggest different color schemes for pop up info notifications

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1364]
**Description:** The color scheme must be in accordance with our new UI. Student should try different colours with notification toast so as to match the UI.

**Comment by HimanshuAwasthi95** [comment]
Is der any one work on it

**Comment by HimanshuAwasthi95** [comment]
or should I take this up ?

**Comment by RishabhJain2018** [comment]
@HimanshuAwasthi95 Yes sure . You can take it up. Feel free to ask if you face any difficulty.

**Comment by harshit98** [comment]
@RishabhJain2018 I understood that this notification toast:

![screen shot 2017-12-17 at 2 31 48 am](https://user-images.githubusercontent.com/22245418/34074334-931c05a2-e2d2-11e7-9518-6964d1460211.png)

should have color scheme which matches the new UI (current). Right? Correct me, if I'm wrong :)
It would be great if you can provide more details. I would like to work on this issue.
