### ISSUE TITLE
403 Forbidden response from Github API

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1373]
See the screenshot below for more details about the error:

<img width="1918" alt="screen shot 2017-11-18 at 6 16 41 am" src="https://user-images.githubusercontent.com/2945708/32979687-3248de50-cc28-11e7-8eb6-1a2ea3ed5325.png">

**Comment by DakshMiglani** [comment]
Hi, to fix these we need an authentication token from github, so i'd request the team leaders to create a client id with a secret and then we can request the api url which will look like: 
`https://api.github.com/users/whatever?client_id=xxxx&client_secret=yyyy`

**Comment by aka-jain** [comment]
@deshraj, @RishabhJain2018  any action on this?

**Comment by deshraj** [comment]
Hi @DakshMiglani, thanks for the suggestion. We would like to leave it as it is for now. We cannot expose the `client_id` and `client_secret` since we are requesting from the client side. We would love to have suggestions from the contributors for various workarounds for this problem.

**Comment by adamstafa** [comment]
@deshraj Currently unauthorized users (user is determined by his IP) can make up to 60 requests per hour so for normal usage this won't be a problem.
Another option is to create a view in backend to access the API with the token. The limit would be 5000 per hour but for all users. We would need to limit the refresh-rate of these stats then.

**Comment by Obtin** [comment]
@deshraj @aka-jain I would like to work on this after this discussion is concluded. Please assign this to me.Thank you.

**Comment by Obtin** [comment]
@adamstafa are we clear which approach do we have to follow to fix it.

**Comment by deshraj** [comment]
@Obtin please feel free to take this issue. :)

**Comment by Obtin** [comment]
@deshraj @adamstafa could you please suggest me the approach that i must follow from the two :

- Instead of doing everything with the GitHub API, Writing a GitHub Mirror script that is able to mirror all of those repos using my parallel python script via pygit2.

-  as suugested by @adamstafa creating a separate view

**Comment by deshraj** [comment]
@Obtin: I just thought about a new way of doing this. Can you integrate the https://buttons.github.io/ for showing the fork and star button? It will help us to remove the dependency of Github API and just use this service.
