### ISSUE TITLE
Python Migrate script, is missing 2 requirements

### ISSUE THREAD

**Issue by trexdinosaur** [Cloud-CV/EvalAI#1393]
hi! I'm part of GCI:

I was in the process of installing the software and using the migrate function to seed my DB. However, the script was missing two dependencies even after installing the requirements. Specifically, i was missing raven and django-storages. I rectified this manually via a pip install, however I think it is a good idea to go ahead and add it to the requirements. Should I open a PR to fix it, and if I do open a PR to fix it, should I version pin it to the latest one, or is a specific version preferred. Also, it is possible, it is just a glitch with my process, if so please let me know.

P.S: I'm going through the process of installing it on WSL, do you think it would be a good idea to create some documentation of going through it? I am not sure if it has been attempted, as I can't find any info on it. If this is desirable, please let me know!

Thanks

**Comment by NSDCars5** [comment]
Maybe this is a WSL issue? Because I didn't get such messages on Ubuntu 16.04 or 17.10, the seed function worked perfectly without them. And they weren't preinstalled on my machine either.

**Comment by trexdinosaur** [comment]
It definitely could be. it also might be related to the fact that I didn't run it under a venv, i'll try it again in a venv, and report back,

**Comment by harshit98** [comment]
@trexdinosaur @NSDCars5 I run it under venv. I was also getting the same message.

**Comment by NSDCars5** [comment]
@harshit98 Does installing those manually fix those like they did for @trexdinosaur?

**Comment by harshit98** [comment]
@NSDCars5 Yes. Manually installing them fixed the issue.

**Comment by deshraj** [comment]
@trexdinosaur: I think you were using the command `python manage.py seed` instead of `python manage.py seed --settings=settings.dev`. I tried to setup the project again and it worked perfectly. Closing this issue for now. Please feel free to open this if you still face this issue.
