### ISSUE TITLE
Create New Team Error

### ISSUE THREAD

**Issue by trexdinosaur** [Cloud-CV/EvalAI#1396]
I was on the instance of EvalAI, Cloud-CV is running, and I tried creating a team of "test". The application gave an arbitrary error of: "team couldn't be created.", however I can see the backend is passing through the more descriptive message of that team name being taken already. Is it better to pass this message through to the error popup? I think it is, as right now, if I was not looking at DevTools, I wouldn't know what's going wrong.

Thanks.

**Comment by RishabhJain2018** [comment]
@trexdinosaur The error is passed to the front-end as shown by this screenshot.
![csv2](https://user-images.githubusercontent.com/12206047/33689133-4e735818-db04-11e7-9bdc-86d14d88c781.jpg)
Also, can you please paste the screenshot showing where it is not working.

**Comment by trexdinosaur** [comment]
Oh, I completely overlooked that, sorry!
