### ISSUE TITLE
Add Footer module on homepage

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#140]
For now just add Some Social sharing Icons and some dummy links like about us, contact us etc.

**Comment by jainarunarunjain** [comment]
@aka-jain  Can I try this?

**Comment by deshraj** [comment]
@jainarunarunjain Sure. Go ahead. :-)

**Comment by aka-jain** [comment]
Sure @jainarunarunjain , and let me know if you find any difficulty regarding directory structure.

**Comment by jainarunarunjain** [comment]
@aka-jain should i make a module or not?

**Comment by aka-jain** [comment]
Yes, please make a different module for footer so that it can be easily used in another pages.

**Comment by aka-jain** [comment]
Fixed in #189.
Closing now.
