### ISSUE TITLE
Size of profile data text is small compared to ther options

### ISSUE THREAD

**Issue by S2606** [Cloud-CV/EvalAI#1405]
Observed feature
![image](https://user-images.githubusercontent.com/18497513/33842703-4d0042a0-dec1-11e7-9621-6e3d7a44a60c.png)

Expected features
The text size should at least be equivalent.

**Would you like to work on this issue?** 
Yes

**Comment by aayusharora** [comment]
Hi @S2606  Please go ahead :)

**Comment by aka-jain** [comment]
I'm not getting your point @S2606, please give more description.

**Comment by S2606** [comment]
@aka-jain If we compare the size of text of dashboard and the profile data, the latter is smaller in size. So we should at least make it equal.

**Comment by aka-jain** [comment]
Text sizes are same in dashboard and profile (14 px). Also the label is smaller and we made that intentionally. Correct me if I'm still missing something. @S2606

**Comment by aka-jain** [comment]
Closing this issue as this is done intentionally.
