### ISSUE TITLE
Add autofocus to login and signup page input box.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#141]
Autofocus username field in login and signup page.

**Comment by anweshknayak** [comment]
This has already been fixed I think ?

**Comment by aka-jain** [comment]
No, it is not fixed. Can you check it once again please.

**Comment by anweshknayak** [comment]
I have one doubt. The autofocus thing shall it lighten the whole input area(username) ? as in already there is one functionality which gives a yellowish indication bar below in the input area .

**Comment by aka-jain** [comment]
By Autofocus I mean to say that whenever user comes to login or signup page then first input field of form gets highlighted automatically. For this you only have to include autofocus in input tag. Give it a try :)

**Comment by aka-jain** [comment]
@anweshknayak : In case you are trying to solve this issue, then please refer #168

**Comment by aka-jain** [comment]
New issue open related to this at #168 
This issue fixed in #166
