### ISSUE TITLE
Validating email address when signing up

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#1421]
When we are signing up ,the message "Please enter valid email address" appears only when we are not entering a proper email address but when we enter an email address like "hello@hello" where ".com" is missing, no error is coming and the error displays when we enter the "SignUp" tab.

**Actual Behaviour**
 
![enter](https://user-images.githubusercontent.com/24366008/34208618-19e3516e-e5b5-11e7-8a6f-974ee61f5db9.JPG)

![hello2](https://user-images.githubusercontent.com/24366008/34208659-49561e36-e5b5-11e7-9d3d-f8c99e062d14.JPG)

**Expected Behaviour**

The error should come at the same time only

**Would you like to work on this issue?**

Yes

**Comment by RishabhJain2018** [comment]
@gautamjajoo No, we can't add it as an email contains a locally interpreted string followed by the at-sign character (`@`) followed by an Internet domain. Now the domain can contain any number of `.` in it. Also, please refer https://validator.w3.org/feed/docs/error/InvalidContact.html for more examples. Also, this validation is on the client side, so there is no api call that will burden the system. Please let me know if you still have doubts.
