### ISSUE TITLE
Test performance of EvalAI

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#1422]
**Actual Behaviour**

Currently the page is not optimized and is likely to deliver a slow user experience. 

**Expected Behaviour** 

Optimized Website.

**Would you like to work**

Yes.

@RishabhJain2018 

![capture](https://user-images.githubusercontent.com/24366008/34299259-02bccca6-e748-11e7-98f3-cdecd8fb02b2.JPG)

**Comment by aka-jain** [comment]
Assigning this to you @gautamjajoo. let me know if you need any help.

NOTE: for minification you have to rewrite gulp prod related tasks.

**Comment by gautamjajoo** [comment]
Here's a option to download the optimized images,css and javascript for the page. So can we just download and make the changes.

@aka-jain 

![capture](https://user-images.githubusercontent.com/24366008/34360557-d06209ea-ea87-11e7-8f6f-0b55ca06205b.JPG)

**Comment by aka-jain** [comment]
No, you have to these minification using gulp task runner.

**Comment by gautamjajoo** [comment]
@aka-jain Do we have to do the same as in the below URL.
https://andy-carter.com/blog/a-beginners-guide-to-the-task-runner-gulp

**Comment by spyshiv** [comment]
@gautamjajoo @aka-jain: I guess the original issue was to enable compression in static files(css, js, images) that was already written in `gulpfile.js`. 
See this
https://github.com/Cloud-CV/EvalAI/blob/9e8cf4dac75972a323f8c4bb26c88a959ab83fca/gulpfile.js#L406
And 
https://github.com/Cloud-CV/EvalAI/blob/9e8cf4dac75972a323f8c4bb26c88a959ab83fca/gulpfile.js#L400

You had to make `flags.production = true;` to enable compresssion.
Ps: code to compress the static files are written in indivisual tasks except `vendorcss` and `vendorjs`. for example for task `css` https://github.com/Cloud-CV/EvalAI/blob/9e8cf4dac75972a323f8c4bb26c88a959ab83fca/gulpfile.js#L102

**Comment by gautamjajoo** [comment]
@spyshiv Yes! I saw and realised that the code was already written so I just compressed the images. Now should I make flags.production = true; ??

**Comment by aka-jain** [comment]
@gautamjajoo yes please enable true on production and test it using production flag by comparing the sizes of images.

**Comment by deshraj** [comment]
The main deliverable of this task requires one to fix the minify command in gulpfile.js and not compressing the image manually. Hence @gautamjajoo: sorry but I have to close your Pull request #1431. Sorry if there was a misunderstanding.
