### ISSUE TITLE
Showing list of featured challenges without authentication.

### ISSUE THREAD

**Issue by Obtin** [Cloud-CV/EvalAI#1423]
On clicking on the the button 'view all' for featured challenges

- Observed behaviour
asks you to SIGN IN

- Expected Behaviour
should display a list of all the past, ongoing and future challenges, may be view similar to the dashboard, even when the user is not registered.

Would You Like to Take this Issue?
YES !

Thanks!

**Comment by aka-jain** [comment]
Thanks for catching this but the issue is already in progress @Obtin.
