### ISSUE TITLE
Password strength indication

### ISSUE THREAD

**Issue by Obtin** [Cloud-CV/EvalAI#1424]
When a user fills SIGN UP form, 
- Observed behaviour
after the clicking on 'sign up', user is informed about the password being common or not secure.

- Expected Behaviour
there should be an indicator telling the user about his password strength as he types each character.

Moreover, we do not have any specifications for password except that it should consist of 8 characters,
for making it better we could impose certain conditions.

Would You Like to Take this Issue?
YES !

Thanks!

**Comment by anuj-rathore** [comment]
@RishabhJain2018 Shall I take this issue?

**Comment by aka-jain** [comment]
Good feature to have, @Obtin you are working on this?

**Comment by Obtin** [comment]
@aka-jain yes I wish to take this issue.

**Comment by aka-jain** [comment]
Sure, assigning this to you.

**Comment by Obtin** [comment]
@aka-jain , I have created a PR for the Issue#1424, please have a look. 
Thank You.

**Comment by deshraj** [comment]
Fixed in #1445
