### ISSUE TITLE
Bug in mysubmission page

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#1425]
Card for my submissions is not visible. Check screenshot for more info.
![screen shot 2017-12-26 at 01 12 20](https://user-images.githubusercontent.com/11537940/34342564-0db6e648-e9da-11e7-9a54-aff65b165bd5.png)

Make submission card visible.

**Comment by aka-jain** [comment]
Feel free to take this task up.

**Comment by NSDCars5** [comment]
@aka-jain What information should be visible, exactly?

Once you select the challenge phase you can see the submissions for that particular phase.

![hi](https://user-images.githubusercontent.com/5107795/34836960-581be894-f71f-11e7-8587-864e87ee57b8.JPG)

Should submissions for all phases be shown by default?

**Comment by aka-jain** [comment]
Initially the submissions was shown in a white card, that card has become transparent due to some improper styling. You only have to take that white card back.
