### ISSUE TITLE
Pasword confirmation should send back a confirmation email.

### ISSUE THREAD

**Issue by Obtin** [Cloud-CV/EvalAI#1429]
- the expected behavior:
   - After the password reset process, a confirmation email stating "your password has been successfully      reset" should be sent to the user.
   - The user should be informed about expired session of the reset link as soon as the link is clicked.

- the observed behavior:
   - After the password reset process no confirmation email is sent to the user.
   - The user is allowed to open the password reset link, enter his/her credentials and after submitting it shows error of session expired.
![evaaiissue](https://user-images.githubusercontent.com/25207205/34463509-f6148ef6-ee83-11e7-9f1c-b78502f7632b.png)

Would you like to take this issue?
Yes

Thanks!

**Comment by aka-jain** [comment]
@Obtin so we can't stop user to use that expired or already used link. But we can add this information to the reset password mail description. Also, password reset confirmation is a good feature, we can implement this.
So, go ahead assigning this to you.

**Comment by Obtin** [comment]
@aka-jain though we can't stop him, but after a particular interval rather than directing it to the "reset password" template we can direct him to a template like:
![image](https://user-images.githubusercontent.com/25207205/34464142-8331f3f4-ee99-11e7-9e92-d3a5635f21e6.png)
Indeed a better one!! :-)

**Comment by aka-jain** [comment]
Agree, start working on it.

**Comment by aka-jain** [comment]
@Obtin Please complete your pending PRs then start working on this.
Till then I'm opening this issue for others.

**Comment by viditjain08** [comment]
Hey, can I take this issue?

**Comment by Obtin** [comment]
@aka-jain is the issue still assigned to me

**Comment by aka-jain** [comment]
No @Obtin, work on your PR first and I think I have already assigned a new task to you.
@viditjain08 you can work on this. Assigning this to you.

**Comment by deshraj** [comment]
We have decided to not move with this feature. If someone is still interested in working on this feature, please feel free to reopen and comment on this issue thread.
