### ISSUE TITLE
Combine frontend and backend servers

### ISSUE THREAD

**Issue by viditjain08** [Cloud-CV/EvalAI#1430]
@RishabhJain2018, @aka-jain  
Currently, the frontend and the backend are hosted on different servers.
But the frontend can be hosted on the backend server.

**Comment by viditjain08** [comment]
Can I take this issue?

**Comment by aka-jain** [comment]
We did this intentionally so to make Frontend independent of Backend. This will reduce the efforts of developers as dependency on each other. 
@deshraj though we have already discussed it but still what do you think?

**Comment by viditjain08** [comment]
But this can be extended to include both options- individual servers or a combined server.

**Comment by aka-jain** [comment]
@deshraj need your thoughts here.

**Comment by deshraj** [comment]
> But this can be extended to include both options- individual servers and a combined server.

@viditjain08 can you please elaborate on this statement? I didn't get this statement exactly.

**Comment by viditjain08** [comment]
gulp dev:runserver hosts the frontend but another setting can be added in gulpfile which can host the frontend stuff on backend server by transferring it to static, so heroku deployment problem is solved

**Comment by aka-jain** [comment]
Yes we can, but for this we also have to integrate Angular with Django. You can work on this. Assigning this to you @viditjain08 
@deshraj if we can do this then I think we can combine our production servers. Let's see the approach of @viditjain08 then will decide it later.

**Comment by deshraj** [comment]
As per the discussion in #1339 , we are not going with this approach. So, I am closing this issue.
