### ISSUE TITLE
Update Text 

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#1456]
## Observed Behaviour

1. The Gitter link is not highlighted and there is no Github link to the repository.

![issue](https://user-images.githubusercontent.com/24366008/34860412-38decd3e-f783-11e7-8f2f-a37c2839b526.JPG)

2. The Information under "What is EVALAI?" is less.

## Expected Behaviour

1. Making the Gitter link highlighted by blue colour and linking the Github repository

2. Addition of information about EvalAI.

## Would you like to work?

Yes.

@RishabhJain2018 @aka-jain

**Comment by aka-jain** [comment]
Hi @gautamjajoo, if you are still working on it then please let us know. Also, in case of any help regarding procedure or workflow you can ask anytime.

**Comment by aka-jain** [comment]
Fixed here #1454
