### ISSUE TITLE
Wrong Link in PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#1461]
### Observed Behaviour
There is no valid link for style rules in PULL_REQUEST_TEMPLATE.md.

![style](https://user-images.githubusercontent.com/24366008/34891079-38fe93c2-f7fa-11e7-9ad8-343c51a0a52b.JPG)

### Expected Behaviour
Remove the link.

@aka-jain @RishabhJain2018

**Comment by spyshiv** [comment]
@gautamjajoo : To fix this issue replace current link with updated link in `PULL_REQUEST_TEMPLATE.md`

Current link: `https://github.com/Cloud-CV/EvalAI/blob/master/CONTRIBUTING.md#style-rules`
Updated link: `https://github.com/Cloud-CV/EvalAI/blob/master/.github/CONTRIBUTING.md#style-rules`
