### ISSUE TITLE
Linking organization images

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#1466]
### Observed Behaviour

Images of several partner organizations who have already hosted their challenges on EvalAI.

### Expected Behaviour

Linking images of several partner organizations who have already hosted their challenges on EvalAI with their website.

@RishabhJain2018 @aka-jain @spyshiv

**Comment by Anupam-dagar** [comment]
@gautamjajoo i would like to work on this

**Comment by deshraj** [comment]
Closing this since we have intentionally not added the links to the organizations. It's by design choice. :)
