### ISSUE TITLE
Fix text "stars" inside the box in footer.

### ISSUE THREAD

**Issue by Arun-Jain** [Cloud-CV/EvalAI#1473]
Currently the text "stars" are not in the correct position in dashboard-footer.
![screenshot from 2018-01-17 05-29-50](https://user-images.githubusercontent.com/16155501/35005493-8547bb9c-fb19-11e7-8aa9-6f84e607fad8.png)

Make it as same as in landing-footer.
![screenshot from 2018-01-17 05-14-14](https://user-images.githubusercontent.com/16155501/35004796-5c8bd01e-fb17-11e7-9977-0a6b1dff8ed2.png)

@deshraj @aka-jain @RishabhJain2018  can i take this up.

**Comment by gautamjajoo** [comment]
![correct](https://user-images.githubusercontent.com/24366008/35043503-e51baaf8-fbb2-11e7-9542-b759d1120b49.JPG)

In Google Chrome it is working correctly!! @Arun-Jain

**Comment by Arun-Jain** [comment]
@gautamjajoo Please check it once in dashboard footer.
check this link : https://evalai.cloudcv.org/web/dashboard

**Comment by gautamjajoo** [comment]
@Arun-Jain Its the same.

**Comment by Arun-Jain** [comment]
@gautamjajoo can you please check it one more time in desktop view rather than mobile view.
Make it sure that you are logged in and let me know if everything is perfect on your side.

![screenshot from 2018-01-18 01-44-39](https://user-images.githubusercontent.com/16155501/35048477-38800a94-fbc3-11e7-8641-6ab892d5f516.png)

**Comment by aka-jain** [comment]
Yes, this problem is coming randomly. Let me check it once from my side. @Arun-Jain @gautamjajoo

**Comment by aka-jain** [comment]
@Arun-Jain can you please try to increase the width of this button a little bit? Please let me know if this issue still exist.

**Comment by Arun-Jain** [comment]
Sure @aka-jain. I'll try to fix this.

**Comment by deshraj** [comment]
Fixed in #1373
