### ISSUE TITLE
Text "Taking you to EvalAI" is not visible at the time of login.

### ISSUE THREAD

**Issue by Arun-Jain** [Cloud-CV/EvalAI#1475]
Change the color of text to make it visible.
![screenshot from 2018-01-18 03-15-59](https://user-images.githubusercontent.com/16155501/35053557-72f55348-fbd0-11e7-9c53-2525f86f24d7.png)

**Comment by aka-jain** [comment]
@Arun-Jain let me know once you are done with this.

**Comment by Arun-Jain** [comment]
Sure @aka-jain
