### ISSUE TITLE
Frontend: Change hyperlink in info provided in create challenge with zip file

### ISSUE THREAD

**Issue by spyshiv** [Cloud-CV/EvalAI#1477]
![screenshot from 2018-01-18 19 46 17](https://user-images.githubusercontent.com/7015220/35102548-3cef2800-fc89-11e7-8ade-72b377cdd01a.png)

In the screenshot, On clicking `here` the relevant part of `EvalAI Documention` should be open. So need to update `current link` with `updated link`

`current link`: https://evalai.readthedocs.io/en/latest/
`updated link`: https://evalai.readthedocs.io/en/latest/challenge_creation.html#challenge-creation-using-zip-configuration

**Comment by Arun-Jain** [comment]
@spyshiv can i work on this?

**Comment by RishabhJain2018** [comment]
@Arun-Jain Yes Sure!

**Comment by Arun-Jain** [comment]
@deshraj Close this. Fixed in #1478

**Comment by deshraj** [comment]
Thanks @Arun-Jain for letting me know.
