### ISSUE TITLE
My Host Teams is always displayed 0

### ISSUE THREAD

**Issue by viditjain08** [Cloud-CV/EvalAI#1479]
In the dashboard, the user's "My Host Teams" is always 0, even if he has created host teams
![screenshot from 2018-01-18 22-28-17](https://user-images.githubusercontent.com/5248993/35111248-d33a3e1e-fca0-11e7-984e-889e4d8bc0e8.png)
![screenshot from 2018-01-18 22-39-27](https://user-images.githubusercontent.com/5248993/35111249-d3a94336-fca0-11e7-9e30-612dc87d8bec.png)

I would like to take this issue.

**Comment by isht3** [comment]
@viditjain08 It seems to be working for me.

**Comment by viditjain08** [comment]
@isht3 I checked it locally and on evalai.cloudcv.org as well, and I am not seeing any increment in MY HOST TEAMS. Can you send a screenshot?

**Comment by gautamjajoo** [comment]
It works fine for me also!!
![host](https://user-images.githubusercontent.com/24366008/35141004-5a75f976-fd1f-11e7-821c-e2d2585c1436.JPG)

**Comment by viditjain08** [comment]
Ok, must be something wrong with my pc.
