### ISSUE TITLE
Create empty challenge

### ISSUE THREAD

**Issue by viditjain08** [Cloud-CV/EvalAI#1481]
- When a user goes to the create a challenge and clicks on the upload button without adding anything, the loading bar gets stuck on the screen
![screenshot from 2018-01-20 21-14-00](https://user-images.githubusercontent.com/5248993/35185254-3e591440-fe27-11e7-950e-e464c5a98fb1.png)

I would like to take this issue.

**Comment by aka-jain** [comment]
You working on this @viditjain08 ?

**Comment by viditjain08** [comment]
Yes, it's just a small change.
