### ISSUE TITLE
Incorrect error display in many cases

### ISSUE THREAD

**Issue by codervivek** [Cloud-CV/EvalAI#1483]
In most of the error display messages present in frontend controllers, response.data returns a HTML string of Django error page and not a json. However, many error messages are present which try to print the HTML string or try to access the string like a js object. I opened an issue #1458 due to above problem. Since I am new to the repo I am not able produce many similar issue but it seems to be a major problem. Can someone please review the controllers part and tell me if this is really a problem?

**Comment by deshraj** [comment]
Closing this issue since we will deprecate the current frontend code as we are working on the new frontend of EvalAI.
