### ISSUE TITLE
Add support for Python3.X

### ISSUE THREAD

**Issue by dibyadas** [Cloud-CV/EvalAI#1497]
## Description
 Considering that Python 2 will no longer be maintained past 2020.
Also, Python 3.6 has native support for asynchronous programming, which can be very useful in the case of EvalAI.
## Deliverables
Check for Python 3 support for EvalAI and discuss the roadmap of supporting both the versions of python

**Comment by deshraj** [comment]
@dibyadas: Yes, we have planned to add support for Python 3.x. Please feel free to work on this if you are interested.

**Comment by dibyadas** [comment]
Sure. Will do!  Will work on this after my tests are over.

**Comment by deshraj** [comment]
Sounds good. Thanks for letting us know.

**Comment by Balance-Breaker** [comment]
@deshraj I want to take this issue. Can you guide me where to get started.

**Comment by Yatish04** [comment]
I would like to work on this. Is there any branch for this @deshraj

**Comment by RishabhJain2018** [comment]
@Yatish04 Yes you can work on it. No there isn't any branch for it, you can fork the repo and then start working on a new branch. Please feel free to ping us if you have doubts or queries.

**Comment by ParthS007** [comment]
@dibyadas are you still working on this or I can take this up ? 
If you are working on this , can we collaborate ? Please let me know :+1:

**Comment by dibyadas** [comment]
Hey @ParthS007 !  Unfortunately, my exams are going on, so I was unable to work on this. Great that you are interested. Please go ahead on this one. So sorry that I did not inform earlier. It seems @Yatish04 is working on this. Just ask him before proceeding. :smile:

**Comment by ParthS007** [comment]
@dibyadas I have updated my previous comment :+1: , Thanks for responding so quickly. @Yatish04  waiting for your response :smiley:

**Comment by siddharth185** [comment]
Hey I also started working on this. I made some progress - https://github.com/siddharth185/EvalAI/tree/port_python3 using Futurize. The dependencies blocking python3 are - `asgiref (which is blocking asgi-redis) django-rest-auth recommonmark uwsgi` Can collaborate if anyone wants :)

**Comment by Ramtingh** [comment]
django-rest-auth asgiref and uwsgi are actually compatible with python3, it seems like a glitch with PyPi not listing their compatible versions. pip will still install them correctly.
I'm not entirely sure about recommonmark, but it looks like its also compatible.

**Comment by Yatish04** [comment]
@ParthS007 feel  Free to work on this. We both can work on this

**Comment by chrustkiran** [comment]
I'm very much interested in this, but I need someone to guide me, what should I do ?

**Comment by deshraj** [comment]
Similar to #1681. Closing it.
