### ISSUE TITLE
Updating Team in README

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#1499]
## Observed Behaviour 

![capture2](https://user-images.githubusercontent.com/24366008/35666940-e45a91b0-0751-11e8-876f-7e6d6402fc16.JPG)

## Expected Behaviour - Better Representation

![capture](https://user-images.githubusercontent.com/24366008/35666966-f74e978a-0751-11e8-9d44-7adf7958ad01.JPG)

@aka-jain @deshraj @RishabhJain2018  @spyshiv

**Comment by HargovindArora** [comment]
@gautamjajoo This looks good. This should be done. What do you say @RishabhJain2018?
