### ISSUE TITLE
Making UI of Email Invite on dashboard better

### ISSUE THREAD

**Issue by Obtin** [Cloud-CV/EvalAI#1503]
This is in continuation with Issue #552. 
![image](https://user-images.githubusercontent.com/25207205/35684292-6d5c8cd6-078c-11e8-9c73-46ec7018fb9b.png)

**Comment by gautamjajoo** [comment]
@Obtin Hey I was using this feature but I didn't receive any email. I got the successful message too. Is the feature not working?

**Comment by anweshknayak** [comment]
@gautamjajoo I think it is in progress.

**Comment by deshraj** [comment]
This issue is invalid now. Hence closing it.
