### ISSUE TITLE
My Submissions Page

### ISSUE THREAD

**Issue by viditjain08** [Cloud-CV/EvalAI#1514]
1. For any challenge, the participant is unable to download all submissions by selecting csv and clicking download button.

2. Also, the submission count remains 0 even if a submission is present.
![screenshot from 2018-02-06 09-38-33](https://user-images.githubusercontent.com/5248993/35841428-f5c11ba8-0b21-11e8-8d65-7712808f28c5.png)
 I would like to take this issue

**Comment by aka-jain** [comment]
Thanks for pointing out this bug @viditjain08.
You can work on this.

**Comment by deshraj** [comment]
This issue is already fixed in #1582
