### ISSUE TITLE
Images should not be draggable

### ISSUE THREAD

**Issue by anweshknayak** [Cloud-CV/EvalAI#1517]
- the expected behaviour
  Images of cloud,rocket should not be draggable

- the observed behaviour
  Certain images are draggable

- steps to reproduce the problem
 Drag the clouds off-screen. 

- which operating system and/or browser you're using, if relevant
 Firefox Quantum
 Ubuntu 16.04

![cloud](https://user-images.githubusercontent.com/8139783/35886580-893c45f2-0bb7-11e8-988d-5caef2952192.gif)

**Comment by anweshknayak** [comment]
@aka-jain is this legit issue?
`<img draggable="false" img>` happens to solve this.

**Comment by deshraj** [comment]
This issue is not valid now since we are moving to Cloud-CV/evalai-ngx
