### ISSUE TITLE
UX Improvements for mobile/tablet view

### ISSUE THREAD

**Issue by anweshknayak** [Cloud-CV/EvalAI#1520]
![mobile](https://user-images.githubusercontent.com/8139783/35913004-52d9e204-0c24-11e8-8c4b-c8babc1231f5.gif)

- For Landing Page 
Okay we can make just one button like **Register and Log In**  as in above. And rest as shown we can show as a menu or dropdown. 

Current view : 
![current](https://user-images.githubusercontent.com/8139783/35913254-12889406-0c25-11e8-8f14-3bba98a574b0.gif)

takes too much space

**Comment by aka-jain** [comment]
Okay, we can do this.
You working on this? @anweshknayak

**Comment by anweshknayak** [comment]
Sure @aka-jain

**Comment by anweshknayak** [comment]
Seems like there are more bugs
![bug_responsive](https://user-images.githubusercontent.com/8139783/35924855-3648546a-0c4a-11e8-9625-1eb3e7f8d686.gif)

**Comment by anweshknayak** [comment]
@aka-jain Would it be good if I include this in GSOC proposal? I will have the mock-ups ready before the proposal period. There are certain bugs. I plan to revamp it completely. Sounds good?

**Comment by deshraj** [comment]
@anweshknayak: this doesn't seem like a lot of work. I would recommend you to fix the bugs beforehand and mention the Pull Requests link in your proposal instead of just listing the idea. Also, since revamping to Angular 5 is not a trivial task and will require a lot of time, so it's better to fix the existing bugs.

**Comment by gautamjajoo** [comment]
@anweshknayak Hey!! Are you on it?

**Comment by anweshknayak** [comment]
No. You can do this if you want to

**Comment by deshraj** [comment]
This issue is not valid now since we are moving to Cloud-CV/EvalAI-ngx. Thanks for opening this @anweshknayak though :)
