### ISSUE TITLE
Scroll-bar overlapping with footer in firefox

### ISSUE THREAD

**Issue by anweshknayak** [Cloud-CV/EvalAI#1521]
If you'd like to report a bug, please include the following information:
- the expected behaviour
  Scroll bar should not overlap

- the observed behaviour
 Scroll overlapping with footer

- steps to reproduce the problem
 Log in -> Dashboard -> Scroll

- which operating system and/or browser you're using, if relevant
  Firefox Quantum
  Ubuntu 16.04

![scrollbar_overlap](https://user-images.githubusercontent.com/8139783/35925065-c4012ab6-0c4a-11e8-8b79-0a19145d5a2a.gif)

**Comment by deshraj** [comment]
Thanks @anweshknayak for opening this issue. Please feel free to work on this issue.

**Comment by spyshiv** [comment]
@anweshknayak Any Update on this? Let me know if you need any help

**Comment by anweshknayak** [comment]
@spyshiv I am going to start on this :smile:. Will let you know if I need any help. Thanks :tada:

**Comment by deshraj** [comment]
This issue is already fixed. Closing it.
