### ISSUE TITLE
clicking on `view more`of VQA challenge leads to permission denied page 

### ISSUE THREAD

**Issue by rupav** [Cloud-CV/EvalAI#1524]
_Thanks for taking the time to report a bug in the EvalAI project, or propose a new feature! Before creating a new issue, please do a quick search to check that it hasn't already been filed on the [issue tracker](https://github.com/Cloud-CV/EvalAI/issues)._

If you'd like to report a bug, please include the following information:
- the expected behaviour
Reason for permission denied if any
- the observed behaviour
![screenshot 2018-02-09 11 27 30](https://user-images.githubusercontent.com/20624380/36013989-7b8943a6-0d8d-11e8-9a1b-48ce44222122.png)
- steps to reproduce the problem
go to https://evalai.cloudcv.org/, then scroll down to bottom and click `view more` of VQA challenge
- which operating system and/or browser you're using, if relevant
windows 10, firefox, I am logged in while experiencing this behaviour

Thanks!

**Comment by Obtin** [comment]
@rupav, We have already started working on it, please have a look at #1337.  Do let me know if I am wrong. Thank you for your contribution :-).

**Comment by rupav** [comment]
@obtin although page denied is more or like the same , But I have verified my account and then I am getting the error. Please see steps to reproduce the problem I mentioned.

**Comment by Obtin** [comment]
@rupav yes you are right. Have you started working on it? If not I would like to fix this. Thank you.
