### ISSUE TITLE
Permission denied: '/tmp/logfile'

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1529]
The submission worker currently faces the problem of permission denied due to the dependency on `/tmp/logfile`. Here is the error log:

```
(EvalAI) 137 ubuntu@staging-evalai:~/Projects/EvalAI⟫ python scripts/workers/submission_worker.py settings.prod
Traceback (most recent call last):
  File "scripts/workers/submission_worker.py", line 44, in <module>
    django.setup()
  File "/home/ubuntu/.virtualenvs/EvalAI/local/lib/python2.7/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/home/ubuntu/.virtualenvs/EvalAI/local/lib/python2.7/site-packages/django/utils/log.py", line 75, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python2.7/logging/config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 576, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'logfile': [Errno 13] Permission denied: '/tmp/logfile'
```

**Comment by isht3** [comment]
@deshraj Shall I look into it?

**Comment by deshraj** [comment]
@isht3: sure, go ahead.

**Comment by isht3** [comment]
@deshraj  How do I reproduce the error?

**Comment by anweshknayak** [comment]
@isht3` python scripts/workers/submission_worker.py settings.prod `
check the first line @deshraj has posted

**Comment by isht3** [comment]
@anweshknayak I missed the settings.prod part :rofl:, thanks for pointing it out.

**Comment by isht3** [comment]
@deshraj @anweshknayak Is there any prerequisite installation required before running the production server? I'm getting a `ImportError: No module named raven` error.

**Comment by anweshknayak** [comment]
@isht3 yep `pip install raven` would do. Check https://github.com/Cloud-CV/EvalAI/pull/517

**Comment by isht3** [comment]
@anweshknayak All the dependencies are taken care off but when I run `python scripts/workers/submission_worker.py settings.prod` it's just stuck, no progress, no errors, no anything. Any ideas?
