### ISSUE TITLE
Add support for changing Participant Team Name

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1536]
Currently, we don't provide support for editing the participant team name on UI. We would like to add a support for this.

**Comment by isht3** [comment]
Can I take this up? 😄

**Comment by deshraj** [comment]
@isht3 sure. This needs to be done quickly. Please take it if you are sure that you can get it done quickly. 

Also, FYI: I have a deadline this friday so I will be able to look at the pending Pull requests after that only.

**Comment by isht3** [comment]
@deshraj Okay, that sounds good! I'll do it in 24 hours.
