### ISSUE TITLE
edit-details dialog box should disable submit button when no changes are made

### ISSUE THREAD

**Issue by Obtin** [Cloud-CV/EvalAI#1548]
- **the expected behavior**
The edit-challenge dialog box submit details buttons should be enabled only when changes are made.

- **the observed behavior**
At present even though no changes are made the successful edition message appears.

![message](https://user-images.githubusercontent.com/25207205/36854237-8103d882-1d96-11e8-9df2-bb57fcf21f56.png)

Would you like to work on this?
Yes.

**Comment by spyshiv** [comment]
@Obtin assigning this to you. Go ahead

**Comment by gautamjajoo** [comment]
@Obtin Are you working on it? If not, can I work.

**Comment by RishabhJain2018** [comment]
No @sachinmukherjee you can go ahead if you want. :)

**Comment by deshraj** [comment]
This issue is not valid now since we are moving to Cloud-CV/EvalAI-ngx
