### ISSUE TITLE
UI Improvements in Leaderboard

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1552]
- [ ] Make the team name as **Bold** on leaderboard.

- [ ] Make `Rank` and `Participant Team` field as left aligned including the title.

- [ ] Make all the other fields as right aligned including the title.

- [ ] In the heading `submission time`, change the text to `Last Submission at` & display the delta between the current time and the last submission time. For Example: If the current time is 10 am, & last submission was made at 6 am, then the field should display `4h` (10am - 6am).

- [ ] Add a border line after every entry in the leaderboard.

Please feel free to ask if you have further doubts or queries.

**Comment by ParthS007** [comment]
I want to work on this @RishabhJain2018

**Comment by RishabhJain2018** [comment]
Sure go ahead @ParthS007 .

**Comment by ParthS007** [comment]
@RishabhJain2018 Now the leaderboard looks like this.
![image](https://user-images.githubusercontent.com/24358501/37252355-c3e3be86-2545-11e8-9d7a-97fd20c18f0f.png)
Can you please help me with the 4th point?

**Comment by RishabhJain2018** [comment]
@ParthS007 There are other fields `(yes/no, number, other, overall)` too in the right side of the screenshot. Please don't remove them. Just make them right aligned. Also, the border line after every entry is very dark. Make it similar to the one just after the heading. 
Moreover, in the fourth point we need to display the time difference between now and when the last submission was made. I think this can be easily handled client side and we don't need to modify the API. Please feel free to ask if you have further doubts.

**Comment by RishabhJain2018** [comment]
@ParthS007 Since we need this feature early, I am taking this up. Please take up any other issue from the list. :-)
