### ISSUE TITLE
Docker build: cannot access frontend content

### ISSUE THREAD

**Issue by schomatis** [Cloud-CV/EvalAI#1563]
I'm trying to reproduce the [Docker build instructions](https://github.com/Cloud-CV/EvalAI#using-virtual-environment) in an Ubuntu 16.04 system. The containers are being built correctly, I can connect to the backend (port 8000) and see the "Hello world", but when I connect to the frontend (port 8888) I always get an 404 error, the container is indeed active and responding but I can't access the web content, is there some configuration I'm missing?

```
git clone https://github.com/Cloud-CV/EvalAI.git evalai && cd evalai
cp settings/dev.sample.py settings/dev.py
docker-compose -f docker-compose.dev.yml up -d --build
```

**Comment by deshraj** [comment]
@schomatis can you please paste the screenshot of the error that you are facing?

**Comment by deshraj** [comment]
@schomatis did you try opening it in your browser? Please let me know if the issue persists on the browser.

**Comment by anweshknayak** [comment]
@deshraj many people are facing this problem as per communication in gitter channel.

**Comment by schomatis** [comment]
@deshraj Yes, the issue persists on my browser. Both Firefox and Chrome failed to retrieve the web page.

**Comment by jheguia** [comment]
I have a similar problem. I'm getting this on Chrome (this is the source, of course):

<!DOCTYPE html>
  | <html lang="en">
  | <head>
  | <meta charset="utf-8">
  | <title>Error</title>
  | </head>
  | <body>
  | <pre>Cannot GET /</pre>
  | </body>
  | </html>

**Comment by deshraj** [comment]
Thanks for reporting. I will test this on my machine and see if the problem persists.

**Comment by jheguia** [comment]
In the docker file for nodejs, the command line for gulp is "gulp connect", whereas in the instructions for using virtualenv the command line is "gulp dev:runserver". I tried changing the gulp command line in the docker file to dev:runserver and it seems to be working. Could that be the problem?

**Comment by deshraj** [comment]
@jheguia Yeah it seems like that is the cause of this issue. I am trying to reproduce the error.
