### ISSUE TITLE
Grammatical errors in E-mail Address confirmation e-mail

### ISSUE THREAD

**Issue by tashachin** [Cloud-CV/EvalAI#1569]
Hi! I'm new to programming and am still relying on manual testing.

I signed up for EvalAI and here is the e-mail I received:
![screen shot 2018-03-16 at 2 22 07 pm](https://user-images.githubusercontent.com/27714199/37545406-efe9f840-2925-11e8-8f88-01d8edc18e5e.png)

I'd be happy to draft up a new confirmation message that's less impersonal and reads better to native speakers.

**Comment by deshraj** [comment]
@tashachin: That would be great. We would love to see a better confirmation email. Feel free to share once you have the new message. :)

**Comment by tashachin** [comment]
I'd like to fork the repo and update the code directly. In which file would I find the confirmation message? (I haven't worked with an email API before, so unfortunately it's not very intuitive for me to know where to look.)

**Comment by deshraj** [comment]
You can find all the email related templates here: https://github.com/Cloud-CV/EvalAI/tree/master/apps/accounts/templates/account
