### ISSUE TITLE
Update Mapillary logo on main page

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1589]
The current Mapillary logo on the main page has to be updated with the one given below:

![mapillary](https://user-images.githubusercontent.com/2945708/37746707-e30b6872-2d51-11e8-8abc-6db410116809.png)

The current logo seems to be squished. Please paste the screenshot of the updated home page while submitting a pull request.

**Comment by deshraj** [comment]
Edit: instead of using Mapillary's logo, we would like to update it with Mapillary Research's logo shown below.

![mapillary_research](https://user-images.githubusercontent.com/2945708/37758078-57e90b12-2d85-11e8-9629-0af484194435.png)

**Comment by RishabhJain2018** [comment]
@geekayush Sure go ahead!

**Comment by gautamjajoo** [comment]
@geekayush Can I work on this issue, if you are not working??

**Comment by RishabhJain2018** [comment]
@gautamjajoo It seems @geekayush is inactive these days, so you can take this up :). Feel free to open a PR once it's done.
