### ISSUE TITLE
Add Random Number Generator Challenge zip file and documentation

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1590]
I have created a new sample challenge named `Lucky Challenge 2018` which we will use as a base challenge so that other challenge hosts can take inspiration from this. 

## What this challenge is about?

This challenge is a simple challenge which generates a random number between 1 and 100 for each entry and whosoever is lucky gets a good random number and reaches the top of the leaderboard. More details can be found in the evaluation script present in the challenge configuration file : [challenge_config.zip](https://github.com/Cloud-CV/EvalAI/files/1836558/challenge_config.zip)

## Deliverables 

- [x] Upload the challenge configuration zip file in the `examples/` directory (challenge configuration file: 
[challenge_config.zip](https://github.com/Cloud-CV/EvalAI/files/1836558/challenge_config.zip))
- [x] Add the challenge to the seed script so that this challenge gets created once we run the seed command `python manage.py seed`
- [x] Add documentation for walking through creating this Challenge (if you need help with writing documentation for this, feel free to comment on this issue thread)

Let us know if you have suggestions for this task.

**Comment by psushaanth23** [comment]
Can I start working on this?

**Comment by deshraj** [comment]
@psushaanth23 sure, go ahead.

**Comment by ezavesky** [comment]
In trying to reuse this file (or the [example in the repo](https://github.com/Cloud-CV/EvalAI/blob/master/examples/example1/test_zip_file.zip)) on the the main website (evalai.cloudcv.org), I get the error...
```
There are more than one YAML files in zip folder!
```
Are there any alternate challenge examples?

**Comment by ezavesky** [comment]
@deshraj Thank you for the quick note and patience. I confirm that the spurious directory was the issue above.

**Comment by niranjani23** [comment]
Is this issue still open?

**Comment by deshraj** [comment]
This issue is already fixed. Hence closing it.
