### ISSUE TITLE
Notify EvalAI Admin upon any contact message

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1594]
The EvalAI admin should get a notification via email as well as a slack message whenever any user submits contact query.

**Comment by isht3** [comment]
@RishabhJain2018 @deshraj Can I take up this issue?

**Comment by deshraj** [comment]
@isht3 I think Rishabh has already solved this one. Feel free to  take up some other issue.

**Comment by isht3** [comment]
@deshraj Okay!

**Comment by deshraj** [comment]
@isht3 Can you please finish this issue? It seems to be very trivial for you. ;)

**Comment by Ayukha** [comment]
@RishabhJain2018  Is this issue still open?

**Comment by yashdusing** [comment]
@RishabhJain2018 I could extend my PR to write about both of them. So, is this issue still open ?

**Comment by RishabhJain2018** [comment]
This is already implemented, hence closing this.
