### ISSUE TITLE
Export challenge data in different formats.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1602]
**Description:** Currently EvalAI supports exporting the submissions using csv only, but we want to extend this support to `json`, `xlsx`, `xls`, `yaml`, `html` .

**Comment by sachinmukherjee** [comment]
I want to work on this issue.

**Comment by RishabhJain2018** [comment]
sure! go ahead.

**Comment by yashdusing** [comment]
@RishabhJain2018 @deshraj If this hasn't been implemented yet, I would like to work on it

**Comment by RishabhJain2018** [comment]
No, it isn't. You can work on it.

**Comment by yashdusing** [comment]
While approving a challenge, reload won't work since docker-compose doesn't have any reload command. I tried restart with evalai_worker_1 (the name that was alloted by me to the container) but after restarting the worker, it won't display the new challenge

**Comment by yashdusing** [comment]
I am finished with the json part. Is this the output desired ? @RishabhJain2018 
`{
  "0": {
    "Team Name": "Host_54476_Team",
    "Method Name": "null",
    "Status": "failed",
    "Execution Time(sec.)": 0.020239,
    "Submission Number": 2,
    "Submitted File": "http://localhost:8000/media/submission_files/submission_9/279a81a4-22c6-433a-a3eb-6cf88bdd3706.txt",
    "Stdout File": "http://localhost:8000/media/submission_files/submission_9/0cc12e49-c9a6-4fcc-96d3-0dbf5a754b92.txt",
    "Stderr File": "http://localhost:8000/media/submission_files/submission_9/07cfb4c2-ae65-4156-a906-e5dbc47c9f6c.txt",
    "Submitted at": "2018-12-05T19:03:52.779Z"
  },
  "1": {
    "Team Name": "Host_54476_Team",
    "Method Name": "",
    "Status": "failed",
    "Execution Time(sec.)": 0.028109,
    "Submission Number": 1,
    "Submitted File": "http://localhost:8000/media/submission_files/submission_7/6c2c43f5-51b3-403d-984d-b72d49bcf881.txt",
    "Stdout File": "http://localhost:8000/media/submission_files/submission_7/102c4c4c-aebb-403f-beb6-400b4a6abd8b.txt",
    "Stderr File": "http://localhost:8000/media/submission_files/submission_7/177a6799-fe04-442c-9bba-419e7c45eb7c.txt",
    "Submitted at": "2018-12-05T19:00:51.634Z"
  }
}`

**Comment by yashdusing** [comment]
HTML is done as well. Please confirm if everything's okay . 
Also, do I also need to inject/apply styling to the html as well or base is okay ?
![screenshot_20181207_011718](https://user-images.githubusercontent.com/19976688/49608124-e3c0d200-f9bd-11e8-87cf-e7628a4a4280.png)

**Comment by RishabhJain2018** [comment]
Thanks @yashdusing for the PR. I'll review it by today.

**Comment by RishabhJain2018** [comment]
Hi @yashdusing 
> While approving a challenge, reload won't work since docker-compose doesn't have any reload command. I tried restart with evalai_worker_1 (the name that was alloted by me to the container) but after restarting the worker, it won't display the new challenge
I didn't get this point very clearly here. What do you want to ask? if you are looking for approving a challenge and reloading a submission worker then are the docs https://evalai.readthedocs.io/en/latest/approve_challenge.html

> I am finished with the json part. Is this the output desired ?
How are outputs structured? Ascending order or descending order. Also, What does 0, 1 signify there?

> HTML is done as well. Please confirm if everything's okay .
Also, do I also need to inject/apply styling to the html as well or base is okay ?
Can you please briefly tell why do we need this HTML file. Am I missing some context here?

**Comment by RishabhJain2018** [comment]
>I followed the given link for approving. In the second step it has an instruction ‘docker-compose reload worker’. This command doesn’t work (I searched for reload for docker-compose on google and couldn’t find any such commands)
(Edit : I tried ‘restart’ instead because that’s the only other instruction I found which seems similar but it won’t work as well)

Thanks for pointing it out. Since we have removed the container name from docker compose file, that's why it didn't work. I will update the documentation for it. for now you can use:
1. `docker ps` : It will list all the running containers
2. Copy the cointainer ID of worker container.
3. Run `docker stop <container_id>`
4. Run `docker start <container_id>`

> They are structured according to their index which starts from 0. The ‘0’, ‘1’ signify the indices of the submissions table.

Just to confirm, you meant how they are structured under My Submissions table. If that is a case then can we please start from `1`. `O` looks confusing on user's end.

> The task is to code the support for exporting in HTML, JSON, xlsx, xls, yaml formats. The outputs I’ve posted are the results of the formats which I’ve currently coded (i.e. HTML and JSON)

I see. I think having HTML as output downloadable file won't be of greater use since most people will prefer JSON or CSV over it. What are your views?

**Comment by yashdusing** [comment]
@RishabhJain2018 could you tell me about the extensions needed ? Do we need xlsx, xls, yaml or not ?

**Comment by yashdusing** [comment]
For yaml, is this correct ?
![screenshot_20181210_201702](https://user-images.githubusercontent.com/19976688/49739746-a065ac80-fcb8-11e8-9440-080bd0d53b3f.png)

**Comment by yashdusing** [comment]
@RishabhJain2018 I was able to reload the worker fine and all approved were shown in the browser. But I can't submit any submissions, the phase button is frozen.
![download](https://user-images.githubusercontent.com/19976688/49740629-a6f52380-fcba-11e8-923a-2a3f4f250bec.png)

**Comment by yashdusing** [comment]
@RishabhJain2018 I added xlsxwriter to common.txt but I got this error
![screenshot_20181212_015013](https://user-images.githubusercontent.com/19976688/49827867-5e1f9680-fdb0-11e8-9795-0fb447d56f80.png)

**Comment by yashdusing** [comment]
[all_submissions.xlsx](https://github.com/Cloud-CV/EvalAI/files/2671405/all_submissions.xlsx)
Done with excel file. Please check the format

**Comment by yashdusing** [comment]
@rishabhjain2018 most of the PRs I made are now marked as stale but they were up for review

**Comment by RishabhJain2018** [comment]
Hi @yashdusing, Don't worry about it. I'll surely get to this and the other PR's in early July. Thanks for your patience.
