### ISSUE TITLE
Add embed leaderboard button 

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1604]
## Current Scenario

Currently, most of the challenge organizers maintain their own leaderboard when the challenge ends. For example, VQA 2017 challenge (http://visualqa.org/challenge_2017.html) manages their own leaderboard manually. We can make it better by having an embed leaderboard button on the leaderboard page. 

## Deliverables

- [ ] Add a button `Embed leaderboard` on the leaderboard of a challenge
- [ ] Make sure that the leaderboard is only shown when embedded. Navigation bar and other things are skipped when shown on a different webpage.

**Comment by nityanandagohain** [comment]
Hi can I work on this.

**Comment by RishabhJain2018** [comment]
Sure! You can work on this.

**Comment by RishabhJain2018** [comment]
@live-wire I am closing this issue here. Can you please open an issue for the same in EvalAI-ngx as we will need this functionality there.
