### ISSUE TITLE
Allow and block particular email domains for a challenge

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1606]
Currently, anyone can participate in a challenge. It would be great to have a functionality to allow/block only particular email domains to participate in a challenge as specified by the challenge host. 

## Deliverables

- [x] Add a field to Challenge model to store the `allowed_email_domains` (default=None, blank=True)
- [x] Add a field to Challenge model to store the `blocked_emails_domains` (default=None, blank=True)
- [ ] Update the challenge creation API to add support to incorporate `allowed_email_domains` and `blocked_email_domains`
- [ ] Update the Challenge creation using zip file documentation to add support for `allowed_email_domains`   and `blocked_email_domains`
- [ ] Update the challenge participation API to only allow `allowed_email_domains` and block `blocked_email_domains`

**Comment by isht3** [comment]
@deshraj @RishabhJain2018 Can I work on this?

**Comment by deshraj** [comment]
Yeah sure. Assigning this to you.

**Comment by isht3** [comment]
@deshraj for the `allowed_email_domains` and the other fields I should be using `ArrayField`, yes?

**Comment by deshraj** [comment]
Yes, you are right.

**Comment by isht3** [comment]
@deshraj, the front-end support for this is not yet required, yes?

**Comment by isht3** [comment]
@deshraj The last part of this issue is still remaining. I'll do it ASAP.

**Comment by deshraj** [comment]
You mean the last 3 parts, right?

**Comment by deshraj** [comment]
Please add all of these remaining things in a single Pull request.
