### ISSUE TITLE
Solve inconsistencies in the response handling for the front-end and back-end.

### ISSUE THREAD

**Issue by isht3** [Cloud-CV/EvalAI#1622]
# Current Scenario
Currently, there's a lot of inconsistencies in handling the various response messages on the front-end and on the back-end. 

* Error responses on controllers don't take in the response argument. `onError: function()` --> `onError: function(response)`
* Responses are not properly displayed. E.g `['Server error']` Which is vague and the user gets no feedback.
* Some responses are displayed in a list, which is a strike for the UI.

# Deliverables
* Try to make the success and the error responses from the back-end to be consistent with the Django and all-auth type responses.
* Make the success and error message display in the front-end to be clean and consistent all throughout the application.

**Comment by sachinmukherjee** [comment]
@isht3 Can you please tell me in which files we need to make changes?

**Comment by isht3** [comment]
@sachinmukherjee https://github.com/Cloud-CV/EvalAI/blob/d86a3924ee8506b6c70223b53f7fe954f87cc8fe/frontend/src/js/controllers/challengeCtrl.js#L1030 In this line you can see that the error pretty much reveals nothing useful the user. Ideally, it should be changed to something useful regarding what's causing the error. Also, the responses sent from the backend aren't displayed and formatted properly. You could also look into that.

**Comment by isht3** [comment]
@nagpalm7 Yes, definitely. You can take this issue up!
