### ISSUE TITLE
Installation Error on UBUNTU 16.04

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#1628]
When EvalAI is installated on UBUNTU 16.04, The webpage looks like below. 

![](https://files.gitter.im/Cloud-CV/EvalAI/Its0/Screenshot-from-2018-04-05-16-32-24.png)

![](https://files.gitter.im/Cloud-CV/EvalAI/MJq2/Screenshot-from-2018-04-05-16-32-15.png)

**Comment by spyshiv** [comment]
@gautamjajoo is there any error log in console/terminal ? If any, paste here.

**Comment by spyshiv** [comment]
And can you try frontend setup using updated `package.json` from PR #1639 and let me know the status

**Comment by gautamjajoo** [comment]
@spyshiv I have taken the latest pull, and here's the terminal window


![](https://files.gitter.im/sridharjajoo/yp1W/Screenshot-from-2018-04-10-01-01-15.png)


![](https://files.gitter.im/sridharjajoo/yp1W/Screenshot-from-2018-04-10-01-01-27.png)

**Comment by deshraj** [comment]
@gautamjajoo @ezavesky It seems like the error is fixed in #1639. After getting the latest changes, update your nodejs and npm to the latest version to get it to work. I am using node version 8.11.1 and npm 5.6.0 and it is working fine. Please let me know if this error is still not fixed.

**Comment by gautamjajoo** [comment]
@deshraj I am using node version 8.11.1 and npm 5.6.0, but I am facing the following issue while executing  ```npm install```

![image](https://user-images.githubusercontent.com/24366008/38541551-0997fda0-3cbd-11e8-9f2b-c75719f031ef.png)

**Comment by gautamjajoo** [comment]
@spyshiv @deshraj I think so #1645 will solve this error.

**Comment by deshraj** [comment]
Yes @gautamjajoo. Just 5 more minutes and then error will be resolved. :)
