### ISSUE TITLE
On Firefox browser, counter for host teams is not accurate

### ISSUE THREAD

**Issue by ezavesky** [Cloud-CV/EvalAI#1632]
Steps to reproduce, as tested on evalai.cloudcv.org (April 6, 2018)

1. Create login, go to dashboard
2. Head to "create challenge", create a team
3. Check the dashboard again, but no team count is present
4. NOTE: This is not an issue for participant teams.

![image](https://user-images.githubusercontent.com/12480297/38429365-be7dc08e-3983-11e8-9f11-16895b6c0706.png)

![image](https://user-images.githubusercontent.com/12480297/38429464-130a87d6-3984-11e8-8eac-d101402a6464.png)

**Comment by RishabhJain2018** [comment]
Hi @ezavesky I tested it and it seems to be working fine for me. Can you please try it again. Please feel free to ping us if you face issues in it.

**Comment by deshraj** [comment]
@ezavesky can you please also check the network tab on the browser console? You will see red colored API endpoint if there any error exists.

**Comment by ezavesky** [comment]
Very odd. It seems to work in Chrome (bottom) but not Firefox (top).  Please close or deprioritize as needed.

![image](https://user-images.githubusercontent.com/12480297/38436295-dcd0363c-3999-11e8-98ad-294af941e1b0.png)

**Comment by deshraj** [comment]
@ezavesky thanks for pointing out. It seems that the behavior that you mentioned is correct. After doing some debugging, it looks like Firefox is sending an `OPTIONS` request type instead of `GET` to fetch the challenge hosts teams hence this is the error. 

@spyshiv can you please look into this issue?

**Comment by spyshiv** [comment]
@deshraj I'm on it.

**Comment by supra08** [comment]
@RishabhJain2018 , is the issue still open? If yes, I would like to take it up.

**Comment by RishabhJain2018** [comment]
@supra08 Would you like to still work on it?
