### ISSUE TITLE
Add tests for challenge creation using zip file.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1641]
## Description
The unit tests for the function `create_challenge_using_zip_file` are missing in `apps/challenges/views.py`.

## Deliverables

- [ ] Add the required tests to increase the coverage.

**Comment by lenniezelk** [comment]
i'd like to work on this

**Comment by RishabhJain2018** [comment]
@lenniezelk Sure go ahead!

**Comment by lenniezelk** [comment]
i started writing a test but i ran into a problem. `zip_challenge.yaml` inside the sample zip `examples/example1/test_zip_file.zip` refers to `evaluation_script: data.py` which is missing in zip file. I found a `evaluation_script.zip` in the sample zip and renamed the `main.py` to `data.py` and created a new sample zip archive. On running test i get error: `{u'error': [u'The submitted data was not a file. Check the encoding type on the form.']}`. I am a bit stuck here. Any assistance is highly appreciated. @RishabhJain2018

**Comment by RishabhJain2018** [comment]
Please read the instructions [here](https://evalai.readthedocs.io/en/latest/challenge_creation.html#challenge-creation-using-zip-configuration) to create a sample zip archive, you need give the the path of evaluation script zip folder relative to the `yaml` file. So, please give the path as `evaluation_script.zip` and try running the tests again. Feel free to ask if you have any further questions.

**Comment by lenniezelk** [comment]
added a pr for this @RishabhJain2018
