### ISSUE TITLE
Configuring test settings for py.test.

### ISSUE THREAD

**Issue by isht3** [Cloud-CV/EvalAI#1655]
# Proposed changes.

* Adding `settings/test.sample.py`
* `cp settings/dev.sample.py settings/dev.py` and adding `dev.py` to .gitignore so that we don't have to stage the changes everytime we are running tests and commiting.
* Deciding between `py.test` and `pytest`.

**Comment by RishabhJain2018** [comment]
Closing this issue, since this is no needed now!
