### ISSUE TITLE
Make a separate directive for Autofocus to input fields.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#168]
@anweshknayak : can you do this?

**Comment by anweshknayak** [comment]
Sure.

**Comment by anweshknayak** [comment]
where shall I place the file ? extend the module in directives/directives.js ?

**Comment by aka-jain** [comment]
Append all your code in directive.js file in a separate function. Don't make a separate file for it.

**Comment by deshraj** [comment]
Fixed in #212
