### ISSUE TITLE
Add support for setting submission limit  per month per team for a challenge

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1690]
## Current Status

Currently, we only provide the capability to set the daily submission limit and total submission limit throughout the challenge. For evaluation of tasks envisioning evaluation of models on EvalAI as long-running test server and not challenge with finite time, we would like to add the feature to limit the number of submissions to a challenge per month per team which eventually limits the number of submissions to test-set per publication.

Thanks @jcjohnson for the feature request.

## Deliverables

- [ ] Add new field `max_submission_per_month` for each challenge phase
- [ ] Set default value to `max_submission_in_total`
- [ ] Add check for monthly submission limit 
- [ ] Add tests
- [ ] Update challenge creation API
- [ ] Modify API to get the remaining submissions and add support to show remaining monthly submissions
- [ ] Update yaml documentation
- [ ] Update EvalAI-Starters to add support for monthly max submission limit

**Comment by vkartik97** [comment]
I am working on this issue

**Comment by RishabhJain2018** [comment]
Sure go ahead!
