### ISSUE TITLE
gulp-deprecation error while running docker-compose command

### ISSUE THREAD

**Issue by HargovindArora** [Cloud-CV/EvalAI#1696]
While running the `docker-compose up --build` command to install and compose the docker container to set up the project the command is exiting with an error. I'm attaching the screenshots of the errors that were occurring even after so many tries.

![docker_gulp](https://user-images.githubusercontent.com/22341493/40987613-9c4663e2-6906-11e8-91c6-49e07cf77e46.png)

![docker_gulp_2](https://user-images.githubusercontent.com/22341493/40987625-a6f54e20-6906-11e8-9dca-b757cc02d94d.png)

![screenshot from 2018-06-05 21-18-31](https://user-images.githubusercontent.com/22341493/40987639-b1bcf4b6-6906-11e8-9180-b7c9b00253e1.png)

Please resolve the above issue as it might be a hurdle for new contributors to set up the project.

**Comment by spyshiv** [comment]
Currently I am working on it. Will update the gulp tasks soon.

**Comment by HargovindArora** [comment]
Ah. Ohkay. And the problem persists even while following trivial installation procedure(non-docker approach). Thanks :)

**Comment by deshraj** [comment]
@HargovindArora the gulp deprecation is a warning and that is not affecting the project in any way as of now. We are working on it as @spyshiv mentioned. Your error seems like while building docker container, your machine is not able to download the package due to some internet issues. Can you please try removing the containers and do it again? It might work then or try changing the internet connection that you are using.

**Comment by varunagrawal** [comment]
Else try restarting the docker daemon. That usually works for me when docker is having a hard time connecting to the internet.

**Comment by HargovindArora** [comment]
@deshraj @varunagrawal I'm trying your given solutions and will let you know if it worked. But "gulp" warning surely did trouble me a lot while following the non-docker installation procedure.

**Comment by deshraj** [comment]
You should check out #1697 for the gulp problems. @spyshiv has already fixed it and the pull request is in the review. 

Please do let us know once your error is resolved.

**Comment by HargovindArora** [comment]
@deshraj As @varunagrawal stated there was an error with docker daemon. I tried restarting it but it didn't help. Therefore I completely removed and reinstalled docker and it finally worked.
But the gulp error isn't letting me to setup using non-docker approach. I'll try it again once #1697 is merged.
Thanks :)

**Comment by RishabhJain2018** [comment]
I think this is resolved. Hence, closing this one.
@HargovindArora Feel free to open up if you find some issues.
