### ISSUE TITLE
Error in creating challenge when host team contains more than 1 members

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1702]
**Issue**
This line [here](https://github.com/Cloud-CV/EvalAI/blob/5be29063e0f88549eedacd9bcbe42bae2336557e/apps/challenges/views.py#L900) throws an  exception when creating a challenge with more than one host team members.

**Steps to Reproduce:**
1. Create a challenge host team
2. Add two members in the team (Total team size:3)
3. Now try creating a challenge by uploading the zip file.
4. Challenge should not get created.

**Fix:**
Use `filter` instead of `get` and loop over all the returned email id's.

**Comment by HargovindArora** [comment]
@RishabhJain2018 I would like to work on this! :)

**Comment by RishabhJain2018** [comment]
@HargovindArora Sure ! But please keep in mind that we have it asap.

**Comment by HargovindArora** [comment]
@RishabhJain2018 Okay. I submit it to you ASAP

**Comment by RishabhJain2018** [comment]
I have updated the issue description. Please take a look again.

**Comment by HargovindArora** [comment]
@RishabhJain2018 It worked for me. The challenge got created

**Comment by RishabhJain2018** [comment]
Can you please upload the screenshot of your host team showing all its members.

**Comment by HargovindArora** [comment]
![screenshot from 2018-06-14 14-19-41](https://user-images.githubusercontent.com/22341493/41401664-0a40e45c-6fde-11e8-838a-e598ce0d6143.png)

@RishabhJain2018 Have a look!

**Comment by RishabhJain2018** [comment]
@HargovindArora Yes, you are right. It is working. Hence, I am closing this.
