### ISSUE TITLE
Show proper error message when Yaml file config has errors

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1703]
### Issue:
Proper error isn't displayed when yaml config for challenge creation isn't correct.

### Culprit Url:
`/api/challenges/challenge/challenge_host_team/{challenge_host_team_pk}/zip_upload/`

### Error:
ScannerError

### Solution
Log the error & display message as:
`Error in creating challenge. Please check the yaml configuration!`
For reference: https://www.programcreek.com/python/example/100007/yaml.scanner.ScannerError

**Comment by sachinmukherjee** [comment]
Is this issue open?

**Comment by RishabhJain2018** [comment]
No @sachinmukherjee 
@calenrobinette is working on it.

**Comment by sachinmukherjee** [comment]
Ok
