### ISSUE TITLE
Add support for editing the challenge start and end date

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1705]
**Current Scenario:**
Currently, a challenge host can't edit the challenge start date and end date. This can only be done by EvalAI admin.

**Deliverables:**
Add functionality to edit the challenge start date and end date on frontend.
Add a check to make sure that challenge end date is always after challenge start date.

Use this(https://indrimuska.github.io/angular-moment-picker/) package for adding date-time support.

**Comment by pujanm** [comment]
I am interested in solving this issue how can I go about the same?

**Comment by pujanm** [comment]
Can you help me out.
I am really interested to contribute to CloudCV.

**Comment by RishabhJain2018** [comment]
Hi, @pujanm I am sorry that I missed this message. Thanks for your interest in CloudCV.

For the above issue, you can check how we have implemented the challenge details edit section. We will be following the same approach as that. Please let me know if you have further doubts. I'll be happy to help.

**Comment by pujanm** [comment]
I was trying to edit the challenge overview it is giving this `/api/challenges/challenge_host_team/undefined/challenge/3` there is an undefined in place of `challengeHostId`. Is there any reason or I might have done some mistake while making this challenge?

**Comment by RishabhJain2018** [comment]
I think @pujanm is still working on this issue.
>/api/challenges/challenge_host_team/undefined/challenge/3 there is an undefined in place of challengeHostId

I am not sure why it is showing this behaviour to you. Can you please try to debug it?

**Comment by pujanm** [comment]
Yes.

**Comment by Ayukha** [comment]
@RishabhJain2018 I would like to work on it.

**Comment by RishabhJain2018** [comment]
Sure!

**Comment by RishabhJain2018** [comment]
Since @Ayukha isn't active these days, would you like to work on this @nikhilmudholkar?

**Comment by Ayukha** [comment]
@RishabhJain2018  I am working on it. And I'll open a PR soon.

**Comment by nikhilmudholkar** [comment]
Yaa i would like to work on it but it seems that someone is already working on this issue

**Comment by RishabhJain2018** [comment]
@Ayukha Can you please let us know ETA on this? This is now becoming a priority thing for us

**Comment by Sanji515** [comment]
@RishabhJain2018 If @Ayukha isn't active these days, then I can work on this issue.

**Comment by Ayukha** [comment]
@RishabhJain2018  I'll try to fix it by tonight. Actually, I'm struggling in using the package suggested.
