### ISSUE TITLE
Change team name dialog box should disable submit button when no team name is entered

### ISSUE THREAD

**Issue by sachinmukherjee** [Cloud-CV/EvalAI#1714]
- The Expected Behavior
The change team name dialog box submit button should be enabled when a team name is entered.
![team name](https://user-images.githubusercontent.com/19318218/41724258-cb857914-758a-11e8-8e2b-ccfa9b4d6ecd.png)

- The Observed Behaviour
 At present even though no team name is entered it successfully updates the team name.
![screenshot from 2018-06-21 06-20-40](https://user-images.githubusercontent.com/19318218/41724285-dadf207c-758a-11e8-909f-186ff488adb3.png)

**Comment by RishabhJain2018** [comment]
@sachinmukherjee Thanks for catching the bug.
 Would you like to work on it ?
