### ISSUE TITLE
Use Yarn instead of Gulp

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1731]
It's time to move away from Gulp. We would like to use Yarn as a package manager instead of gulp.
See https://bower.io/blog/2017/how-to-migrate-away-from-bower/ for more details.

**Comment by rakesh-1601** [comment]
I would like to solve this issue!!!

**Comment by deshraj** [comment]
@rakesh-1601: Please take one issue at a time. You can take it once you finish the other issue that you are working on right now.

**Comment by Arpitrf** [comment]
Can I work on this issue?

**Comment by RishabhJain2018** [comment]
This issue is invalid since we are planning to move with https://github.com/Cloud-CV/EvalAI-ngx
