### ISSUE TITLE
Show explicit error message while creating a team.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1734]
**Current Scenario:**
We only display a error message that says `Team cannot be created`.

**Deliverables:**
We want to show the specific error message returned from backend stating that why the team can't be created.

**What you have to do:**
1. Change the error message [here](https://github.com/Cloud-CV/EvalAI/blob/master/frontend/src/js/controllers/teamsCtrl.js#L239) to `error.team_name[0]`.
2. Change the error message [here](https://github.com/Cloud-CV/EvalAI/blob/master/frontend/src/js/controllers/challengeHostTeamsCtrl.js#L225) to `error.team_name[0]`.

**Comment by HargovindArora** [comment]
@RishabhJain2018 I would like to do this one!

**Comment by RishabhJain2018** [comment]
Sure @HargovindArora Go Ahead!

**Comment by HargovindArora** [comment]
Okay. I'm on it
