### ISSUE TITLE
Change the uploaded challenge logo to some random name.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1736]
### Current Scenario:
Currently all the challenge logo images are being uploaded by the same name as the user has them on their local machine.

Hint: See the names for https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/models.py#L42 evaluation script.

### Deliverables:
We want that the logo images should be stored with unique random string on the server.

**Comment by HargovindArora** [comment]
@RishabhJain2018 I would like to work on this!

**Comment by RishabhJain2018** [comment]
Sure @HargovindArora Go Ahead!
