### ISSUE TITLE
Set object level permissions to update a challenge

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#174]
Set object level permissions so that the user who is creator of the challenge can only edit/delete the challenge. 

For reference, see this http://www.django-rest-framework.org/api-guide/permissions/#object-level-permissions

**Comment by RishabhJain2018** [comment]
I think we need to write again the `challenge_detail` view of the challenges app using the class based views. As for function based views we can't implement the object level permissions. For reference please check [this](https://github.com/tomchristie/django-rest-framework/issues/1697) link.

**Comment by deshraj** [comment]
No, I don't think so. We can do it easily for FBV. 

I realized that I posted the wrong reference link. Please see this http://www.django-rest-framework.org/api-guide/permissions/#custom-permissions

**Comment by RishabhJain2018** [comment]
@deshraj ThePR is merged. I think we should close this.

**Comment by deshraj** [comment]
Thanks @RishabhJain2018 for working on this. 

Fixed in #231
