### ISSUE TITLE
Modify challenge phase query for displaying challenge phase detail

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1740]
**Current Scenario:**
The function [here](https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/views.py#L398) will **not** throw the error even if there are no challenge phase corresponding to the challenge.

**Steps to Reproduce:** You will only be able to check it only at the API level.
Let us suppose there exists a challenge with id 34 and phase ids 120, 121. Now when you will hit the [url ](https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/urls.py#L17)with challenge id 34 and phase id say 1 then it won't give error if phase id 1 exists(for any other challenge). 

Ideally, it this [url](https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/urls.py#L17) should only accept the phase ids 120 and 121 and should throw error for every other phase id.

**Deliverables:**
Modify the challenge phase query [here](https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/views.py#L406) to include the `challenge` parameter in it.

What should be added:
`challenge_phase = ChallengePhase.objects.get(challenge=challenge, pk=pk)`
Also, Update the response message to
`response_data = {'error': 'Challenge Phase {} does not exist'.format(pk)}`

**Comment by HargovindArora** [comment]
@RishabhJain2018 I would like to work up on this!

**Comment by HargovindArora** [comment]
@RishabhJain2018 I would like to work up on this!

**Comment by RishabhJain2018** [comment]
Sure @HargovindArora go ahead!

**Comment by HargovindArora** [comment]
@RishabhJain2018 How to check whether the changes made are showing effect? I meant how should I reproduce error after making the required changes? I tried deleting the phases of the challenges already present there, nothing happened.

**Comment by RishabhJain2018** [comment]
@HargovindArora I have updated the description.

**Comment by rakesh-1601** [comment]
I would like to start contributing by working on this !!

**Comment by isht3** [comment]
@rakesh-1601 Sounds good! Please let us know here or on our Gitter channel if you're having any difficulties. :)

**Comment by RishabhJain2018** [comment]
@rakesh-1601 Please feel free to take up any other issue since @HargovindArora has already opened a PR for this.

**Comment by Arpitrf** [comment]
Hello. Is this issue still open? Can I work on this?

**Comment by deshraj** [comment]
@Arpitrf looks like #1751 is already there for this. Please feel free to take any other unassigned issue.

**Comment by Ayukha** [comment]
@RishabhJain2018  I would like to work on it.

**Comment by RishabhJain2018** [comment]
Sure!

**Comment by kurianbenoy** [comment]
Can I work on this issue @RishabhJain2018 ?

**Comment by Ayukha** [comment]
@kurianbenoy  There is already a PR opened for this issue which is yet to be reviewed.

**Comment by kurianbenoy** [comment]
> @kurianbenoy There is already a PR opened for this issue which is yet to be reviewed.

The travis tests for your PR is failing. That's why it's not being reviewed. This is why I put a PR and I hope I can fix test failures in my PR soon.
