### ISSUE TITLE
Bug in showing remaining submissions

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1746]
Currently, if the number of total remaining submissions is less than that of the limit set for doing the total number of submissions in a day, then ideally total submissions that can be done should be equal to the total remaining submissions which is not the case right now. Please see the screenshot below for illustration:

<img width="1186" alt="screen shot 2018-07-11 at 10 22 14 pm" src="https://user-images.githubusercontent.com/2945708/42614102-3618ffb6-8559-11e8-95f9-adee793c1a24.png">

**Comment by Gautam1630** [comment]
Can I work on this issue?

**Comment by RishabhJain2018** [comment]
Hi @Gautam1630 I have already completed the above issue and opened a PR. Please feel free to take up any other issue.
