### ISSUE TITLE
Add Filtering by participant team name in EvalAI Admin

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1759]

**Comment by sachinmukherjee** [comment]
Can I work on this issue?

**Comment by sachinmukherjee** [comment]
Hey I think filtering by participant team name is already there.
![paricipant team](https://user-images.githubusercontent.com/19318218/44629711-c87f0900-a970-11e8-8056-3b1bb7e41e35.png)
Here is the code that filters according to participant team name
`list_filter = ('team_name',)`

**Comment by RishabhJain2018** [comment]
yes! thanks for pointing out. Closing this issue.
