### ISSUE TITLE
Add cloudcv logo in header

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#176]
Need to add the cloudcv logo just above the link www.cloudcv.org. Download logo fromthe official site www.cloudcv.org

**Comment by deshraj** [comment]
To make life easier, the logo can be found here http://deshraj.github.io/static/img/cloudcv.png

**Comment by jainarunarunjain** [comment]
@aka-jain @deshraj can you provide this logo without background

**Comment by aka-jain** [comment]
Sure, I'll make that one. Will let you know when finished with it.

**Comment by aka-jain** [comment]
![cloudcv](https://cloud.githubusercontent.com/assets/11537940/20827532/ba8c0a70-b898-11e6-8e39-442b9a913741.png)
@jainarunarunjain I hope this logo works fine. Let me know if you have any query.

**Comment by deshraj** [comment]
Fixed in #202
