### ISSUE TITLE
Signup failing with Cross Origin Read Block

### ISSUE THREAD

**Issue by apsdehal** [Cloud-CV/EvalAI#1760]
Options preflight is failing to evalapi.cloudcv.org on sign up.

Browser: Google Chrome (Version 67.0.3396.87, 64-bit)
OS: Mac OS 10.3.5

**Comment by deshraj** [comment]
@apsdehal : Sorry for the inconvenience. There is some issue with the gunicorn prod setup that we are fixing. As of now, the issue is fixed temporarily. We will keep you posted about the permanent fix.

**Comment by RishabhJain2018** [comment]
This seems to be fixed!
