### ISSUE TITLE
Add functionality to update the profile picture

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1777]
**Current Scenario:**
A user can't update his profile picture.

**Deliverables:**
A field on the profile page where a user can upload an image in order to update it.
The screenshot of the Update Profile Page is given below.
<img width="1440" alt="screen shot 2018-08-22 at 6 33 23 pm" src="https://user-images.githubusercontent.com/12206047/44494531-28587580-a63a-11e8-8e0d-e02190ee29e3.png">

**Comment by party98** [comment]
Hey, I would like to take this issue. However, I am new to the project and was hoping if some assistance could be provided

**Comment by usmanmuhd** [comment]
Hey @RishabhJain2018 , I am interested to work on this issue. Would you assign it to me or shall I just start working?

**Comment by AshleyTR** [comment]
@RishabJain2018 . If this issue is still unsolved, do you mind if  I give it a shot. I'm new at this, but I'll try my best

**Comment by usmanmuhd** [comment]
@AshleyTR I'm still working on the issue.

**Comment by AshleyTR** [comment]
@usmanmuhd No worries. I'll find another one. Thanks for replying fast

**Comment by RishabhJain2018** [comment]
@usmanmuhd Any update on this issue?

**Comment by usmanmuhd** [comment]
@RishabhJain2018 I have added the backend functionality. I am yet to do the front end part (quite new to angular).

**Comment by RishabhJain2018** [comment]
Can you please open up a PR for that. We generally merge front-end and backend code in different PR's.

**Comment by usmanmuhd** [comment]
@RishabhJain2018 I will do it in a few days. Currently on a vacation.

**Comment by RishabhJain2018** [comment]
Sure! No problem. Thanks for keeping us posted.

**Comment by Abhi-1198** [comment]
Is this Issue still open? 
I would liem to work on it.

**Comment by kurianbenoy** [comment]
Can I work on this issue @RishabhJain2018

**Comment by kurianbenoy** [comment]
Is this issue a priority as our frontend is now being migrated to `new frontend`, this year. If yes, I was interested to work on this project
