### ISSUE TITLE
Unable to login via Safari

### ISSUE THREAD

**Issue by party98** [Cloud-CV/EvalAI#1782]
### The expected behaviour
Successfully be able to login to the dashboard on Safari

### The observed behaviour
Unable to maintain a session. After 5 seconds of logging in, a timeout error is generated and the site logouts automatically.

### Steps to reproduce the problem
Try logging in via safari

### Which operating system and/or browser you're using, if relevant
macOS 10.13.6
Safari 11.1.2

### (if possible) copies of the console/server logs
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (challenge_host_team, line 0)

![image](https://user-images.githubusercontent.com/22412980/44630750-7b0a9800-a980-11e8-9e95-3325ba2c9c76.png)

**Comment by matthew-z** [comment]
+1

**Comment by RishabhJain2018** [comment]
@matthew-z @party98 Would you like to work on it?

**Comment by matthew-z** [comment]
Sorry, I am not familiar with web development

**Comment by RishabhJain2018** [comment]
Okay! No problem.

**Comment by party98** [comment]
I can try to give it a go. But I am not super confident about it.

**Comment by RishabhJain2018** [comment]
Sure! Please keep me posted regarding it.

**Comment by RishabhJain2018** [comment]
@party98 Any update on this issue?
