### ISSUE TITLE
CORS error while using django server with frontend server.

### ISSUE THREAD

**Issue by jainarunarunjain** [Cloud-CV/EvalAI#179]
![screenshot 110](https://cloud.githubusercontent.com/assets/16155501/20721362/65df055a-b617-11e6-84b5-9021184e8eee.png)
CORS error is coming while accessing django server from localhost.

**Comment by deshraj** [comment]
Thanks @jainarunarunjain for reporting this. I will check and get back to you soon.

**Comment by deshraj** [comment]
Fixed in #180. Closing it now.
