### ISSUE TITLE
Fix Failing test cases in Python 3

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1791]
The Travis-CI build for python 3 is failing.
The tasks involved are:
1. Fix the flake8 errors
2. Fix the failing test cases

**Comment by RishabhJain2018** [comment]
Sure @kurianbenoy You can take this issue. Just for the head start here is the link to failing test cases & flake8 errors https://travis-ci.org/Cloud-CV/EvalAI/jobs/425998771#L1340

**Comment by kurianbenoy** [comment]
@RishabhJain2018 thanks
