### ISSUE TITLE
https://evalai.cloudcv.org/web/permission-denied should redirect if already verified.

### ISSUE THREAD

**Issue by souravbadami** [Cloud-CV/EvalAI#1793]
_Thanks for taking the time to report a bug in the EvalAI project, or propose a new feature! Before creating a new issue, please do a quick search to check that it hasn't already been filed on the [issue tracker](https://github.com/Cloud-CV/EvalAI/issues)._

If you'd like to report a bug, please include the following information:
- the expected behaviour
- the observed behaviour
- steps to reproduce the problem
- which operating system and/or browser you're using, if relevant
- (if possible) copies of the console/server logs

On the other hand, if you'd like to propose a new feature:
- please describe, as clearly as possible, what you'd like to see
- (if possible) include mockups/screenshots, if these would help convey the meaning better

Thanks!

![screen shot 2018-09-07 at 11 26 23 am](https://user-images.githubusercontent.com/11073943/45201001-10672f80-b291-11e8-9324-8c1d1e19ff02.png)

Message: **false** should be more intuitive.
Issue: On hitting the url (https://evalai.cloudcv.org/web/permission-denied), if user is already verified -- redirect to dashboard.
Reproduce: Create an account, it takes you to permission denied view. Verify your email by clicking on the link. Go back to the previous page and refresh.

**Comment by RishabhJain2018** [comment]
This is the desired behavior. Hence Closing this issue!

**Comment by souravbadami** [comment]
Really ? Sure!
