### ISSUE TITLE
Update profile button not shown in mobile view

### ISSUE THREAD

**Issue by usmanmuhd** [Cloud-CV/EvalAI#1795]
In mobile view the update profile button is not shown as expected.
![screenshot from 2018-09-08 13-05-36](https://user-images.githubusercontent.com/26684281/45251691-0cf2a780-b368-11e8-8610-a01cc62828e9.png)

**Comment by RishabhJain2018** [comment]
Thanks @usmanmuhd for pointing out. Would you like to work on it?

**Comment by usmanmuhd** [comment]
@RishabhJain2018 Currently I am more interested in working on #1777 . I was thinking of making this one as a GCI task. There a lot more instances of this kind. Example:
![inc](https://user-images.githubusercontent.com/26684281/45260988-c8244a80-b413-11e8-8df9-be7415848227.png)

**Comment by RishabhJain2018** [comment]
Sure @usmanmuhd . You can work on it. But for GCI tasks please make sure that the tasks are easy enough for the students (Remember that they are high school students 13-17 years). If there is a tough task then break it into smaller tasks & later on combine all these tasks.

**Comment by usmanmuhd** [comment]
@RishabhJain2018 Could I PM you on gitter  in order to discuss the tasks for the GCI.
PS: I have filled the form for being a GCI mentor.

**Comment by RishabhJain2018** [comment]
This is not the right place to talk about GCI. Please send all the GCI related messaged on the gitter channel. Moreover, if you want to work on the frontend for EvalAI then please use this https://github.com/Cloud-CV/EvalAI-ngx repository.
