### ISSUE TITLE
KeyError: 'evaluation_details'

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1799]
https://sentry.io/cloudcv/evalai/issues/680906137/

```
KeyError: 'evaluation_details'
  File "challenges/views.py", line 672, in create_challenge_using_zip_file
    yaml_file_data['evaluation_details']

There is no key for evalutaion details. Please add it and then try again!
```

**Comment by darthgera123** [comment]
ill solve this one

**Comment by RishabhJain2018** [comment]
@darthgera123 Any update on this?

**Comment by darthgera123** [comment]
sorry, completely forgot about this. Will make a pr within a day or 2

**Comment by nagpalm7** [comment]
Can I work on this issue if no one is working ! @darthgera123

**Comment by deshraj** [comment]
I think @darthgera123 is working on it. Please feel free to take another issue. :)

**Comment by darthgera123** [comment]
@deshraj  can you give me access to sentry so i can completely figure out the issue. Thanks

**Comment by darthgera123** [comment]
@deshraj  can you please share the sentry access so that i can recreate the issue

**Comment by deshraj** [comment]
@darthgera123 sorry I cannot give the sentry access since it's only accessible to maintainers. Also, there is no need to see sentry for the error. The error is posted in the issue description. Please see that for more information.
