### ISSUE TITLE
Host Challenge link on Home Page not working

### ISSUE THREAD

**Issue by vkartik97** [Cloud-CV/EvalAI#1810]
-  the observed behaviour
`Host Challenge` is having href `unsafe:javascript:void(0)` and giving `The address wasn’t understood` after clicked
![screenshot from 2018-09-17 02-27-08](https://user-images.githubusercontent.com/3920286/45600858-61112200-ba21-11e8-9f9b-2de353fbde27.png)
- which operating system and/or browser you're using, if relevant
Ubuntu 18.04 LTS
Firefox 62.0 (64-bit)

**Comment by deshraj** [comment]
@vkartik97 thanks for reporting this. I can also reproduce this error on Firefox. If you are interested in fixing this issue, please let me know.

**Comment by w3x10e8** [comment]
I'll fix this if @vkartik97 wants to work on some other issue

**Comment by vkartik97** [comment]
@w3x10e8 you can work on this.

**Comment by vkartik97** [comment]
@deshraj 
Can you have this as an Task in GCI ?

**Comment by party98** [comment]
The same issue is observable on Safari on macOS as well.
