### ISSUE TITLE
Make code into PEP8 format

### ISSUE THREAD

**Issue by kurianbenoy** [Cloud-CV/EvalAI#1813]
As per EvalAI [contributing guidelines](https://github.com/Cloud-CV/EvalAI/blob/master/.github/CONTRIBUTING.md). The source code should be in PEP8.

When I typed the mentioned docs in PEP8 . I realised that PEP8 was not enforced in some files. 

**Expected Action**
- `  autopep8 --in-place --exclude env,docs --recursive . `
-  Add your commit message

Thanks!

**Comment by party98** [comment]
If you have gone through the travis configuration, flake8 is implemented to be run to check the formatting.

**Comment by deshraj** [comment]
Yes, @party98 is right. We enforce PEP8 guidelines but Autopep8 adds up bunch of extra things that are not required. 

Although thanks for opening this issue @kurianbenoy :)
