### ISSUE TITLE
Using Python 3 ONLY

### ISSUE THREAD

**Issue by vkartik97** [Cloud-CV/EvalAI#1815]
Currently, EvalAI is based on Python2.7([docker/prod/django/Dockerfile#L1](https://github.com/Cloud-CV/EvalAI/blob/4e725674bd2ee2fd5f4daf23328f6b868d2c9ca2/docker/prod/django/Dockerfile#L1)), but [`it will retire soon`](https://pythonclock.org/).
It will be better if we start migrating to Python3.
Thanks!

**Comment by kurianbenoy** [comment]
@vkartik97 the process to migrate has already started. Check #1791 #1786

**Comment by RishabhJain2018** [comment]
Thanks, @vkartik97 for the suggestion. We are already working on this feature and are about to release it.
Hence closing this issue.
