### ISSUE TITLE
Bugged contact us page if https://evalai.cloudcv.org/contact is directly opened 

### ISSUE THREAD

**Issue by w3x10e8** [Cloud-CV/EvalAI#1816]
Hi the Contact Us page if directly opened from the link https://evalai.cloudcv.org/contact is bugged.
Steps to reproduce :- 
Login to https://evalai.cloudcv.org
Open the page https://evalai.cloudcv.org/contact

![capture](https://user-images.githubusercontent.com/29617462/45769314-e2a0c400-bc5c-11e8-9e52-7d93f35d0236.PNG)

System details 
Windows 10
Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by deshraj** [comment]
It's not a big, it's a feature. :) 

This is an expected behaviour where we automatically fill the email address field of the user if he is logged in. Hence, closing it. 

If this issue is about something else, then please feel free to reopen this issue.

**Comment by w3x10e8** [comment]
I was talking about the UI it isn't aligned properly vertically if you open the link directly

**Comment by deshraj** [comment]
Ah I see. Thanks for bringing that up. Reopening the issue.

Please feel free to work on this issue if interested. :)

**Comment by w3x10e8** [comment]
Yea I will try to work on it:)
