### ISSUE TITLE
Download JSON  is not working in API Authentication Token pop-up box

### ISSUE THREAD

**Issue by knakul853** [Cloud-CV/EvalAI#1821]
* the observed bevaviour 

in user profile  **Download JSON** is not working
after clicking it doesn't give any response

![screenshot from 2018-09-24 00-44-03](https://user-images.githubusercontent.com/32031946/45921203-ef2c5300-bece-11e8-89a6-7e2ba226a1d6.png)

**Comment by deshraj** [comment]
@knakul853 Can you please add the browser name and version that you are using? I think this might be relevant to PR #1812 (issue #1810).

**Comment by knakul853** [comment]
* firfox version 62
* ubuntu

**Comment by party98** [comment]
I’ll try to fix this and reference in the same PR (#1812)

**Comment by deshraj** [comment]
Thanks @party98 :)

**Comment by party98** [comment]
The issue is unrelated to the said PR(#1812) hence I will be submitting a separate PR for the same.

**Comment by gautamjajoo** [comment]
@deshraj @RishabhJain2018 Can I make a PR regarding the issue, I have found a possible solution.

**Comment by kurianbenoy** [comment]
Even I am facing the same issue in Firefox version 60
