### ISSUE TITLE
Create a Pipfile

### ISSUE THREAD

**Issue by kurianbenoy** [Cloud-CV/EvalAI#1822]
As an alternative to virtualenv which is currently used in the project, we can use pipenv also for easy installation. Also now pipenv is officially recommended python package and virtualization manager. 

https://stackoverflow.com/questions/46330327/please-explain-the-usage-of-pipfile-and-pipfile-lock

https://pipenv.readthedocs.io/en/latest/

**Comment by deshraj** [comment]
@kurianbenoy thanks for taking out time to open the issue. We are going to deprecate the method of installation of EvalAI using virtualenv and won't provide support using pipenv. Hence closing this issue.

**Comment by kurianbenoy** [comment]
@deshraj are you planning to use docker in future?

**Comment by deshraj** [comment]
Yeah, we support docker based support now also.
