### ISSUE TITLE
HTTP Cache to Speed up the Frontend

### ISSUE THREAD

**Issue by vkartik97** [Cloud-CV/EvalAI#1825]
- [`HTTP Caching`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching) Services for `.html`, `.css`, `.js` and other image files can be used
- This will help the Site to Load fast

Thanks!

**Comment by RishabhJain2018** [comment]
@vkartik97 Can you please describe how you are thinking of it?

**Comment by kurianbenoy** [comment]
@vkartik97 are you thinking of some caching anything to speed up?

**Comment by vkartik97** [comment]
I am currently experimenting with IaaS/SaaS and Reverse Proxies for Page Caching.
I will soon post my findings here!

**Comment by vkartik97** [comment]
Closing this as this issue deals with IaaS.
