### ISSUE TITLE
Add exception handling when key is not present in leaderboard API

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1829]
The backend server throws 500 internal server error whenever any key in the results stored in the leaderboard data table is not present in the leaderboard schema for that particular challenge. Instead we want to show meaningful error on the UI with proper status code. Please see the relevant error log given below:

Sentry Report: https://sentry.io/cloudcv/evalai-staging/issues/605096490/

```
KeyError: u'spl'
(5 additional frame(s) were not displayed)
...
  File "rest_framework/views.py", line 477, in dispatch
    response = self.handle_exception(exc)
  File "rest_framework/views.py", line 437, in handle_exception
    self.raise_uncaught_exception(exc)
  File "rest_framework/views.py", line 474, in dispatch
    response = handler(request, *args, **kwargs)
  File "rest_framework/decorators.py", line 52, in handler
    return func(*args, **kwargs)
  File "jobs/views.py", line 259, in leaderboard
    item['result'] = [item['result'][index] for index in leaderboard_labels]

KeyError: u'spl'
```

**Comment by Joel-hanson** [comment]
is this done already?

**Comment by Joel-hanson** [comment]
if no shall I take it.

**Comment by Ram81** [comment]
@RishabhJain2018 can I pick this up?

**Comment by RishabhJain2018** [comment]
Sure you can!

**Comment by RishabhJain2018** [comment]
Closing this since it is already fixed!
