### ISSUE TITLE
Remove discussions tab from challenge page

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1833]
Currently the discussions tab is always shown whether a link in it exists or not but we would like to show the discussions tab only when there is a link in it from the backend.

**Comment by nagpalm7** [comment]
I want to work on this issue!!

**Comment by RishabhJain2018** [comment]
Sure! Go ahead.

**Comment by spyshiv** [comment]
ytdytfy
![asset-37-4-x 3x](https://user-images.githubusercontent.com/7015220/47180574-7d64ef00-d33e-11e8-9abd-5511f16e143f.png)

hbuyb
lmnijnui
