### ISSUE TITLE
Fix potential vulnerabilities due to outdated requirements

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1834]
There are some outdated requirements which can open potential security threats. Hence we should update the vulnerable package versions as suggested by Github. Here is the list of upgrades to be done (as suggested by Github):

1. django ~> 1.11.15

Please make sure to verify the validity and compatibility of suggestions with EvalAI codebase.

**Comment by kaansan** [comment]
Hey there, I couldn't see any vulnerable package info on Dependency Graph section. I wanted to take this issue to myself but I couldn't find the problem.

**Comment by kaansan** [comment]
![image](https://user-images.githubusercontent.com/20618151/46561093-cceafa00-c8fe-11e8-9768-67e1e1bfa662.png)
I can not see it. I don't know why. Thanks for the info.

**Comment by deshraj** [comment]
Only project maintainers can see it.

**Comment by vkartik97** [comment]
Upgrades should also be done for `django-storages` in `requirements/prod.txt`
```sh
╞══════════════════════════════════════════════════════════════════════════════╡
│ REPORT                                                                       │
│ For requirements/prod.txt                                                    │
╞════════════════════════════╤═══════════╤══════════════════════════╤══════════╡
│ package                    │ installed │ affected                 │ ID       │
╞════════════════════════════╧═══════════╧══════════════════════════╧══════════╡
│ django-storages            │ 1.5.1     │ <1.7                     │ 36434    │
╘══════════════════════════════════════════════════════════════════════════════╛
```
