### ISSUE TITLE
Add horizontal scroll in leaderboard

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1843]
Currently, the leaderboard displays maximum 10 custom metrics without horizontal scroll. We want to increase that number by adding horizontal scroll.

**Comment by haivp3010** [comment]
Hi @RishabhJain2018, is this horizontal scroll bar at the bottom of the table the desired implementation? Or do we need something more advanced like column freezing, etc.?

![image](https://user-images.githubusercontent.com/7151454/47078377-5f5b9980-d22d-11e8-9af9-c393927b1d9d.png)

**Comment by haivp3010** [comment]
Oh, is this meant to be different from issue #1798?

**Comment by RishabhJain2018** [comment]
I can't see the uploaded image. can you please upload it again.
Yeah, this is different from #1798 . as we want the leaderboard to horizontally scrollable in desktop view.

**Comment by RishabhJain2018** [comment]
yeah, the image looks good to me. 
The two issues are alike in terms of same functionality but we would like to have different PRs for both of them.

**Comment by RishabhJain2018** [comment]
Hi @haivp3010 Since we need that feature urgently, so I added it. Please feel free to take up any other issue.

**Comment by haivp3010** [comment]
@RishabhJain2018 That's fine. I'll see other issues then.
