### ISSUE TITLE
Add Challenge name in submissions model in django admin

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1848]
Currently, we only show challenge phase name in the submissions table, we also want to show the corresponding challenge name in the table near to the challenge phase name.

**Comment by SinghSatbir** [comment]
Hey, I want to work on this issue. Please assign it to me.

**Comment by RishabhJain2018** [comment]
Sure! You can work on it.

**Comment by rajesh1993** [comment]
Hey! Is this still open? If so, can you point me to the file I need to look at for fixing this issue?

**Comment by RishabhJain2018** [comment]
@rajesh1993 I think @SinghSatbir is working on it. Please feel free to take up any other issue.

**Comment by RishabhJain2018** [comment]
Closing this since it is the duplicate of #1826 .
