### ISSUE TITLE
Display execution time only when greater than zero.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1850]
Currently, all the types of execution time is shown on the frontend under `my submissions`. We would like to show only the execution time which is greater than zero.

Helpful link: https://stackoverflow.com/questions/18403835/how-to-make-less-than-or-greater-than-comparison-in-angularjs?answertab=active#tab-top

**Comment by kciecinski** [comment]
Hi It's my first time in open-source project. I like to take that issue if that's ok
