### ISSUE TITLE
Delete Teams app and move the models and views to Participants and Hosts app

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#186]

**Comment by jainarunarunjain** [comment]
@deshraj Can i try this

**Comment by deshraj** [comment]
Sorry @jainarunarunjain, @TroJan is already working on this.

**Comment by jainarunarunjain** [comment]
@deshraj ok, no problem

**Comment by TroJan** [comment]
Reason for deleting this app ::
This app contains models `Team` and `TeamMembers` that are more generic. `Team` and `TeamMembers` as entity belongs to both challenge and participant. For Challenge, `ChallengeHost` and `ChallengeHostTeam` already exists. Hence these models can be successfully merged into Participant app

**Comment by deshraj** [comment]
Resolved in #188
