### ISSUE TITLE
Edit challenge name button disbaled when no changes are made

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#1875]
### The Observed Behaviour
If a host clicks the edit challenge name button but does not make any changes and submit, then a successful return message is there.

### The Expected Behaviour
The button should be disbaled if no changes are made.

### Would you like to work on this issue?
Yes

@RishabhJain2018 @deshraj 

![screenshot-from-2018-10-31-01-26-22](https://user-images.githubusercontent.com/24366008/47746518-3d8df800-dcac-11e8-9cd1-c180f403bd17.png)

![screenshot-from-2018-10-31-01-26-27](https://user-images.githubusercontent.com/24366008/47746520-3e268e80-dcac-11e8-8868-035637450cd5.png)

**Comment by gautamjajoo** [comment]
Facing the following error when I edit the team name and submit. @RishabhJain2018 
![screenshot-from-2018-10-31-13-50-11](https://user-images.githubusercontent.com/24366008/47780152-d78f8800-dd20-11e8-98cf-387488e1e86f.png)

**Comment by RishabhJain2018** [comment]
Team name or Challenge name?

**Comment by gautamjajoo** [comment]
@RishabhJain2018 Challenge name
