### ISSUE TITLE
Display error if filename is too long

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1876]
**Current Scenario:**
While submitting to EvalAI, if the filename is greater than 100 characters then the submission isn't accepted & no error is being thrown on the front-end, so a participant doesn't get to know about the state of his submission.

**Deliverables:**
Display the error thrown by API on the frontend.

**Comment by yashdusing** [comment]
Can I work on this ?

**Comment by RishabhJain2018** [comment]
Sure @yashdusing. You can work on it.

**Comment by yashdusing** [comment]
I saw your message today so sorry for the delay. Anyways, is this okay ? (I directly checked the length of string without passing it to backend since it would throw off error anyway)
![download](https://user-images.githubusercontent.com/19976688/48217911-aa8d4600-e3ae-11e8-95c3-6bf2e04e57c0.png)
