### ISSUE TITLE
Addition of Copyright Year in Dashboard footer

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#1878]
Currently, there is no Copyright Year in the footer of Dashboard. 
@RishabhJain2018 @deshraj 

![capture](https://user-images.githubusercontent.com/24366008/47844063-71ba0380-dde7-11e8-9a45-7cff8e52cfa6.JPG)

**Comment by gautamjajoo** [comment]
@deshraj @RishabhJain2018 I am suggesting to add copyright year in the dashboard footer. The PR #1867 , makes copyright year dynamic of landing footer. So, please reopen the issue

**Comment by deshraj** [comment]
@gautamjajoo please feel free to open a pull request for that as well. We will be more than happy to merge it. Thanks!
