### ISSUE TITLE
Update EvalAI Users List

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1887]
Deliverables:

- [ ] Add HD logo for Ebay 
![download](https://user-images.githubusercontent.com/12206047/48034765-aeab3080-e12e-11e8-9279-3647fe37eaf2.png)

- [ ] Add HD logo for IIT Madras
![1200px-iit_madras_logo svg](https://user-images.githubusercontent.com/12206047/48034861-047fd880-e12f-11e8-80b1-8bf42c97ad8d.png)

- [ ] Add HD logo for University Of Adelaide
![the-university-of-adelaide-1-logo-png-transparent](https://user-images.githubusercontent.com/12206047/48034972-912a9680-e12f-11e8-9160-3e6e2ea566af.png)

**Comment by gautamjajoo** [comment]
@RishabhJain2018 I would like to work on this issue!

**Comment by RishabhJain2018** [comment]
Sure You can take it up.
