### ISSUE TITLE
Add support for show and hide password

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#1892]
### Observed Behaviour
Currently , there is no feature for showing or hiding password in login and sign up page.

### Expected Behaviour
There should be a one eye icon which on clicking shows or hides the password.

**Comment by Sanji515** [comment]
@deshraj @RishabhJain2018 I want to work on this issue.
Should I just replace the current key icon with an eye icon?

**Comment by RishabhJain2018** [comment]
@Sanji515 yes! replace the key icon with an eye icon :)
