### ISSUE TITLE
Add support for Editing Host Team name

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#1893]
### Observed Behaviour
Currently , there is no option to edit Host Team name.

### Expected Behaviour
Add support for editing challenge host team name.

### Would you like to work on this?
Yes.

@deshraj @RishabhJain2018 
![img_20181108_004200](https://user-images.githubusercontent.com/24366008/48154645-258f2780-e2ef-11e8-9067-35280d55aa2e.jpg)

**Comment by Sanji515** [comment]
I want to work on this..... Please assign this issue to me.
Thank you.
