### ISSUE TITLE
Add created_by in ParticipantTeam model

### ISSUE THREAD

**Issue by TroJan** [Cloud-CV/EvalAI#190]
So that cases like get all participant_team by particular user can be easily solved. This otherwise would involve very complex joins

**Comment by TroJan** [comment]
To keep master stable and not break migrations, a default null value should be added for all the existing rows. May be in futures, when we are rebasing migrations, then we can drop this null value clause on `created_by` in `ParticipantTeam` model.

@deshraj : FYI

**Comment by deshraj** [comment]
Fixed in #210
