### ISSUE TITLE
Bug in Count of My Particpant Teams

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#1900]
### Observed Behaviour
The count of ```My Participant Teams``` is same as ```My Host Teams```.

### Steps to Reproduce
Create 2-3 Host teams and go to ```dashboard```.
We will see Host teams equal to Particpant Teams.

@deshraj @RishabhJain2018 

![screenshot-from-2018-11-10-19-06-59](https://user-images.githubusercontent.com/24366008/48303866-25349d80-e536-11e8-95fe-64adc690cd20.png)

**Comment by w3x10e8** [comment]
I'll fix this

**Comment by w3x10e8** [comment]
@gautamjajoo I tried to reproduce this issue but I am not able to, am I missing something?
![screenshot from 2018-11-11 13-56-43](https://user-images.githubusercontent.com/29617462/48317048-d6304c00-e5b9-11e8-9a40-14648626e6e7.png)

**Comment by gautamjajoo** [comment]
@w3x10e8 I tried once more and the count was right. I think so the error is only sometimes.
