### ISSUE TITLE
Token not shown when windows width is < ~980px

### ISSUE THREAD

**Issue by radiantly** [Cloud-CV/EvalAI#1903]
## Overview
When the window size is smaller than ~980px in width, the Token is not shown.

![token_get](https://user-images.githubusercontent.com/44368997/48406922-afaa1680-e75b-11e8-8d35-ad053ecd75c5.gif)

### Steps to reproduce the problem:
With browser window at less than 980px in width, visit the profile page to get the token.

**Comment by C0derLint** [comment]
@gautamjajoo Sure

**Comment by gautamjajoo** [comment]
@C0derLint Hey! This issue is already reported in #1795 itself.

**Comment by gautamjajoo** [comment]
@RishabhJain2018 Please close this issue as well.
