### ISSUE TITLE
Disable auth token when account not activated

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#1913]
### Observed Behaviour
When a user is not activated , he is able to go to `Get your auth token` tab. Where it also downloads the json file with false message.

### Expected Behaviour
The tab should be disabled.

![screenshot from 2018-11-19 01-01-05](https://user-images.githubusercontent.com/24366008/48677232-9a881a00-eb97-11e8-80b8-1fec1a854fb0.png)

@deshraj @RishabhJain2018

**Comment by thesashi7** [comment]
> ### Observed Behaviour
> When a user is not activated , he is able to go to `Get your auth token` tab. Where it also downloads the json file with false message.
> 
> ### Expected Behaviour
> The tab should be disabled.
> 
> ### Would you like to work on it?
> Yes
> 
> ![screenshot from 2018-11-19 01-01-05](https://user-images.githubusercontent.com/24366008/48677232-9a881a00-eb97-11e8-80b8-1fec1a854fb0.png)
> 
> @deshraj @RishabhJain2018

Has anyone started working on this? If not then i would like to work on it.

**Comment by yashdusing** [comment]
@RishabhJain2018 @gautamjajoo is this taken ? If not, I'd like to work on it

**Comment by gautamjajoo** [comment]
@yashdusing I haven't made a PR regarding the issue but not sure if the issue is valid or not. Let it be confirmed by @RishabhJain2018 .

**Comment by RishabhJain2018** [comment]
Yup, I agree with the issue. Thanks @gautamjajoo for pointing it.

**Comment by sachinmukherjee** [comment]
Can I work on this?

**Comment by RishabhJain2018** [comment]
@sachinmukherjee I think you are already working on an issue, right?

**Comment by sachinmukherjee** [comment]
@RishabhJain2018 I have submitted a PR for the previous issue.

**Comment by RishabhJain2018** [comment]
I see..You can work on this :)

**Comment by yashdusing** [comment]
Actually even I have finished with my PR and I was working on it. So what should be done ? @RishabhJain2018 @sachinmukherjee

**Comment by yashdusing** [comment]
Thanks @sachinmukherjee !

**Comment by yashdusing** [comment]
@gautamjajoo Should the tab be disabled or the button ?

**Comment by gautamjajoo** [comment]
@yashdusing You could disable the button `Get you Auth token`.

**Comment by yashdusing** [comment]
Disable or freeze ?
