### ISSUE TITLE
Add test cases for Update submission data API

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1923]
Since we have an API for updating submission data after a remote evaluation is completed, so we would like to have it's unit cases.
Link to the API: https://github.com/Cloud-CV/EvalAI/blob/master/apps/jobs/views.py#L583

**Comment by Ayukha** [comment]
Can I take this up?

**Comment by RishabhJain2018** [comment]
Sure @ayukha you can work on it.

**Comment by RishabhJain2018** [comment]
@Aykha we will need these tests soon. So, can you please let us know what will be the ETA for the them.

**Comment by RishabhJain2018** [comment]
Sounds good. You can open up a PR so that I can help you.

**Comment by kurianbenoy** [comment]
@Ayukha @RishabhJain2018 can I work on this issue?
