### ISSUE TITLE
Two Loaders working at same time

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#1929]
### Observed Behaviour
When a user wants to participate in a challenge, there are two loaders that are working. As seen in the attached screenshot.

### Expected Behaviour
There should be only one loader working.

### Steps to Reproduce
Go to a challenge and participate in a challenge. When you register a team for the challenge, you can observe two loaders working at the same time.

### Would you like to work on it?
Yes

@deshraj @RishabhJain2018 

![image](https://user-images.githubusercontent.com/24366008/49066651-d5e5b100-f247-11e8-8a4e-ede20448ff8f.png)

**Comment by RishabhJain2018** [comment]
Hi, @Sanji515 Thanks for the PR. Please do ask for assignment of the issue before start working on it, so that it should be fair with other enthusiastic contributors.
