### ISSUE TITLE
Integrate django-spaghetti-and-meatballs to visualize database schema

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#193]
@RishabhJain2018 would you like to work on this? 

For reference: https://github.com/LegoStormtroopr/django-spaghetti-and-meatballs

**Comment by RishabhJain2018** [comment]
@deshraj yeah sure.

**Comment by deshraj** [comment]
Awesome. :-)

**Comment by deshraj** [comment]
Fixed in #196
