### ISSUE TITLE
Invalid comment in models.py

### ISSUE THREAD

**Issue by jarnugirdhar** [Cloud-CV/EvalAI#1931]
**The expected behaviour**
The comment should say """Returns the end date of Phase"""
**The observed behaviour**
It says: """"Returns the end date of Challenge"""
**Steps to reproduce the problem**
https://github.com/Cloud-CV/EvalAI/blob/2a8670a4d1e037329c38ebc7d1b8a49c4ebb2188/apps/challenges/models.py#L148

However the issue is insignificant but it might confuse contributors.

@RishabhJain2018 @deshraj 

Thanks!

**Comment by gautamjajoo** [comment]
@jarnugirdhar I am currently working on #1866. Will make the above change when I send the PR for the same.

**Comment by jarnugirdhar** [comment]
> @jarnugirdhar I am currently working on #1866. Will make the above change when I send the PR for the same.

Alright! :+1:
