### ISSUE TITLE
Verification mail is not being sent

### ISSUE THREAD

**Issue by supra08** [Cloud-CV/EvalAI#1934]
### Observed Behaviour

After the user signs up, no verification mail is being received, hence permission denied appears for further tasks.

### Expected Behaviour

The user should receive a verification email.

### Steps to Reproduce

Just signup for a new account and check your mail.

### Would you like to work on it?

Yes

@deshraj , @RishabhJain2018

**Comment by deshraj** [comment]
It looks like you have missed checking the terminal. Once you sign up, you will see the email content on the terminal itself in the development version. 

Closing this issue for now. Please feel free to re-open it if you cannot still see the email on terminal.

**Comment by supra08** [comment]
@deshraj can't we simulate the exact process of sending the mail? Why just printing it on the terminal?

**Comment by deshraj** [comment]
You can do that by changing email settings here https://github.com/Cloud-CV/EvalAI/blob/master/settings/dev.py#L21 but in the development environment, it's not recommended to use the original email.
