### ISSUE TITLE
Improve challenge creation pipeline

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#1938]
## Current Scenario

If you directly zip the challenge configuration and upload it on the server, then you see an error saying `zip file has more than one .yaml files` which is mainly the case due to temporary files added to the zip while zipping.

## Deliverables

- [ ] Handle the case where temp files are ignored while unzipping in challenge creation API
- [ ] Show a meaningful error rather than showing `zip file has more than one .yaml` files

## How to reproduce

You can reproduce this error by uploading the following challenge zip file to create a challenge. 
[challenge.zip](https://github.com/Cloud-CV/EvalAI/files/2642344/challenge.zip)

**Comment by vkartik97** [comment]
Can I work on this issue?

**Comment by deshraj** [comment]
Sure @vkartik97 :)
