### ISSUE TITLE
MacOS Installation Docker Installation Instructions

### ISSUE THREAD

**Issue by anigasan** [Cloud-CV/EvalAI#1945]
Installation instructions for MacOS (or for any OS using Docker) seems to be confusing. Credentials given in step 6 of Virtual Environment are common to both for Docker and Virtual Environment, they are made as part of Virtual Environment. Like installation instructions given for Fabrik, it is better to provide these details as part of instructions for both Docker and Virtual Environment.

**Comment by gautamjajoo** [comment]
@deshraj @RishabhJain2018 This issue can be closed. Fixed in #1946 .

**Comment by RishabhJain2018** [comment]
Thanks, @gautamjajoo for pointing this out.
Closing this issue too!
