### ISSUE TITLE
Add tests for get_broker_urls API

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1957]
We have added a new API in [apps/challenges/view.py](https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/views.py#L1330). Hence, tests are required in order to make the system robust.

Please feel free to ask if there are more questions/doubts. I'll be happy to help.

**Comment by inishchith** [comment]
@RishabhJain2018 can i take up this issue ? 😅

**Comment by RishabhJain2018** [comment]
sure! go ahead.

**Comment by inishchith** [comment]
@RishabhJain2018 Over [here](https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/views.py#L1340) we do not have a field `queue` in the database, i didn't get what values would be returned when `http://0.0.0.0:8000/api/challenges/get_broker_urls/` gets called . Am i missing something?

**Comment by RishabhJain2018** [comment]
We do have the field named `queue` in the database https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/models.py#L57. Also, the output format is shown here: https://github.com/Cloud-CV/EvalAI/pull/1948

Please let me know if you have some other questions too.
