### ISSUE TITLE
Viewing challenge stars should not require logging in

### ISSUE THREAD

**Issue by abhshkdz** [Cloud-CV/EvalAI#1964]
Without logging in:
<img width="287" alt="screen shot 2018-12-16 at 1 35 10 pm" src="https://user-images.githubusercontent.com/1156489/50057373-6f153280-0137-11e9-9bf8-cf6e3db93f84.png">

After logging in:
<img width="339" alt="screen shot 2018-12-16 at 1 35 00 pm" src="https://user-images.githubusercontent.com/1156489/50057372-6f153280-0137-11e9-8af0-3593377706a7.png">

**Comment by RishabhJain2018** [comment]
Sure! go ahead.
