### ISSUE TITLE
Update response format for the API

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1965]
The response formats in the API's here https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/views.py#L1330 should be of JSON type (Currently, it returns list) and consistent with other API's. For e.g. the `result` key should be used for showing the results and `error` key should be used for displaying the error.

Please feel free to ask if you have any doubts.

**Comment by inishchith** [comment]
@RishabhJain2018 In reference to the `get_broker_urls`, i had to convert the response to a list explicitly [here](https://github.com/Cloud-CV/EvalAI/pull/1961/files#diff-7b5c4a15a7006ac909ae8faa7b5d7e65R3040). 
Please let me know if i can work on this issue and subsequently make changes in the tests #1961 .
> For e.g. the result key should be used for showing the results and error key should be used for displaying the error.

In case of get_broker_url_by_challenge_pk :
```
{
'result' : ['queue-name-1']
}
```
In case of get_broker_urls:
```
{
'result' : [ 'queue-name-1',
             'queue-name-2']
}
```

**Comment by RishabhJain2018** [comment]
> Please let me know if i can work on this issue and subsequently make changes in the tests #1961 .
Yeah you can do this.

Also, the format pasted by you above looks good to me! Please do return a dict with `error` key in case of errors.

**Comment by inishchith** [comment]
> Please do return a dict with error key in case of errors.

@RishabhJain2018 `error` key is being used already here ( [1](https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/views.py#L1343) | [2](https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/views.py#L1361) | [3](https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/views.py#L1367) )
