### ISSUE TITLE
Frontend: incorrect "back" behavior from landing page

### ISSUE THREAD

**Issue by dhruvbatra** [Cloud-CV/EvalAI#1977]
Steps to reproduce:
- Go to https://evalai.cloudcv.org/ using Firefox
- Click on "Participate" button which links to https://evalai.cloudcv.org/web/challenges/list (other links have similar problems)
- Now press back in browser. 

Expected behavior: browser should go back to https://evalai.cloudcv.org/

Buggy behavior: browser goes to Firefox new tab (presumably because landing page never registered as a visit/page).

**Comment by deshraj** [comment]
It appears that #1977 didn't fix this issue. Reopening it so that we don't forget this issue.

**Comment by KhalidRmb** [comment]
Hi! New to EvalAI :) May I work on this for now?

**Comment by RishabhJain2018** [comment]
Hi @KhalidRmb Thanks for your interest! I think we have already resolved this issue. Please feel free to take up any other issue from the list. We have issues with labels as `good-first-issue` for beginners.
Also, do join our Gitter channel for your doubts. Feel free to ask questions/doubts you face while settings up EvalAI or solving the issue. I'll be happy to help.

**Comment by RishabhJain2018** [comment]
Closing this, since this is already fixed!
