### ISSUE TITLE
Add a decorator to check if the user has confirmed the email address or not 

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#198]
For most of the endpoints, we need to add a permission decorator that checks if the user has verified his email address or not. If not, then return json object that says "Please verify your account first".

**Comment by anweshknayak** [comment]
@deshraj can you assign this to me?

**Comment by deshraj** [comment]
Yeah, you can work on it. :-)

**Comment by anweshknayak** [comment]
if anyone wants to work on this feel free to do. I have my semester exams going on.

**Comment by deshraj** [comment]
Thanks @anweshknayak for letting us know. All the best for your semester exams. :-)

**Comment by deshraj** [comment]
Fixed in #245
