### ISSUE TITLE
Absence of decorators for authenticating and checking user status.

### ISSUE THREAD

**Issue by charanjit-singh** [Cloud-CV/EvalAI#1984]
I'd like to propose code standard optimisation:

**Observation**

- [Line 45](https://github.com/Cloud-CV/EvalAI/blob/master/apps/web/views.py), view notify_users_about_challenge will only rendered if and only if user is authenticated and it passes test of being a superuser. There are so many nested if else s, which can be eliminated by:

- [ ] Using Decorators: login_required and user_passes_test.

- [ ] Creating decorators for handling server error and page_not_found error.

Please note that there is no optimisation in performance. But the code management is effected.
For example we may want to handle 500 error for every view. So we cant use if else for handling. Usage of decorators can help there.

Thanks!

**Comment by vkartik97** [comment]
@charanjit-singh Great Observation! 
What do you think about using `permissions.IsAuthenticated` instead of  `login_required`?

**Comment by charanjit-singh** [comment]
Yes! using permissions will keep it in DRF's way.

**Comment by charanjit-singh** [comment]
And Instead of rendering 404.html in views, we should Raise `Http404 `Exception.

`from django.http import Http404`
