### ISSUE TITLE
Add feature to make the baseline entry by challenge host show on leaderboard

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#1995]
**Deliverables**: 

- [ ] Add a  Boolean field in submissions model `baseline_submission`
- [ ] Update API `change_submission_data_and_visibility` to change to toggle the value of the field `baseline`
- [ ] Add a column in the `My submissions`  table for challenge hosts only, so that they can toggle this functionality.
- [ ] In the leaderboard API after filtering the submissions while creating the `distinct_leaderboard_entry_list` , if the value of `baseline_submission` is True, then add it into this list otherwise ignore it.
- [ ] Add a tag on leaderboard as `baseline` to show which entries are baseline.

**Comment by vkartik97** [comment]
I am working on this issue

**Comment by RishabhJain2018** [comment]
Sure! you can take it up.

**Comment by RishabhJain2018** [comment]
@vkartik97 Is this issue completed? It would be nice if you'll complete the previous taken issues and then work on new one :)

**Comment by vkartik97** [comment]
@RishabhJain2018 I'll try to open PR for this ASAP

**Comment by RishabhJain2018** [comment]
Sounds good! Please complete it asap, till then @yashdusing you can take up #2070

**Comment by sanchit-ahuja** [comment]
Is this issue still open? @RishabhJain2018
