### ISSUE TITLE
Adding Non Test Source Files to Coverage Exclusion List

### ISSUE THREAD

**Issue by vkartik97** [Cloud-CV/EvalAI#1997]
Following Source Files are not used in Tests and are decreasing Coverage
- settings/custom_storages.py
- settings/staging.py
- settings/dev.py
![screenshot from 2019-01-15 02-19-49](https://user-images.githubusercontent.com/3920286/51140315-3ff3fd00-186c-11e9-9cd7-79bcc8b3cd97.png)

**Comment by RishabhJain2018** [comment]
Closing this one, since we already have an issue for the same!
