### ISSUE TITLE
Improper error message shown

### ISSUE THREAD

**Issue by Ayukha** [Cloud-CV/EvalAI#2006]
**Expected behaviour :**
"User not logged In" or similar error message.

 **Observed behaviour :**

![error](https://user-images.githubusercontent.com/19167324/51288077-838f6800-1a20-11e9-9464-ea738875462e.png)

**Steps to reproduce the problem :**

Click on star challenge without logging In.

**Comment by RishabhJain2018** [comment]
Sure! go ahead.
