### ISSUE TITLE
Update seed script to add broker url in challenge

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2014]
## Current Behaviour:

Currently, when the challenge is created using the seed script, the `queue` field is not populated.

## Expected Behaviour:
When the seed script is run, the `queue` field must be populated with the random string of 75 characters in length.

**Comment by yashdusing** [comment]
I'd like to take this up @RishabhJain2018

**Comment by RishabhJain2018** [comment]
Sure! You can work on it.
