### ISSUE TITLE
Change the submission visibility to public by default

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2019]
## Current Behaviour

Currently, when a submission is made then it is always private by default. A participant has to explicitly make it public to be visible on the leaderboard even if the leaderboard is public.

## Expected Behavior

The submission made should have the default visibility as public.

## Deliverables

- [ ] Change the `is_public` flag default value in Submissions model to `True`.
- [ ] Create the migrations for the same with name `Change_submission_visibility_default_to_public`

**Comment by vkartik97** [comment]
Can I take this issue?

**Comment by RishabhJain2018** [comment]
Sure!
