### ISSUE TITLE
Add a http response interceptor to catch all responses with status code 401

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2021]
## Current Behaviour

Currently, all the 401 responses are handled separately in different controllers which increases redundancy in the code.

## Expected Behaviour

A single function which will handle all the requests.

## Deliverables

- [ ] Create an interceptor service in `services.js` in order to catch all the response and check for 401 status code and return the response if there is 401 code in the response.
The below code can be utilized to create an interceptor service.

```
    angular
        .module('evalai')
        .service('utilities', utilities)
        .factory('authHttpResponseInterceptor',['$q','$location',function($q, $location){
            return {
                responseError: function(rejection) {
                    if (rejection.status === 401) {
                        localStorage.clear();
                        $location.path('/auth/login');
                    }
                    return $q.reject(rejection);
                }
            };
        }])
        .config(['$httpProvider',function($httpProvider) {
            //Http Intercpetor to check auth failures for xhr requests
            $httpProvider.interceptors.push('authHttpResponseInterceptor');
        }]);
```

- [ ] Remove all the 401 response codes from different controllers.

- [ ] Test the system end to end after removing the code.

**Comment by RishabhJain2018** [comment]
Sure! go ahead.

**Comment by RishabhJain2018** [comment]
Yeah, currently we don't have unit tests written for the frontend. I meant to test it manually if it is working or not. Can you please do that too!

**Comment by yashdusing** [comment]
@RishabhJain2018 Could you help me out producing 401 errors ? Most of the 401 errors are due to login timeouts and I'm not sure how to produce them on my build manually

**Comment by deshraj** [comment]
You can change the token expiration time to something like 30 seconds or 1 minute and then you will be able to reproduce this error. Change has to be made in this line: https://github.com/Cloud-CV/EvalAI/blob/master/settings/common.py#L194
