### ISSUE TITLE
Add feature to toggle leaderboard visibility by challenge host

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2022]
## Current Behaviour

The challenge host can view the challenge leaderboard but can't make it public/private after the challenge is completed.

## Expected Behaviour

A challenge host will be able to make the leaderboard public/private using the UI.

### Backend
- [ ] Add a check in `get_or_update_challenge_phase_split` API for PATCH requests that the requesting user should a challenge host or a member of challenge host team.
- [ ] Add two tests one when the requesting user is a member of host team and one if the user isn't the member of host team.

### Frontend
- [ ] Add a toggle button in the leaderboard tab of the challenge host which will appear when the leaderboard is selected.
- [ ] Add a function in the challenge controller to which will be bind to the above toggle button to change the visibility.

Please feel free to ask if you have some doubts!

**Comment by nileshprasad137** [comment]
I'm just getting started with the project and I'd like to work on this.

**Comment by yashdusing** [comment]
I'd like to take this up

**Comment by RishabhJain2018** [comment]
yeah, you can work on it. Please feel free to ask if you have any doubts.

**Comment by nileshprasad137** [comment]
Hi @RishabhJain2018 , I'd like to clarify two things..

1. > The challenge can view the challenge leaderboard but can't make it public/private after the challenge is completed.

Should challenge host be allowed to change visibility only after challenge completes or anytime?

2. If we have to use `get_or_update_challenge_phase_split`, should toggle button be presented to host only after he chooses challenge phase in leaderboard tab?

**Comment by nileshprasad137** [comment]
@RishabhJain2018 , When you have some time, can you clarify the above doubts. I'll submit the PR soon.

**Comment by RishabhJain2018** [comment]
Ohh..I missed this,

> Should challenge host be allowed to change visibility only after challenge completes or anytime?

Anytime the challenge host wants to toggle the visibility.

> visibility of challenge_phase_split model needs to be set to 1 for it to be private?
yeah.

> leaderboard_public status of challenge_phase table is not to be affected right?
right.

> If we have to use get_or_update_challenge_phase_split, should toggle button be presented to host only after he chooses challenge phase in leaderboard tab?

yeah, the toggle button should appear only after the challenge host chooses challenge phase and split in the leaderboard tab.

Please feel free to ask if you have some other questions too!
