### ISSUE TITLE
Editing hosted challenges directly doesn't work

### ISSUE THREAD

**Issue by yashdusing** [Cloud-CV/EvalAI#2025]
- The expected behaviour : 
     Editing any hosted challenge properties should go smoothly
- The observed behaviour :
     Editing gives off an error
- Reason : localStorage which should contain the current challenge is not updated when we directly go through the 'Hosted Challenges' section. Only the 'All Challenges' section updates the localStorage
- Steps to reproduce the problem :
     1. Create a challenge (don't go to the 'All Challenges' section)
     2. Go to Hosted Challenges page and select your hosted challenge
     3. Edit the properties

![screenshot_20190121_203454](https://user-images.githubusercontent.com/19976688/51482372-49292080-1dbc-11e9-9f02-305e080bde09.png)
![screenshot-0 0 0 0-8888-2019 01 21-20-36-11](https://user-images.githubusercontent.com/19976688/51482403-5b0ac380-1dbc-11e9-86c8-681fe09030f2.png)

Would I like to take this up ? 
Yes.
Thanks!

**Comment by sachinmukherjee** [comment]
I think this issue is already opened. Please check https://github.com/Cloud-CV/EvalAI/issues/1802

**Comment by yashdusing** [comment]
@sachinmukherjee this one is different.

**Comment by deshraj** [comment]
@yashdusing I am not sure if this is a bug. It seems more like someone is tampering with the local storage related to a particular hostname on the browser. It will cause the ame issue for every website (which uses local storage) if you just go ahead and delete the contents of the local storage. 

Please let me know if I am missing something here.

**Comment by yashdusing** [comment]
I should have used the term 'empty localStorage' carefully. What I meant was a localStorage that doesn't yet contain the newly created challenge

**Comment by deshraj** [comment]
Thanks for the clarification. This makes sense. It's a valid issue. Can you please update your issue description so that it is clear for anyone who reads it for the first time? :)
