### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by abhshkdz** [Cloud-CV/EvalAI#2036]
https://github.com/Cloud-CV/EvalAI/blob/fa2756c6e6c2c049f8fdf1649c05e1d0d1bf7ae1/frontend/src/views/web/challenge/participate.html#L90

https://github.com/Cloud-CV/EvalAI/blob/98065e3257db0cd629bc64b959a29bae519b0bfe/frontend/src/views/web/challenge/submission.html#L186

"Sorry, The Challenge is not active!" —> "Sorry, the challenge is not active."

**Comment by vkartik97** [comment]
Can I work on this issue?

**Comment by RishabhJain2018** [comment]
Sure! go ahead.

**Comment by abhshkdz** [comment]
https://github.com/Cloud-CV/EvalAI/blob/b9246417c50d4a7308a1ae05457e1be10bcf292d/frontend/src/views/web/featured-challenge/participate.html#L11

"Proceed to challenge page to participate in this Challenge!" —> "Proceed to challenge page to participate in this challenge."

https://github.com/Cloud-CV/EvalAI/blob/b9246417c50d4a7308a1ae05457e1be10bcf292d/frontend/src/views/web/featured-challenge/participate.html#L12

https://github.com/Cloud-CV/EvalAI/blob/fa2756c6e6c2c049f8fdf1649c05e1d0d1bf7ae1/frontend/src/views/web/challenge/participate.html#L96

"Please Log In to participate in this Challenge!" —> "Please log in to participate in this challenge."
