### ISSUE TITLE
Update Django version in docs

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#2040]
Django version was updated to `1.11.18`. It should be updated in [Docs](https://evalai.readthedocs.io/en/latest/architecture.html#django
) also
@deshraj @RishabhJain2018

**Comment by kurianbenoy** [comment]
Can I work on this issue @gautamjajoo ?

**Comment by RishabhJain2018** [comment]
Sure! @kurianbenoy .
