### ISSUE TITLE
Add feature for slack notification

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2041]
## Current Behaviour

Currently, when a challenge is created, submission is made or a contact message is received, EvalAI Admin doesn't get any notification.

## Expected Behaviour

A slack notification should be added for all the three events.

## Deliverables
- [ ] Create a common function in `base/utils` which will take input a slack webhook URL and a message to be sent to the slack.
- [ ] Add the notification for following events:
	- [ ] When a challenge zip is uploaded
	- [ ] When a contact message is received
	- [ ] When a submission is made
- [ ] Write test cases.

## Starter Code
```
def send_slack_notification(webhook=settings.SLACK_WEBHOOKS['default'], message=""):
    '''Send slack notification to any workspace
    
    Keyword Arguments:
        webhook {string} -- slack webhook URL (default: {settings.SLACK_WEBHOOKS['default']})
        message {str} -- JSON/Text message to be sent to slack (default: {""})
    '''

    try:
        response = requests.post(
            webhook,
            data=json.dumps({'text': str(message)}),
            headers={'Content-Type': 'application/json'}
        )
    except Exception as e:
        logger.info('Exception raised while sending slack notification. \n Exception message: {}'.format(e))
```

Please feel free to ask if you have any doubts!

**Comment by yashdusing** [comment]
I'd like to take this up

**Comment by RishabhJain2018** [comment]
Sure! go ahead.

**Comment by yashdusing** [comment]
@RishabhJain2018 What all information should be posted to the slack channel when any of these are created ? Just a notification or some other related info as well ?

**Comment by yashdusing** [comment]
@RishabhJain2018 what all test cases need to be written ? All I've done is include the send slack notification function, so should I write a test case for that ?
