### ISSUE TITLE
Bug while editing Participating Team name

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#2045]
### Observed Behaviour
When a user edits his team name he could see the previous name on the right side of the page. (See attached screenshot)

### Expected Behaviour
The team name on the right side should not be visible.

### Steps to Reproduce
 Make a Team and try to edit the team name/ you could cancel the change as well.

@deshraj @RishabhJain2018 

![2019-01-26](https://user-images.githubusercontent.com/24366008/51787380-19e92980-2197-11e9-9a6f-4fcfbc2ce531.png)

![2019-01-26 1 _li](https://user-images.githubusercontent.com/24366008/51787381-1c4b8380-2197-11e9-8b7d-fab0e982e729.jpg)

**Comment by Ayukha** [comment]
@gautamjajoo  This issue has already been reported. Please see #2017  is its same.
