### ISSUE TITLE
Center align the footer of dashboard when viewed below medium screen

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#2046]
The dashboard footer be aligned properly as in the homepage when viewed below medium screen size.
@deshraj @RishabhJain2018 

<table border="0">
<tr>
<td width="300">
<p align="center"><b> Observed </b></p>
<img src="https://user-images.githubusercontent.com/24366008/51787549-78afa280-2199-11e9-9a75-fa3835da104e.png" width="300" />
</td>
<td width="300">
<p align="center"><b> Expected </b></p>
<img src="https://user-images.githubusercontent.com/24366008/51787545-72b9c180-2199-11e9-8db6-c3f3a736d385.png" width="300" />
</td>
</tr>
</table>

**Comment by RishabhJain2018** [comment]
Sure! You can.

**Comment by Anonymous-2k18** [comment]
@RishabhJain2018 Can i still work on this or has it been resolved?
