### ISSUE TITLE
Display success and error message notification

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2047]
## Current Behaviour
We don't show a notification for success and error messages when a participant toggles the submission visibility.

## Expected Behaviour & Deliverable
Display a notification for both cases on Success and on Error.

**Comment by Ayukha** [comment]
Can I take this?

**Comment by RishabhJain2018** [comment]
Sure! You can work on this.

**Comment by indranilbiswas7** [comment]
is this issue still workable on ?

**Comment by Ayukha** [comment]
@indranilbiswas7 I have already opened a PR for this, please take up another issue.
