### ISSUE TITLE
Add leaderboard description field

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2048]
## Current Behaviour
Currently, we don't display leaderboard description under the leaderboard tab.

## Expected Behaviour
A text field which will display the description about the leaderboard.

## Deliverables
- [ ] Add a blank and nullable text field in the Challenge model with the name `leaderboard_description`.
- [ ] Name the migrations as `Add_leaderboard_description_field_in_challenge`
- [ ] Add a card on the frontend above the card for selecting phases to display the leaderboard with the heading `Description`
- [ ] Paste the screenshot of the leaderboard with some sample data in the `Description` card.

**Comment by vkartik97** [comment]
Can I work on this issue?

**Comment by RishabhJain2018** [comment]
Sure! you can work on this issue.

**Comment by indranilbiswas7** [comment]
is this issue still workable on ?

**Comment by vkartik97** [comment]
@indranilbiswas7 
I am working on this feature and about to make a PR for this.

**Comment by iamjayantk** [comment]
Is this issue still open?
Can i work on this issue?

**Comment by vkartik97** [comment]
Hi @iamjayantk 
I have opened a PR for this #2056
