### ISSUE TITLE
Feature Request: Show accuracy/submission stats on the challenge page

### ISSUE THREAD

**Issue by dhruvbatra** [Cloud-CV/EvalAI#2055]
People who visit a challenge page often want to know how active it is and what the rate of progress is (when did state of art last improve). 

Example on Codalabs: https://competitions.codalab.org/competitions/20687#learn_the_details

**Comment by Ayukha** [comment]
can i take this?

**Comment by nikhilmudholkar** [comment]
@RishabhJain2018 can you give some details for this issue?
