### ISSUE TITLE
Inaccuracy in page number in Existing Teams

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#2059]
### Observed Behaviour
When we have less than 10 teams on existing teams page, the intial page count is shown as 0. (Refer to the screenshot) 

### Expected Behaviour
The initial count should be 1.

### Steps to Reproduce
Go to any challenge in which you have not particpated. Select the `Participate` tab.

### Deliverables
- [ ] Update the intial page number on the participant side.
- [ ] Check for any other pagination issue and fix that too.

@deshraj @RishabhJain2018 

![capture](https://user-images.githubusercontent.com/24366008/52141011-74442780-267a-11e9-991e-d08d086ae9aa.JPG)

**Comment by Sanji515** [comment]
@RishabhJain2018 I want to work on this issue.

**Comment by gautamjajoo** [comment]
@Sanji515 Sure! You can work on this issue.

**Comment by anuj-rathore** [comment]
Since there is no progress, Can I take this now?

**Comment by Sanji515** [comment]
@anuj-rathore It's already under review.
