### ISSUE TITLE
Rewrite Participant Team api to remove dependency of challenge

### ISSUE THREAD

**Issue by TroJan** [Cloud-CV/EvalAI#206]
As of [b02d43](https://github.com/Cloud-CV/EvalAI/tree/b02d433b21e34a4c39985c6e490614d02435cfce), Participant model has foreign key to challenge. This means that to create entry for participant a challenge should exists. This could have been handled by making challenge a nullable foreign key, but this is not the way to do it.

Proposed solution involves a many to many key in challenge to participant team. Flow will be something like 

* Create a participant entry(without challenge dependency)
* When user clicks on `Participate in Challenge`, then pass challenge id and participant id to do entry in many to many mapping.

So this issue will involve updating participant team api to remove its dependency on challenge model. From now, participant will be independent of challenge. Mapping participant with challenge will be done in later release.

This also involves changing the url patters and tests. Also migration will be created for the same.

**Comment by deshraj** [comment]
Fixed in #207
