### ISSUE TITLE
Unnecessary notification for unverified users

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#2060]
### Observed Behaviour
When an un-verified user tries to see his profile, he is shown a blanck notification.

### Expected Behaviour
Remove the notification.

### Steps to reproduce
Create a user and go to the profile section. You could see a black notification popping out

@deshraj @RishabhJain2018 

![capture](https://user-images.githubusercontent.com/24366008/52142675-54fbc900-267f-11e9-8c29-4a9328d2cb44.JPG)

**Comment by yashdusing** [comment]
I'd like to solve this bug @gautamjajoo

**Comment by gautamjajoo** [comment]
@yashdusing Sure! You can work on this.

**Comment by RishabhJain2018** [comment]
I believe @yashdusing you are still on an issue. Hence this is still unassigned :)

**Comment by sachinmukherjee** [comment]
Can I work on this?

**Comment by RishabhJain2018** [comment]
Sure! You can work on this.
