### ISSUE TITLE
Update the Documentation for Monthly Submission Limit Per Team for Challenge Creation

### ISSUE THREAD

**Issue by vkartik97** [Cloud-CV/EvalAI#2061]
### *This is Issue is only for Newbies i.e. who haven't been assigned any issues yet*
Deliverables:
- [ ] Add field for *Monthly Submission Limit Per Team* to [`challenge_config.yaml` in EvalAI-Starters](https://github.com/Cloud-CV/EvalAI-Starters/blob/master/challenge_config.yaml)
- [ ] Update the [Challenge Creation Documentation](https://github.com/Cloud-CV/EvalAI/blob/master/docs/source/challenge_creation.md) for field added in [challenge_config.yaml](https://github.com/Cloud-CV/EvalAI-Starters/blob/master/challenge_config.yaml)

Important Links:
- EvalAI Website: https://evalai.cloudcv.org
- EvalAI Github repository: https://github.com/Cloud-CV/EvalAI
- EvalAI Docs: http://evalai.readthedocs.io/en/latest/
- Gitter Channel: https://gitter.im/Cloud-CV/

**Comment by Mike-Dai** [comment]
Hi, I'm new to CloudCV. can I work on this issue?

**Comment by vkartik97** [comment]
@Mike-Dai Sure! you can work on this issue.

**Comment by luck-u** [comment]
I am a newbie can i work on these issue please
