### ISSUE TITLE
Disable user to participate in a challenge when one of the user is unverified

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#2067]
### Observed Behaviour
When a verified user adds an unverified user to his team and then tries to participate in a challenge, he is successfully able to submit his entry to the challenge.
Please see the [screencast](https://drive.google.com/file/d/0B1bLU2zTKVNmRUhRSkVpSGRheEFQSmVHWTdUMnhaWnNXd2I4/view?usp=sharing) for reference.

### Expected Behaviour
If the user hasn’t verified and is invited to a team, then he/she cannot participate in the challenge. They have to first verify their email address.

@deshraj @RishabhJain2018

**Comment by KhalidRmb** [comment]
Can I take this one?

**Comment by RishabhJain2018** [comment]
Good Catch @gautamjajoo .
@KhalidRmb You can work on it.

**Comment by KhalidRmb** [comment]
@RishabhJain2018 We can consider being a verified user as a pre-requisite for being invited into any team. If not verified, we can display an appropriate message. 
Either that or to disable the submit tab until all team members are verified. What do you think?

**Comment by gautamjajoo** [comment]
@KhalidRmb We should allow all the users to be added in the team irrespective of the fact that the email address is verified or not. If the user hasn’t verified and is invited to a team, then he/she cannot participate in the challenge. They have to verify their email address.
cc: @RishabhJain2018

**Comment by KhalidRmb** [comment]
I see. In that case, we can throw an appropriate warning while inviting (i.e, you can't participate until the user is verified) and follow through by not displaying/throwing an appropriate error when a user tries to participate through the team under question. 
**P.S:** Isn't the whole purpose of creating a team to participate in a challenge? So, I thought a user is not to be added unless they're verified. The above step seems unnecessary. (As in, why at all add them to the team if they can't participate?).
@gautamjajoo  @RishabhJain2018

**Comment by akshay0505** [comment]
Is this issue still open. Can i work on it?

**Comment by KhalidRmb** [comment]
@akshay0505 I'm already doing this one. Take up other open issues :)

**Comment by prakharrathi25** [comment]
@gautamjajoo Hi, I'm new to the CloudCV community and would love to get started with this issue. Has this been resolved already or is there room for improvement? :)

**Comment by RishabhJain2018** [comment]
This is already fixed, hence closing.
