### ISSUE TITLE
Bug while editing evaluation script

### ISSUE THREAD

**Issue by Ayukha** [Cloud-CV/EvalAI#2068]
@RishabhJain2018 

![out](https://user-images.githubusercontent.com/19167324/52169141-e8a1c800-2759-11e9-8cb9-abfb685faf30.gif)

Text under Evaluation Criteria disappears.

**Comment by Ayukha** [comment]
@Sanji515  I have solved the issue and opened a PR for it.

**Comment by vkartik97** [comment]
Hi @Ayukha 
Thanks for opening an Issue and Making a PR for this!
Can you please correct the title `evaluation script` -> `evaluation criteria`, as `evaluation script` is used for Submission Evaluation. Please See [docs/source/challenge_creation.md](https://github.com/Cloud-CV/EvalAI/blob/master/docs/source/challenge_creation.md) and [docs/source/submission.md](https://github.com/Cloud-CV/EvalAI/blob/master/docs/source/submission.md)

**Comment by Ayukha** [comment]
Hi @vkartik97 
I think the title is correct as the bug was observed while trying to edit the evaluation script.
Please let me know if I'm missing something :)

**Comment by vkartik97** [comment]
@Ayukha 
The Title is correct!
Apologies :)
