### ISSUE TITLE
Automate the process of sending Emails to challenge hosts

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2070]
## Current Scenario

Whenever a user creates a challenge on EvalAI, then EvalAI admin has to send the email manually saying
```
Hi,

We noticed that you tried to create a challenge on EvalAI recently and you could not create it due to some reason. Please let us know if you need help in creating the challenge configuration for your challenge. We would be more than happy to help in creating the challenge.

Thanks,
EvalAI Team

```

## Deliverables

We would like to automate this process of sending the emails. We would like to use Send Grid API for sending the emails.

So, ideally, the flow should be - 
- [ ] A user creates a challenge on EvalAI
- [ ] An Email is sent to the user on the Email Id registered on EvalAI with the above content.

Please let me know if you have doubts about it.

**Comment by vkartik97** [comment]
Can I work on this issue?

**Comment by yashdusing** [comment]
Can i work on this?

**Comment by RishabhJain2018** [comment]
Assigning this to @vkartik97 . Opening some more issues shortly :)

**Comment by RishabhJain2018** [comment]
Since @vkartik97 is already working on an issue, so assigning this to @yashdusing .

**Comment by yashdusing** [comment]
@RishabhJain2018 do you mean the user tries to create the challenge ? Because the email says that the user was trying to create a challenge (and was unsuccessful) but the description says that the user was successful..

**Comment by RishabhJain2018** [comment]
So, what I meant is that user created a challenge on EvalAI but the worker needs to be restarted (which can only be done by EvalAI Admin) so that challenge can accept submissions (Now the challenge is created successfully). So, to start a conversation with challenge host we need this feature saying that the challenge isn't successfully created so that they don't announce it publically to participants for participation. Do you see what I mean?

**Comment by RishabhJain2018** [comment]
>  I initially thought that you meant that we need to send an email to users who tried sending in their zip file but did something wrong(like not upload the annotations file) so I wrote the logic with that in mind.

This is also a nice idea but we need to reframe the email content in that case though by adding emails for contacting EvalAI admin. I'll change the content for the email.  No, don't the logic for it. We can change the email content in both the situations and use a single function to send the email.

**Comment by sanchit-ahuja** [comment]
If this is issue is still open, I would like to work on it please.

**Comment by yashdusing** [comment]
@sanchit-ahuja I have already sent a PR for it. Please feel free to take up some other issue

**Comment by sanchit-ahuja** [comment]
Alright. It's really difficult to find any open issues right now. Almost all of the issues are taken.

**Comment by RishabhJain2018** [comment]
Don't worry, I'll open more in few hours :)
