### ISSUE TITLE
After deleting a challenge, redirect to Dashboard.

### ISSUE THREAD

**Issue by KhalidRmb** [Cloud-CV/EvalAI#2080]
**Current Behaviour:**
After deleting a challenge, the page does not change and the user can still modify the contents of the page which obviously won't persist. 
**Expected:**
As the challenge has been deleted, it makes more sense to redirect the user to some relevant page like the dashboard or the Hosted Challenges page.
@RishabhJain2018 

**Deliverables:** 

- [x] Add necessary frontend code to redirect the user to the aforementioned page after confirming the deletion.

**Comment by Sanji515** [comment]
@KhalidRmb @RishabhJain2018 I want to work on this issue.

**Comment by nikhilmudholkar** [comment]
@KhalidRmb @RishabhJain2018 can i work on this issue?

**Comment by ArshdeepSingh98** [comment]
@KhalidRmb @RishabhJain2018 can i work on this issue?

**Comment by ArshdeepSingh98** [comment]
I have written the code for this, if you want i can raise PR for this. This is my first time contributing and i don't know the procedure.

**Comment by KhalidRmb** [comment]
Hi! @ArshdeepSingh98 Sure, since you've already worked on this make a PR, but from next time it would be better to wait until it's assigned. :) Here's the process to make a PR: https://github.com/Cloud-CV/EvalAI/blob/master/.github/CONTRIBUTING.md.

**Comment by ArshdeepSingh98** [comment]
#2106 https://github.com/Cloud-CV/EvalAI/pull/2106/commits/b37b6c96185d41ee14e4f0574b5b54f9cb556ef1 Deleting challenge redirects to dashboard
