### ISSUE TITLE
Requirement Incompatibility

### ISSUE THREAD

**Issue by kurianbenoy** [Cloud-CV/EvalAI#2087]
Following warnings are show during `docker-compose build` when I was doing a fresh install. Certain packages in requirements are incompatible to certain other and would require changes in version no for certain package. I fell a long term solution other than using requirements.txt can also be thought about

```
docker-compose 1.21.0 has requirement PyYAML<4,>=3.10, but you'll have pyyaml 4.2b1 which is incompatible.
djangorestframework-expiring-authtoken 0.1.4 has requirement djangorestframework<=3.4.6,>=3.2.3, 
but you'll have djangorestframework 3.7.7 which is incompatible.
boto3 1.7.31 has requirement botocore<1.11.0,>=1.10.31, but you'll have botocore 1.10.12 which is incompatible.
```

#### Would you like to work on this issue?
Yes

**Comment by RishabhJain2018** [comment]
> I fell a long term solution other than using requirements.txt can also be thought about
Can you please share your thoughts about it?

**Comment by kurianbenoy** [comment]
The python requirements management is currently being criticised by a no of people like Armin Ronacher(creator of flask). The issue is being tried to fix by PSF also. What I feel is a better solution than current requirements.txt is `pipenv` [website]([https://pipenv.readthedocs.io/en/latest/). It has features like check to detect old packages which are incompatible. 

I am not sure how suitable `pipenv` is for EvalAI project and may need setup.py also to fix requriements. Also now pipenv is not yet mature and is now just about 2 years into development.
