### ISSUE TITLE
Add permission for all the members of host teams

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#2088]
### Observed Behaviour
If a user makes a host team with additional members in it, and then hosts a challenge. It is observed that the user who made the challenge is only able to delete the challenge and any other member of the team can't do it.

### Expected Behaviour
Add support for giving permissions to other team members of the host team .

### Deliverables
- [ ] Allow other members of the host team to delete the challenge.
- [ ] Check whether the other host members can't perform any other task and fix that too.

@deshraj @RishabhJain2018

**Comment by yashdusing** [comment]
I’d like to take this up

**Comment by yashdusing** [comment]
@gautamjajoo But I think that anyone besides the team lead shouldn't be allowed to make drastic changes to the host team. Instead of deleting, we could think of other privileges which are exclusive to the team lead (i.e. challenge creator/host)

**Comment by kurianbenoy** [comment]
Can I work on this issue @gautamjajoo @RishabhJain2018 @Ram81

**Comment by ArshdeepSingh98** [comment]
Can I work on this Issue, also how to add additional members in host team ?

**Comment by gautamjajoo** [comment]
@yashdusing You can work on this!

**Comment by gautamjajoo** [comment]
@yashdusing Are you working on the issue?

**Comment by yashdusing** [comment]
@gautamjajoo I have my exams coming up so I won’t be able to push out any commits for now. Is it alright if I solve the issue after 2 weeks?

**Comment by gautamjajoo** [comment]
@yashdusing Maybe there would be new issues till then and you can take up them! Till then this issue is open!!

**Comment by KhalidRmb** [comment]
@gautamjajoo  I'll work on this then. I've made PRs for my prev assignments and just waiting for a reply.

**Comment by Helinia** [comment]
I am more than happy to take on this issue. I haven't have any issue assigned and always looking for an open issue for me to work on! :) @gautamjajoo

**Comment by KhalidRmb** [comment]
So, right now only the creator can disable the challenge, delete the challenge or make any edits to the phase details or to the challenge details. So, I think we can make all the above available to the host team members as well. (But this will remove any exclusivity the creator has over the challenge.)

**Comment by KhalidRmb** [comment]
@gautamjajoo Maybe the disabling the challenge is to be kept exclusive to the creator as suggested by @yashdusing since it's rather drastic. We could add permissions for other hosts to edit challenge details & phase details, including changing the visibility of the challenge.
