### ISSUE TITLE
Create api to map a participant team with challenge.

### ISSUE THREAD

**Issue by TroJan** [Cloud-CV/EvalAI#209]
This is a big change. This will involve the following

* create a many to many mapping between __Challenge__ and __ParticipantTeam__. key can exist in either model, but we will be keeping it in Challenge model, because queries like _list all teams that have participated or are participating in a challenge_ will be more common and frequent than _get all challenges in which a team has participated or participating_. Both are easily retrievable but to facilitate convenience, __Challenge__ will have many to many key to __ParticipantTeam__ model
* migrations for the above
* an api which takes challenge id and participant team id in url and maps that challenge with a participant team. API is _POST_ only
* tests for the api

**Comment by deshraj** [comment]
Fixed in #210
