### ISSUE TITLE
Outdated zip_challenge.yml leads to creation of challenge that is already expired

### ISSUE THREAD

**Issue by nikhilmudholkar** [Cloud-CV/EvalAI#2092]
EvalAI takes metadata from zip_challenge.yaml file inside the test_zip_folder to create a new challenge. The start and end dates in the .yaml file are outdated. So if a new user when tries to create a new challenge, the challenge is already over when created. This creates a lot of issues, particularly while submission.

Deliverables:-
- Update the dates in zip_challenge.yml

**Comment by kurianbenoy** [comment]
Duplicate of #2151
