### ISSUE TITLE
Add leaderboard sorting for featured challenges

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2093]
## Current Scenario

Currently, the leaderboard fields can be sorted using the arrows under the `All Challenges Tab` as shown here https://evalai.cloudcv.org/web/challenges/challenge-page/161/leaderboard/483 but when the same challenge is in `Featured challenges` then the arrows don't appear as shown here: https://evalai.cloudcv.org/featured-challenges/161/leaderboard/483 

## Expected Scenario

The arrows should appear on both the challenge pages and the entries should be sorted using these arrows.

Hint:
https://github.com/Cloud-CV/EvalAI/blob/master/frontend/src/views/web/challenge/leaderboard.html#L42

**Comment by yashdusing** [comment]
@RishabhJain2018 I'd like to take this up

**Comment by RishabhJain2018** [comment]
Sure! you can work on it.

**Comment by RishabhJain2018** [comment]
This issue is still open :)

**Comment by Sanji515** [comment]
> This issue is still open :)

@RishabhJain2018 Can I work on this issue?

**Comment by RishabhJain2018** [comment]
Sure! you can work on this.

**Comment by kurianbenoy** [comment]
@RishabhJain2018 , can I work this issue. I will put a PR now itself

**Comment by yashdusing** [comment]
@kurianbenoy since @sanji515 is already assigned for the PR I think you should ask to be assigned first before working on a PR

**Comment by Sanji515** [comment]
@yashdusing @kurianbenoy  ok, that's fine, waiting for another issue to work on :)

**Comment by kurianbenoy** [comment]
Sorry @Sanji515. I thought the issue was of high priority that's why I worked on it immediately. Also seeing 2 people being assigned to work on the issue, I thought maybe I can also come in and start working :smiley:

**Comment by RishabhJain2018** [comment]
Closing this one because we are not redirecting users to the featured challenges page now.
