### ISSUE TITLE
Redirect users to Profile section on less than medium screen

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#2103]
### Observed Behaviour
When a user visits any page on less than medium screen and tries to see `Profile` section, he is redirected to Home page.  You could see the Profile section from homepage only.

### Expected Behaviour
The user should be directed to the `Profile` page. 

@deshraj @RishabhJain2018

**Comment by Sanji515** [comment]
@deshraj @RishabhJain2018 @gautamjajoo I want to work on this issue.

**Comment by ArshdeepSingh98** [comment]
@deshraj @RishabhJain2018 @gautamjajoo I would like to work on this issue ?

**Comment by gautamjajoo** [comment]
@Sanji515 You can work on it!
