### ISSUE TITLE
Add Updates to docs

### ISSUE THREAD

**Issue by kurianbenoy** [Cloud-CV/EvalAI#2104]
- In [submission page](https://evalai.readthedocs.io/en/latest/submission.html) the `url namespace` link points to the django 1.10 docs
- In [Approve submission page](https://evalai.readthedocs.io/en/latest/approve_challenge.html) Reloading Submission worker is done by command `docker-compose reload worker `. Current the command reload is replaced by [restart](https://docs.docker.com/compose/reference/restart/)

**Comment by kurianbenoy** [comment]
@RishabhJain2018 @deshraj is this issue necessary?

**Comment by RishabhJain2018** [comment]
Hi, @kurianbenoy Thanks for updating the documentation. Can you create two separate PR's for docs and leaderboard fix.
