### ISSUE TITLE
Add unit tests for get_challenge_phase_by_pk API

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2109]
There are missing unit tests for the API added in #2108

**Comment by Sanji515** [comment]
@RishabhJain2018 I want to work on this issue but I haven't written unit tests before.

**Comment by RishabhJain2018** [comment]
Sure, you can work on it! For reference, you can take a look at the `tests/` folder in the repository. Also, feel free to ask if you have some doubts.

**Comment by Sanji515** [comment]
@RishabhJain2018 I've added the unit tests but how can I verify if they are correct.

**Comment by kurianbenoy** [comment]
@Sanji515 haven't you put a PR for this issue?

**Comment by Sanji515** [comment]
@kurianbenoy Hii!!, yup! I've already dropped a PR 3 days ago.
