### ISSUE TITLE
Add tests for the add_participant_team_to_challenge API

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2110]
Add tests for adding participant team to the challenge API if the challenge is docker based.
The API is written [here](https://github.com/Cloud-CV/EvalAI/commit/09741c1ccf259660c426d70f955d8d935fa68550#diff-ff54996dc8925e4c7dbde340701c7086R233).
For mocking the boto3 requests to ECR, please use https://github.com/spulec/moto

**Comment by Mike-Dai** [comment]
Can I work on this issue?

**Comment by RishabhJain2018** [comment]
Sure @Mike-Dai You can work on this.

**Comment by Mike-Dai** [comment]
@RishabhJain2018 Since it's my first time to write tests I'm confused about it. Should I add tests in `class MapChallengeAndParticipantTeam(BaseAPITestClass)` in `tests/unit/challenges/test_view.py`?

**Comment by Mike-Dai** [comment]
@RishabhJain2018 I should test whether the ecr repository is successfully created or not and whether the participant team has the correct `docker_repository_uri` or not, right? Please correct me if my understand is wrong.

**Comment by kurianbenoy** [comment]
@Mike-Dai can I work on this issue. If you are feeling difficulty to understand this challenge

**Comment by kurianbenoy** [comment]
Can I take up this issue?

**Comment by yashdusing** [comment]
@Mike-Dai I’ll try to solve the confusions you have.
@RishabhJain2018 correct me if I’m wrong.
The tests will be of the following things:
1. The one you mentioned
2. Make another same name participant team and check whether the docker ecr entry is the same.
3. Hidden test cases like getting ecr name wrong, etc.
There might be some I missed and I think @RishabhJain2018 can explain these better but you can get started writing these first off

**Comment by Mike-Dai** [comment]
@yashdusing Thank you for your explanation!
@kurianbenoy I'm sorry for my late response. I'm still working on this issue.
