### ISSUE TITLE
Display submission pk in the submissions table in admin

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2111]

**Comment by nikhilmudholkar** [comment]
I would like to work on this issue

**Comment by RishabhJain2018** [comment]
sure @nikhilmudholkar, you can work on this issue!

**Comment by nikhilmudholkar** [comment]
@RishabhJain2018 
The primary key should be a new field in the table or is there some particular field which has to be made as the primary key. 
If the latter is true then which field has to be made as primary key?

**Comment by sanchit-ahuja** [comment]
Is this issue still open? If yes, I would like to work on it please. Thank You

**Comment by nikhilmudholkar** [comment]
I am already working on it. Just waiting for @RishabhJain to clarify some doubts.
Feel free to take up some other issue :)

**Comment by jebinphilipose** [comment]
@RishabhJain2018 I would like to work on this issue since its still open. Thank you.

**Comment by gautamjajoo** [comment]
@nikhilmudholkar Are you working on it?

**Comment by Ayukha** [comment]
@RishabhJain2018  This issue can be closed.

**Comment by RishabhJain2018** [comment]
Thanks for pointing it @Ayukha.
Fixed by #2309 .
