### ISSUE TITLE
Add feature to resend verification Email link

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2122]
## Description
Suppose the user loses verification email without verifying the link, then neither user will be able to verify his account nor create a new account with the same email address. 

## Deliverables
- [ ] API endpoint to resend verification email (Use #1355 as a reference)
- [ ] Front to show the link (Use #1354 as a reference)

Also, there should be button/Link ("Resend Verification Email" ) inside rounded (dark red) portion of the following screenshot. 
![screenshot from 2017-02-05 11 39 21](https://cloud.githubusercontent.com/assets/7015220/22624135/31d25094-eb98-11e6-882d-26bf2c090d00.png)

**Comment by ArshdeepSingh98** [comment]
I would like to work on this issue.

**Comment by RishabhJain2018** [comment]
Sure @ArshdeepSingh98 , you can take this issue.

**Comment by dhruveshk** [comment]
no one else can work on it then?

**Comment by AlwaysHumble** [comment]
Sir , I would like to work on this issue.

**Comment by RishabhJain2018** [comment]
Hi @ArshdeepSingh98 are you still working on this issue?

**Comment by ArshdeepSingh98** [comment]
yes, i am working on it. I had some issues with backend setup but now they are resolved.

**Comment by chidauri** [comment]
Hi @RishabhJain2018 i,ve worked on the issue.How do i test?

**Comment by ArshdeepSingh98** [comment]
Hi, feel free to take this issue because i will not be able to do this on time as i am still learning.

**Comment by geekayush** [comment]
@RishabhJain2018
Can I take this up?

**Comment by kurianbenoy** [comment]
> Hi, feel free to take this issue because i will not be able to do this on time as i am still learning.
@ArshdeepSingh98 if you are not working on this can I work on this. @RishabhJain2018 can you  assign this issue to me?

**Comment by krishnadey30** [comment]
@RishabhJain2018 I would like to take this issue if no one is working in it currently.

**Comment by kurianbenoy** [comment]
I had made some work on this issue. WIth almost 50% completed(ie the
backend part). I will complete the rest in a week or two
[image: photo]
*Kurian Benoy*

+91 9400125402 <+91+9400125402> | kurian.bkk@gmail.com

https://kurianbenoy.github.io/
<http://us.linkedin.com/in/kurian-benoy-75642b120>
<http://github.com/kurianbenoy> <http://twitter.com/kurianbenoy2>
<http://medium.com/@kurianbenoy1998>

**Comment by krishnadey30** [comment]
Ok @kurianbenoy

**Comment by KhalidRmb** [comment]
@kurianbenoy I'm actually done with this and since this is a high-priority issue, will make a PR now. Just a  heads-up :)

**Comment by hk1997** [comment]
Is this issue still open, I would love to work on this

**Comment by Suryansh5545** [comment]
Can i work on it?
