### ISSUE TITLE
Modify the tweet button in the footer for sharing the webpage

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2123]
For Reference:
1. https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview.html
2. https://help.twitter.com/en/using-twitter/add-twitter-share-button

**Comment by sachinmukherjee** [comment]
I want to work on this

**Comment by kurianbenoy** [comment]
Can I work on this issue?

**Comment by nikhilmudholkar** [comment]
I would like to work on this as well

**Comment by kurianbenoy** [comment]
@RishabhJain2018 do you want a tweet button which redirects to tweet with some hash tag's and contets like 

` --------------------       #OpenSOurce #EvalAI @CloudCV`

**Comment by shaunak-badani** [comment]
@RishabhJain2018 could you please elaborate on what modifications you would like to the footer button, as I am unable to understand the exact issue? Some screenshots with what it is now vs what you would like would be great. Also, is this the tweet button you are referring to?
![eval-ai issue](https://user-images.githubusercontent.com/32260623/54979365-fd1b7780-4fc8-11e9-90f8-eed7096a07fa.jpg)

**Comment by kurianbenoy** [comment]
Hello @shaunak-badani, yes that is tweet button. So on clicked that button a share button like this should come like this:
![Uploading 53038318-742d8f80-34a2-11e9-8197-346c5754160d.png…]()

Even I am doubtful on exact message to be shared using the tweet share button but I made a PR #2139 regarding that
