### ISSUE TITLE
Hide pagination buttons when tab is changed

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#2126]
### Observed Behaviour
When we select a phase and see the submissions for the same and then change the tab, the pagination buttons and the `Total Submissions Done` are still visible.

### Expected Behaviour
The pagination buttons and `Total Submissions Done` should not be visible after a tab is changed.

### Deliverables
- [ ] Hide the pagination buttons.
- [ ] Hide the text showing`Total Submissions Done` 
- [ ] Fix the bug for both, `My Submissions` and `View All Submissions`.

@deshraj @RishabhJain2018 

![screenshot from 2019-02-15 16-53-25](https://user-images.githubusercontent.com/24366008/52854005-3697d200-3143-11e9-9307-c7b1feb4dd82.png)

**Comment by sachinmukherjee** [comment]
Can I work on this

**Comment by Sanji515** [comment]
@RishabhJain2018 @gautamjajoo Can I work on this issue?

**Comment by ArshdeepSingh98** [comment]
Can i work on this ?

**Comment by RishabhJain2018** [comment]
@ArshdeepSingh98 You are already assigned #2122 . Please finish that then you can take this up.

**Comment by nikhilmudholkar** [comment]
can i work on this issue?

**Comment by rohitjha941** [comment]
Can i work on this

**Comment by gautamjajoo** [comment]
@sachinmukherjee Hey! You can take this up since you commented first.

**Comment by sachinmukherjee** [comment]
@gautamjajoo  I'm not able to see View all Submission Tab. Here is the screenshot for that
![image](https://user-images.githubusercontent.com/19318218/53299570-f7176700-3861-11e9-8574-9a101eae0405.png).

**Comment by Sanji515** [comment]
@sachinmukherjee Hi!, maybe you should log in as a host user for `view all submissions` tab

**Comment by KhalidRmb** [comment]
Hi! @sachinmukherjee What's the status on this one? Can I work on this?

**Comment by sachinmukherjee** [comment]
I have solved the issue. Will create a pull request within 2 days.
