### ISSUE TITLE
Update seed script to add challenge slug

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2131]
## Current Behaviour:
Currently, when the challenge is created using the seed script, the `slug` field is not populated.

## Expected Behaviour:
When the seed script is run, the `slug` field must be populated with the challenge title and it must include a year in the name to keep it unique like `abc-challenge-2019`

**Comment by kurianbenoy** [comment]
Can I work on this issue?

**Comment by RishabhJain2018** [comment]
Sure!
