### ISSUE TITLE
Remove duplicate statements from Tests

### ISSUE THREAD

**Issue by vkartik97** [Cloud-CV/EvalAI#2134]
Statement `self.challenge_phase.save()`  [tests/unit/jobs/test_views.py](https://github.com/Cloud-CV/EvalAI/blob/master/tests/unit/jobs/test_views.py)  has been repeated at **multiple places**. 
For example, At [tests/unit/jobs/test_views.py#L680](https://github.com/Cloud-CV/EvalAI/blob/master/tests/unit/jobs/test_views.py#L680):
```python
self.challenge_phase.save()
self.challenge_phase.save()
```
#### Deliverables
- [ ] Remove duplicates of `self.challenge_phase.save()`

<br>

Please feel free to work on this issue and let me know if you have questions. :)

**Comment by rohitjha941** [comment]
Can I work on this

**Comment by kurianbenoy** [comment]
Can I work on this issue?

**Comment by vkartik97** [comment]
As @rohitjha941 commented first, assigning it to @rohitjha941 .

**Comment by kurianbenoy** [comment]
Okay @vkartik97. I am pretty close to finishing the issue. I hope @rohitjha941 can easily fix this issue soon.

**Comment by rohitjha941** [comment]
> Can I work on this

#2136   will solve this issue

**Comment by luck-u** [comment]
can i work on this issue
