### ISSUE TITLE
Add SIOP logo in "Who uses EvalAI" list.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2137]
Here is the SIOP [logo](https://drive.google.com/file/d/1zcw3uqDyM1iHha-o1_zUzKSAkt__98sG/view)

**Comment by Ayukha** [comment]
@RishabhJain2018 Can I take this?

**Comment by RishabhJain2018** [comment]
@Ayukha Please complete the previous issue before taking this one.

**Comment by anuj-rathore** [comment]
Can I take this issue?

**Comment by yashbhutoria** [comment]
May I fix this issue ?

**Comment by yashbhutoria** [comment]
Fixed in #2185, please review.
