### ISSUE TITLE
Add feature for filtering the submissions

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2141]
## Current Scenario

If there are a large number of submissions in a challenge and a challenge host wants to view all the submissions for a participant team then they have to scroll through all the submissions.

## Expected

The challenge host should be able to filter the submissions by participant team name in `View All Submissions` Tab.

## Deliverables
- [ ] Add the required API's.
- [ ] Add the required frontend UI.

Please feel free to discuss the approach before start coding.

**Comment by Sanji515** [comment]
Can i work on this issue?

**Comment by anuj-rathore** [comment]
Can I take this, as I am done with my previous issue?

**Comment by Sanji515** [comment]
@anuj-rathore You can take #2142 issue.

**Comment by RishabhJain2018** [comment]
Wait, wait. I'm here to help :)

Since @Sanji515 you commented first, you can take this one. @anuj-rathore Please take the issue #2142 or you can wait I'm opening some more issues.

**Comment by yashdusing** [comment]
@RishabhJain2018 Could you please take a look at the proposal I've sent ?

**Comment by RishabhJain2018** [comment]
Yeah, I've it in my todo's. I'll get to it soon.

**Comment by Sanji515** [comment]
@RishabhJain2018 For frontend should I add another `dropdown` similar to `phase list` populated with the list of the participating team for filtering?

**Comment by RishabhJain2018** [comment]
Hmm..I am thinking of having a `Filter Submissions` button near the `Download` button under `View All Submissions` Tab which will appear when the host will select a phase. Upon clicking that button a modal comes up saying
`Filter submissions by using participant team` with a list of participant teams having input as a checkbox and of course scrollable, out of which the host selects one or multiple participant teams` and the submissions by those team will appear in the results.

@deshraj Thoughts on this?

**Comment by deshraj** [comment]
After having an offline discussion with @RishabhJain2018, we have converged on trying to get a search based filtering implemented instead of filtering through a modal. This will be a much simpler approach and provides a better user experience. 

So basically the flow will be something like this:

1. Select phase to see all submissions
2. Enter submission id or team name in a search box to filter the submissions
3. Show filtered submissions

See the following demo to get a sense of what we are looking for: http://plnkr.co/edit/XklvXtc1AZpndjLvXrh8?p=preview

**Comment by Sanji515** [comment]
So we are going to give to option for filtering one with `submission ID` and another with `team name` and the user can select among these two options, by which method he wants to search like in the `demo` dropdown is given for `Designation, name and company name`.
am I right? @RishabhJain2018 @deshraj

**Comment by RishabhJain2018** [comment]
yeah

**Comment by Sanji515** [comment]
@RishabhJain2018 @deshraj Please have a look to screencast.

![recording 4](https://user-images.githubusercontent.com/32524438/53214800-01740e00-3674-11e9-86c4-a9aa80ea98a6.gif)

**Comment by Helinia** [comment]
@Sanji515 Could I ask which tool did you use to make this amazing gif? Many thanks!

**Comment by Sanji515** [comment]
@Helinia **Screencast-O-Matic** :)

**Comment by Sanji515** [comment]
> @RishabhJain2018 @deshraj Please have a look to screencast.
> 
> ![recording 4](https://user-images.githubusercontent.com/32524438/53214800-01740e00-3674-11e9-86c4-a9aa80ea98a6.gif)

@RishabhJain2018 @deshraj Please look into it.

**Comment by deshraj** [comment]
@Sanji515 this looks good in general. We might have more comments when we try it on our local machine. There might be some UI alignment we would want to do. Can you please open a PR for this?

**Comment by Sanji515** [comment]
@deshraj @RishabhJain2018 sure!
