### ISSUE TITLE
Create a unique link for each of the entry on the leaderboard

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2143]
## Current Scenario

If a participant wants to share their rank in a challenge on twitter/facebook then they have to share the entire leaderboard link.

## Expected scenario
There should be a unique link for each entry and upon opening, it should scroll to that particular entry and highlight it.

**Comment by kurianbenoy** [comment]
I was interested to work on this issue, yet as mentioned in PR #2097 I am unable to obtain a submission to be shown in leaderboard. With proper help, I hope I can solve this issue :smile:

**Comment by yashdusing** [comment]
@RishabhJain2018 Can I take this up if no one's working on this ?

**Comment by Ayukha** [comment]
@RishabhJain2018  Can I take this up? I've finished working on my previous issue.

**Comment by sarthak212** [comment]
@RishabhJain2018 Can i take this issue..?

**Comment by Ayukha** [comment]
@RishabhJain2018 , As @yashdusing  and @kurianbenoy have shown interest in solving other issues. May I start working on this one?

**Comment by kurianbenoy** [comment]
I am not currently interested to work on this issue. I hope the mentors can assign some one else

**Comment by sarthak212** [comment]
@RishabhJain2018 Can i take this .?I think i can solve this..

**Comment by shaunak-badani** [comment]
@RishabhJain2018 I can try to solve this. I think I can solve it
