### ISSUE TITLE
Update the test zip challenge in the example folder

### ISSUE THREAD

**Issue by yashdusing** [Cloud-CV/EvalAI#2151]
The challenge zip in the examples folder uses the python 2 version of the script which causes an issue with the submission worker.
Update the script and the yaml file dates as well
![screenshot_20190225_230622](https://user-images.githubusercontent.com/19976688/53356735-17beea00-3952-11e9-8057-81a71f6ab6df.png)

**Comment by sanchit-ahuja** [comment]
Can I take this issue?

**Comment by yashdusing** [comment]
@sanchit-ahuja sure !

**Comment by UpcominTerminator** [comment]
Hey can I take up this Issue

**Comment by sanchit-ahuja** [comment]
@UpcominTerminator . Hi! I am working on this issue. I will try to submit a Pull request today. You can take up another issue. :)

**Comment by yashdusing** [comment]
@sanchit-ahuja are you still working on this ?

**Comment by sanchit-ahuja** [comment]
Not right now. You may assign to anyone else.

**Comment by kurianbenoy** [comment]
If no is assigned. May I work on this issue as fixed the issue locally in my system. I can put the PR today itself

**Comment by yashdusing** [comment]
@kurianbenoy sure !
