### ISSUE TITLE
can't able to build and run

### ISSUE THREAD

**Issue by luck-u** [Cloud-CV/EvalAI#2159]
observed behavior: when I run sudo docker-compose up --build the error comes up
Starting evalai_sqs_1 ... 
Starting evalai_nodejs_1 ... 
Starting evalai_sqs_1
Starting evalai_nodejs_1
Starting evalai_db_1 ... error

ERROR: for evalai_db_1  Cannot start service db: driver failed programming external connectivity on endpoint evalai_db_1 (4d07fb63496320fc7ae31d3623679376daaafcae4c325d5de5fb3457555b2db1): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use
Starting evalai_nodejs_1 ... error
ERROR: for evalai_nodejs_1  Cannot start service nodejs: driver failed programming external connectivity on endpoint evalai_nodejs_1 (adbd02e83b94b6b11abcf5fb03d4ce5880a9160eb60eda03fbbfad032e54a740): Error starting userland Starting evalai_sqs_1 ... done

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint evalai_db_1 (4d07fb63496320fc7ae31d3623679376daaafcae4c325d5de5fb3457555b2db1): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use

ERROR: for nodejs  Cannot start service nodejs: driver failed programming external connectivity on endpoint evalai_nodejs_1 (adbd02e83b94b6b11abcf5fb03d4ce5880a9160eb60eda03fbbfad032e54a740): Error starting userland proxy: listen tcp 0.0.0.0:8888: bind: address already in use
ERROR: Encountered errors while bringing up the project.

expected behavior: It should build and run on localhost in the given link:https://127.0.0.1:8888

**Comment by gautamjajoo** [comment]
Hey @luck-u ! Check [common errors](https://evalai.readthedocs.io/en/latest/faq(developers).html#common-errors-during-installation) page, you could find the solution for your problem there. Also, you can redirect the issues you are facing during installation to the [gitter](https://gitter.im/Cloud-CV/EvalAI/) channel. Thanks! :)

**Comment by deshraj** [comment]
@luck-u it looks like your port 5432 and 8888 are already occupied by some other process. Please kill them first. See our [FAQ](https://evalai.readthedocs.io/en/latest/faq(developers).html#q-getting-the-following-error) page that @gautamjajoo pointed you to. Closing this issue meanwhile. Plese feel free to re-open it issue persists.

**Comment by luck-u** [comment]
Thanks @gautamjajoo and @deshraj issue solved
