### ISSUE TITLE
Mock AWS ECR requests for development environment

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2160]
## Current Behaviour

When the challenge is docker based then in the development environment you can't participate in it.

## Expected Behaviour

The challenge host and participant in the development environment should be able to participate in the docker based challenges.

## Fix
Mock boto3 ECR repository API calls in the development environment same as we do for AWS SQS.
Resource that can be useful: https://github.com/spulec/moto

**Comment by vkartik97** [comment]
Can I work on this issue?

**Comment by RishabhJain2018** [comment]
Sure but you are still working on https://github.com/Cloud-CV/evalai-cli/issues/145 issue. Please finish that issue first.

**Comment by Ayukha** [comment]
Can i take this ?

**Comment by RishabhJain2018** [comment]
Sure, you can take this issue.

**Comment by Ayukha** [comment]
Yes, I've finished working on my previous assigned issue.

**Comment by Helinia** [comment]
I would love to take this one if the problem needs to transfer someone else in the future.

**Comment by kurianbenoy** [comment]
> I would love to take this one if the problem needs to transfer someone else in the future.

Even I too would like to work on this problem, if its transferred to someone in fututre
