### ISSUE TITLE
Fix challenge page display on mobile 

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2162]
## Current Behaviour
The tabs on the mobile are not properly aligned as shown here -
![file](https://user-images.githubusercontent.com/12206047/53713501-12addf00-3e19-11e9-8abc-472dc1732838.jpg)

## Expected Behaviour
Fix the alignments.

**Comment by geekayush** [comment]
@RishabhJain2018 Can I work on it?

**Comment by RishabhJain2018** [comment]
Sure, you can work on this issue.

**Comment by Anonymous-2k18** [comment]
@geekayush Have you solved this issue or can I solve this issue?

**Comment by Anonymous-2k18** [comment]
@RishabhJain2018  Can I work on this if @geekayush  is not able to resolve the issue?

**Comment by shaunak-badani** [comment]
@RishabhJain2018 I can also try to work on it.

**Comment by RishabhJain2018** [comment]
Hi @GearGit @shaunak-badani I think @geekayush has already opened a PR for it.

**Comment by GearGit** [comment]
@geekayush have you fixed the issue?

**Comment by geekayush** [comment]
@GearGit Yes. I am working on the changes requested.
