### ISSUE TITLE
couldn't approve a challenge 

### ISSUE THREAD

**Issue by nadzma** [Cloud-CV/EvalAI#2167]
Hello I am runny EvalAI locally using docker. I created a challenge , but I couldn't approve it using the superuser django admin interface.  I checked the official documentation
https://evalai.readthedocs.io/en/latest/approve_challenge.html

However I couldn't approve the challenge since I couldn't access it (The title of the challenge is not a link in my Django admin interface)

- the expected behaviour : click on the challenge title and approve the challenge
- the observed behaviour: the challenge title is not a link so I couldn't click on it

<img width="1201" alt="django admin" src="https://user-images.githubusercontent.com/33626402/53823314-d17d1280-3f71-11e9-8a74-a7b7e36a3d5a.png">

Thanks!

**Comment by KhalidRmb** [comment]
Hi! @nadzma .To approve a challenge, you can click the hyperlink in the 'ID' column, scroll down and check the 'Approved by Admin' checkbox.

**Comment by nadzma** [comment]
@KhalidRmb  Thank you so much for your answer

**Comment by gautamjajoo** [comment]
@nadzma Was your issue resolved?

**Comment by nadzma** [comment]
@gautamjajoo  Yes it was resolved

**Comment by gautamjajoo** [comment]
Closing this since it is resolved. @nadzma Please free to ping the gitter channel for any other issue you face during installation.
