### ISSUE TITLE
Misplaced logout button in mobile view

### ISSUE THREAD

**Issue by cafeshoes** [Cloud-CV/EvalAI#2169]
# Logout button falls out of the menu bar in mobile view

### Observed behaviour : 
![screencapture-evalai-cloudcv-org-web-host-analytics-2019-03-08-04_19_57 1](https://user-images.githubusercontent.com/20144724/53995095-0481fa80-415a-11e9-8ad1-82013b5bf335.png)

### Expected behaviour : 
![4](https://user-images.githubusercontent.com/20144724/53995587-7e66b380-415b-11e9-809d-f30aab5c792c.png)

OS: Android Pie ( tested on Motorola G5 Plus )

P.S. If this is by design, it is a bit inconvenient design, I guess.

**Comment by rohitjha941** [comment]
Can i work on this

**Comment by GearGit** [comment]
@cafeshoes I would like to work on this, can you tell me the width, height of the mobile that you tried it on, so that I can inspect the page.

**Comment by GearGit** [comment]
After inspecting the source code I came to the conclusion that in the file.EvalAI\frontend\src\views\web\partials\sim-header.html
under <div class="nav-wrapper">
 <a href="javascript:void(0)" data-activates="mobile-demo" class="button-collapse sim-header-link"><i class="fa fa-bars"></i></a>

this is the reason that logout button is misplaced. <a> contains the logo and <i> contains the hamburger button for menu.

Right now I am thinking of updating css in such a way that the media screen won't show the logo while it will show only the hamburger button.

**Comment by geekayush** [comment]
@cafeshoes @GearGit #2162 A similar issue already exists.

**Comment by RishabhJain2018** [comment]
Thanks, @GearGit for reporting it but I'm closing it since it is the duplicate issue of #2162 .
