### ISSUE TITLE
Fix the feature of editing challenge details

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2172]
## Current Behaviour

When a challenge host tries to edit the challenge details after creating a challenge then the details aren't edited.

## Expected Behaviour
The challenge should be able to edit the challenge details in the challenge.

**Comment by KhalidRmb** [comment]
@RishabhJain2018 I would like to work on this :).

**Comment by RishabhJain2018** [comment]
Sure! It would be really nice if you can fix this asap.

**Comment by KhalidRmb** [comment]
Noted. 
Just a clarification: What all details exactly do you mean? 
Currently, only the host team creator can edit anything in the challenge (we thereby need to add a permission class for host team members as well).
Also, the edit is successfully made only upon going through `All Challenges` page and displays an error through `Hosted Challenges` page.

**Comment by KhalidRmb** [comment]
It seems that issue #2088 and #2025 are related to this.

**Comment by KhalidRmb** [comment]
If everything's alright I can go ahead and make a PR to satisfy both 1 & 2 above. (Since #2035 is stale.)
