### ISSUE TITLE
Active states of links in SideBar

### ISSUE THREAD

**Issue by geekayush** [Cloud-CV/EvalAI#2178]
The active states in SideBar are not properly set. The issue exists for almost every link.

- the expected behaviour
Example: The dashboard link should be in active state ( bold font ) when on dashboard as shown in the screenshot below.

- the observed behaviour
![Screen Shot 2019-03-12 at 01 44 58](https://user-images.githubusercontent.com/22499864/54154699-8a5aba00-4468-11e9-84ee-02dd218cb092.png)

**Comment by Sanji515** [comment]
@RishabhJain2018 @geekayush Can I work on this issue?

**Comment by geekayush** [comment]
@Sanji515 Let @RishabhJain2018 confirm the issue then you can surely work on it.

**Comment by RishabhJain2018** [comment]
Hi, @geekayush Thanks for reporting this issue. Since you've reported the issue would you like to work on it?

**Comment by kshitizkashyap** [comment]
@RishabhJain2018 Can I fix this?

**Comment by sarthak212** [comment]
@geekayush @RishabhJain2018 I would like to work on this if no one is assigned.
