### ISSUE TITLE
Add status in contact messages

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2179]
## Current Behaviour

If there are multiple EvalAI admins then it is not clear in contact messages if one admin has resolved it or not.

## Expected Behaviour
Add a choice field in the contact model with status as `pending` and `resolved` having default as `pending`.

## Deliverables
- [ ] Add the fields in the model.
- [ ] Display it in Contact admin.

**Comment by Sanji515** [comment]
@RishabhJain2018 Can I work on this issue?

**Comment by RishabhJain2018** [comment]
Sure!

**Comment by sumitskj** [comment]
can i work on this issue if it's not solved?
