### ISSUE TITLE
Display GitHub stats in footer

### ISSUE THREAD

**Issue by C-Anirudh** [Cloud-CV/EvalAI#2187]
**The observed behaviour**
![Screenshot from 2019-03-13 18-00-49](https://user-images.githubusercontent.com/40494926/54291736-08d36b00-45d3-11e9-910e-9ce64ab986b3.png)
 
**The expected behaviour**
Count of stars and forks displayed properly.

**Comment by C-Anirudh** [comment]
@RishabhJain2018  can you help me with this?

**Comment by gautamjajoo** [comment]
@C-Anirudh Can you verify once more. It is working on my end!

**Comment by C-Anirudh** [comment]
@gautamjajoo the stats aren't visible to me locally or in the [website](https://evalai.cloudcv.org/).

**Comment by gautamjajoo** [comment]
@C-Anirudh Which browser are you using?

**Comment by C-Anirudh** [comment]
@gautamjajoo I am using Google Chrome 72

**Comment by gautamjajoo** [comment]
@C-Anirudh It is working for me!
![Capture](https://user-images.githubusercontent.com/24366008/54607427-51c46d00-4a74-11e9-954a-97f74ec4bfd0.JPG)

**Comment by C-Anirudh** [comment]
@gautamjajoo It most probably is an error from my side, I will look into it again.

**Comment by gautamjajoo** [comment]
@C-Anirudh Feel free to open if you still face the issue

**Comment by C-Anirudh** [comment]
@gautamjajoo issue was caused by AdBlocker , sorry for the trouble.
