### ISSUE TITLE
Add unit tests for create challenge API

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2188]
## Current Scenario
There are no unit tests for create challenge using zip [API](https://github.com/Cloud-CV/EvalAI/blob/c156f3d54c95861c4ac4eaef1d2e3419bab83a7a/apps/challenges/views.py#L488) 

## Deliverables
- [ ] Add unit tests for the API

**Comment by KhalidRmb** [comment]
I'd like to do this @RishabhJain2018

**Comment by RishabhJain2018** [comment]
sure @KhalidRmb . Please feel free to ask doubts if you have any.

**Comment by KhalidRmb** [comment]
Surely @RishabhJain2018 . Just wanted to remind you to take a look at #2172 comments when you can. Thanks!

**Comment by RishabhJain2018** [comment]
yep, I've it on my list. I'll review it soon.

**Comment by KhalidRmb** [comment]
@RishabhJain2018 Unit tests for this already exist:
https://github.com/Cloud-CV/EvalAI/blob/c156f3d54c95861c4ac4eaef1d2e3419bab83a7a/tests/unit/challenges/test_views.py#L2101
Infact the coverage of the challenge/views.py file is 100%.

**Comment by KhalidRmb** [comment]
So, this issue to be closed right?

**Comment by RishabhJain2018** [comment]
Hey @KhalidRmb,I missed this the test cases are there but all the cases aren't covered in it.

**Comment by KhalidRmb** [comment]
@RishabhJain2018 
There are 2 ways we can proceed:
1. Use a sandbox to create the YAML file (different for each test as keys will be different) & the final zip file (with other files chosen from the examples folder), and send it in the post request.
2. Use a mock of the API and test the specific functionality without using any additional YAML file. Thereby verifying that the backend works properly, and sends the proper response.

What do you suggest?

**Comment by sanchit-ahuja** [comment]
Can I take this issue?

**Comment by KhalidRmb** [comment]
@sanchit-ahuja I'm working on this one. Will make a PR soon.
