### ISSUE TITLE
Display error on UI while creating challenge

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2189]
## Current Behaviour
When there are syntax errors in the `yaml` challenge configs then the challenge creation using zip [API](https://github.com/Cloud-CV/EvalAI/blob/c156f3d54c95861c4ac4eaef1d2e3419bab83a7a/apps/challenges/views.py#L575) fails with 500 Internal Server error which should not be the case.

## Expected Behaviour
The API should give a proper error with 406 error code. The error should be displayed on the UI.

## Resources
For creating a challenge zip, please use [EvalAI-Starters](https://github.com/Cloud-CV/EvalAI-Starters)

**Comment by Sanji515** [comment]
@RishabhJain2018 Can I work on this issue?

**Comment by RishabhJain2018** [comment]
Sure!

**Comment by Sanji515** [comment]
@RishabhJain2018 Should I show all the syntax errors of the yaml file on the UI (over toast) or just show the message saying `There is a syntax error on the yaml file, Please correct them before creating challenge!`

**Comment by Sanji515** [comment]
@RishabhJain2018 Can you please confirm my comment?

**Comment by RishabhJain2018** [comment]
Hi @Sanji515, It'd nice to show all the specific errors.
