### ISSUE TITLE
Display total number of participated participant teams in a challenge

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2194]
# Current Scenario
We don't display the total number of participant teams in a challenge.
The API is already written in `analytics` app.

## Expected scenario
The total number of participant teams in a challenge should be displayed here:
![Screenshot 2019-03-14 at 5 10 11 PM](https://user-images.githubusercontent.com/12206047/54391764-3e805e80-467c-11e9-8483-c8923d8be420.png)

**Comment by vkartik97** [comment]
Can I work on this issue?

**Comment by RishabhJain2018** [comment]
Sure!
