### ISSUE TITLE
Challenges not displayed on the challenge page if > 10

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2197]
## Current Behaviour:
If there are more than 10 challenges on the challenge page then those challenges aren't displayed on the page.

## Expected Behaviour:
All the challenges should be displayed on the challenge page.

## Deliverables - 
- [ ] The API already returns the challenge data along with a URL for the next set of challenges.
- [ ] Make an API call to the next URL and append the data into the existing list in the controller.
- [ ] Terminate the appending once the `next` field is null in the API's response.

**Comment by vkartik97** [comment]
Can I work on this issue?

**Comment by RishabhJain2018** [comment]
Sure!
