### ISSUE TITLE
Error while executing evaluation script 

### ISSUE THREAD

**Issue by nadzma** [Cloud-CV/EvalAI#2200]
I have a bug after submitting a solution

- the expected behaviour : After submitting a solution , I access "my submissions" and I can see my score , Execution Time , Result file , STDout file , STDERR file
- the observed behaviour : All these value are "None" , Show on Leaderboard: N/A 
<img width="878" alt="Capture d’écran 2019-03-15 à 16 49 16" src="https://user-images.githubusercontent.com/33626402/54524489-628cba00-4972-11e9-91bb-b8abdbedc683.png">
<img width="854" alt="Capture d’écran 2019-03-15 à 17 04 18" src="https://user-images.githubusercontent.com/33626402/54524490-628cba00-4972-11e9-9286-31e0d15b46bd.png">

When I run : docker-compose up --build , I got this message error
worker_1  | ModuleNotFoundError: No module named 'challenge_data.challenge_2'

When I submit a solution I got this error: 
worker_1  | [2019-03-18 12:45:37] ERROR Exception while receiving message from submission queue with error 'NoneType' object has no attribute 'get'
Thanks!

**Comment by RishabhJain2018** [comment]
Hey @nadzma, Please restart the worker after approving the challenge from the backend. It'll work fine. I'm closing this issue, for now, please feel free to reopen it if you still face some problem.

**Comment by nadzma** [comment]
Hey @RishabhJain2018    Unfortunately I still having the same issue by restarting the python worker:

<img width="1013" alt="Capture d’écran 2019-03-19 à 11 27 17" src="https://user-images.githubusercontent.com/33626402/54599178-61bf5b00-4a3a-11e9-989b-cd83e9ca0364.png">
<img width="605" alt="Capture d’écran 2019-03-19 à 11 27 35" src="https://user-images.githubusercontent.com/33626402/54599179-6257f180-4a3a-11e9-897c-7a132c93da75.png">
<img width="1010" alt="Capture d’écran 2019-03-19 à 11 28 03" src="https://user-images.githubusercontent.com/33626402/54599180-6257f180-4a3a-11e9-9df5-c5b6c2af14cf.png">
<img width="1018" alt="Capture d’écran 2019-03-19 à 11 28 16" src="https://user-images.githubusercontent.com/33626402/54599181-6257f180-4a3a-11e9-9461-1a02063a5d03.png">
