### ISSUE TITLE
error while executing evaluation script

### ISSUE THREAD

**Issue by nadhem-zmandar** [Cloud-CV/EvalAI#2202]
#2200 
I still  couldn't have a result after the submission.In fact I tried to restart the python worker But I still have the same error. Could any one help me please ?

**Comment by RishabhJain2018** [comment]
@nadzma Did you approve the challenge first before restarting the worker. Here is the documentation: https://evalai.readthedocs.io/en/latest/approve_challenge.html

**Comment by nadzma** [comment]
@RishabhJain2018  Yes I followed all the steps in the official documentation but when I approve the challenge and restart the submission worker I have this error on the terminal : 
worker_1  | ModuleNotFoundError: No module named 'challenge_data.challenge_2'
evalaibis_worker_1 exited with code 1

**Comment by nadzma** [comment]
PS : I managed to fix the problem But every time I approve a new challenge and before restarting the worker I should execute  : 

sudo pip uninstall requests
sudo pip install requests
sudo pip uninstall docopt
sudo pip install docopt

Could you help me to solve the problem definitely ?

**Comment by RishabhJain2018** [comment]
hey, @nadzma Don't worry, we'll be able to fix it. Which challenge config are you using?

**Comment by nadzma** [comment]
Hey @RishabhJain2018  I am using the one given in EvalAI-Starters

**Comment by RishabhJain2018** [comment]
I'm not sure what errors are you getting. Can you please post the screenshot here?>

**Comment by nadzma** [comment]
Hey @RishabhJain2018  So after approving the challenge and restarting the worker I get this errors
<img width="1369" alt="Capture d’écran 2019-03-22 à 14 53 31" src="https://user-images.githubusercontent.com/33626402/54828368-54150a00-4cb4-11e9-86a4-6d8f0dfecbbf.png">

**Comment by kurianbenoy** [comment]
@nadzma its ok for evalai_worker_1 to fail like that. Just go to: `localhost:8888` and check if the EvalAI website is rendered. 

If you want to make worker running(which is needed when submitting challenge entries). Go to another terminal and run the command: `docker-compose restart`. This usually works for me

**Comment by nadzma** [comment]
@kurianbenoy  Thank you for your answer. Unfortunately I couldn't solve the problem
I did like this
1)Run the EvalAI dev setup using docker-compose up in the EvalAI folder where docker-compose.yml is present.
2)Check if all the 5 containers are running using docker ps
3)Create a challenge by logging in using host account using the EvalAI-Starters repository.
4)Approve the challenge using Django Admin on http://127.0.0.1:8000/admin
5)Restart the worker container using docker-compose restart worker
6)Go to another terminal and run the command: docker-compose restart
7)Create a submission by logging in using participant account and it should be evaluated successfully

But I still have the same error and the submission worker doesn't work. So I have the status of the submission : submitted and not finished. could you help me through your experience with this issue.

**Comment by kurianbenoy** [comment]
Please ensure you pull from upstream and run command `docker compose up --build` before running.

As your challenge is already approved, go to this page:
![image](https://user-images.githubusercontent.com/24592806/55331288-973f5c00-54b0-11e9-9e6b-8a43cf2a3807.png)

Then upload evaluation_script.zip as submission:
![Screenshot-2019-4-1 EvalAI Evaluating state of the art in AI](https://user-images.githubusercontent.com/24592806/55331483-fe5d1080-54b0-11e9-8ca2-1e9f85d29bef.png)

![Screenshot_20190401_190938](https://user-images.githubusercontent.com/24592806/55331872-d4f0b480-54b1-11e9-9077-5e15f5135068.png)


Before submitting, go to terminal and run 

> docker ps

Ensure that evalai_worker is running. Incase its not working and showing a evalai_worker exit code. Go ahead and run:

> docker-compose restart worker

Then upload submission and ensure _evalai_worker has not Exited during this time_. Then go to submission tab and click option for show entry in leaderboard. Now go ahead and look leaderboard for test_phase.

If you are still facing any issues, just comment here

**Comment by nadzma** [comment]
I've followed all the steps . when I submit I get an other error on the terminal and the status is submitted and not finished
<img width="1334" alt="Capture d’écran 2019-04-02 à 11 55 23" src="https://user-images.githubusercontent.com/33626402/55393944-7d4c5a80-553e-11e9-90b0-24646ebd5e81.png">

**Comment by kurianbenoy** [comment]
@RishabhJain2018 now the submission worker abruptly stops in development environment. Also why is there two workers: remote_worker and evalai_worker?

**Comment by nadzma** [comment]
@kurianbenoy   Do you have this error while submitting a solution ?

**Comment by KhalidRmb** [comment]
I think that the 2 workers have to do with the fact that the host should be able to evaluate the submission on a remote server of their own if they choose so (this will be different from the EC2 container of the submission worker on the same instance as of the other containers). It's a new feature I think.

**Comment by RishabhJain2018** [comment]
This is resolved, closing it.
