### ISSUE TITLE
Outdated Python 2 code while creating challenge using zip file.

### ISSUE THREAD

**Issue by KhalidRmb** [Cloud-CV/EvalAI#2203]
**Observed behavior:** When the serializer is not valid while creating a challenge, the error message never gets sent due to incompatible python 2 code which raises an error. Instead, the control is redirected to the except block, sending a generic message.

**Expected behavior:** The serializer error should be sent in the response when appropriate.

**Reason:** This happens because because of this line https://github.com/Cloud-CV/EvalAI/blob/1dde5467e6cfc4c7338f0107757025f5f80d1fed/apps/challenges/views.py#L940
In Python 3, dictionaries  return "view" objects from the `values()` which are iterable but don't support indexing. In python 2, they returned lists.
@RishabhJain2018 @deshraj

**Comment by KhalidRmb** [comment]
I'm working on this.

**Comment by kurianbenoy** [comment]
Duplicate of #2151
