### ISSUE TITLE
Display error message when Leaderboard schema is missing while creating challenge.

### ISSUE THREAD

**Issue by KhalidRmb** [Cloud-CV/EvalAI#2206]
**Expected behavior**: A message like the following `"There is no leaderboard schema in the YAML configuration file. Please add it and then try again!"` with 406 status code should be returned when the schema is missing from the YAML file. This provides information to the user as to what needs to be done.

**Observed behavior:** A 500 internal server error.

**Deliverables:**
- [ ] Change the API to return appropriate response when the schema is not present.

@RishabhJain2018 @deshraj

**Comment by RishabhJain2018** [comment]
Thanks, @KhalidRmb for reporting it. Since you're working on another issue. This issue is open for all to work on.

**Comment by shiv6146** [comment]
@RishabhJain2018 can I take this up??

**Comment by RishabhJain2018** [comment]
Sure @shiv6146

**Comment by shiv6146** [comment]
Meanwhile @RishabhJain2018 please go through #2205 whenever you find time :+1: Thanks!
