### ISSUE TITLE
Add a feature to send emails to all the participants of a challenge

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2207]
## Current Behaviour
If a `challenge host` wants to send an email to all the participants of a challenge then they have to download the `csv` file for all the submissions and send the email manually.

## Expected Behaviour
We want to automate this process in which the challenge host should have to fill the subject, body and any attachments and the email is sent automatically.

## Deliverables
- [ ] Add the required API's.
- [ ] Add the required frontend code. 
- [ ] Make sure that the feature is only accessible to the challenge host of that challenge.

**Comment by yashdusing** [comment]
@RishabhJain2018 Can I take this up ?

**Comment by Sanji515** [comment]
@RishabhJain2018 Can I work on this?

**Comment by KhalidRmb** [comment]
@RishabhJain2018 Can I work on this?

**Comment by RishabhJain2018** [comment]
@Sanji515 You can take this up.

**Comment by Sanji515** [comment]
@RishabhJain2018 I'm thinking to give `trix-toolbar` for some styling content of `body of the email` but currently the styling of `trix` is not upto the mark. So should I write my own `trix.css` or update the current one. If I update the current one, then where should I update it

**Comment by PalashTanejaPro** [comment]
Hey @RishabhJain2018, this issue hasn't been active since half a month and no PRs have been made. I wrote some sample code for this, can I open a PR?
