### ISSUE TITLE
Add support for installing requirements from the requirements.txt file in the challenge config.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2208]
## Current Scenario
Since we're having challenge specific workers paired with challenge specific queues, suppose if a challenge host wants to install some custom requirements for a particular challenge, then we have to install it for all the challenge workers which should not be the case.

## Expected Scenario
There should be a file in the evaluation script `requirements.txt` which contains these requirements and the worker while starting up should check for this file and if this file is present then it should install the dependencies first and then load the challenge evaluation script.

Please feel free to ask if you've doubts.
For creating sample challenge use `EvalAI-Starters` repository.

**Comment by mahim23** [comment]
@rishabhjain2018 can I work on this issue?

**Comment by KhalidRmb** [comment]
I would like to work on this. @RishabhJain2018

**Comment by yashdusing** [comment]
@RishabhJain2018 I'd like to work on this

**Comment by RishabhJain2018** [comment]
@KhalidRmb You can take this up.

**Comment by KhalidRmb** [comment]
Sure! @RishabhJain2018 could you please review #2172  and corresponding PR #2174 ?

**Comment by RishabhJain2018** [comment]
@KhalidRmb Since you are working on #2188, I'm sorry you can't work on this. As a piece of advice please do make sure that you've opened up the PR for the issue you were working on and then pick another issue.

This issue is open for all to work on. :)

**Comment by vkartik97** [comment]
Can I work on this issue?

**Comment by RishabhJain2018** [comment]
Sure!
