### ISSUE TITLE
Add a feature to change the status of a submission by challenge host

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2210]
## Current Scenario
If a challenge host wants to cancel the submission status of submission, then they can't do it. They have to approach EvalAI admin in order to do it.

## Expected Scenario
The challenge host should be able to change the submission status using UI.

**Comment by mahim23** [comment]
@rishabhjan2018 can I work on this?

**Comment by RishabhJain2018** [comment]
Sure, I was about to mention you :)

**Comment by mahim23** [comment]
Hey @RishabhJain2018 , I was going through the repo trying to figure out how it works and the changes I need to make. So as I've understood, I need to 
* give a provision for the "host" of the challenge in the UI to change the status of any submission (to *any* of the possible `STATUS_OPTIONS`?). 
* provide an API endpoint in django to change the status and save it. 

Did I miss anything? I've started working on the backend and will send a WIP PR soon.

**Comment by RishabhJain2018** [comment]
yeah, this seems to be correct.

**Comment by mahim23** [comment]
@RishabhJain2018 So the closest API is `change_submission_data_and_visibility` which changes the submission data. But this API needs the user that requested it to be a participant of the team that made the submission. This is not the case in this feature/issue. So I've created a new API named `change_submission_status`. Is that fine?
