### ISSUE TITLE
Command not copied properly

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2214]
When a challenge is docker based then the command `evalai set_token <auth_token>` isn't copied properly. Basically, the token isn't copied.

 
<img width="1161" alt="Screenshot 2019-03-20 at 1 44 50 PM" src="https://user-images.githubusercontent.com/12206047/54706996-8ab51e00-4b16-11e9-9652-128e44c9789b.png">

**Comment by Ayukha** [comment]
Can I take this?

**Comment by RishabhJain2018** [comment]
Sure! please fix this asap.
