### ISSUE TITLE
Add filtering package for and unit tests

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2219]
## Current Scenario
Since we require #2129 urgently, hence the unit tests are missing in it. Also, the standard way to do filtering is using [django-filters](https://github.com/carltongibson/django-filter).

## Expected Scenario

Modify the API to use django filters and write the unit tests.

## Deliverables
- [ ] Add django-filters package in requirements.
- [ ] Modify the API to use django-filters
- [ ] Add unit tests for the API.

**Comment by sudharsana-kjl** [comment]
Hey! can I work on this issue?

**Comment by RishabhJain2018** [comment]
Hi @sudharsana-kjl Welcome to CloudCV! Sure, you can work on this.

**Comment by kurianbenoy** [comment]
Can I be the next person on waiting list to work on this @RishabhJain2018 ?

**Comment by sudharsana-kjl** [comment]
Hey @RishabhJain2018! Do you want to use django-filter to ```get_submissions_for_challenge``` API as discussed in #2129 or do you want to add this to other APIs as well?
