### ISSUE TITLE
Add discussions tab and star button to featured challenge

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#2232]
### Observed Behaviour
When a user visits a featured challenge on the homepage when he/she is not logined, the discussion tab and star button is not visible. (Ref : attached screenshot)

### Expected Behaviour
The discussion tab ans star button should be visible on the challenge page.

@RishabhJain2018 @deshraj 

![featured_challenge](https://user-images.githubusercontent.com/24366008/54900060-ebb66a80-4ef7-11e9-8840-6764aeee13e1.PNG)

**Comment by kurianbenoy** [comment]
Can I work on this issue?

**Comment by RishabhJain2018** [comment]
Sure @kurianbenoy !

**Comment by gautamjajoo** [comment]
@RishabhJain2018 Do we need to add star button also?

**Comment by RishabhJain2018** [comment]
yep.

**Comment by adrijshikhar** [comment]
is this issue resolved?

**Comment by RishabhJain2018** [comment]
Closing this since we will remove featured challenges.
