### ISSUE TITLE
Update method to store queue name in Challenge model

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#2238]
Currently, we store the queue name for each challenge using something like this:

```
challenge_queue_name = "{}-{}-{}".format(challenge_title, challenge_pk, random_challenge_id)[:75]
```

Where the challenge title can be any string. But SQS does not allow special characters in the queue name and hence we should validate the queue name before storing it. 

## Deliverables

- [ ] Write a utils function that generates a valid SQS queue name given a string as an input
- [ ] Use the function written in the previous step to generate the queue name for a challenge
- [ ] Write tests to check if the function created in the first step is robust enough

**Comment by tawAsh1** [comment]
Can i work on this?

**Comment by deshraj** [comment]
@tawAsh1 Go ahead. :)

**Comment by pushkalkatara** [comment]
Hi,

Is this issue resolved?

**Comment by Sanji515** [comment]
Hey @pushkalkatara , I think it is already been added [here](https://github.com/Cloud-CV/EvalAI/blob/master/apps/base/utils.py#L196). Hence this issue can be closed @RishabhJain2018 @deshraj 

Feel free to take another issue @pushkalkatara

**Comment by Sanji515** [comment]
@pushkalkatara but the tests still left for that function, so if you want then you can work on writing tests for it.

Thanks!

**Comment by pushkalkatara** [comment]
@Sanji515 The tests were also written in the pull requests. Due to conflicts, it was not merged and the [PR](https://github.com/Cloud-CV/EvalAI/pull/2244/commits/f863e09d8c1a628209ee1b9e6c695133f2c2428f) was closed due to inactivity. Should I add the tests @deshraj?

**Comment by RishabhJain2018** [comment]
Sure @pushkalkatara .

**Comment by pushkalkatara** [comment]
@RishabhJain2018 ive added the tests. please review #2450
