### ISSUE TITLE
Add team in ParticipantAdmin class in Participant app

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#224]

**Comment by gauthamzz** [comment]
isnt this already solved ? #220

**Comment by deshraj** [comment]
@gauthamzz My bad. Actually we want to add `team` in the ParticipantAdmin model. Updating the issue title.

**Comment by deshraj** [comment]
`team` should be present in `list_display`, `search_fields` and `list_filter`.

**Comment by jainarunarunjain** [comment]
@deshraj Is anyone working on it

**Comment by deshraj** [comment]
I don't think so. If you want, you can work on this.

**Comment by jainarunarunjain** [comment]
@deshraj Sure

**Comment by RishabhJain2018** [comment]
@deshraj I think team is already there in the ParticipantAdmin class. What do you say?

**Comment by deshraj** [comment]
Yup. Thanks for pointing @RishabhJain2018 . Forgot to close this one. 

Fixed in #226. Closing it now.
