### ISSUE TITLE
Allow unverified user to view the challenge

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#2241]
### Observed Behaviour
If an unverified user tries to view a challenge page, he is not able to do so and is told to verify the email first.

### Expected Behaviour
The unverified user should be allowed to view the challenge page and if he visits the `Participate` tab , an error stating to verify email address should be shown.

@RishabhJain2018 @deshraj

**Comment by sachinmukherjee** [comment]
Can I work on this?

**Comment by daniel22373** [comment]
Hi, can I start working on this? @gautamjajoo

**Comment by RishabhJain2018** [comment]
Thanks @daedaldan , @nikochiko for the efforts but we already have this page https://evalai.cloudcv.org/web/challenges/list which doesn't require email verification.

**Comment by gautamjajoo** [comment]
@RishabhJain2018 Actually the issue was not in displaying the All Challenges Page but the details of a specific challenge which are shown once a user clicks on it.
A user who hasn't login can view it but an unverified user cannot.
