### ISSUE TITLE
Submission file cannot be unzipped

### ISSUE THREAD

**Issue by veritas9872** [Cloud-CV/EvalAI#2243]
### **Bug report**

Expected behavior: The submission should work.
Observed behavior: Submission status is "Failed" and the stderr file states only that "Submission file cannot be unzipped".

Operating system and browser: Ubuntu 16.04 Firefox and Windows 10 Chrome. I think that it is browser independent.

Issue: I am trying to submit a file to the fastMRI challenge but I always get the same "Submission file cannot be unzipped" message and my submission fails. I believe that I have done everything correctly and I do not understand why the submission process is not working. 

The contents of my json file (named 'submission.json') are the same as this .txt file: [submission.txt](https://github.com/Cloud-CV/EvalAI/files/3012408/submission.txt)

The .zip file (uploaded on a Google drive school account) is structured to first open a folder, which contains all the data files. I have also tried .tar and .tar.gz files. They all do not work.

For some reason, there are in fact no submissions to the fastMRI challenge. I would like to be given an example of what exactly I should do to make a successful submission.

**Comment by RishabhJain2018** [comment]
Hi @veritas9872 , The url that you're giving in the submission file doesn't download a zip file, instead it downloads the content of an html page.
To check it please use this command - `wget <url_from_the_file>`
I think this is causing the issue.

I'm closing this issue. Please feel free to reopen it if you still face the difficulty. Thanks!

**Comment by veritas9872** [comment]
Thank you for your help. I will fix my submission file.
