### ISSUE TITLE
Prevent the user to edit the uploaded filename

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#2248]
### Observed Behaviour
Currently a user is able to edit the uploaded file name during submission to a challenge or when uploading zip file to host a challenge.

### Expected Behaviour
DIsable user to edit the filename or enter any text in the field.

@RishabhJain2018 @deshraj 

![Capture](https://user-images.githubusercontent.com/24366008/55153450-7ad1b580-5178-11e9-903e-eaa95c296345.JPG)

**Comment by thanos-pakou** [comment]
Hello, can I work on this issue?

**Comment by galipremsagar** [comment]
Sure, @thanos-pakou

**Comment by ThongVoHien** [comment]
@galipremsagar Can I work on that issue too?
