### ISSUE TITLE
Add tests for API

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2250]
Add tests for the following APIs added in the PR #2249 .

1. get_challenge_phase_by_pk
2. get_challenge_phase_by_slug

**Comment by kurianbenoy** [comment]
Can I work on this issue, I will submit a PR for #2227 by today. After this I will work this also

**Comment by yashdusing** [comment]
@RishabhJain2018 Can I work on this ? I’ve finished all of my other tasks

**Comment by kurianbenoy** [comment]
You can work on it @yashdusing.

**Comment by ThongVoHien** [comment]
@RishabhJain2018 Can I work on this too?
