### ISSUE TITLE
Challenge creation using configuration zip doesn't work

### ISSUE THREAD

**Issue by mtahafarooq** [Cloud-CV/EvalAI#2274]
- the expected behaviour
When the configuration zip is uploaded it says that the challenge is sent to admin for approval. When I approve it through django admin panel I expect to see in challenges list on frontend.

- the observed behaviour
But it doesn't show up in the challenges section, if I create a new one through django admin panel I am able to see it.
- steps to reproduce the problem
Select a team, click create challenge, upload a test configuration file and approve it through djnago admin panel
- which operating system and/or browser you're using, if relevant
Ubuntu 18.04
- (if possible) copies of the console/server logs

Thanks!

**Comment by deshraj** [comment]
@mtahafarooq can you please share which challenge configuration file you are trying to upload?
