### ISSUE TITLE
Add new logos on homepage

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2286]
Some of the new organizations have started using EvalAI for hosting their challenge, hence we would like to mention them as our users on the homepage -

Here are logos to be added alphabetically -
1. [UIUC](https://i.ibb.co/S3WnN7z/UIUC.png)
2. [NanKai University](https://upload.wikimedia.org/wikipedia/en/thumb/a/a5/Nankai_University_logo.svg/1200px-Nankai_University_logo.svg.png)
3. [MIT](https://iwi.mit.edu/sites/default/files/images/MIT_logo.png)
4. [IBM](http://pngimg.com/uploads/ibm/ibm_PNG19658.png)
5. [APTIV](https://www.aptiv.com/images/default-source/email-campaigns/aptiv_logo_color_rgb.png)
6. [Intel](https://github.com/cvwc2019/cvwc2019.github.io/blob/master/imgs/Intel_logo.png)
7. [UGM](https://banner2.kisspng.com/20190204/fjg/kisspng-gadjah-mada-university-ugm-logo-campus-5c591498b0cdc8.3184659715493418487242.jpg)
8. [Jinan University](https://english.jnu.edu.cn/_upload/site/00/5d/93/logo.png) (crop this image to contain only the logo)

**Comment by WillPaulRyan** [comment]
@RishabhJain2018 I'm interested in helping

**Comment by RishabhJain2018** [comment]
sure!

**Comment by HimanshuJanbandhu** [comment]
Hi guys, I would like to contribute, can I take take this issue.

**Comment by RishabhJain2018** [comment]
@Sanji515 Can you please add it in the current version as well as in EvalAI-ngx.

**Comment by Sanji515** [comment]
@RishabhJain2018 Sure!

**Comment by generationXcode** [comment]
Hi I would like to help in this issue
