### ISSUE TITLE
Add countdown timer for the challenges

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2295]
**Current Behaviour**:

There is no timer shown when the challenge deadline is approaching.

**Expected Behaviour**:

There should be a counter which will automatically appear one month before the challenge deadline.

Reference: #1769

**Comment by RishabhJain2018** [comment]
@Sanji515 Would you like to work on this?

**Comment by Sanji515** [comment]
@RishabhJain2018 Sure!

**Comment by Sanji515** [comment]
@RishabhJain2018 Hey, I'm thinking of UI for countdown timer something similar to this please take a look at the screenshots.

![Screenshot (223)](https://user-images.githubusercontent.com/32524438/57164506-f4149600-6e11-11e9-9fb8-ac4c4631d96d.png)

**Or we can remove the background**

![Screenshot (224)](https://user-images.githubusercontent.com/32524438/57165179-fd066700-6e13-11e9-9ddd-148085f00172.png)

**Comment by galipremsagar** [comment]
2nd one looks better but Look into this: http://flipclockjs.com/faces/daily-counter
FlipClock looks nice and we can theme it accordingly to our UI color.
