### ISSUE TITLE
Add Timezone while displaying time in challenges

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2296]
**Current Behaviour**

The challenge/challenge phase start and end date are shown without the timezone which sometimes confuses the user.

**Expected Behaviour**
The timezone should be visible on the UI.

For reference: #1766

**Comment by sarthak212** [comment]
@RishabhJain2018 Can i work on this.?

**Comment by RishabhJain2018** [comment]
Sure @sarthak212
