### ISSUE TITLE
Fix staging travis build

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2311]
**Description**:

The Travis build here(https://travis-ci.org/Cloud-CV/EvalAI/jobs/532140171#L5087) fails after the latest commit in master(https://github.com/Cloud-CV/EvalAI/commit/d9166ae8a20a1e4e35c851d99905223a91d7e0fb)

**Expected:**

Fix the Travis build

@sarthak212 Would you like to take this up since it fails after I merged your PR in master branch.

**Comment by sarthak212** [comment]
@RishabhJain2018 Sure.
