### ISSUE TITLE
Wrong input field when updating existing participant teams 

### ISSUE THREAD

**Issue by nataliavramidou** [Cloud-CV/EvalAI#2324]
**Observed behavior**
When someone tries to edit an existing participant team' s name or url, the value passes also at the input fields (name, url) of the create new participant team form.
![issue](https://user-images.githubusercontent.com/15125284/57982730-0c132900-7a52-11e9-80e5-b6ada36ad912.png)

**Excpected behavior**
When editing existing participant team' s name or url, the only input fields that should show the change are the fields name and url fields of the mdDialog Box.

**Comment by RishabhJain2018** [comment]
Closing this for now.
