### ISSUE TITLE
submission worker error : 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by RyanLHU** [Cloud-CV/EvalAI#2347]
When I upload an evaluation script, the system shows the following error messages at the server side
(I follow the instructions in https://evalai.readthedocs.io/en/latest/challenge_creation.html#challenge-configuration-examples to create the challenge) 

> worker_1_c60bbe8e7733 | [2019-05-27 17:50:28] ERROR Exception while receiving message from submission queue with error 'NoneType' object has no attribute 'get'
> worker_1_c60bbe8e7733 | Traceback (most recent call last):
> worker_1_c60bbe8e7733 |   File "/code/scripts/workers/submission_worker.py", line 600, in process_submission_callback
> worker_1_c60bbe8e7733 |     process_submission_message(body)
> worker_1_c60bbe8e7733 |   File "/code/scripts/workers/submission_worker.py", line 579, in process_submission_message
> worker_1_c60bbe8e7733 |     user_annotation_file_path,
> n process_submission_callback
> worker_1_c60bbe8e7733 |   File "/code/scripts/workers/submission_worker.py", line 326, in run_submission
> worker_1_c60bbe8e7733 |     challenge_id
> worker_1_c60bbe8e7733 | AttributeError: 'NoneType' object has no attribute 'get'

I know this problem has been discussed in #2254. However, it is close but I cannot find any solution on this problem.

**Comment by RyanLHU** [comment]
I make it working for ONE challenge now 
> I update the docker environment variable "CHALLENGE_PK" to the specific challenge ID, then it works

However, I have no idea to make it work for multiple challenges.

**Comment by RishabhJain2018** [comment]
This is fixed.
