### ISSUE TITLE
Cannot submit results into a challenge

### ISSUE THREAD

**Issue by fhalhani** [Cloud-CV/EvalAI#2366]
- the expected behavior
A challenge was created following the steps provided in [EvalAI Documentation release 1.1.] link here https://buildmedia.readthedocs.org/media/pdf/evalai/latest/evalai.pdf
When logged as host, we should be able to submit into a challenge.

- the observed behavior
  1. I logged as host (also for the participant), when I clicked on the phase a warning came up as shown in the picture below

 	![](https://drive.google.com/uc?export=view&id=1f5ioAz4kMmeziiV5zqqxA_QhnzNlVRr8)

 	The server also reported this:
 	`django_1  | [2019-07-02 10:47:41] WARNING "GET /api/jobs/2/remaining_submissions/ HTTP/1.1" 401 58`.

  2. No submission was allowed. I wasn't able to click on the submission bottom as shown in the picture below
  ![](https://drive.google.com/uc?export=view&id=1KKy1Uzsb2N_T8dvRXByX9i20tTLE-H2U)

  I cleared all docker containers and redo all the steps using the example challenge provided [here](https://buildmedia.readthedocs.org/media/pdf/evalai/latest/evalai.pdf) and still got the same warning and same problem. Note that the example is from this repo.

- steps to reproduce the problem
  1. Get a copy from EvalAI master branch.
  1. Build and run Docker containers following the installation procedure in the master branch.
  1. Go localhost:8888 and uploaded the challenge as a host.
  1. Created the [challenge](https://github.com/Cloud-CV/EvalAI/blob/master/examples/example1/test_zip_file.zip) following the documentation provided by EvalAI 1.1.
  1. Approve the challenge as admin in Django-site, localhost:8000/admin 
  1. Log in as a participant and try to submit a file.

- which operating system and/or browser you're using, if relevant
  Mac OSx, safari

Thanks!

**Comment by RishabhJain2018** [comment]
Hi @fhalhani,
Thanks for reporting the issue. We've fixed this issue with this PR: https://github.com/Cloud-CV/EvalAI/pull/2367. Once this is merged then it should not cause further issues. Please feel free to reopen the issue if it doesn't get resolved.

Thanks, @vkartik97 for the quick fix.
