### ISSUE TITLE
submission error 

### ISSUE THREAD

**Issue by fhalhani** [Cloud-CV/EvalAI#2375]
- the expected behavior: 
when submitting a file to the challenge it should show the details of the submission 
- the observed behavior
when a file is submitted to the challenge all submission details are non as shown below 
![](https://drive.google.com/uc?export=view&id=1YtD6-ytled3_pFA3VIP1ynHmr_3z_M2E)
and the following error shows in terminal:
" worker_1  | [2019-07-06 10:06:45] ERROR Exception while receiving message from submission queue with error 'NoneType' object has no attribute 'get'
worker_1  | Traceback (most recent call last):
worker_1  |   File "/code/scripts/workers/submission_worker.py", line 599, in process_submission_callback
worker_1  |     process_submission_message(body)
worker_1  |   File "/code/scripts/workers/submission_worker.py", line 578, in process_submission_message
worker_1  |     user_annotation_file_path,
worker_1  |   File "/code/scripts/workers/submission_worker.py", line 325, in run_submission
worker_1  |     challenge_id
worker_1  | AttributeError: 'NoneType' object has no attribute 'get'" 
This was done using different challenges including the example from EvalAI_starters and the same problem happens every time 
- steps to reproduce the problem
submit a file to the challenge 
- which operating system and/or browser you're using, if relevant
Mac OSx, safari 

Thanks!

**Comment by RyanLHU** [comment]
Try to restart your worker 
sudo docker-compose restart worker and submit again
