### ISSUE TITLE
Update submission API results in 500 error

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2387]
**Issue:**

The update submission API results into the 500 error when the parameters passed aren't correct. Here is the error: https://sentry.io/share/issue/f8a2925b30604ba0b950abb04853d04d/

**Fix**
All the errors should be properly handled and the response should be displayed to the challenge host.

**Comment by rohitjha941** [comment]
@RishabhJain2018  Can I work on this?

**Comment by pushkalkatara** [comment]
Hi @RishabhJain2018 isn't this already implemented in the repo [here](https://github.com/Cloud-CV/EvalAI/blob/ca0351dda61be800b2ee50a2b9d4f41b913e8ea9/apps/jobs/views.py#L854) with [tests](https://github.com/Cloud-CV/EvalAI/blob/ca0351dda61be800b2ee50a2b9d4f41b913e8ea9/tests/unit/jobs/test_views.py#L2309). Is something else expected out of this issue?

**Comment by abbasidaniyal** [comment]
@RishabhJain2018  Is this issue still open?

**Comment by RishabhJain2018** [comment]
This is fixed!
