### ISSUE TITLE
Update emailError key of localStorage on error in the dashboard controller.

### ISSUE THREAD

**Issue by KhalidRmb** [Cloud-CV/EvalAI#2400]
### Bug
![Screenshot from 2019-07-21 18-52-13](https://user-images.githubusercontent.com/31621523/61591838-ee487880-abe8-11e9-9c06-99a6c1c1c60c.png)
**Expected** -> For an unverified user, the message displayed should be _"Please verify your email first!"_

**Current** -> The message is "_false_". It os only updated to the former if the user attempts to move to other pages in the menu. (Where localStorage *is* updated on Error.)

**Comment by KhalidRmb** [comment]
@Ram81 @RishabhJain2018 PTAL.

**Comment by RishabhJain2018** [comment]
This is fixed!
#2193
