### ISSUE TITLE
Change color of radio buttons to EvalAI's primary color (Dark Gray)

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#243]
Change color of radio buttons in Create Team page.
Refer variable.scss file for color themes. Use $dark-gray for the radio button. Currently it is of green color and needs to be changed.

**Comment by jainarunarunjain** [comment]
@aka-jain Can i work on this?

**Comment by aka-jain** [comment]
@jainarunarunjain sure.

**Comment by aka-jain** [comment]
Closing and fixed with #248
