### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by julianmukaj** [Cloud-CV/EvalAI#2434]
**- Expected behaviour**
 Able to login with default users
**- Observed behaviour**
 Login page does nothing
**- steps to reproduce the problem**
 Run steps on the guide then try a default login
**- which operating system**
 Running on Ubuntu Server

**Comment by Suryansh5545** [comment]
Same problem here 
**OS**-Windows 10 1903 
Docker-19.03.1

**Comment by bismitaguha** [comment]
The login works fine on my system.
So could you post screenshots of the problem? @julianmukaj

**Comment by julianmukaj** [comment]
There is nothing to screenshot, the login button fires off but 'connection refused' error is returned on console on OPTIONS verb.

**Comment by RishabhJain2018** [comment]
Hi @julianmukaj, From the screenshot, it looks like the `nodejs` container isn't build properly. Can you please try building and running it again.

**Comment by julianmukaj** [comment]
I have tried 2 re-builds, same issue unfortunately.

**Comment by RishabhJain2018** [comment]
@julianmukaj Which web browser are you using? (The login works perfectly fine in the current master branch and with chrome browser Version 77.0.3865.75 (Official Build) (64-bit))

**Comment by RishabhJain2018** [comment]
Also, please paste the traceback of the error shown by the nodejs or django container.

**Comment by julianmukaj** [comment]
I am on exact same version of chrome as you: Version 77.0.3865.75 (Official Build) (64-bit)

How can I change the base URL of the app? So instead of localhost it calls ##.## ?

I lost the logs but trying to get them up again.

**Comment by julianmukaj** [comment]
Possible to change the base URL or not?

**Comment by RishabhJain2018** [comment]
yes, it is possible to change the base URL from this file: https://github.com/Cloud-CV/EvalAI/blob/master/frontend/src/js/config.json

**Comment by julianmukaj** [comment]
![image](https://user-images.githubusercontent.com/25327531/65886165-c10c0980-e393-11e9-8092-c684c4cd4bde.png)

Tried again, no logs pop up when I attempt a login.

**Comment by julianmukaj** [comment]
I think the API is not running, hitting localhost:8000 returns nothing, are there any other requirements for running the Django app?

**Comment by julianmukaj** [comment]
Any idea as to why the Django doesn't run?

**Comment by RishabhJain2018** [comment]
> Any idea as to why the Django doesn't run?
Can you please check the logs for the docker container?

**Comment by RishabhJain2018** [comment]
> are there any other requirements for running the Django app?

No there aren't any other requirements for running the application. `docker-compose up` should work for launching all the cantainers.

**Comment by RishabhJain2018** [comment]
@Suryansh5545 Is your problem resolved?

**Comment by Suryansh5545** [comment]
i Tried on Windows multiple times. but then i tried it on ubuntu 18.04 LTS and it worked perfectly

**Comment by RishabhJain2018** [comment]
Were you able to figure out the issue on Windows?

**Comment by Suryansh5545** [comment]
Nope

**Comment by Suryansh5545** [comment]
I am going to retry once more on windows today . Will update soon on situation

**Comment by Suryansh5545** [comment]
Hey i rebuild and this time i got a log of db_1 when i try to login. i am attaching all logs related to db_1.
![evalai_db1_logimg](https://user-images.githubusercontent.com/34577232/66632020-2af2a180-ec25-11e9-9aa0-996ba22507ce.PNG)
![evalai_db1_logimg2](https://user-images.githubusercontent.com/34577232/66632021-2af2a180-ec25-11e9-803a-2f3a23d40f36.PNG)
![evalai_db1_logimg3](https://user-images.githubusercontent.com/34577232/66632022-2b8b3800-ec25-11e9-876f-1d6831335037.PNG)

**Comment by Suryansh5545** [comment]
Did you guys find out whats wrong with windows build

**Comment by kumarrajan4264** [comment]
I want to work on this issue .Can i ??

**Comment by RishabhJain2018** [comment]
Sure @kumarrajan4264, Please note that it is failing on Windows only.

**Comment by julianmukaj** [comment]
Urm no, I was running it on an Ubuntu 18.04 server. Issue happens on both.

**Comment by ataata107** [comment]
I faced the same issue while installing on windows.
It is because of the change of parsing when you download from github. Bash expects Linux line endings but it is being fed windows line endings.
Here is a quick solution 
1) Go to the root folder of EvalAI
2) Type the following commands in bash (you can install bash in windows)
sudo apt-get install -y dos2unix 
sudo find . -type f -exec dos2unix {} \; 

Hope it helps

**Comment by joaoplm** [comment]
Hi. im having the same problem. Log in does nothing. 

This is the log:

celery_1  | /usr/local/lib/python3.7/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
celery_1  |   EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
celery_1  | /usr/local/lib/python3.7/site-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
celery_1  | absolutely not recommended!
celery_1  |
celery_1  | Please specify a different user using the --uid option.
celery_1  |
celery_1  | User information: uid=0 euid=0 gid=0 egid=0
celery_1  |
celery_1  |   uid=uid, euid=euid, gid=gid, egid=egid,
celery_1  |
celery_1  |  -------------- celery@celery v4.3.0 (rhubarb)
celery_1  | ---- ** -----
celery_1  | --- * *  * -- Linux-4.15.0-88-generic-x86_64-with-debian-10.2 2020-03-12 12:31:49
celery_1  | -- * - ** ---
celery_1  | - ** ---------- [config]
celery_1  | - ** ---------- .> app:         _main_:0x7f2000483a90
celery_1  | - * ---------- .> transport:   sqs://x:*@localhost//
celery_1  | - ** ---------- .> results:     disabled://
celery_1  | - * --- * --- .> concurrency: 4 (prefork)
celery_1  | -- *** ---- .> task events: OFF (enable -E to monitor tasks in this worker)
celery_1  | --- *** -----
celery_1  |  -------------- [queues]
celery_1  |                 .> celery_dev       exchange=celery_dev(direct) key=celery_dev
celery_1  |
celery_1  |
celery_1  | [tasks]
celery_1  |   . jobs.tasks.download_file_and_publish_submission_message
celery_1  |
celery_1  | [2020-03-12 12:31:54,782: CRITICAL/MainProcess] Unrecoverable error: ClientError('An error occurred (InvalidClientTokenId) when calling the ListQueues operation: The security token included in the request is invalid.')
celery_1  | Traceback (most recent call last):
celery_1  |   File "/usr/local/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 921, in create_channel
celery_1  |     return self._avail_channels.pop()
celery_1  | IndexError: pop from empty list
celery_1  |
celery_1  | During handling of the above exception, another exception occurred:
celery_1  |
celery_1  | Traceback (most recent call last):
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/worker.py", line 205, in start
celery_1  |     self.blueprint.start(self)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
celery_1  |     step.start(parent)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 369, in start
celery_1  |     return self.obj.start()
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
celery_1  |     blueprint.start(self)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
celery_1  |     step.start(parent)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/connection.py", line 23, in start
celery_1  |     c.connection = c.connect()
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 405, in connect
celery_1  |     conn = self.connection_for_read(heartbeat=self.amqheartbeat)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 412, in connection_for_read
celery_1  |     self.app.connection_for_read(heartbeat=heartbeat))
celery_1  |   File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 436, in ensure_connected
celery_1  |     callback=maybe_shutdown,
celery_1  |   File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 430, in ensure_connection
celery_1  |     callback, timeout=timeout)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/kombu/utils/functional.py", line 344, in retry_over_time
celery_1  |     return fun(*args, **kwargs)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 283, in connect
celery_1  |     return self.connection
celery_1  |   File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 839, in connection
celery_1  |     self._connection = self._establish_connection()
celery_1  |   File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 794, in _establish_connection
celery_1  |     conn = self.transport.establish_connection()
celery_1  |   File "/usr/local/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 941, in establish_connection
celery_1  |     self._avail_channels.append(self.create_channel(self))
celery_1  |   File "/usr/local/lib/python3.7/site-packages/kombu/transport/virtual/base.py", line 923, in create_channel
celery_1  |     channel = self.Channel(connection)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/kombu/transport/SQS.py", line 133, in _init_
celery_1  |     self._update_queue_cache(self.queue_name_prefix)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/kombu/transport/SQS.py", line 143, in _update_queue_cache
celery_1  |     resp = self.sqs().list_queues(QueueNamePrefix=queue_name_prefix)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
celery_1  |     return self._make_api_call(operation_name, kwargs)
celery_1  |   File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
celery_1  |     raise error_class(parsed_response, operation_name)
celery_1  | botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the ListQueues operation: The security token included in the request is invalid.
evalai_celery_1 exited with code 1

**Comment by joaoplm** [comment]
My server config:

Linux spark 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

HD: 70 GB

RAM: 32GB

**Comment by RishabhJain2018** [comment]
The current master branch is stable.
