### ISSUE TITLE
Integrate with EvalAI-ngx

### ISSUE THREAD

**Issue by MichCest** [Cloud-CV/EvalAI#2440]
This may already be in the works but I couldn't find any information on it. We are trying to use EvalAI with https://github.com/Cloud-CV/EvalAI-ngx instead of the built in UI. This may be more of a question/request for help than an issue.

This is the Dockerfile we are using for the front end (pretty much just copied from the ngx project):
```
FROM node:12.2.0

RUN apt-get update
RUN apt-get install -y build-essential git curl libfontconfig
RUN apt-get install nodejs-legacy -y
RUN npm install -g @angular/cli@7.3.9

RUN mkdir /code

RUN git clone https://github.com/Cloud-CV/EvalAI-ngx /code/

WORKDIR /code
RUN npm install
RUN npm audit fix

EXPOSE 8888

CMD ["ng","serve", "--host", "0.0.0.0"]
```
When I do a `docker-compose --build` I get this error for the container:
`The serve command requires to be run in an Angular project, but a project definition could not be found.`

This error makes me think there is no `angular.json` file in the `/code` folder but there should be after cloning the repo.

Some documentation on how to connect the back end to the new front end would be very helpful.

**Comment by pushkalkatara** [comment]
Hi, @MichCest I recently set up the https://github.com/Cloud-CV/EvalAI-ngx, I didn't face such an error.

**Comment by RishabhJain2018** [comment]
We are actively working to solve this.
