### ISSUE TITLE
Set DrfDocs to be only available on development server only

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#247]
See this: https://github.com/Cloud-CV/EvalAI/blob/master/evalai/urls.py#L24 . This URL pattern should be only available in the development environment.

**Comment by RishabhJain2018** [comment]
@deshraj I will fix this.

**Comment by RishabhJain2018** [comment]
@deshra The PR is merged . I think we should close this.

**Comment by deshraj** [comment]
Fixed in #254. Closing it.
