### ISSUE TITLE
update installation instruction in readme 

### ISSUE THREAD

**Issue by Saloni-Tayal** [Cloud-CV/EvalAI#2471]
When I was setting up EvalAI on my system then for Building and running the Docker containers I had to give the command with admin priviledges(in both windows & ubuntu). 
So ``` sudo  docker-compose up --build``` for ubuntu and running cmd with **Run as Administration** should be there.

Thanks!

**Comment by RishabhJain2018** [comment]
Closing this since because it is an installation issue and if the docker is set up properly, it shouldn't need admin privileges.
