### ISSUE TITLE
The documentation page on 'challenge-creation-using-zip-configuration' does not exist

### ISSUE THREAD

**Issue by VishwaasHegde** [Cloud-CV/EvalAI#2473]
[This](https://evalai.readthedocs.io/en/latest/challenge_creation.html#challenge-creation-using-zip-configuration) link to the documentation page on 'challenge-creation-using-zip-configuration' does not exist.
- the expected behaviour: To open the documentation
- the observed behaviour: Gives page not found error
- steps to reproduce the problem: Click on 'Host Competition' on the main page, and go to your host team, and then got to the link where it says, 'To know how to create a challenge using zip file configuration, please see our documentation here'
-browser: Google Chrome

Thanks!

**Comment by nikochiko** [comment]
@VishwaasHegde , I think you are referring to this page: https://evalai.cloudcv.org/web/challenge-create
Also facing same issue here: https://github.com/Cloud-CV/EvalAI-Starters/blob/master/challenge_config.yaml
We can use this link instead: https://evalai.readthedocs.io/en/latest/configuration.html#challenge-configuration.
@RishabhJain2018 There are a few more similar issues with the docs pages. Like a missing '/blob/' in the 'Edit in GitHub' and also, one 'challenge phases' hyperlink refers to this non-existing page: https://evalai.readthedocs.io/glossary.html#challenge-phase
Shall I take up this issue? I will batch a few fixes in one PR.

**Comment by RishabhJain2018** [comment]
Thanks, @nikochiko for picking up on this issue and opening a PR.

**Comment by nikochiko** [comment]
@VishwaasHegde @RishabhJain2018 , I think we can close this issue.

**Comment by VishwaasHegde** [comment]
@nikochiko okay, Thank you :)
