### ISSUE TITLE
Does evalai push support adding different container registry?

### ISSUE THREAD

**Issue by asm582** [Cloud-CV/EvalAI#2475]
Hello,

Can you provide information on how can one add a different container registry to evalai cli?

Thanks!

**Comment by RishabhJain2018** [comment]
Hi @asm582 ,
I didn't quite get your point.
What do you mean by different container registry? Do you mean to point to the docker hub?

**Comment by asm582** [comment]
yes, how can I configure evalai-cli it to store containers in docker.io or quay.io

**Comment by yashdusing** [comment]
@RishabhJain2018 Could you please answer this ? I also have this doubt since most of the functionality which was added was for AWS. So does the CLI support other container registry hubs ?

**Comment by vkartik97** [comment]
Hi @asm582 
Currently, EvalAI only supports AWS' ECR as container registry for challenge submissions, as the project is tightly coupled with AWS.
I hope this resolves your issue.

**Comment by yashdusing** [comment]
@vkartik97 is there any get started page for the AWS functionality, k8s code and GPU schedule that was implemented during GSOC? I’d like to understand what all was implemented to have an idea of the functionalities
