### ISSUE TITLE
UI Design : Signup page displays your password is weak even though password field is empty

### ISSUE THREAD

**Issue by vs74** [Cloud-CV/EvalAI#2478]
**- the observed behaviour**
   When a user tries to sign up the web page, the first enters the password and then clears this field, the sign up page displays your password is weak 
**- the expected behaviour**

   Ideally, it should only display that password is required

**- steps to reproduce the problem**

1. Go to SignUP page
2. First try to enter a random password 
3. Clear this password field 
The screenshot below displays this error. I have circled the error(`weak`) with black marker on the screenshot below. 

<img width="709" alt="Screenshot 2019-11-23 at 11 58 49 PM" src="https://user-images.githubusercontent.com/31419210/69483601-50431400-0e4f-11ea-885b-a895766a34f0.png">

**Solution**
If there is no password in the password field it should only display` password is required`

**System Requirements**
Browser - Safari 
OS - MAC OS

**Comment by tusharfc** [comment]
@RishabhJain2018 can I work on this?

**Comment by pushkalkatara** [comment]
@tusharfc Already there is an open PR for the issue. https://github.com/Cloud-CV/EvalAI-ngx/pull/222

**Comment by RishabhJain2018** [comment]
@Kajol-Kumari We should fix this in ngx version.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari We should fix this in ngx version.

Hey @RishabhJain2018 I just checked it for ngx and this issue is not with ngx it's only with the EvalAI. So should i go for fixing it in EvalAI?
