### ISSUE TITLE
Two links serving same purpose on same webpage

### ISSUE THREAD

**Issue by Saloni-Tayal** [Cloud-CV/EvalAI#2485]
There is "All Challenges" two times on the same page.

- the expected behaviour
There is no need of having two ["All Challenges"](https://evalai.cloudcv.org/web/dashboard) on the same page as both are serving the same purpose. 
I understand that it could have made some sense if we were watching it NOT on desktop view only but still it doesn't go so well(here) as there remain two links to same page on the same webpage.

- the observed behaviour

checkout the screenshot below: 
![Screenshot from 2019-11-24 04-01-37](https://user-images.githubusercontent.com/47540976/69491276-e7908180-0eb8-11ea-9d4d-e6efb8affe03.png)
There should be one of them only.

- steps to reproduce the problem

    - Login/Signup 
    - Go to dashboard

- operating system and/or browser

    - Ubuntu , Firefox

Thanks!

**Comment by RishabhJain2018** [comment]
This is fixed!
