### ISSUE TITLE
Add ArgoAI as one of our users

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2488]
Add the logo for [ArgoAI](https://www.argo.ai/) alphabetically in the users list.

**Comment by yashdusing** [comment]
@RishabhJain2018 can I work on this?

**Comment by RishabhJain2018** [comment]
sure!

**Comment by iamdarshshah** [comment]
@RishabhJain2018 Do we have to add the logo in the "Partner Organizations section"? Or In which specific section should I update this logo?

**Comment by RishabhJain2018** [comment]
Hi @iamdarshshah, I think @yashdusing is working on it.

**Comment by RishabhJain2018** [comment]
@yashdusing Any updates on this one?

**Comment by yashdusing** [comment]
@RishabhJain2018 is it okay if I complete this by week end ?

**Comment by RishabhJain2018** [comment]
sure, sounds good!

**Comment by Akash16s** [comment]
Any updates on this issue?
