### ISSUE TITLE
Sidebar on Dashboard view is not working properly for Mobile view.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#249]
Currently sidebar is collapsing at ~640px but it should be collapsed at screensize<992 px.

**Comment by RishabhJain2018** [comment]
@aka-jain can I fix this?

**Comment by aka-jain** [comment]
@RishabhJain2018 : Sure.

**Comment by RishabhJain2018** [comment]
@aka-jain @deshraj I think this issue is soved. Please refer https://github.com/Cloud-CV/EvalAI/blob/master/frontend/src/css/modules/web.scss#L24 and https://github.com/Cloud-CV/EvalAI/blob/master/frontend/src/css/modules/variables.scss#L45

**Comment by aka-jain** [comment]
@RishabhJain2018 : Nope, sidebar is not getting collapse at 992px, only container is expanding.  Have a look at sidebar.

**Comment by RishabhJain2018** [comment]
okk sure.

**Comment by aka-jain** [comment]
@RishabhJain2018 : I think you are working on 404 page. So let's make this issue free for other users. You can take it back after solving issue #290 
I hope it'll be Ok for you :)

**Comment by RishabhJain2018** [comment]
@aka-jain yeah sure. no problem.

**Comment by anweshknayak** [comment]
@aka-jain can I work ?

**Comment by aka-jain** [comment]
@anweshknayak : sure go ahead.

**Comment by deshraj** [comment]
@aka-jain is anyone working on this? Or we are planning to do this in `v2`. If yes, please add a label of `v2`

**Comment by MAKOSCAFEE** [comment]
Hi I am new here. can I claim this? and I have already submitted a [PR](https://github.com/Cloud-CV/EvalAI/pull/740) to fix it. 
Thanks

**Comment by aka-jain** [comment]
Sure @MAKOSCAFEE, will check your PR. Thanks :)

**Comment by aka-jain** [comment]
Fixed with #740
