### ISSUE TITLE
Mobile view header for Dashboard is not working properly.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#250]
Header of Dashboard view doesn't seem to be responsive. Need to fix that.

**Comment by anweshknayak** [comment]
can I fix this too ?

**Comment by anweshknayak** [comment]
sorry for asking this late. I solved this issue. can you review ?

**Comment by dexter1691** [comment]
@deshraj : Actually, I am not sure - Is this fixed now?

**Comment by deshraj** [comment]
@aka-jain is keeping track of this issue. Lets keep it open and let Akash make a decision on this.

**Comment by aka-jain** [comment]
@spyshiv : do you want to work on this?

**Comment by spyshiv** [comment]
this issue is fixed. @aka-jain : please close this issue.

**Comment by deshraj** [comment]
Fixed in #434. Closing it.
