### ISSUE TITLE
[Feature Request] How about we add a beginner dataset for users to get familiar with the interface?

### ISSUE THREAD

**Issue by nikochiko** [Cloud-CV/EvalAI#2500]
I have been using Kaggle from a long time. And I realized that as a beginner, the [Titanic dataset](https://www.kaggle.com/c/titanic) competition helped me become familiar with their interface. I am relatively new to EvalAI and maybe some sample dataset such as the Titanic along with Tutorial instructions would be cool to have.
Maybe having a tutorial on MNIST dataset will be simple and helpful. It has been used in several tutorials as well. 
What do you think?

**Comment by Akash16s** [comment]
Yes, I think It will be great for newcomers

**Comment by veb7vmehra** [comment]
Can I contribute for this issue by creating a tutorial or something?

**Comment by rcannood** [comment]
Why was this closed? Has such a tutorial been created?
