### ISSUE TITLE
make challenge tabs stick under navbar

### ISSUE THREAD

**Issue by salonitayal** [Cloud-CV/EvalAI#2503]
- the expected behaviour

 As we scroll down the ongoing challenges, upcoming challenges secs etc. stick the top under the navbar. Same as navbar sticks the top of screen. This will help improve the overall experience on the page.

![Peek 2019-12-11 21-58](https://user-images.githubusercontent.com/47540976/70640226-a55d9300-1c61-11ea-940d-bb646e01ad0c.gif)

- the observed behaviour
As we scroll down these sections too scroll along.
- steps to reproduce the problem
click the All challenges on homepage.

Thanks!

**Comment by ShubhamPandey28** [comment]
Can I take this issue?

**Comment by Sanji515** [comment]
@Saloni-Tayal As you have reported this issue, would you like to build this feature?

**Comment by Saloni-Tayal** [comment]
@sanji515 yes I'd like to take this issue:)

**Comment by Sanji515** [comment]
@Saloni-Tayal Looking forward to your PR.

Please wait @ShubhamPandey28 Will open more issues soon :smiley:

**Comment by Suryansh5545** [comment]
I think no one is working on this?

**Comment by adrijshikhar** [comment]
@Saloni-Tayal are you still working on this?

**Comment by adityaketkar** [comment]
@Saloni-Tayal are you working on this issue? if not, @Sanji515 can I take this issue up?

**Comment by Kajol-Kumari** [comment]
Hey @RishabhJain2018 I think after adding tabs, we won't need this anymore. I had opened a PR for adding tabs in EvalAI [#2668](https://github.com/Cloud-CV/EvalAI/pull/2668)

**Comment by ajinkya7** [comment]
Is this still open?
