### ISSUE TITLE
[Docs] Documentation for making a submission

### ISSUE THREAD

**Issue by nikochiko** [Cloud-CV/EvalAI#2506]
Reference: https://evalai.readthedocs.io/en/latest

I wanted to find steps on how to make a submission, but I think it is not there in the docs (please correct me if I am missing something). 
The [submissions section](https://evalai.readthedocs.io/en/latest/submission.html) only covers how the submission proceeds, it does not guide through the submission process.
I think there should be a documentation to explain the contents of zip, json and txt file when uploading file for submission and also a documentation for uploading file with URL.

**Comment by adrijshikhar** [comment]
@nikochiko i would like to work on this, can you assign it to me?

**Comment by nikochiko** [comment]
@adrijshikhar Sure! Go ahead

**Comment by RishabhJain2018** [comment]
This is challenge specific and each challenge host needs to mention their own format.
