### ISSUE TITLE
[Feature Request] Sync accounts for EvalAI and EvalAI-forum

### ISSUE THREAD

**Issue by nikochiko** [Cloud-CV/EvalAI#2507]
Currently, if an account is created on [EvalAI](https://evalai.cloudcv.org), the same account cannot be used to login into [EvalAI-forum](https://evalai-forum.cloudcv.org).
I think it will be easier for users to have to create just one account and use it for both as both are part of one project. 
Also as a note, the forum has functionality to accept registrations through GitHub and Google other than with Email which is not present in EvalAI.

**Comment by ataata107** [comment]
I would like to work on to add the functionality to accept registrations through GitHub and google in EvalAI. Can I proceed?

**Comment by nikochiko** [comment]
@ataata107 I cannot assign the task. Please wait till the project maintainers decide whether this feature should be added or not and then they can assign it. :)

**Comment by RishabhJain2018** [comment]
This isn't on the project roadmap for now.
