### ISSUE TITLE
Edit Host Competition button on home page

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#251]
In home page there is a button for Host Competition. We have to replace it with "View Challenge" button and redirect it to challenge page (url : /web/challenge-page/overview)

**Comment by anweshknayak** [comment]
Im on it.

**Comment by anweshknayak** [comment]
@aka-jain this feature is applicable for both the users who are logged in and who are not.

**Comment by aka-jain** [comment]
Just add URL of challenge page, it will automatically handle authentication. 
p.s Only logged in user can visit this page.

**Comment by aka-jain** [comment]
Closing this issue, need some discussion.
