### ISSUE TITLE
[Feature Request] Add feature to see challenges which the user has participated in.

### ISSUE THREAD

**Issue by nikochiko** [Cloud-CV/EvalAI#2515]
Currently, there is no way to get a list of all challenges in which the user has participated. (Except for using CLI which has that feature) It would be a good addition here as well.

**Comment by tusharfc** [comment]
@RishabhJain2018  can I work on this?

**Comment by abhimnc** [comment]
hi @nikochiko. I am a newbie here. I want to work on this. Please help me to figure out which part code should I look for working on this. Thanks!

**Comment by Suryansh5545** [comment]
@nikochiko Can i work on it

**Comment by Sanji515** [comment]
Closing this as it is opened [here](https://github.com/Cloud-CV/EvalAI/issues/2698) now.
