### ISSUE TITLE
[docs, urgent] Update CrowdAI status

### ISSUE THREAD

**Issue by nikochiko** [Cloud-CV/EvalAI#2546]
The comparison table in the readme shows crowdAI, but according to this [blog post](https://www.crowdai.org/blogs/7), crowdAI has been shut down and replaced with a new closed-source platform AIcrowd.
Updates:
1. Change name CrowdAI -> AICrowd
2. Change open-source Yes -> No

**Comment by apoorvkhare07** [comment]
Hey @nikochiko 
I would like to take up this issue.

**Comment by nikochiko** [comment]
@apoorvkhare07 I'm not a maintainer but I don't think they will mind for a doc update, so sure! :+1:

**Comment by prakhargurunani** [comment]
@nikochiko @apoorvkhare07 
https://github.com/Cloud-CV/EvalAI-ngx/pull/245 
This is for Eval AI Angular Frontend, not for CrowdAI :smiley:

**Comment by nikochiko** [comment]
@prakhargurunani Yes I know. But if you go through this issue carefully, the problem mentioned here is that the status of the organization CrowdAI in the comparison table is outdated. You have implemented the same outdated comparison table in your PR.

**Comment by prakhargurunani** [comment]
Ok @nikochiko 
I will make the changes.
