### ISSUE TITLE
Header Buttons Not behaving as expected on Mobile view

### ISSUE THREAD

**Issue by Suryansh5545** [Cloud-CV/EvalAI#2553]
- the expected behaviour:-

The 3 Buttons Challenge,Docs & Forum should have either collapse with header or align in more proper way so user dont have problem viewing and the log out button should stick to the header 
- the observed behaviour:-

All 4 Buttons mentioned above follow the view if user scroll down it would have been correct if aligned properly . But they will interrupt when user might try to click something else 
- steps to reproduce the problem:-

Login and go to any page like dashboard in smartphone 
- which operating system and/or browser you're using, if relevant
Android 8.0, Chrome

![Screenshot_20191229-051254_Chrome](https://user-images.githubusercontent.com/34577232/71550575-f14a5f00-29f9-11ea-9353-923399e01ab4.jpg)

**Comment by Sanji515** [comment]
@Suryansh5545 As you have reported this issue, would you like to work on it?

**Comment by Suryansh5545** [comment]
@Sanji515  Can I work on it?

**Comment by Kajol-Kumari** [comment]
Hey @RishabhJain2018 @Suryansh5545  this issue has been solved both for EvalAI ang ngx so i think we can close this one. Attaching the screenshot for confirming the same. 
![Screenshot_2020-06-09-22-49-20-064_com android chrome](https://user-images.githubusercontent.com/44888949/84179527-bb7acd80-aaa3-11ea-960a-6e4cc03f6eee.jpg)
![Screenshot_2020-06-09-22-49-33-216_com android chrome](https://user-images.githubusercontent.com/44888949/84179540-c03f8180-aaa3-11ea-85e0-ffb486d978ff.jpg)

**Comment by Suryansh5545** [comment]
@RishabhJain2018 I also agree with @Kajol-Kumari the recent UI fix have addressed this issue and the UI is functioning well. So this issue can be closed.
