### ISSUE TITLE
Increase the z-index of Profile Page sidebar

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#257]

**Comment by anweshknayak** [comment]
Increase how much ? @aka-jain

**Comment by aka-jain** [comment]
Can you set it by yourself, so that everything will work fine?

**Comment by aka-jain** [comment]
@anweshknayak : Are you still working on this?

**Comment by anweshknayak** [comment]
@aka-jain sure you can take it. I will be engaged for 2-3 days or more.

**Comment by anweshknayak** [comment]
@aka-jain can I work on it ?

**Comment by aka-jain** [comment]
@anweshknayak : Sorry to not update it, this issue has been solved with PR #279.
@deshraj : Closing it.
