### ISSUE TITLE
Improper error message

### ISSUE THREAD

**Issue by hkmatsumoto** [Cloud-CV/EvalAI#2574]
**The observed behavior**:
When I input Japanese words into team name, the error message "This field is required" is shown.
![Screenshot from 2020-01-04 02-06-17](https://user-images.githubusercontent.com/57856193/71737568-5e953e80-2e97-11ea-87f9-22d276e3d0f1.png)

**The expected behavior**:
When unexpected letter (not limited to Japanese letter) is in input, the error message should be something like "Invalid letter is contained".

**Comment by drepram** [comment]
Can you try this out in EvalAI-ngx too?

**Comment by takitsuse** [comment]
Sure :smile_cat:

**Comment by Tanuj22** [comment]
@takitsuse Are you solving this or can I?

**Comment by takitsuse** [comment]
@Tanuj22 I'm not working on this, so go ahead :+1:

**Comment by Tanuj22** [comment]
I was looking into this issue. Does creating a regex to allow only english letter sound good?

**Comment by takitsuse** [comment]
Sounds good to me. What do you say @Sanji515?

**Comment by deshraj** [comment]
We are only planning to support only alphanumeric characters for the team name going forward. 

Here are the updated rules:
- Team name can be contain alphanumeric characters with spaces, `-`, and `_`
- Show proper error message if not correct team name is entered

\cc @Kajol-Kumari

**Comment by RishabhJain2018** [comment]
Closing this as we already have this.
