### ISSUE TITLE
Add footer to all inside pages (dashboard view)

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#258]

**Comment by aka-jain** [comment]
Sure @ram81 go ahead

**Comment by Ram81** [comment]
@aka-jain  as you said to include the footer template I've done that,but because of sidebar footer needs to be adjusted so can I go for that?

**Comment by anweshknayak** [comment]
close this ?

**Comment by aka-jain** [comment]
Thanks @anweshknayak .
Closing issue with reference PR at #315
