### ISSUE TITLE
[docs] 2 partially inconsistent instances of contributing guidelines

### ISSUE THREAD

**Issue by nikochiko** [Cloud-CV/EvalAI#2580]
#### The issue:
* There are two different instances of contributing guidelines: https://github.com/Cloud-CV/EvalAI/blob/master/.github/CONTRIBUTING.md and https://github.com/Cloud-CV/EvalAI/blob/master/docs/source/contribution.rst
* It is confusing as it is hard to understand which is the more up-to-date one (from the commit history, both have been updated separately before the last commit).
* As we make more updates, the guidelines will have to be updated in two places, which is an overhead and can be easily forgotten.

#### The solution:
* There should be only one up-to-date file for contributing guidelines.

**Comment by Suryansh5545** [comment]
@nikochiko There are two contribution guidelines because one is for github which support .md file only and other for readthedocs site which support .rst files only . So we can't have one. For both

**Comment by Suryansh5545** [comment]
I think this issue can now be closed

**Comment by nikochiko** [comment]
@Suryansh5545 We have support for markdown files in Sphinx (see https://github.com/Cloud-CV/EvalAI/blob/master/docs/source/conf.py#L37) through CommonMarkParser, which is why all the other documents in docs/source directory are in markdown format. 
(Sphinx is the one building the documentation, not readthedocs).
Moreover, simply that two services we use do not support similar filetype is not a reason to compromise on the quality of the project. In that case, we could have an in-between script or some other arrangement to convert md to rst or vice versa so that both remain in sync.

**Comment by Suryansh5545** [comment]
Markdown doesn’t support a lot of the features of Sphinx, like inline markup and directives. However, it works for basic prose content. reStructuredText is the preferred format for technical documentation

**Comment by Suryansh5545** [comment]
I think this answers it

**Comment by Suryansh5545** [comment]
And making sync will be for now more difficult than perhaps updating both

**Comment by nikochiko** [comment]
@Suryansh5545 Yes, I agree with that, but I think markdown is still very usable. Almost all of our documentation is in markdown. So I think we can go with Markdown for consistency purposes. And I don't think the contributing file would need to contain any technical information. 
So I think this is still a critical issue as both of the guidelines differ (I think one is even outdated and shows incorrect information). 
The threat of this is twofold:
* Overhead of maintaining an extra file for same purpose
* Could cause confusion among new developers.

**Comment by Suryansh5545** [comment]
We can give it a try

**Comment by RishabhJain2018** [comment]
Similar to #2578 and keeping one issue open for all documentation related issues.
