### ISSUE TITLE
[Frontend V2] Only one footer component

### ISSUE THREAD

**Issue by Suryansh5545** [Cloud-CV/EvalAI#2586]
**Current Scenario** 
Currently We have two footer component one for Authenticated users and other for none authenticated . But both are almost identical. With very little different. 
**Expected Scenario**
We can have the functionality of both in just one footer component this will reduce the work of editing both footer . if we have to change it .

Can i work on it?

**Comment by Kajol-Kumari** [comment]
Hey @RishabhJain2018  @deshraj we have a single footer component for both verified and non-verified users in `frontend_v2`.

**Comment by RishabhJain2018** [comment]
Closing this as it is fixed.
