### ISSUE TITLE
Scroll up Button not showing up 

### ISSUE THREAD

**Issue by Suryansh5545** [Cloud-CV/EvalAI#2588]
- **The expected behaviour**
In the challenge list the scroll up button should show up after going down a bit the page.  
- **The observed behaviour**
The scroll up button doesn't show up at all even after reaching at the bottom 
- steps to reproduce the problem
1.go to evalai.cloudcv.org/web/challenges/list
2. Scroll down 

Can i work on it?

**Comment by RishabhJain2018** [comment]
@Kajol-Kumari Can you please check if this is fixed in frontend v2.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari Can you please check if this is fixed in frontend v2.

Yes @RishabhJain2018 It's working perfectly fine for frontend_v2.

**Comment by devanshraj3000** [comment]
Though the scroll up button is visible in the page but it's width is quite less and a lot of space is getting wasted in left and the right side, so we can increase the width of scroll bar a little to make it user friendly.
Should I do this?

**Comment by shikhar168** [comment]
i would like to work on this issue
