### ISSUE TITLE
Add Collapsible to Challenge list

### ISSUE THREAD

**Issue by Suryansh5545** [Cloud-CV/EvalAI#2589]
Currently When user visits the evalai challenge list page . He is bombarded with all the challenges the on going, up coming and past ones . This make it hard for user to navigate and search. Currently there are 48! challenges on evalai challenge list .

Expected Solution:
Add a Collapsible so the user can open and close the list he wants . like if he want to look for current challenge then we will open on going tab .etc

Can i work on this

**Comment by RishabhJain2018** [comment]
This is fixed in frontend v2.
