### ISSUE TITLE
Add a Search Bar In Challenge-List

### ISSUE THREAD

**Issue by Suryansh5545** [Cloud-CV/EvalAI#2591]
Currently the evalai challenge list have 48 challenges Which make it hard for user to search. While We can add a Collapsible to increase the navigability . We need to have a search bar so if user knows the name of challenge then he can search it and wouldn't require to search though all the challenges.

Can i Work on this?

**Comment by RishabhJain2018** [comment]
Hi @Suryansh5545, Thanks for opening this. I've added this as an issue and noticed it later. I'm closing it.
