### ISSUE TITLE
Fix toggle problem between login and signup tabs on UI

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#260]
Here is the way to replicate the bug: 

1. Go to the login page 
2. Enter some details
3. Click on the signup button above the form
4. Enter details on the signup page
5. Switch back to the login page by clicking the login button above the form

You will get to see that the password field's label should go up as I switch but it does not behave like that. So, we need to fix this. 

Let me know if this is not clear or you need help with this.

**Comment by anweshknayak** [comment]
So one thing. as you see the input email field in sign up page gets cleared when you switch back and forth.Rest the issue persists as said.  So can we just not store the field input variables when we switch ?

**Comment by deshraj** [comment]
Yeah, we need to store all the fields including the email field.

**Comment by aka-jain** [comment]
@anweshknayak : You have to add material script for this. Please make a directive and add $.material.options.autofill = true in directive and add it to login and signup page.
Let if know it you need more help.

**Comment by aka-jain** [comment]
@anweshknayak : I hope you haven't solved this issue, actually I've solved it because we have an urgent requirements of this. Please work on other issues :)
@deshraj :  Closing this issue, fixed with PR #268 .
