### ISSUE TITLE
Dark Theme Option

### ISSUE THREAD

**Issue by Suryansh5545** [Cloud-CV/EvalAI#2602]
These days many big sites and app have dark theme and it is also good for eye in dark(i open evalai at night in dark and it is not eye friendly )
I have created a prototype with black and dark grey of homepage here are  images of it.
**Black in background  and dark grey in the rest**
![Selection_015](https://user-images.githubusercontent.com/34577232/72087341-4f4a4100-332e-11ea-8dae-44e74375b9e4.png)
![Selection_016](https://user-images.githubusercontent.com/34577232/72087343-4f4a4100-332e-11ea-885f-07d033a593a8.png)
![Selection_017](https://user-images.githubusercontent.com/34577232/72087344-4fe2d780-332e-11ea-9cc4-cd3417bfc3c9.png)
![Selection_018](https://user-images.githubusercontent.com/34577232/72087345-4fe2d780-332e-11ea-92a8-bcd270346061.png)
**dark grey in background and black in rest**
![Selection_020](https://user-images.githubusercontent.com/34577232/72087466-802a7600-332e-11ea-8546-484c0df9ad2b.png)

I have changed most images for dark theme . but they are not present in this prototype.

**Comment by nikochiko** [comment]
@Suryansh5545 Just throwing a personal opinion: the screenshots look really cool! :D

**Comment by Suryansh5545** [comment]
@RishabhJain2018 @Sanji515 @Ram81 @KhalidRmb

**Comment by Suryansh5545** [comment]
Closing This as the feature is currently not required but can be revisited later
