### ISSUE TITLE
Editing team name adds data to other fields

### ISSUE THREAD

**Issue by Suryansh5545** [Cloud-CV/EvalAI#2624]
- the expected behaviour:-
The data should not be automatically entered into the field creating a participant new team
- the observed behaviour:-
the data of user is automatically added to the field of creating a participant new team
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34577232/72522034-af873880-3882-11ea-8ae3-19cc558f719a.gif)

- steps to reproduce the problem:-
1.Try to edit the participant team name

Can i work on it?

**Comment by Kajol-Kumari** [comment]
@Suryansh5545 Can i work on this,please?

**Comment by Suryansh5545** [comment]
@Kajol-Kumari yea sure go for it:+1:
