### ISSUE TITLE
Update paper link on landing page and README

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#2625]
Currently the paper link in README and the landing page points to the arxiv version. Recently, the paper was accepted at AI Systems Workshop at SOSP 2019. We want to update the link and bibtext to that. 

Here is the updated link: http://learningsys.org/sosp19/assets/papers/23_CameraReadySubmission_EvalAI_SOSP_2019%20(8)%20(1).pdf

**Comment by bosecodes** [comment]
I'd like to work on this! @deshraj

**Comment by RishabhJain2018** [comment]
Sure @bosecodes
