### ISSUE TITLE
Remove tests.py from all the django apps

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#264]
We have all the unit and integration tests in `tests/` directory. Hence, don't need the `tests.py` file in all django apps.

**Comment by souravsingh** [comment]
@deshraj I would like to take a stab at the issue.

**Comment by deshraj** [comment]
Sure, go ahead. :-)

**Comment by TroJan** [comment]
@souravsingh : it will be great if you remove `tests/test_dummy.py` :)
