### ISSUE TITLE
Admin Dashboard don't give correct count of host and participant teams

### ISSUE THREAD

**Issue by Kajol-Kumari** [Cloud-CV/EvalAI#2641]
After adding 3 host teams and two participant teams:
- the expected behaviour:
The count should have been 3 for host team and 2 for participant team
- the observed behaviour: The count showed 2 for both of them

Screen record link:
https://drive.google.com/file/d/1mwk7XcQ8xQm6pwsx5uwBrVpWVtyTxGUh/view?usp=sharing

**Comment by Suryansh5545** [comment]
Thank you @Kajol-Kumari for reporting this issue and as you have reported this would you like to work on it?

**Comment by Kajol-Kumari** [comment]
I would love to work on it @Suryansh5545

**Comment by Sanji515** [comment]
Nice catch @Kajol-Kumari Thanks for reporting this issue and opening PR.
