### ISSUE TITLE
Hardware configuration

### ISSUE THREAD

**Issue by msubglb** [Cloud-CV/EvalAI#2654]
Hi,

This question is related to hardware configuration. We would like to host a "Host Prediction upload based challenge" based internal challenge.  What kind of server capacity and HW configuration needed to host this challenge with 1000 team participants.

Thanks,
Mahesh

**Comment by RishabhJain2018** [comment]
Hi @msubglb ,

Thanks for reaching out to us. For hosting, you can use `m4.2xlarge`  but it will again depend upon the size of your annotation files as they are loaded in the RAM.
Please feel free to ask if you've more questions.
