### ISSUE TITLE
Host team can't remove member 

### ISSUE THREAD

**Issue by Kajol-Kumari** [Cloud-CV/EvalAI#2656]
Current Behaviour:
If a Host Team add a member in his/her team by mistake,he/she will have to create a new host team from scratch in order to remove that particular member.

Feature Requested:
There should be a delete option(in the form of icon will be more suitable) after the name of each member of the team. It will make it easier for the host to remove any of his/her member if needed.

Screenshot
![Screenshot from 2020-02-08 02-25-27](https://user-images.githubusercontent.com/44888949/74065562-33b08400-4a1b-11ea-960b-9fb859d737f9.png)

**Comment by Suryansh5545** [comment]
@Kajol-Kumari As this is similar to other issue can we just change the name of your other issue and include both of these and merge this delete member change in single pr.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari As this is similar to other issue can we just change the name of your other issue and include both of these and merge this delete member change in single pr.

I was thinking of the same @Suryansh5545 but was not sure.Thanks for suggestion, i am adding it in the other issue and removing this one.
