### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by Kajol-Kumari** [Cloud-CV/EvalAI#2657]
- Expected behaviour
After adding a particular number of host team(4-5),the next team should go too the next page.

- Observed behaviour
Even after adding 12 teams, all the teams are being displayed on the same page
- Steps to reproduce the problem
Go to Host team -> Add 5-6 team there.

GIF:
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/44888949/74066414-0a90f300-4a1d-11ea-860d-39c91e1ee07f.gif)

**Comment by Sanji515** [comment]
Thanks for the issue but if we lessen the enteries per page then the challenges won't be displayed on the challenge list page as we have not added pagination on the [challenge list page](https://cloudcv.slack.com/archives/C2P84STC6/p1581110162002900). And for adding pagination first we are thinking to add tabs (Ongoing, Upcoming and Past Challenges) on top of the page for displaying these challenges.

@Kajol-Kumari First can you please add tabs (Ongoing, Upcoming and Past Challenges) in challenge list page?

**Comment by Suryansh5545** [comment]
@Sanji515 Sir where are we talking to add these tabs

**Comment by Kajol-Kumari** [comment]
> Thanks for the issue but if we lessen the enteries per page then the challenges won't be displayed on the challenge list page as we have not added pagination on the [challenge list page](https://cloudcv.slack.com/archives/C2P84STC6/p1581110162002900). And for adding pagination first we are thinking to add tabs (Ongoing, Upcoming and Past Challenges) on top of the page for displaying these challenges.
> 
> @Kajol-Kumari First can you please add tabs (Ongoing, Upcoming and Past Challenges) in challenge list page?

@Sanji515 sir, I will add the tabs first but can you please elaborate what and where should the feature added.

**Comment by Sanji515** [comment]
> where are we talking to add these tabs?

> I will add the tabs first but can you please elaborate what and where should the feature added.

@Suryansh5545 @Kajol-Kumari We want to add tabs on the page where all the challenges are listed ([here](https://evalai.cloudcv.org/web/challenges/list)). Instead of showing `Ongoing`, `Upcoming` and `Past` challenges in one page we want to show them in different tabs. So basically there will be 3 tabs for Ongoing, Upcoming and Past Challenges.

And also we want to add this feature directly in [ngx-project](https://github.com/Cloud-CV/EvalAI-ngx).

**Comment by Suryansh5545** [comment]
@Sanji515 Sir like a collapsible for each tab ?

**Comment by Kajol-Kumari** [comment]
@Sanji515 If i am getting it correctly, the requirement is to have three tabs on the top of the challenge list page which will help the user to navigate to the particular page containing particular type of challenge(upcoming,past,ongoing). If this is so, then challenge list page will have to look somewhat like main Dashboard having three tabs each for creating of viewing particular type of challenge.

Please correct me i am wrong.

**Comment by Suryansh5545** [comment]
@Sanji515 A month ago I made a pr to add collapsible to all three tab upcoming, ongoing and past . So user can navigate easily.  So are we talking about adding that sort of thing? #2590

**Comment by Sanji515** [comment]
> @Sanji515 Sir, A month ago I made a pr to add collapsible to all three tab upcoming, ongoing and past . So user can navigate easily. So are we talking about adding that sort of thing? #2590

No @Suryansh5545 , actually we are thinking to add tabs on the top instead of collapsible.

**Comment by Suryansh5545** [comment]
@Sanji515 Ok, Sir got it also I am closing that old pr.

**Comment by Sanji515** [comment]
> @Sanji515 If i am getting it correctly, the requirement is to have three tabs on the top of the challenge list page which will help the user to navigate to the particular page containing particular type of challenge(upcoming,past,ongoing). If this is so, then challenge list page will have to look somewhat like main Dashboard having three tabs each for creating of viewing particular type of challenge.

Yes, correct! @Kajol-Kumari but we don't have tabs on the [dashboard page](https://evalai.cloudcv.org/web/dashboard).

**Comment by Suryansh5545** [comment]
@Kajol-Kumari I think @Sanji515 sir is talking about this type of tab https://materializecss.com/tabs.html

**Comment by Kajol-Kumari** [comment]
Got it @Sanji515 and @Suryansh5545 thanks for that link. Can i start working on it?

**Comment by Sanji515** [comment]
Sure @Kajol-Kumari

**Comment by Suryansh5545** [comment]
@Sanji515 Sir , I was thinking maybe we can show some pagination below each challenge card containing small description. This might decrease the time the user takes to search for or decide.?

**Comment by apoorvkhare07** [comment]
Hello @RishabhJain2018, Is this issue still open or the pull request fixes it?

**Comment by Kajol-Kumari** [comment]
@apoorvkhare07 The PR is for adding tabs to the challenge list page. Pagination part is still left, so if you wish, you can work on pagination part.

cc: @RishabhJain2018 @Sanji515

**Comment by amanpro1** [comment]
@apoorvkhare07  @RishabhJain2018  @Sanji515  I would like to work on adding pagination as no one is currently working on this.
