### ISSUE TITLE
Squash all commits into single commit in pull request

### ISSUE THREAD

**Issue by Kajol-Kumari** [Cloud-CV/EvalAI#2658]
Current Behaviour:
Each pull request contains many commits that makes it difficult for the reader.

Feature Requested:
Add squash feature in the Contribution guideline (https://github.com/Cloud-CV/EvalAI/blob/master/.github/CONTRIBUTING.md). This will help the contributors to squash all the commits in a single commit making the pull request much cleaner than now.

Steps to squash:
1. git rebase -i HEAD~N(N is the number of commits you want to squash into 1).
2. Then a screen will appear with all N commits having "pick" written in front of every commit.
3. change pick to s for the last N-1 commits and let it be pick for the first one and save it.
4. Then it will ask to change commit message change it accordingly and save it and then force push

For further info, please visit:
https://www.internalpointers.com/post/squash-commits-into-one-git

**Comment by Suryansh5545** [comment]
@Kajol-Kumari The suggestion is quite good . But we should also see the pros and cons http://www.davidchudzicki.com/posts/first-parent and after this if community finds it ok then we can add this as a mandatory or suggested way to keep pr nice and organized

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari The suggestion is quite good . But we should also see the pros and cons http://www.davidchudzicki.com/posts/first-parent and after this if community finds it ok then we can add this as a mandatory or suggested way to keep pr nice and organized

@Suryansh5545 Most of the against points can be tackled by adding a note in the guideline i.e "Please squash only if you are done with all the work to done with that pr and has been reviewed by one of the mentor." And rest as the community decides after looking at the suggestions and docs.

**Comment by Suryansh5545** [comment]
@Kajol-Kumari Yea this can be done.

**Comment by RishabhJain2018** [comment]
Thanks, @Kajol-Kumari for the issue and @Suryansh5545 for the suggestion. Can anyone of you please add this and open up a PR?

**Comment by Kajol-Kumari** [comment]
@RishabhJain2018 I would like to work on it.

**Comment by RishabhJain2018** [comment]
This is fixed.
