### ISSUE TITLE
Unclear Naming to variables

### ISSUE THREAD

**Issue by Kajol-Kumari** [Cloud-CV/EvalAI#2666]
Current Behaviour:
Many Variable names are unclear and creates confusion regarding their purpose.

Expected Behaviour:
Variable names should clearly describe its purpose.

References:
1. https://github.com/Cloud-CV/EvalAI/blob/master/frontend/tests/controllers-test/challengeHostTeamsCtrl.test.js#L418
Here, the test is written for delete function for hostTeam where Variable name "ParticipantId" is not appropriate and hence leading to the confusion.

2. https://github.com/Cloud-CV/EvalAI/blob/master/frontend/tests/controllers-test/challengeHostTeamsCtrl.test.js#L441
Here, the controller function is written for delete function for hostTeam where Variable name "ParticipantId" is not appropriate and hence leading to the confusion.

3. https://github.com/Cloud-CV/EvalAI/blob/master/apps/hosts/urls.py#L27
According to the name the url has got, it should have been for getting details of the hostTeam but instead it's doing all of the get,post,patch and delete operations on the challenge_host_team

**Comment by RishabhJain2018** [comment]
Hi @Kajol-Kumari,
Thanks for opening the issue and the corresponding PR. We would be happy to incorporate the suggestion. Can you please write in the description here why the variable names are incorrect and are creating confusion?
