### ISSUE TITLE
Remote worker tests missing.

### ISSUE THREAD

**Issue by pushkalkatara** [Cloud-CV/EvalAI#2678]
Hi,

There are several tests missing for `remote_worker.py`.

Codebase - https://github.com/Cloud-CV/EvalAI/blob/master/scripts/workers/remote_submission_worker.py

Testfile - https://github.com/Cloud-CV/EvalAI/blob/master/tests/unit/remoteworker/test_remote_worker.py

Coverage report: https://codecov.io/gh/Cloud-CV/EvalAI/src/master/scripts/workers/remote_submission_worker.py

@RishabhJain2018 @vkartik97 Can I work on this issue?

Missing Tests:
`remote_submission_worker.py`

- [x] download_and_extract_zip_file (https://github.com/Cloud-CV/EvalAI/pull/2690)
- [x] load_challenge (https://github.com/Cloud-CV/EvalAI/pull/2527)
- [x] process_submission_message (https://github.com/Cloud-CV/EvalAI/pull/2551)
- [x] extract_challenge_data (https://github.com/Cloud-CV/EvalAI/pull/2690)
- [x] extract_submission_data (https://github.com/Cloud-CV/EvalAI/pull/2690)
- [x] process_submission_callback (https://github.com/Cloud-CV/EvalAI/pull/2690)

**Comment by RishabhJain2018** [comment]
Yes, definitely.

**Comment by pushkalkatara** [comment]
Noticed two open PR for the issue - 

1. https://github.com/Cloud-CV/EvalAI/pull/2551
2. https://github.com/Cloud-CV/EvalAI/pull/2527

**Comment by nikochiko** [comment]
I would like to add that apart from the unit tests, the integration tests for remote submission worker are also missing (ref: https://github.com/Cloud-CV/EvalAI/issues/2607).
I am not sure how it is supposed to be, but consistency-wise it makes sense to have both.
cc: @RishabhJain2018

**Comment by pushkalkatara** [comment]
@nikochiko Thanks for pointing out. I have added a list above of missing tests, also referenced open PRs for the same. Do add to the list if you find something missing.

**Comment by RishabhJain2018** [comment]
Similar to #2607, hence closing it.
