### ISSUE TITLE
Test and Verify django, worker container with python 3.7.5

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2685]
**Description:**

We would like to update the python dependency from 3.6.5  to 3.7.5 and it requires testing of django and worker development container with python3.7.5

**Deliverables:**
- [ ] Test the Django docker container and if it works fine, then update the dev Dockerfile with python3.7.5 as the base image.
- [ ] Test the worker docker container and if it works fine, then update the dev Dockerfile with python3.7.5 as the base image.

**Comment by Ayukha** [comment]
Can I take this up?

**Comment by RishabhJain2018** [comment]
Sure @Ayukha

**Comment by Ayukha** [comment]
@RishabhJain2018  `Python:3.7.5` is built upon `Debian 10 Buster`and `Python:3.6.5` was on `Debian 9 stretch`, it has dropped support for `openjdk-8-jdk` because of security issues, I have updated to `jdk 11` which is the latest LTS and it works fine. Should i open a PR for same?

**Comment by RishabhJain2018** [comment]
sounds good, please open the PR.
