### ISSUE TITLE
Irrelevant dependencies installed in docker images

### ISSUE THREAD

**Issue by Ayukha** [Cloud-CV/EvalAI#2693]
The docker files contain dependencies related to Django which are not used by the Workers and Celery. The current size of the docker images can be reduced to a large amount if we remove the irrelevant requirements.

- [ ] Separate requirement files for worker and remote worker

- [ ]  Seperate dockerfile for remote worker

- [ ] remove irrelevant dependencies from dockerfile

@RishabhJain2018

**Comment by RishabhJain2018** [comment]
Thanks @Ayukha for pointing it out. Please feel free to work on it.

**Comment by RishabhJain2018** [comment]
This issue is still open :)

**Comment by pystar-oss** [comment]
@RishabhJain2018  I would like to work on it

**Comment by RishabhJain2018** [comment]
Sure @pystar-oss you can take this up.

**Comment by adityaketkar** [comment]
@pystar-oss if you are still working on this issue? if not, @RishabhJain2018 can I take this up?

**Comment by RishabhJain2018** [comment]
This is fixed, hence closing it.
