### ISSUE TITLE
django-import-export is not able to export the files

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2694]
**Description:**
Django import-export isn't able to export the files. The list for the type of file to be exported doesn't open. Please see the screenshot for more reference.
<img width="1390" alt="Screenshot 2020-03-01 at 2 22 28 PM" src="https://user-images.githubusercontent.com/12206047/75632267-66880b00-5bc8-11ea-84e7-d90ee695f848.png">

**Comment by Ayukha** [comment]
can i take this up?

**Comment by RishabhJain2018** [comment]
Sure @Ayukha .

**Comment by yashdusing** [comment]
@Ayukha aren't you working on #2693 ?

**Comment by RishabhJain2018** [comment]
I think @Ayukha didn't ask to work on #2693. I simply asked him to work. My bad. Since @Ayukha is working on this one, @yashdusing would you like to pick up #2693 ?

**Comment by yashdusing** [comment]
@RishabhJain2018 Yes, sure

**Comment by RishabhJain2018** [comment]
Perfect!
