### ISSUE TITLE
Display stats on homepage dynamically

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2695]
**Description**
The count for hosted AI challenges, users, submissions on homepage is hardcoded in the codebase and we want to update it dynamically.

**Deliverables:**
- [ ] Add API to fetch the total count of ongoing and past challenges, users and submissions.
- [ ] Update the homepage code fetch using the above API.
- [ ] Add unit tests for the backend and frontend.

cc: @Ram81 @Sanji515 @vkartik97

**Comment by yashdusing** [comment]
Can I work on this instead of #2693 ?

**Comment by RishabhJain2018** [comment]
Sure.

**Comment by yashdusing** [comment]
@RishabhJain2018 do we need real time updates ? Or updates on load only ?

**Comment by srichakradhar** [comment]
Hi.. Is this issue still open to claim? Are you finished working on this @yashdusing ?

**Comment by yashdusing** [comment]
@srichakradhar I already have made a PR for it. It’s still underway. Could you please take up some other issue?

**Comment by deshraj** [comment]
Thank you for your interest everyone. We have decided to punt this feature for a future relase, hence closing this issue for now.
