### ISSUE TITLE
Add models for storing organization information

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2696]
**Description:**
The information for the organization name, logo are hardcoded in the homepage. We would like to update this information dynamically from the backend.

 **Deliverables:**
- [ ] Add models for storing the information of the organizations in the `web` app.
- [ ] The table name should be - Organization
- [ ] The model fields should be - name, logo, is_active (boolean flag to decide if we want to show it on the homepage or not, defaults to True)
- [ ] Register the models in the Django admin.
- [ ] Name the migration file to -`add_models_to_store_partner_organizations`

**Comment by pushkalkatara** [comment]
Hi @RishabhJain2018 Would it be fine if I take this up with #2678 in review?

**Comment by RishabhJain2018** [comment]
Sure.

**Comment by pushkalkatara** [comment]
@abbasidaniyal Please claim the issue before making a PR to avoid conflicts. I already claimed the issue with the https://github.com/Cloud-CV/EvalAI/issues/2696#issuecomment-593231047 and recently made a PR for the same. I noticed you worked on the same issue with the PR #2705 and now we two same PR for the issue.

**Comment by abbasidaniyal** [comment]
@pushkalkatara My apologies. I'll take care from now onwards!

**Comment by deshraj** [comment]
We have decided to punt this feature to a later release and work on other important stuff we have on plate.
