### ISSUE TITLE
Show organization logos dynamically from backend

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2697]
Dependent on #2696 (Can be worked only when this is merged.)

**Description:**
The organizations using EvalAI are hardcoded in the codebase with their logos. We would like to load these organizations from the backend.

**Deliverables:**
- [ ] Add an API to fetch the logos from the backend for which `is_active=True`.
- [ ] Change the frontend code to use this API and display the logos.

**Comment by pystar-oss** [comment]
@RishabhJain2018 I would like to work on it

**Comment by Sanji515** [comment]
Sure @pystar-oss

**Comment by pushkalkatara** [comment]
@pystar-oss Are you still working on the issue? If not, can I take this up @Sanji515 ?

**Comment by aryanmediratta** [comment]
@Sanji515 Can I work on this?

**Comment by yashdusing** [comment]
@RishabhJain2018 is this issue still open ? If yes, can I work on it ?

**Comment by RishabhJain2018** [comment]
Yes, it is open.

**Comment by pushkalkatara** [comment]
@yashdusing Are you working on this? 

Also, @RishabhJain2018 there is an open PR (https://github.com/Cloud-CV/EvalAI/pull/2707) for the referenced issue. Please review.

**Comment by yashdusing** [comment]
@pushkalkatara yes, I'd like to work on this issue

**Comment by deshraj** [comment]
Lets punt this feature. I am afraid that this will make the frontend page slow and doesn't add too much value. We can once in a while keep updating the stats on the main page. Thanks all for your interest in working on this issue.
