### ISSUE TITLE
Add a tab for participated challenges for participants

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2698]
**Description**:
As the number of challenges is increasing on EvalAI, we need a separate tab for participants which will show only the challenges in which they have participated (Similar to Hosted Challenges).

**Deliverables**:
- [ ] Add an API to fetch the participated challenges for a particular user.
- [ ] Add a tab in the left sidebar to show the participated challenges for a participant like the hosted challenges.

**Comment by Ayukha** [comment]
@RishabhJain2018  Can I take this up?

**Comment by Suryansh5545** [comment]
@RishabhJain2018 Sir i think we have a similar issue already #2515

**Comment by Sanji515** [comment]
I see @Suryansh5545 ... lets close [#2515 ](https://github.com/Cloud-CV/EvalAI/issues/2515). And I think as no one is working on this issue @Ayukha you can take this one.

**Comment by Sanji515** [comment]
I think @Ayukha is already working on [this](https://github.com/Cloud-CV/EvalAI/issues/2694) issue so this issue is still open.

**Comment by aryanmediratta** [comment]
@Sanji515 Can I take this up?

**Comment by Sanji515** [comment]
Sure @aryanmediratta

**Comment by Ayukha** [comment]
@Sanji515  i have already opened a PR for #2694

**Comment by Sanji515** [comment]
oh I see then @Ayukha you can work on this issue.

**Comment by Sanji515** [comment]
@aryanmediratta Please feel free to take up any other issue :)
