### ISSUE TITLE
[Feature Proposal] Add support to signup/login using Github OAuth

### ISSUE THREAD

**Issue by adityaketkar** [Cloud-CV/EvalAI#2710]
The signup experience can be simplified by integrating a "Sign up using Github" link along with the current sign up form. 

Proposed Feature : 
- "Sign up using Github" option during registration.
- "Sign in using Github" option during login.

**Comment by Kajol-Kumari** [comment]
Hey @adityaketkar  I think it's a copy of #2291

**Comment by adityaketkar** [comment]
@Kajol-Kumari yes, indeed they are same. I'll close this issue. Thanks for pointing out.
