### ISSUE TITLE
Add search bar in all challenges view to filter challenges based on title

### ISSUE THREAD

**Issue by adityaketkar** [Cloud-CV/EvalAI#2711]
**Description:**

Following up with #2699, use the new API to query the database for challenges based on title input by the user.   

**Deliverables:**
- [ ] Add appropriate functions in the controller to call the new API
- [ ] Add a search bar in front-end and connect it to the controller

**Comment by adityaketkar** [comment]
@RishabhJain2018 can you review #2699 so I can take this up?

**Comment by Suryansh5545** [comment]
@adityaketkar I think  this issue is similar to #2591 . And it was decided to close it for #2699 . As it seems much better.

**Comment by adityaketkar** [comment]
@Suryansh5545 I agree. Should I add these deliverables in #2699 and close this issue ?

**Comment by Suryansh5545** [comment]
@adityaketkar the idea is already rejected in #2591  so I don't think the community needs it now . But it's your choice.

**Comment by adityaketkar** [comment]
Thanks for the information @Suryansh5545. Closing this issue.

**Comment by RishabhJain2018** [comment]
@adityaketkar Is it possible for you to open up a PR for the same as you have a working demo here: https://github.com/Cloud-CV/EvalAI/issues/2699#issuecomment-593934154

**Comment by adityaketkar** [comment]
> @adityaketkar Is it possible for you to open up a PR for the same as you have a working demo here: [#2699 (comment)](https://github.com/Cloud-CV/EvalAI/issues/2699#issuecomment-593934154)

Sure. I'll create a PR.

**Comment by RishabhJain2018** [comment]
Similar to #2699 and closing this one.
