### ISSUE TITLE
Add a proper API Documentation 

### ISSUE THREAD

**Issue by mrinalwahal** [Cloud-CV/EvalAI#2737]
The current **ReadTheDocs** documentation only points to the codebase `eval-ai/urls` for APIs. This makes it complicated for the reader to browse through and understand which endpoint serves which purpose. The reader, who perhaps might be a developer writing a new external integration with EvalAI, may need to waste their time going through the codebase only to understand which endpoints to interact with and how.

EvalAI needs to publish a fresh and thorough API documentation. Perhaps this can be done in a more straight-forward manner by using Swagger with Django REST Framework, to automate the process.

**Comment by deshraj** [comment]
@mrinalwahal thanks for opening the issue. This seems like a reasonable idea to have the REST API documentation available for general use. Right now, we have integrated DRF Docs for seeing API documentation during development only (you can visit http://localhost:8000/docs/ to see on your local development environment). 

We would love to expose the API documentation to the general public. If you are interested in working on this issue, please let us know. :)

**Comment by mrinalwahal** [comment]
@deshraj sure I'm up for it.

**Comment by RishabhJain2018** [comment]
@deshraj Thanks for the suggestion and we have already exposed the documentation to general public here https://evalapi.cloudcv.org/api-docs/ .

@mrinalwahal If you want to work on it then please help us in enhancing the documentation.

**Comment by deshraj** [comment]
My bad. Thanks Rishabh for pointing out. Didn't realize that we exposed it long back. 😅 

Closing this issue.
