### ISSUE TITLE
## [Warning] : Logged into multiple windows

### ISSUE THREAD

**Issue by amanpro1** [Cloud-CV/EvalAI#2738]
# Warning : You may be disabled from previous logged in windows
A warning message should popped up when user attempts to log in into another browser window if he/she is already logged in into an existing window.
- [ ] Create warning before logging the user into existing window

**Comment by amanpro1** [comment]
@RishabhJain2018 If it's seems to be genuine issue to me. I would like to work on this.

**Comment by deshraj** [comment]
@amanpro1 thanks for opening the issue but this behavior is something which is works fine and we would still keep it the way it is right now.
