### ISSUE TITLE
Requirements broken

### ISSUE THREAD

**Issue by gauthamzz** [Cloud-CV/EvalAI#275]
This error was being thrown   
` File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named storages `

fixed by `pip install django-storages` Should this be added to requirements ?

**Comment by deshraj** [comment]
@gauthamzz I think you tried to run with the production config file, that's why you encountered this error. Can you tell me the command which threw this error?

**Comment by gauthamzz** [comment]
python manage.py runserver 
It was working fine earlier.

**Comment by deshraj** [comment]
It would have worked earlier but as we are making changes, it will break since the default settings is `settings.prod`. So, you will have to run the command `python manage.py runserver --settings=settings.dev`.

**Comment by gauthamzz** [comment]
Okay . Thanks
