### ISSUE TITLE
Add functionality to send slack notifications

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2761]
**Description:**
Some of the challenge hosts are curious to know when the submissions to their challenge are coming, hence they want to post on the slack channel whenever a new submission comes in.

**Deliverables:**
- [ ] Add a nullable with blank=True URL field in the Challenge model with the name `slack_webhook_url`.
- [ ] Add a migrations file for the same.
- [ ] Use the function from base/utils for sending slack notification.
- [ ] In the function `publish_submission_message` in `jobs/sender.py`, if there is a `slack_webhook_url` in the challenge model, then call the function in the above step with this URL after sending the message in the queue.
- [ ] Add required unit tests.

**Comment by Ayukha** [comment]
@RishabhJain2018 I'd like to work on it

**Comment by RishabhJain2018** [comment]
Sure, @Ayukha. Thanks for picking it up.
