### ISSUE TITLE
Add models to disable/delete submissions

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#2767]
**Motivation**:
Some of the challenge hosts want to delete the 'canceled` submissions and the submission in which participants have uploaded non-standard submission files from their All Submissions view. Hence, we require this feature.

**Deliverables**:
- [ ] Add a boolean field `ignore_submission` with default as False in the Submissions model.
- [ ] Add migration file for the added models.

**Comment by Ayukha** [comment]
@RishabhJain2018 can I take this up?

**Comment by RishabhJain2018** [comment]
sure, @Ayukha .

**Comment by RishabhJain2018** [comment]
@Ayukha Please change the boolean field name to `ignore_submission`.
