### ISSUE TITLE
Make Browsable API endpoint to be served in development environment only 

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#277]
We want the browsable API urlpattern https://github.com/Cloud-CV/EvalAI/blob/master/evalai/urls.py#L45 to be only served in the development environment.

**Comment by gauthamzz** [comment]
can i try this?

**Comment by deshraj** [comment]
@gauthamzz Sure, go ahead.

**Comment by deshraj** [comment]
Fixed in #278
