### ISSUE TITLE
Tiles in Challenges List page not aligned properly

### ISSUE THREAD

**Issue by vkartik97** [Cloud-CV/EvalAI#2773]
- The Observed Behaviour: 
The Challenge Listing is not aligned properly
<img width="1280" alt="Screenshot 2020-05-03 at 4 10 08 PM" src="https://user-images.githubusercontent.com/3920286/80926919-cca33100-8db7-11ea-9f38-a6c384979330.png">
- Steps to reproduce the problem: Open https://evalai.cloudcv.org/web/challenges/list <br>
- OS: macOS Mojave<br>
- Browser: Firefox 75.0<br>
<br><br>
Thanks!

**Comment by RishabhJain2018** [comment]
@Kajol-Kumari Would you like to wok on this?

**Comment by Kajol-Kumari** [comment]
sure @RishabhJain2018 sir.
