### ISSUE TITLE
Alignment in sponsors list 

### ISSUE THREAD

**Issue by Ayukha** [Cloud-CV/EvalAI#2776]
- the observed behaviour
 Sponsors list not Centrally aligned 
![Screenshot_20200504-063016~2](https://user-images.githubusercontent.com/19167324/80976955-b772e480-8e41-11ea-90a8-2dab249522e6.png)

- steps to reproduce the problem
 Open evalai.cloudcv.org in mobile view

**Comment by RishabhJain2018** [comment]
Thanks @Ayukha for catching it. Would you like to work on this?

**Comment by Ayukha** [comment]
@RishabhJain2018 sure!

**Comment by yashdusing** [comment]
Weirdly, I can't see the images on my PC but it's visible on other devices 

![screenshot-evalai cloudcv org-2020 05 04-20_16_10](https://user-images.githubusercontent.com/19976688/80978781-23eee300-8e44-11ea-9cbb-2d2be1d8f5b4.png)

**Comment by RishabhJain2018** [comment]
It's a cache issue. Can you please do a hard refresh.

**Comment by yashdusing** [comment]
Tried emptying cache and doing a hard refresh. Still the same issue

**Comment by yashdusing** [comment]
I think it has something to do with the 'sponsor-logo' tag in CSS since after debugging and trying to remove the 'sponsor-logo' tag the images did appear.

**Comment by deshraj** [comment]
I think it's more of an issue with the current config of Nginx which caches the static files. Might want to look into nginx config and see what needs to be changed.

**Comment by yashdusing** [comment]
I think it's because of the css tag because the image does load and it did show up in the dev debug tools. My resolution is higher (3840 x 2160) which could be another cause for the non-rendering
![screencast-evalai cloudcv org-2020 05 04-22_26_54](https://user-images.githubusercontent.com/19976688/80992123-ad0f1580-8e56-11ea-9446-113bbfb18bd6.gif)

**Comment by Ayukha** [comment]
![img](https://user-images.githubusercontent.com/19167324/80992710-8d2c2180-8e57-11ea-8428-bf8c4145df66.png)
 @yashdusing I am able to get the images with same css.
Can you specify the browser yo are using?

**Comment by yashdusing** [comment]
I am using Chrome. I also checked the version and there's no pending updates

**Comment by Ayukha** [comment]
I tried it on chrome and firefox both, it works fine for me.

**Comment by yashdusing** [comment]
It shows up on edge.

**Comment by deshraj** [comment]
I am fairly confident it's a cache issue. The fix is by looking and changing the nginx configuration appropriately. :)

**Comment by deshraj** [comment]
Ok I was wrong. 😅 Turns out that this issue is related to the css getting overriden by some other class. I believe @RishabhJain2018 is going to open a PR for the same soon.

**Comment by RishabhJain2018** [comment]
This is already fixed in #2790 :).
Closing this issue.
