### ISSUE TITLE
Installation error: nodejs failed to build

### ISSUE THREAD

**Issue by vpozdnyakov** [Cloud-CV/EvalAI#2787]
- Expected behaviour: Installation EvalAI is successful
- Observed behaviour: Error
`Service 'nodejs' failed to build: The command '/bin/sh -c apt-get update && 	apt-get -y install gconf-service libasound2 libatk1.0-0 libc6 libcairo2libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 		libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 		libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 		libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 		libnss3 lsb-release xdg-utils wget' returned a non-zero code: 100`
[installation_log.txt](https://github.com/Cloud-CV/EvalAI/files/4603232/installation_log.txt)
- Steps to reproduce the problem: 
1. Install Docker and Docker-compose
2. `git clone https://github.com/Cloud-CV/EvalAI.git evalai `
3. `cd evalai`
4. `docker-compose up --build`
- Operating system and Docker version
First setup: macOS Mojave 10.14.6, Docker version 2.2.0.5 (43884), Compose 1.24.4
Second setup: Windows 10 Pro 1909, Docker version 2.2.0.5 (43884), Compose 1.25.4

**Comment by vpozdnyakov** [comment]
I fixed it using this correction in evalai/docker/dev/nodejs/Dockerfile
![image](https://user-images.githubusercontent.com/12996098/81476800-7b15fe80-921c-11ea-8c15-f97c73d3e80f.png)

**Comment by RishabhJain2018** [comment]
Thanks @vpozdnyakov for reporting this.

Fix for this issue #2789
