### ISSUE TITLE
Setup logging in django

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#28]
For more information, see this https://docs.djangoproject.com/en/1.10/topics/logging/

**Comment by TroJan** [comment]
I can work on this

**Comment by deshraj** [comment]
Great. :-)

**Comment by anweshknayak** [comment]
is someone working on this ?

**Comment by TroJan** [comment]
@anweshknayak : the work is already done, just forget to get it into master.

**Comment by TroJan** [comment]
where is this stuck? @deshraj

**Comment by deshraj** [comment]
Fixed in #33
