### ISSUE TITLE
Create a custom 500 and 404 error page in for django

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#280]
For reference, see this http://stackoverflow.com/questions/17662928/django-creating-a-custom-500-404-error-page

**Comment by anweshknayak** [comment]
@deshraj Im working on this.

**Comment by deshraj** [comment]
Sure, go ahead. Please ask before working on any issue otherwise it would be a duplicate effort.

**Comment by anweshknayak** [comment]
@deshraj sure :)

**Comment by anweshknayak** [comment]
@deshraj this custom error page for every app?

**Comment by deshraj** [comment]
No, there will be a single 404 and 500 error page. Please see the reference link that I shared.

**Comment by RishabhJain2018** [comment]
@deshraj Is someone still working on this issue??

**Comment by anweshknayak** [comment]
Yes. Code is almost done. Tests needs to be added

**Comment by anweshknayak** [comment]
@RishabhJain2018 let me know if you can help with the tests. you can see the closed PR. @deshraj can we split this ?

**Comment by deshraj** [comment]
Yeah sure. That sounds like a collaborative effort. :-)

**Comment by RishabhJain2018** [comment]
@anweshknayak yeah sure, I will help you with the tests. :+1:

**Comment by anweshknayak** [comment]
@aka-jain #290 related to this ?

**Comment by aka-jain** [comment]
No @anweshnayak , It's on backend side.

**Comment by RishabhJain2018** [comment]
@deshraj For adding tests, Can I create a file on this path `tests/unit/evalai/test_urls.py`.

**Comment by deshraj** [comment]
@RishabhJain2018 please use this file `tests/unit/evalai/test_views.py` for test or create one if does not exist.

**Comment by deshraj** [comment]
@RishabhJain2018 We will remove the URL later. Not related to this PR. Also, we might use it somewhere in future.

**Comment by RishabhJain2018** [comment]
@deshraj ok.

**Comment by deshraj** [comment]
Looks like this is causing issue. @jainarunarunjain is working on it. Let me know @jainarunarunjain if you want some context about the bug.

**Comment by deshraj** [comment]
Forgot to close. Fixed now.

**Comment by deshraj** [comment]
Reopening this since now the 404 and 500 template would be on backend and won't be dependent on the frontend. @jainarunarunjain let me know if you are interested in working on this issue. I can guide you. :-)

**Comment by jainarunarunjain** [comment]
@deshraj Sure, I want to work on this.

**Comment by deshraj** [comment]
Awesome. Let me know if you need any help. :-)

**Comment by jainarunarunjain** [comment]
@deshraj please give me some details.

**Comment by deshraj** [comment]
So, in `apps/web/templates` directory create two templates named `500.html` and `404.html` in which you can add basic html content that can be modified later. Also, you would need to create a custom 404 and 500 handler for the same as it was before.

**Comment by deshraj** [comment]
fixed in #631
