### ISSUE TITLE
Evalai UI leaving White Space in both sides

### ISSUE THREAD

**Issue by Suryansh5545** [Cloud-CV/EvalAI#2830]
**The expected behaviour:-**
The UI should make use of all the space provided leaving no white space in left and right sides of the screen.
**The observed behaviour:-**
The Screen leaves a lot of white space in both the left and right. i tried debugging it but there is no paramenter which might make UI leave these types of margins. I also tried running the evalai in VM and other devices and the results are same.
**Screenshot:-**
![Selection_001](https://user-images.githubusercontent.com/34577232/83385230-7bae4900-a406-11ea-9f42-fe7abd3959c2.png)
OS:- Ubuntu 20.04

**Comment by Suryansh5545** [comment]
@Kajol-Kumari is this a new update or a bug . because it wasn't like that do you have any idea what has happened to UI?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari is this a new update or a bug . because it wasn't like that do you have any idea what has happened to UI?

Hey @Suryansh5545 please check you browser's view once as I don't see any problem in the UI on my PC.

**Comment by Suryansh5545** [comment]
@Kajol-Kumari what is your screen resolution . i just checked it in a small laptop with 1366*768 resolution and it was ok . but on big screens bigger than 1366*768 or 1440*900 it is not expending well and leaving white space. I previously have ran evalai main website and the github repo on monitor bigger than 1366*768 but problem never occured.

**Comment by Suryansh5545** [comment]
See even the evalai.cloudcv.org is acting differently
![Capture](https://user-images.githubusercontent.com/34577232/83515152-834b1c00-a4f2-11ea-843b-8e41e5817029.PNG)

**Comment by Suryansh5545** [comment]
can someone other than me confirm that weather they are having problem on bigger resolution displays?

**Comment by Kajol-Kumari** [comment]
@Suryansh5545 my screen resolution is also 1366 x 768 and i am getting the correct UI.
Please try resetting your browser view once 'coz i am getting the similar UI as you have mentioned here only when i reduced the browser's view to 75%. Please see the below screenshots:

At at view set to 75%
![Screenshot from 2020-06-02 17-06-21](https://user-images.githubusercontent.com/44888949/83515697-6cf19000-a4f3-11ea-9a6b-fcf97f441ae0.png)

After view reset:
![Screenshot from 2020-06-02 17-06-26](https://user-images.githubusercontent.com/44888949/83515741-80046000-a4f3-11ea-9982-a8d212813da2.png)

**Comment by Suryansh5545** [comment]
@Kajol-Kumari I have tested this on Ubuntu 20.04 , 18.04 and windows 10 and one other laptop of 1366^768. and on different browsers(Chrome and Firefox). So this definitely isn't something related to browser i think. maybe the UI is not longer scaling perfectly or something else.

**Comment by Suryansh5545** [comment]
Also i would like to add that this problem is only in the main repository. i have tested the ngx one and it works fine.

**Comment by Suryansh5545** [comment]
#2723 PR explains the reason for this issue so i am closing it. Also btw i think the older version was actually much better
