### ISSUE TITLE
Login fails for dafault user 

### ISSUE THREAD

**Issue by samcom12** [Cloud-CV/EvalAI#2859]
_
- the expected behaviour
Login of default user should be successful
- the observed behaviour
LOgin window keeps mum, doing nothing
- steps to reproduce the problem
Installed docker and docker-compose utility. and git clone evalAI from master branch. 
cd evalAI
docker-compose up --build 

It will start service on localhost:8888. click on login button use user admin and password as password.

- which operating system and/or browser you're using, if relevant
I have tried it on Windows 10 and CentOS 7 with latest chrome browser.

Thanks!

**Comment by deshraj** [comment]
@samcom12 I am not able to reproduce this issue. Can you please try a fresh install? Please make sure to remove all the EvalAI related docker containers first.

**Comment by deshraj** [comment]
Closing this for now. Please feel free to reopen if you still see the issue after retrying based on the above instructions.
