### ISSUE TITLE
Create Apis for Test Environment model

### ISSUE THREAD

**Issue by TroJan** [Cloud-CV/EvalAI#288]
Following apis should be created
* get list of all test environments for a particular challenge
* create a new test environment
* get details about a particular test environment
* update(partial also) a particular test environment
* delete specific test environment

**Comment by dexter1691** [comment]
@TroJan - This issue is resolved completely? 
Please feel free to close this issue if it's complete.

**Comment by TroJan** [comment]
For reference, Test Environment model is now ChallengePhase
