### ISSUE TITLE
Create 404 page for Client side.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#290]
Just add a content for 404 and a link for home page of Evalai.

**Comment by RishabhJain2018** [comment]
@aka-jain I will fix it.

**Comment by aka-jain** [comment]
@RishabhJain2018 : Please ask before started working on any issue, it'll be god for managing tasks :)

**Comment by RishabhJain2018** [comment]
@aka-jain sure.

**Comment by aka-jain** [comment]
@RishabhJain2018 : are you still working on it. Let me know please, so that others can work on this.

**Comment by RishabhJain2018** [comment]
@aka-jain Yeah I am working on the issue. I apologize for the delay.

**Comment by aka-jain** [comment]
Done with PR #314 .
Closing it.
