### ISSUE TITLE
Exception when model not found in `get_model_object` utils

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#2994]
### Description

Currently, the `get_model_object` util raises an exception when a model object with queried primary key is not found. This exception is not being handled in partial submission evaluation API. See [this](https://sentry.io/organizations/cloudcv/issues/1883775184/?project=152529&referrer=slack) error for an example

**Comment by burnerlee** [comment]
@Ram81 @RishabhJain2018, can I please take up this issue? I'll make a PR quickly to sort this out

**Comment by RishabhJain2018** [comment]
Sure!

**Comment by burnerlee** [comment]
@RishabhJain2018 the above error link does not work for me. Could you please also tell me the API where this error takes place?

**Comment by burnerlee** [comment]
``` 
url(
        r"^challenges/(?P<challenge_pk>[0-9]+)/update_partially_evaluated_submission/$",
        views.update_partially_evaluated_submission,
        name="update_partially_evaluated_submission",
    )
```
Is it the above API we are taking about?

**Comment by burnerlee** [comment]
@RishabhJain2018 please reassign this issue to me when possible. I have solved the other assigned issue and made a PR for the same. Also, please provide some insights on the error by answering the above query too

**Comment by RishabhJain2018** [comment]
Hey @burnerlee , You can work on this now. 

Regarding your query, I'll let @Ram81 respond to this.

**Comment by Ram81** [comment]
@burnerlee  yes this issue is for `update_partially_evaluated_submission` API

**Comment by burnerlee** [comment]
Oh thanks, I'll fix this. Thanks

**Comment by burnerlee** [comment]
@Ram81 @RishabhJain2018 made a PR #3150 to fix this. Please review

**Comment by RishabhJain2018** [comment]
Closing this as well as we will throw `404` for not found error.
