### ISSUE TITLE
Add pagination to challenge List page

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#300]
Need to add pagination for each challenge list (Past, Ongoing & Future) on challenge page.

For pagination use load more, clicking on which gets next list of data.

Let me know if anyone finds it difficult :)

**Comment by anweshknayak** [comment]
is the static data for pagination already there ? I see nothing.

**Comment by aka-jain** [comment]
@anweshnayak sure go ahead.
 You can create challenges by using django admin for now.
And yes, you have to include the pagination in same view.
Also for pagination use load more instead of page numbers.

**Comment by anweshknayak** [comment]
@aka-jain ne doubt regarding the pagination. As the attributes from the django-admin is not showing up in the challenge-list.html ? So how shall I proceed with it ?

**Comment by aka-jain** [comment]
Sorry, I'm not getting your point @anweshknayak.

**Comment by anweshknayak** [comment]
After I created challenges in django-admin. The html file should render all that created in django-admin as per the html file ? But it isn't ?

**Comment by aka-jain** [comment]
Yup, then what is coming there?

**Comment by anweshknayak** [comment]
![123](https://cloud.githubusercontent.com/assets/8139783/21621131/ab642dc2-d21d-11e6-95fe-2dfaa3bd630c.jpg)

nothing

**Comment by aka-jain** [comment]
Check console log.

**Comment by anweshknayak** [comment]
ERROR "GET /api/challenges/present HTTP/1.1" 500 21876
[2017-01-03 20:04:58] ERROR "GET /api/challenges/present HTTP/1.1" 500 21876
[2017-01-03 20:04:58] ERROR "GET /api/auth/user/ HTTP/1.1" 500 21844
[2017-01-03 20:04:58] ERROR "GET /api/auth/user/ HTTP/1.1" 500 21844
[2017-01-03 20:05:00] ERROR "GET /api/auth/user/ HTTP/1.1" 500 21844
[2017-01-03 20:05:00] ERROR "GET /api/auth/user/ HTTP/1.1" 500 21844
[2017-01-03 20:05:01] ERROR "GET /api/challenges/present HTTP/1.1" 500 21870
[2017-01-03 20:05:01] ERROR "GET /api/challenges/present HTTP/1.1" 500 21870

**Comment by aka-jain** [comment]
Are you logged in? I think your token has been expired. So try to open it in incognito.

**Comment by anweshknayak** [comment]
Yes im logged in. Tried in incognito not working. It is an issue from my end ?

**Comment by deshraj** [comment]
@anweshknayak can you try with this url localhost:8000/api/auth/user and try entering details there? Let me know what the response is.

**Comment by anweshknayak** [comment]
HTTP 401 Unauthorized
Allow: GET, PUT, PATCH, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
WWW-Authenticate: Token

{
    "detail": "Authentication credentials were not provided."
}

**Comment by deshraj** [comment]
Can you copy the token from django admin and then set it as authorization header in the API call that you are making. You can make API calls using the django docs that we have integrated with the project. Link for django docs to test the live API: http://localghost:8000/docs

**Comment by anweshknayak** [comment]
![screenshot from 2017-01-04 02 44 11](https://cloud.githubusercontent.com/assets/8139783/21623311/c5ab6970-d227-11e6-80e0-521567f54e54.png)

**Comment by deshraj** [comment]
@anweshknayak Please set authorization header as `Token <token_id>`. Then it will work.

**Comment by itaditya** [comment]
For the front end pagination load more button  ,this [link](http://jsfiddle.net/api/post/library/pure/) can help.

**Comment by dexter1691** [comment]
@anweshknayak : Any progress on this?

**Comment by anweshknayak** [comment]
@dexter1691 yes pagination is almost done. A few tweaks to the button(next,previous) is required. Will fix it soon :)

**Comment by aka-jain** [comment]
@anweshknayak : sorry to inform you late, but why you are using prev and next button here? We hae to show only load more button. Do you need any help?

**Comment by anweshknayak** [comment]
@aka-jain That was before when I was using plug - in. I thought that would be better to include prev and next. I will let you know in case of help :) I am working on it.

**Comment by aka-jain** [comment]
This task is free. Anybody up for it?

**Comment by jainarunarunjain** [comment]
@aka-jain Can i work on this

**Comment by aka-jain** [comment]
@jainarunarunjain : sure go ahead. let me know if you need any help.

**Comment by anweshknayak** [comment]
@jainarunarunjain you still working on this ?

**Comment by jainarunarunjain** [comment]
@anweshknayak sure, if you want then you can work on this.

**Comment by anweshknayak** [comment]
@jainarunarunjain  yup sure thanks :)

**Comment by aka-jain** [comment]
@anweshknayak : are you still trying this?

**Comment by anweshknayak** [comment]
@aka-jain Is it dependent on the pagination thing ? I was waiting for that to be fixed first as it was throwing error.

**Comment by aka-jain** [comment]
Anyone interested to solve this issue? Let me know.

**Comment by AliRaza3997** [comment]
I would like to work on this. Can I?

**Comment by deshraj** [comment]
Sure @AliRaza3997 :)

**Comment by deshraj** [comment]
@AliRaza3997 any progress on this?

**Comment by AliRaza3997** [comment]
@deshraj I won't be able to work on this for the next week. You can assign it to someone else. Sorry, for the inconvenience.

**Comment by TroJan** [comment]
@aka-jain : is this still required ?

**Comment by aka-jain** [comment]
Yes @taranjeet , We have to implement this on All Challenges Pages.

**Comment by spyshiv** [comment]
@aka-jain @RishabhJain2018 Any update on this? Is this done?

**Comment by RishabhJain2018** [comment]
@spyshiv No I don't think so.

**Comment by Obtin** [comment]
@RishabhJain2018 @aka-jain @spyshiv I would like to work on this, Thank you.

**Comment by deshraj** [comment]
@Obtin: feel free to work on this issue.

**Comment by deshraj** [comment]
We haven't reached to the state where we will need to add it in the client side. We already have the support for pagination on the backend side. We can revisit this later. Closing it as of now.
