### ISSUE TITLE
Auto deployment script failing

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3001]
### Description

The `./scripts/deployment/deploy.sh auto_deploy` is failing in the travis build. For reference see the build [here](https://travis-ci.org/github/Cloud-CV/EvalAI/builds/726818184#L6908). It is failing with following error

```
bash: docker-compose: command not found
```

**Comment by RishabhJain2018** [comment]
It was the docker-compose path issue on the server. It is fixed now!
