### ISSUE TITLE
Add a field max_submissions_per_day and max_submissions in ChallengePhase model

### ISSUE THREAD

**Issue by TroJan** [Cloud-CV/EvalAI#302]
Both the fields should be positive integer field with default value of 100K. 100K here means number of submissions are unlimited.

Adding these fields will involve creating a migration. Also please create a named migration.

**Comment by gauthamzz** [comment]
Can I try if unassigned?

**Comment by TroJan** [comment]
Yeah sure :)

**Comment by gauthamzz** [comment]
Close this ?

**Comment by TroJan** [comment]
@gauthamzz : sure. Thanks for the help :)
