### ISSUE TITLE
2099 End Date Issue

### ISSUE THREAD

**Issue by vivektalwar13071999** [Cloud-CV/EvalAI#3059]
![Screenshot from 2020-11-02 01-57-00](https://user-images.githubusercontent.com/24211231/97813516-c3374a80-1cae-11eb-819a-c6c6b77a739f.png)

Some End Dates in Challenges are showing 2099.
Expected Error in Date/Time Local code in the front-end.

**Comment by RishabhJain2018** [comment]
Hi @vivektalwar13071999, Thanks for opening the issue. The challenges that have `2099` as the end date are never-ending challenges, hence the date is in the future.

I am closing this thread as this is not an issue. Please feel free to reopen if you have any doubts.
