### ISSUE TITLE
Challenge Start Date is showing year 2020 and End Date is showing 2019

### ISSUE THREAD

**Issue by vivektalwar13071999** [Cloud-CV/EvalAI#3060]
![Screenshot from 2020-11-02 02-06-54](https://user-images.githubusercontent.com/24211231/97814839-1fe73500-1cb0-11eb-91bd-fe32b82a792f.png)

A front-end issue in the Past-Challenge section where challenge year is 2019 and start year is 2020.

**Comment by RishabhJain2018** [comment]
@vivektalwar13071999 thanks for catching this. Would you like to work on this

**Comment by vivektalwar13071999** [comment]
Yes will definitely work on it

**Comment by vivektalwar13071999** [comment]
Yes will work and resolve the issue and ask if any help would be needed.

**Comment by vivektalwar13071999** [comment]
Closing the issue as it is resolved in the production enviornment.
