### ISSUE TITLE
Submit button leads to freeze/hang, same observed over CLI

### ISSUE THREAD

**Issue by johnwlambert** [Cloud-CV/EvalAI#3113]
Hello EvalAI, thanks for all your work building this platform.

I'm having trouble submitting to the Argoverse 3d Detection challenge (challenge 725 phase 1554) over the online interface or over CLI.

The CLI hangs forever at
```
evalai challenge 725 phase 1554 submit --file myfile.zip --private
...
Publication URL []: 
Uploading the file...
  0%|                                                                                                                | 0/1 [00:00<?, ?it/s]
```

The online interface turns grey and hangs forever when I press "submit" for a 80 MB zip file.

Could you please take a look to see what might be going wrong?

**Comment by johnwlambert** [comment]
was successful on another machine, seems to be a network issue

**Comment by RishabhJain2018** [comment]
Hi @johnwlambert, Glad that it got resolved. Please feel free to ping us back, if the issue appears again.
