### ISSUE TITLE
Add swagger api documentation for get_all_entries_on_public_leaderboard API

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3127]
### Description

Hosts can use EvalAI APIs to get details of the leaderboard entries. The get leaderboard entries API documentation is missing documentation on EvalAI [docs](http://eval.ai/api/docs/).

### Deliverables
Add documentation for using `get_all_entries_on_public_leaderboard` API using swagger. An example of using swagger for API documentation is available [here](https://github.com/Cloud-CV/EvalAI/blob/master/apps/jobs/views.py#L87). The documentation should provide a list of query and header params described briefly and an example.

**Comment by burnerlee** [comment]
hello @Ram81, can I please work on and complete the issue?

**Comment by Ram81** [comment]
@burnerlee yes, go ahead. Assigned the issue

**Comment by burnerlee** [comment]
thank you so much

**Comment by burnerlee** [comment]
@Ram81, made a PR #3140 to solve this issue, please review. Also please suggest some other issues which I can work on for further contribution

**Comment by RishabhJain2018** [comment]
Fixed using #3140
