### ISSUE TITLE
Add swagger api documentation for download_all_submissions API

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3128]
### Description

Hosts can use EvalAI APIs to download all submission details. The download all submissions API documentation is missing documentation on EvalAI [docs](http://eval.ai/api/docs/).

### Deliverables
Add documentation for using `download_all_submissions` API using swagger. An example of using swagger for API documentation is available [here](https://github.com/Cloud-CV/EvalAI/blob/master/apps/jobs/views.py#L87). The documentation should provide a list of query and header params described briefly and an example.

**Comment by mukul20-21** [comment]
I am new to open source contribution, Can I help to resolve the issue.
I used swagger and know how it works.
Can you assign an issue?

**Comment by Ram81** [comment]
@mukul20-21 sure, go ahead.

**Comment by mukul20-21** [comment]
Thank you, Sir,
I tried my best to contribute to the community, please guide me if I cause
an error.

**Comment by nikki1234567** [comment]
Hello sir, I am Nikhilesh I have  experience in writing swagger documentation for two REST api's I created.Can I work on this issue if its still open?

**Comment by Alabhya268** [comment]
@Ram81 , Seems like nobody is working on this issue, Could you please assign it to me.
