### ISSUE TITLE
Add swagger api documentation for remove_participant_team_from_challenge API

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3129]
### Description

Hosts can use EvalAI APIs to remove participant teams from an active challenge. The remove participant team from challenge API documentation is missing documentation on EvalAI [docs](http://eval.ai/api/docs/).

### Deliverables
Add documentation for using `remove_participant_team_from_challenge` API using swagger. An example of using swagger for API documentation is available [here](https://github.com/Cloud-CV/EvalAI/blob/master/apps/jobs/views.py#L87). The documentation should provide a list of query and header params described briefly and an example.

**Comment by 17Rajat** [comment]
Hello Sir,
I have deployed an machine learning model using Swagger API, So, I know how it works.
I am also new to open source contribution .
Can you please assign this issue to me ?
I want to help in resolving it and want to contribute to open source community.

**Comment by Ram81** [comment]
@17Rajat yes, go ahead.

**Comment by 17Rajat** [comment]
> @17Rajat yes, go ahead.

Thanks

**Comment by nikki1234567** [comment]
Hello Sir, I am Nikhilesh. I have experience in writing swagger documentation can I work on it if it is still open?

**Comment by lkbhitesh07** [comment]
Hi @Ram81 , Can I work on this issue?
Thanks

**Comment by lkbhitesh07** [comment]
Hello @Ram81 @RishabhJain2018 
Small doubt,
I'm working on this issue but I'm stuck at one point. I was trying to test the API using postman then I got an error "Authentication credentials were not provided." So I passed the Token to the authorization part but still I'm getting this error. Can you provide some insights?
I tried searching on google but got nothing.
Thanks
