### ISSUE TITLE
Fix About us page css inconsistencies in frontend v2

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3130]
### Description

Fix the about us page on large screens. Currently, the about us page css is not consistent between frontend v1 and v2. The page css is broken for larger screens in frontend v2. Page css should be same as frontend v1

Frontend V1:
![Screen Shot 2021-01-10 at 7 30 04 PM](https://user-images.githubusercontent.com/16323427/104125095-92445780-537a-11eb-9b05-35c597f41664.png)

Frontend V2
![Screen Shot 2021-01-10 at 7 30 06 PM](https://user-images.githubusercontent.com/16323427/104125100-983a3880-537a-11eb-9d27-20ba16fb0f7e.png)

 Also, make sure that the content css is the same as that of the frontend V1.

**Comment by burnerlee** [comment]
@Ram81 can I work on this please. I'll make a PR to fix this quickly

**Comment by Ram81** [comment]
Hi @burnerlee, yes go ahead.
