### ISSUE TITLE
Fix Our team page css inconsistencies in frontend v2

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3131]
### Description

Fix the our team page css. Currently, our team page css is not consistent between frontend v1 and v2. The page css is broken for larger screens in frontend v2. Page css should be same as frontend v1.

Frontend V1:
![Screen Shot 2021-01-10 at 7 35 17 PM](https://user-images.githubusercontent.com/16323427/104125204-565dc200-537b-11eb-9164-6635ea4b45a5.png)

Frontend V2:
![Screen Shot 2021-01-10 at 7 35 20 PM](https://user-images.githubusercontent.com/16323427/104125228-68d7fb80-537b-11eb-85e4-6722e8375c93.png)

 Also, make sure that the content css is the same as that of the frontend V1.

**Comment by gautamjajoo** [comment]
Working on it!

**Comment by gautamjajoo** [comment]
Should there be a box-shadow in the background and division of Core Team and Contributor in v2? Or it should be same as it is currently.

**Comment by RishabhJain2018** [comment]
Let's make it the same as it is now.

**Comment by gautamjajoo** [comment]
@RishabhJain2018 This can also be closed as #3133 has been merged.

**Comment by RishabhJain2018** [comment]
Closing this. Thanks for pointing it out.
