### ISSUE TITLE
Sandbox or late submissions

### ISSUE THREAD

**Issue by maya-ami** [Cloud-CV/EvalAI#3135]
Hi!
Great framework that has virtually everything that is needed for hosting AI competitions!

The one feature I am looking for is a so called sandbox. Is it possible to enable late submissions after the deadline? E.g., kaggle allows to submit predictions even after the competition has ended. The leaderboard doesn't change of course but  the participant see where his/her score.

I have searched an admin panel for some parameters that could be toggled, but no luck.

Would appreciate if someone clears this for me. Probably, I was looking into a wrong direction.

**Comment by RishabhJain2018** [comment]
Hi @maya-ami ,

Thanks for reaching out.

> The one feature I am looking for is a so called sandbox. Is it possible to enable late submissions after the deadline? E.g., kaggle allows to submit predictions even after the competition has ended. The leaderboard doesn't change of course but the participant see where his/her score.

No, we don't allow late submissions after the challenge deadline. One thing you can do is to have two phases within the challenge and you can use one phase for the deadline and another one after the deadline.

Please feel free to ask if you have further questions.

**Comment by maya-ami** [comment]
@RishabhJain2018 I see, thank you!
