### ISSUE TITLE
Build should take less time

### ISSUE THREAD

**Issue by jayndu** [Cloud-CV/EvalAI#3141]
Wouldn't it reduce the build time by installing the `prod.txt` dependencies before adding all the code (to leverage caching)? Or is there any specific reason we are not doing this?

https://github.com/Cloud-CV/EvalAI/blob/aa0f4ffc464fc7c934f2702f02ab20c1a2c3e022/docker/prod/django/Dockerfile#L4-L9

**Comment by Ram81** [comment]
This is fixed after moving to travis.com
