### ISSUE TITLE
Optimize Travis CI Build during checks on making a Pull Request

### ISSUE THREAD

**Issue by burnerlee** [Cloud-CV/EvalAI#3151]
When a pull request is made, Travis CI runs a single test to check for all errors/warnings in the code, and with an exit status after the complete check is finished. Even if some part of the check fails, it continues to run the check further and notifies the user about the failure only at the end of the complete test which wastes a lot of time. 
For e.g. the flake8 test occurs at the very beginning of the whole test. Even if it fails, the complete test continues to run and after around 20-30 minutes the user is notified of an error.
The single test also does not clearly mentions which part of the test exactly failed. One has to open up the entire logs of the boot machine of Travis CI and look for the error.
I propose that we can break all these tests into a number of tests that could run simultaneously on different boot machines and would give faster and clear results. 
Also, we can return a particular check with a status code as soon as a single error is found in a check so that the build only checks ahead once that particular error is sorted out.

**Comment by burnerlee** [comment]
@RishabhJain2018 @Ram81 I would love to work on this if this seems useful. I have completed my previous issues and made a PR

**Comment by Ram81** [comment]
@burnerlee setting up multiple boot machines also takes time and recently the boot time has increased. So I am not sure if we  start multiple boot machines we will get any benefit from it.

**Comment by burnerlee** [comment]
@Ram81, I understand your point. Can we at least return the build with an error as soon as one of the checks fails so that the user does not have to wait for a long time?

**Comment by Ram81** [comment]
Yeah that change is good to have.

**Comment by Ram81** [comment]
@burnerlee I would suggest you first complete the tasks you are working on before picking up any new task. I can see that you already have 3 PRs open which needs some work before they can be approved and merged. Once you are done with them then you can pick this up or if you are interested in a backend related task you can look at this [issue](https://github.com/Cloud-CV/evalai-cli/issues/305)

**Comment by burnerlee** [comment]
@Ram81 @RishabhJain2018 completed the already assigned issues/ requested reviews. Should I start working on this change? Or is there some other issue on a higher priority than this? Could you please assign it to me? :) Thank you

**Comment by Ram81** [comment]
This is fixed after moving to travis.com
