### ISSUE TITLE
[FrontendV2] Fix error message on My Submissions page refresh 

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3154]
### Description

In frontend v2 when a challenge host goes to the `My Submissions` tab on the challenge page and refreshes the page the UI shows error notification with message `Success`.

Steps to reproduce the error:

1. Select any active challenge
2. Go to `My Submissions` tab
3. Refresh the page

Here's the screenshot of the error notification.

<img width="1440" alt="Screen Shot 2021-01-20 at 8 55 00 PM" src="https://user-images.githubusercontent.com/16323427/105197165-57080c80-5b62-11eb-9fa9-2e0c22200e20.png">

Expected behavior:

No error notification should be shown.

**Comment by gautamjajoo** [comment]
Can I work on it?

**Comment by Ram81** [comment]
@gautamjajoo Sure, go ahead
