### ISSUE TITLE
[FrontendV2] Allow toggling Show on leaderboard when submission is submitted/runnning

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3155]
### Description

When a participant goes to `My Submission` page and select a submission they can't toggle `Show on leaderboard` checkbox when status of submission is `Submitted/Running`. We should allow toggling of this checkbox even when submission is not in `Finished` state.

Steps to reproduce:

1. Select a challenge
2. Go to Submit tab and make a submission
3. Go to My Submissions tab
4. Select a submission with `Submitted/Running` status and try to toggle `Show on Leaderboard` checkbox.

Here's a screenshot for reference:

<img width="1440" alt="Screen Shot 2021-01-20 at 9 17 55 PM" src="https://user-images.githubusercontent.com/16323427/105199635-f9c18a80-5b64-11eb-951c-d1c62fc9bb4f.png">

**Comment by burnerlee** [comment]
@Ram81 can I make a PR for this issue?

**Comment by Ram81** [comment]
@burnerlee Sure, go ahead

**Comment by burnerlee** [comment]
#3160 made
