### ISSUE TITLE
[FrontendV2] Show selected submission details in 3 columns

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3157]
### Description

When a submission is selected on the `My Submissions` tab we currently divide the fields into two columns. The metadata fields should be shown in 3 columns for meta fields in each column.

Here is the current screenshot for reference

<img width="1440" alt="Screen Shot 2021-01-20 at 9 38 18 PM" src="https://user-images.githubusercontent.com/16323427/105202465-07c4da80-5b68-11eb-8681-db1f008097b8.png">

Expected:

Column 1 fields: Team Name, Method Name, Method Description, Project Url, Publication URL
Column 2 fields: Status, Submitted At, Execution Time
Column 3 fields: Show on Leaderboard, Baseline, Edit Submission details

**Comment by burnerlee** [comment]
@Ram81 in the latest master pull, there Baseline is not visible. Does this need to be fixed too?

**Comment by Ram81** [comment]
Are you using host account or participant account? Baseline option is only available to challenge hosts

**Comment by burnerlee** [comment]
Oh yes, thank you :)

**Comment by burnerlee** [comment]
![Screenshot from 2021-01-21 00-23-35](https://user-images.githubusercontent.com/55936223/105227995-060b0f00-5b88-11eb-9352-a02da8f4f5d2.png)

**Comment by burnerlee** [comment]
#3163 made.
