### ISSUE TITLE
[FrontendV2] Show selected submission details in 3 columns All submissions page

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3159]
### Description

When a submission is selected on the `All submissions` tab we currently divide the fields into two columns which makes it look cluttered. The metadata fields should be shown in 3 columns for meta fields in each column.

Here is the current screenshot for reference
<img width="1440" alt="Screen Shot 2021-01-20 at 9 52 56 PM" src="https://user-images.githubusercontent.com/16323427/105204235-f67ccd80-5b69-11eb-90be-a34174c31b4c.png">

Expected:

Column 1 fields: Submission Number, Team Members , Team Members Email Id, Submitted At
Column 2 fields: Stdout file, Stderr file, Metadata file
Column 3 fields: Show on Leaderboard, Unflagged, Re-run submission, Delete submission

**Comment by burnerlee** [comment]
@Ram81 please assign the issue to me. Made a PR for the last assigned issue

**Comment by Ram81** [comment]
@burnerlee sure, but please complete the requested changes on your previous PRs before picking up new issues.

**Comment by burnerlee** [comment]
Sure, #3160 has been updated. #3146 needs review from @RishabhJain2018 and #3150 needs further actions to be decided.

**Comment by RishabhJain2018** [comment]
@burnerlee Please do complete https://github.com/Cloud-CV/evalai-cli/issues/305 before starting with new issues. We definitely need that feature :)

**Comment by burnerlee** [comment]
![Screenshot from 2021-01-21 00-23-35](https://user-images.githubusercontent.com/55936223/105224980-ed98f580-5b83-11eb-8487-f4fb4eb09a14.png)

**Comment by burnerlee** [comment]
> @burnerlee Please do complete [Cloud-CV/evalai-cli#305](https://github.com/Cloud-CV/evalai-cli/issues/305) before starting with new issues. We definitely need that feature :)
> cc: @Ram81

I thought that issue would take a bit time and I have my exams going on in my college. I would get a prep leave on 23 and complete the issue on 23 itself. Till that just thought to give a go on these small issues

**Comment by RishabhJain2018** [comment]
Okay! Thanks for letting us know.

**Comment by burnerlee** [comment]
I'll surely submit it on 23, please please do not unassign me :(

**Comment by RishabhJain2018** [comment]
Sure :)

**Comment by burnerlee** [comment]
Will complete this as #3163 is merged. Will use same CSS classes

**Comment by debashishnanda** [comment]
Is this issue still open? @burnerlee are you working on it?

**Comment by burnerlee** [comment]
I think it was completed and merged

**Comment by Ram81** [comment]
Closing this as this was done
