### ISSUE TITLE
[frontendV2] Profile screen is not showing properly with screen-width more than 1440px

### ISSUE THREAD

**Issue by Alabhya268** [Cloud-CV/EvalAI#3182]
Profile screen is not showing properly with screen-width more than 1440px .

"Side bar" is overlapping with "Dashboard" .

For better understanding please have a look at this Image --
![cloudcv_profile](https://user-images.githubusercontent.com/57143358/106051508-8a244000-610e-11eb-8ace-de958768156d.PNG)

I want to work on this issue , Please assign it to me .

**Comment by RishabhJain2018** [comment]
Thanks @Alabhya268 for catching this. Assigned you!
