### ISSUE TITLE
Database backup quickly growing until eating up all space 

### ISSUE THREAD

**Issue by scorpionsky** [Cloud-CV/EvalAI#3189]
We created a local EvalAI server and it runs well until we encountered no space errors. We found there are over one hundred of large files under `docker/volumnes/xxxxxxxxxxx/_data/12994/758505.*`... It seems to be some backup files for a same entry 758505. Can you help on this and is there a way to avoid these backup files? Thank you!

**Comment by RishabhJain2018** [comment]
HI @scorpionsky,

Thanks for reaching out. Could you please give me a bit more context on how you are running the dockers, i.e. using the development setup or the production setup?

**Comment by Ram81** [comment]
Closing the issue due to inactivity
