### ISSUE TITLE
Redesign 404 page for Clientside.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#319]
Need to redesign a 404 page as shown in the given attachment. 
In case of any help or requirement, let me know.
(use evalai.cloudcv.org as a link to redirect user to homepage)
![eval-404](https://cloud.githubusercontent.com/assets/11537940/21596089/36beb6e8-d15c-11e6-9c44-095a7a6c050a.png)

**Comment by aka-jain** [comment]
Suggestions are also welcome related to design.
One can also use some AI related image or robot image in place of owl because our platform is based on AI and it will be good if we go for the same (evalAi) :D :)
(make sure that image shouldn't contain any copyright issue)

**Comment by Ram81** [comment]
@aka-jain Can You assign this to me ?

**Comment by aka-jain** [comment]
@Ram81 : let PR #314 be merged, then you can start working on this.

**Comment by aka-jain** [comment]
@Ram81: You can work on this now. Please be ready with the updated code

**Comment by aka-jain** [comment]
@Ram81 : PFA of image of OWL.
![owl](https://cloud.githubusercontent.com/assets/11537940/21653385/d29e1646-d2d6-11e6-92ee-5954fd0ee795.png)

**Comment by Ram81** [comment]
@aka-jain  I will add it. :+1:

**Comment by aka-jain** [comment]
Closing it, fix with #359
