### ISSUE TITLE
[Frontend V1] Add support to edit submission meta attributes of submissions

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3191]
### Description

Currently, participants can only fill in submission meta attributes details when making a submission. The task is to add frontend and backend changes for allowing users to edit submission meta attributes fields after a submission is made.

Screenshot below shows current fields user can edit after making a submission:
![Screen Shot 2021-01-31 at 10 29 11 PM](https://user-images.githubusercontent.com/16323427/106391590-2eaac880-6414-11eb-8492-8327a039d5b0.png)

**Comment by gautamjajoo** [comment]
Can I work on it?

**Comment by RishabhJain2018** [comment]
Sure @gautamjajoo 
cc: @Ram81

**Comment by gautamjajoo** [comment]
@Ram81 What does submission meta attributes include?

**Comment by gautamjajoo** [comment]
@Ram81 Currently we can edit method name, description etc
> @Ram81 What does submission meta attributes include?

**Comment by Ram81** [comment]
@gautamjajoo if you check [here](https://github.com/Cloud-CV/EvalAI-Starters/blob/master/challenge_config.yaml#L49) challenge host can pass custom submission meta attributes for a challenge phase. Currently, we don't allow editing those from `My Submissions` page. You can try uploading a new challenge from EvalAI-Starters repo and see how they work.

**Comment by Ram81** [comment]
@gautamjajoo any updates on this task?

**Comment by gautamjajoo** [comment]
@Ram81 I had some evaluatives this week. Will open a PR in a day or two.

**Comment by gautamjajoo** [comment]
@Ram81 It seems it would take some time for me to open a PR, you can unassign me the issue.

**Comment by burnerlee** [comment]
@Ram81, can I please work on this issue? I've an idea about the meta attributes too due to the cli issue. I'll make a PR asap

**Comment by Ram81** [comment]
@burnerlee Sure, go ahead.

>@Ram81 It seems it would take some time for me to open a PR, you can unassign me the issue.

Thanks for updating @gautamjajoo

**Comment by Ram81** [comment]
@burnerlee any updates on this?

**Comment by burnerlee** [comment]
Yes I'll make a PR by tonight positively

**Comment by burnerlee** [comment]
@Ram81, should I fetch all the submission meta-attributes available for the challenge phase and then show them in the above shown box along with method name, description, project URL and others? Then the user can enter values for them can submit them to edit. This is what I think is required in the PR

**Comment by Ram81** [comment]
Yes

**Comment by burnerlee** [comment]
@Ram81, if I try to make a new submission for a challenge with phase with submission meta attributes, it doesn't give me fields for those attributes while making a new submission too

**Comment by Ram81** [comment]
@burnerlee I didn't get what you are trying to ask. Are you saying the current edit feature on `My submissions` page doesn't return meta attributes?

**Comment by burnerlee** [comment]
@Ram81, when I go to the submit page after selecting a challenge, I choose some phase for the challenge.. This phase has some submission meta attributes stored in the database. But after I upload a file, I am only asked for name,description, project URL, publication URL, and not the other submission meta attributes. I was expecting to see all the other submission meta attributes along with them while making a new submission

**Comment by Ram81** [comment]
Is this happening for seeded challenges i.e. ones that are available when you start the container? or you are seeing this behavior for new uploaded challenges with meta attributes too?

**Comment by burnerlee** [comment]
this is happening for challenges already available. I added some submission meta attributes for their phases manually using the django database interface

**Comment by Ram81** [comment]
Can you try uploading a new challenge created using EvalAI-Starters [repo](https://github.com/Cloud-CV/EvalAI-starters) and see if it happens for those challenges too. I suspect when you are populating from django admin you might be missing updating some field.

**Comment by burnerlee** [comment]
sure, i'll do this

**Comment by burnerlee** [comment]
how do I approve the challenge as an admin? are the host username and admin same here?

**Comment by Ram81** [comment]
To test submissions locally you don't need to approve a challenge. You can just restart worker container to pick up latest challenge evaluation script. Also to answer your question you could go to the django admin and select the challenge and check the `Approved by admin` field and save the challenge to approve it.

**Comment by burnerlee** [comment]
oh, thank you... I hosted this challenge successfully. For this challenge too, I am not shown all the meta attributes while making a new submission

**Comment by Ram81** [comment]
Can you share a screenshot?

**Comment by burnerlee** [comment]
![Screenshot from 2021-02-13 18-43-03](https://user-images.githubusercontent.com/55936223/107850814-6ad62400-6e2b-11eb-83bc-463d853b5659.png)
![Screenshot from 2021-02-13 18-43-10](https://user-images.githubusercontent.com/55936223/107850817-6c9fe780-6e2b-11eb-8bc4-53571aa5d742.png)
![Screenshot from 2021-02-13 18-43-19](https://user-images.githubusercontent.com/55936223/107850819-6dd11480-6e2b-11eb-8cfd-3ae67e4b8589.png)
![Screenshot from 2021-02-13 18-43-15](https://user-images.githubusercontent.com/55936223/107850818-6d387e00-6e2b-11eb-95d8-666edb3f4ee5.png)

**Comment by Ram81** [comment]
@burnerlee you are using frontend v2. You should be able to see the submissions meta attributes in frontend v1. You can access it on `localhost:8888`

**Comment by burnerlee** [comment]
oh 🤦🏻‍♂️ that's why the logger statements were not working too for me. Thank you so much @Ram81
