### ISSUE TITLE
[FrontendV2] Item on every navbar page is floating towards right in  for screen width more than 1440px

### ISSUE THREAD

**Issue by Alabhya268** [Cloud-CV/EvalAI#3195]
Frontend v2 is unoptimized for screen width greater than 1440px.

Item on Participant challenges navbar page is floating towards right in  for screen width more than 1440px, Same behaviour can be seen under in all navbar page section.

Please look at following image for better understanding.
![Screenshot from 2021-02-01 21-22-09](https://user-images.githubusercontent.com/57143358/106642510-6fd6e000-65ae-11eb-89f4-aef17d3ac9b6.png)

Frontend v2 is unoptimized for screen width greater than 1440px

**Comment by RishabhJain2018** [comment]
@Alabhya268 Do you want to work on this issue?

**Comment by Alabhya268** [comment]
> @Alabhya268 Do you want to work on this issue? If yes, then please feel free to take this up.

@RishabhJain2018, I would like to work on this.
Assign me please
