### ISSUE TITLE
[FrontendV2] Buttons are not easily clickable in Get Auth Token at /profile

### ISSUE THREAD

**Issue by ShauryaAg** [Cloud-CV/EvalAI#3200]
**Cancel**, **Download JSON** and **Refresh Token** buttons are not easily clickable in **Get Your Auth Token** Modal at `/profile`.

In order to click the above mentioned buttons, one needs to click precisely right below the button instead of clicking on them.
This problem becomes adverse in mobile screens.

If you'd like to report a bug, please include the following information:
#### Expected behaviour
Buttons should be easily clickable.

#### Observed behaviour
The button is not clickable even when you hover on them.
![image](https://user-images.githubusercontent.com/31778302/106770721-3e205080-6664-11eb-9ff7-f1d470699268.png)

### Steps to reproduce the problem
1. Go to `/profile` on the frontend.
2. Click **Get your Auth Token**.
3. Hover over **Cancel**, **Download JSON**, or **Refresh Token** button.

**I would like to work on this issue. Thanks**

**Comment by Ram81** [comment]
Thanks @ShauryaAg for creating this issue
