### ISSUE TITLE
[Frontend_v2] Fix spacing of get auth token dialog

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3205]
### Description

The spacing in the `Get your Auth Token` modal is inconsistent. The token appears to be floating because of too much space in the text box. The spacing shouldn't be this big. 

Refer the following gif:

![dummy](https://user-images.githubusercontent.com/16323427/106896896-30c49e00-6718-11eb-8875-1b7e654c1f75.gif)

**Comment by ShauryaAg** [comment]
@Ram81 I would like to work on this.
