### ISSUE TITLE
[Frontend_v2] Fix inconsistent padding on Submit page

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3206]
### Description

The padding for the list of phases and submission meta attributes is inconsistent on the challenge submit page. It should be the same for the whole page.

Refer the screenshot:

<img width="1440" alt="Screen Shot 2021-02-03 at 4 59 36 PM" src="https://user-images.githubusercontent.com/16323427/106897118-81d49200-6718-11eb-9df0-12f0b9e1e3ba.png">

**Comment by Alabhya268** [comment]
@Ram81  , Could you please explain more precisely as to what needs to be done?

**Comment by Ram81** [comment]
Hi @Alabhya268 , the alignment of file upload and submission metadata components is incorrect in frontend v2. It should be same as current version. Please see this screenshot for reference.

![Screen Shot 2021-02-04 at 8 01 58 PM](https://user-images.githubusercontent.com/16323427/106907209-04af1a00-6724-11eb-8387-4bdeecddf0e5.png)

**Comment by Alabhya268** [comment]
Thanks @Ram81 , I would like to work on this issue.

**Comment by Alabhya268** [comment]
@Ram81 , I've PR for this , Please a have look on #3220 .

**Comment by Alabhya268** [comment]
@Ram81  This issue is now fixed, Please close the issue.
