### ISSUE TITLE
[Backend] Add tests for GET/PATCH/DELETE allowed_email_ids APIs

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3208]
### Description

PR #3194 adds an API to get, append and delete email ids allowed to participate in a challenge phase. The PR is missing tests. We need to add tests to fetch, append a set of email ids and delete existing email ids from `allowed_email_ids` field.

**Comment by codeboy5** [comment]
Hey can i take it up ?

**Comment by Ram81** [comment]
@codeboy5 sure, go ahead. PR #3194 will be merged tonight, till then you could pull the PR branch and go through the codebase.

**Comment by cgoxo** [comment]
Can I work on this issue?

**Comment by Ram81** [comment]
@cgoxo sure, go ahead.

**Comment by afif-fahim** [comment]
Can I work on this please?

**Comment by afif-fahim** [comment]
Sorry for a beginner question, what is adding a test for some API?

**Comment by cgoxo** [comment]
I was talking about this issue how to proceed!
