### ISSUE TITLE
[Frontend_v2] Fix padding of select phase placeholder on All submissions and My submissions page

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3209]
### Description

The padding of the placeholder `Select Phase` is inconsistent in the dropdown on All Submissions page. Following screenshots show the current style :

No phase is selected:

<img width="1440" alt="Screen Shot 2021-02-04 at 7 19 03 PM" src="https://user-images.githubusercontent.com/16323427/106901840-3329f680-671e-11eb-84f3-8c365c131ed1.png">

Phase selected:

<img width="1440" alt="Screen Shot 2021-02-04 at 7 19 28 PM" src="https://user-images.githubusercontent.com/16323427/106901865-38874100-671e-11eb-96ab-952cb0290006.png">

Padding is expected to be same for both placeholder text and selected phase name in the dropdown. Same issue occurs on the `My Submissions` page.

**Comment by gautamjajoo** [comment]
Can I work on it?

**Comment by Ram81** [comment]
@gautamjajoo Sure, assigning issue to you.

**Comment by cgoxo** [comment]
May I work on this one?

**Comment by Alabhya268** [comment]
@gautamjajoo , Are you working on this, If not  @Ram81  could you please assign this issue to me.

**Comment by gautamjajoo** [comment]
@Ram81 Actually my end semester exams are going on so cannot resolve the issues. After this Sunday will start working on them once again.

**Comment by Ram81** [comment]
@Alabhya268 sure, you can work on this issue. 

@gautamjajoo please pick up another issue once you are available.

**Comment by lovesh12** [comment]
@Alabhya268 are you working on this? If not, can I work on it @Ram81 ?

**Comment by Alabhya268** [comment]
@lovesh12 , I have open a PR for this issue, it has been already approved. Feel free to take up any other issue.

**Comment by lovesh12** [comment]
@Alabhya268 sorry, mybad
