### ISSUE TITLE
[Frontend_v2] Fix padding of select phase placeholder on Leaderbord page

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3210]
### Description

The padding of the placeholder `Challeng Phase` is inconsistent in the dropdown on Leaderboard page. Following screenshots show the current style :

No phase is selected:
<img width="1440" alt="Screen Shot 2021-02-04 at 7 27 15 PM" src="https://user-images.githubusercontent.com/16323427/106902584-032f2300-671f-11eb-91bd-f423a9bc6abd.png">

Phase selected:

<img width="1440" alt="Screen Shot 2021-02-04 at 7 27 18 PM" src="https://user-images.githubusercontent.com/16323427/106902605-088c6d80-671f-11eb-8a8e-f247028580f3.png">

Padding is expected to be same for both placeholder text and selected phase name in the dropdown.

**Comment by burnerlee** [comment]
@Ram81, made a PR for the previous assigned issue along with the screenshots. May I take up this issue now?

**Comment by Alabhya268** [comment]
@Ram81 I want to work on this , Please assign this issue to me .
