### ISSUE TITLE
[Frontend_v2] Fix edit button alignment on Evaluation page

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3211]
### Description

<img width="1440" alt="Screen Shot 2021-02-04 at 7 28 25 PM" src="https://user-images.githubusercontent.com/16323427/106902852-4ab5af00-671f-11eb-908a-2dc1a33d3d18.png">

The  `Edit` buttons are misaligned for `Evaluation` and `Terms and Conditions` cards. We should move `Edit` buttons next to `Upload` button on `Evaluation` card and make sure buttons are aligned between cards.

**Comment by burnerlee** [comment]
@Ram81, may I please take up this issue?

**Comment by Ram81** [comment]
@burnerlee Sure, go ahead

**Comment by burnerlee** [comment]
@Ram81 #3218 made for the same

**Comment by Ram81** [comment]
Closing the issue as #3218 is merged
