### ISSUE TITLE
[Frontend_v2] Fix Private tag alignment on Leaderboard page

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3212]
### Description

<img width="1000" alt="Screenshot_2020-10-11_at_11 30 29_AM" src="https://user-images.githubusercontent.com/16323427/106905090-ef38f080-6721-11eb-900f-3cc599afa6e3.png">

The private tag for a phase split is misaligned. It should appear next to the challenge phase split name itself and not downwards.

**Comment by ShauryaAg** [comment]
@Ram81 I have done the necessary changes. Please take a look,
