### ISSUE TITLE
[Frontend_v2] P tag should not appear for private leaderboards

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3213]
### Description

<img width="1000" alt="Screenshot_2020-10-11_at_11 38 42_AM" src="https://user-images.githubusercontent.com/16323427/106905953-b3eaf180-6722-11eb-90ce-7e48fcfef12c.png">

P tag should not appear for submissions on the private leaderboards. And change column `Last Submitted At` to `Submitted At` on the leaderboard

**Comment by burnerlee** [comment]
@Ram81 may I take up this issue?

**Comment by burnerlee** [comment]
using the selectedPhaseSplit in the file, I am able to access the challenge_phase's id but not the leaderboard_public property in angular. I saw some solutions for this. Am I allowed to make some change in the serializer to achieve this?

**Comment by burnerlee** [comment]
@Ram81 ping^

**Comment by burnerlee** [comment]
@Ram81 ping

**Comment by Ram81** [comment]
@burnerlee sure, adding fields to serializer is fine

**Comment by Ram81** [comment]
@burnerlee any updates on this issue?

**Comment by burnerlee** [comment]
@Ram81 sorry for the delay, completely slipped off my mind. Made a PR for the same. During resolving this, I found another error. I'll open it up in the issues section
