### ISSUE TITLE
[Frontend_v2] Size of team name filter and team list cards should be same

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3215]
### Description

<img width="1440" alt="Screen Shot 2021-02-04 at 7 56 12 PM" src="https://user-images.githubusercontent.com/16323427/106906437-2cea4900-6723-11eb-8cd1-a3beac8c071d.png">

The size of the team name filter component and team list cards should be the same

**Comment by Alabhya268** [comment]
@Ram81 , I've attached PR for this, Please have a look.

**Comment by cgoxo** [comment]
Can I work on this issue?
