### ISSUE TITLE
[Frontend_v2] Add option to set submission visibility on Submit page

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3217]
### Description

In current EvalAI frontend we allow user to specify submission visibility on the `Submit` page. This feature is not present in frontend v2. We need to add an option on the Submit page in frontend v2 to allow users to submit submission visibility (i.e. public/private)

Please the screenshot of current version:

![Screen Shot 2021-02-04 at 8 01 58 PM](https://user-images.githubusercontent.com/16323427/106907482-4dff6980-6724-11eb-97ab-48222cf26c7b.png)

**Comment by igarg2001** [comment]
Please assign me this issue

**Comment by Alabhya268** [comment]
@Ram81 , I would like to work on this issue .
