### ISSUE TITLE
Backend: Submit page on EvalAI for code upload challenges shows old auth token

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#3249]
**Issue**: Since we recently changed to JWT auth token, the submit page for code upload challenges on EvalAI still shows the old token.
![image](https://user-images.githubusercontent.com/12206047/108097490-2d9eab80-7050-11eb-9f31-1f3b0be74361.png)

**Fix**:
- [x] Replace the current auth token with the  new token.

**Comment by ShauryaAg** [comment]
@RishabhJain2018 May I take this?

**Comment by RishabhJain2018** [comment]
Hey @ShauryaAg , Yes you can take this up. Please note that this is `high priority` issue.

**Comment by ShauryaAg** [comment]
Sure. I'll get it done as soon as possible.
