### ISSUE TITLE
[Frontendv1] Dynamic width for web container.

### ISSUE THREAD

**Issue by Alabhya268** [Cloud-CV/EvalAI#3254]
Width of container in not dynamic, hence challenge list grid always show only 4 items in row and footer does not use full width in wider screen width.

For better understanding see following screenshots -

All screenshots are taken in screenwidth 1080p.

![before1](https://user-images.githubusercontent.com/57143358/108620392-f5350e00-7451-11eb-868f-474d1c866f15.png)
![before2](https://user-images.githubusercontent.com/57143358/108620394-f6fed180-7451-11eb-9712-df26e5175ccd.png)
![before3](https://user-images.githubusercontent.com/57143358/108620395-f7976800-7451-11eb-9957-3122b5bae04a.png)
![before4](https://user-images.githubusercontent.com/57143358/108620396-f7976800-7451-11eb-9b42-83f8a57cf5d1.png)

**Comment by Alabhya268** [comment]
@RishabhJain2018 I want to work on this issue .

**Comment by RishabhJain2018** [comment]
Hi @Alabhya268,
Thank you for the effort but it is a design choice. We actually don't want to make the challenge cards scale dynamically. We would like to keep it centered only.

Please feel free to pick up another issue. Also, please be on the lookout as @Ram81 will open more issues in the next few days.
