### ISSUE TITLE
Getting error while Build and run the Docker containers. (docker-compose up --build) 

### ISSUE THREAD

**Issue by AbhisekOmkar** [Cloud-CV/EvalAI#3269]
![Screenshot (62)](https://user-images.githubusercontent.com/67184718/109263954-32bae200-782a-11eb-868d-5871aa3292d3.png)
_Thanks for taking the time to report a bug in the EvalAI project, or propose a new feature! Before creating a new issue, please do a quick search to check that it hasn't already been filed on the [issue tracker](https://github.com/Cloud-CV/EvalAI/issues)._

If you'd like to report a bug, please include the following information:
- the expected behaviour
- the observed behaviour
- steps to reproduce the problem
- which operating system and/or browser you're using, if relevant
- (if possible) copies of the console/server logs

On the other hand, if you'd like to propose a new feature:
- please describe, as clearly as possible, what you'd like to see
- (if possible) include mockups/screenshots, if these would help convey the meaning better

Thanks!

**Comment by ShauryaAg** [comment]
Are you sure you have started the docker service?

**Comment by AbhisekOmkar** [comment]
> Are you sure you have started the docker service?

Yes I have started docker service

**Comment by Ram81** [comment]
@AbhisekOmkar our docker setup is tested and verified on Linux and OSX. On windows there are multiple issues. It would be easier if you could set up EvalAI on Linux machine. If you face any issues after switching OS let us know we will be happy to help.

**Comment by AbhisekOmkar** [comment]
Yeah sure I have tested it on Linux its working fine thnx for your support
