### ISSUE TITLE
Add Docstring to all the API Endpoints

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#327]

**Comment by souravsingh** [comment]
@deshraj I would like to work on the issue.

**Comment by deshraj** [comment]
@souravsingh Sorry, this one is already assigned to @TroJan. Feel free to pick any unassigned issue. :-)

**Comment by TroJan** [comment]
@souravsingh : you can work on this, I am little busy with other issues.
@deshraj : please re assign it.

**Comment by deshraj** [comment]
Oh Ok. @souravsingh If you are interested then you can work on this issue. :-)

**Comment by dexter1691** [comment]
@souravsingh: Status update? Are you still working on this issue?

**Comment by souravsingh** [comment]
@dexter1691 I am working on it

**Comment by deshraj** [comment]
@souravsingh any updates on this? I think it has been really long time since you have been working on this. If you are not working on this, then please let me know so that I can assign it to someone else.

**Comment by souravsingh** [comment]
@deshraj I got caught up with some commitments. I will finish this up right away.

**Comment by deshraj** [comment]
@souravsingh looks like you are busy and hence I am unassigning this issue.

**Comment by souravsingh** [comment]
@deshraj I almost forgot the issue. I will send a WIP PR right away.

**Comment by deshraj** [comment]
Oh Ok. Thanks for letting me know. :-)

**Comment by souravsingh** [comment]
I apologize for keeping this pending

**Comment by deshraj** [comment]
Looks like @souravsingh is not able to work on this. Anyone interested in working on this issue is welcome. :)

**Comment by RishabhJain2018** [comment]
@deshraj Can I work on this?

**Comment by deshraj** [comment]
Sure. Assigning it to you.

**Comment by gauthamzz** [comment]
is anyone working on this ?

**Comment by RishabhJain2018** [comment]
@gauthamzz No, I am not working on this but @souravsingh is working on this.

**Comment by deshraj** [comment]
Closing this for now. Will reopen it once there comes a requirement.
