### ISSUE TITLE
Error while building and run the Docker Container (docker-compose up --build)

### ISSUE THREAD

**Issue by piyushsingariya** [Cloud-CV/EvalAI#3272]
Ended up with this error while building Eval in my local ubuntu.
![2021-03-01_11-11](https://user-images.githubusercontent.com/50979887/109456458-e5837e00-7a7e-11eb-8ea9-0869329a99fa.png)

**Comment by burnerlee** [comment]
@piyushsingariya try  using the command `docker-compose build` instead.

**Comment by piyushsingariya** [comment]
@burnerlee I am ending up with the same error. :sweat_smile:

**Comment by burnerlee** [comment]
did you try `apt-get update`?

**Comment by piyushsingariya** [comment]
Yes I tried that but this didn't solve the concerned error

**Comment by AbhisekOmkar** [comment]
Delete the whole repo and clone it once again it might work

**Comment by piyushsingariya** [comment]
@AbhisekOmkar Thanks! It actually worked...

**Comment by piyushsingariya** [comment]
Encountered a new error. I killed the service running on the port just to be sure.
![2021-03-03_13-24](https://user-images.githubusercontent.com/50979887/109772349-e4d81c80-7c23-11eb-9f2e-3da1a813e42d.png)
Could you help me with this?

**Comment by gautamjajoo** [comment]
@piyushsingariya This will help
 https://evalai.readthedocs.io/en/latest/faq(developers).html#q-getting-the-following-error

**Comment by AbhisekOmkar** [comment]
To solve, execute the following commands:

npm config set registry=registry.npmjs.org
If the above does not work, try deleting them by following commands:

npm config delete proxy
npm config delete https-proxy

**Comment by piyushsingariya** [comment]
Thanks @AbhisekOmkar @gautamjajoo It worked finally. Thanks a lot.

**Comment by AbhisekOmkar** [comment]
welc
