### ISSUE TITLE
[Backend]Add boolean check in github challenge update API to avoid overwriting annotations uploaded using cli

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3312]
### Description

Currently, when challenge hosts update the challenge using github based challenge workflow the test annotations get overwrite after each update. We also allow hosts to update annotations using EvalAI cli. When a challenge host updates the annotation using CLI we should not overwrite the annotations passed from github based challenge update API.

### Deliverable

- [ ] Add `annotations_uploaded_using_cli` field in challenge phase model
- [ ] Set `annotations_uploaded_using_cli` to `true` when annotations are uploaded using CLI
- [ ] Add check in update github based challenge API to look up whether annotations were uploaded using CLI before overwriting annotations

**Comment by burnerlee** [comment]
@Ram81 can I please work on this issue?

**Comment by GrimmeryGonsa** [comment]
@Ram81 is this issue still free for picking?

**Comment by burnerlee** [comment]
@Ram81 ping, may I start working on the issue if required

**Comment by xavierfigueroav** [comment]
@Ram81 Can I work on this issue?
