### ISSUE TITLE
Make the execution time human readable on UI.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#3319]
**Issue**:
We now show the `Execution time` on the leaderboard but it is in seconds. We would like to make it more human-readable on UI like for `3600` seconds, it should display 1 hour.
For e.g. in the below screenshot, `134983.881963 seconds` isn't readable.

![image](https://user-images.githubusercontent.com/12206047/111252407-701fbd80-85e7-11eb-9476-03d3e5193019.png)

**Tasks:**
- [ ] Convert the seconds from the API to human-readable format in the controller.

Please feel free to ask if you have any doubts/questions.

Note: This is a high very priority issue, please pick it up only when a PR can be opened within 24 hours.

**Comment by RishabhJain2018** [comment]
@Alabhya268 Would you like to work on this?

**Comment by Alabhya268** [comment]
Yes @RishabhJain2018  I want to work on this.

**Comment by RishabhJain2018** [comment]
@Alabhya268 There is one more issue, the sorting on the UI is off. Can you please check that as well.

**Comment by Alabhya268** [comment]
> @Alabhya268 There is one more issue, the sorting on the UI is off. Can you please check that as well.

@RishabhJain2018 , I will look into it.

**Comment by burnerlee** [comment]
> @Alabhya268 There is one more issue, the sorting on the UI is off. Can you please check that as well.

@RishabhJain2018 isn't the sorting with execution time not working? I tested it in my PR actually 😅

**Comment by Alabhya268** [comment]
@RishabhJain2018 , execution can be converted in day, hour and sec but what should I about time after decimal ? How should it be represented ?

**Comment by RishabhJain2018** [comment]
> @RishabhJain2018 isn't the sorting with execution time not working? I tested it in my PR actually 

Hey @burnerlee, No it isn't working correctly. Check here -- https://eval.ai/web/challenges/challenge-page/580/leaderboard/1631

> execution can be converted in a day, hour, min, and sec but what should I about time after decimal? How should it be represented?

You can drop the time after decimals.

**Comment by RishabhJain2018** [comment]
> @RishabhJain2018 isn't the sorting with execution time not working? I tested it in my PR actually 

Hey @burnerlee, No it isn't working correctly. Check here -- https://eval.ai/web/challenges/challenge-page/580/leaderboard/1631

> execution can be converted in a day, hour, min, and sec but what should I about time after decimal? How should it be represented?

You can drop the time after decimals.

**Comment by burnerlee** [comment]
> > @RishabhJain2018 isn't the sorting with execution time not working? I tested it in my PR actually
> 
> Hey @burnerlee, No it isn't working correctly. Check here -- https://eval.ai/web/challenges/challenge-page/580/leaderboard/1631
oh sorry, i checked it with 2 values and it seemed to work correctly to me that time 😅 
> > execution can be converted in a day, hour, min, and sec but what should I about time after decimal? How should it be represented?
> 
> You can drop the time after decimals.
