### ISSUE TITLE
Add tests for testing urls in accounts app.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#333]
The tests file must be located at `tests/unit/accounts/test_urls.py`. Create one, if it doesn't exists.
For reference please use http://stackoverflow.com/questions/18987051/how-do-i-unit-test-django-urls

**Comment by anweshknayak** [comment]
@deshraj @RishabhJain2018 anyone working on this ?

**Comment by RishabhJain2018** [comment]
@anweshknayak No, I don't think so. If you want to work then please ask **deshraj** to assign it to you.

**Comment by deshraj** [comment]
@anweshknayak You can work on it. Assigning it to you. :-)

**Comment by anweshknayak** [comment]
@RishabhJain2018 as you said django-allauth is already a tested. close this ?

**Comment by deshraj** [comment]
@anweshknayak there is one url in accounts app that needs to be tested. Please see this https://github.com/Cloud-CV/EvalAI/blob/master/apps/accounts/urls.py#L7

**Comment by Ram81** [comment]
@RishabhJain2018  @deshraj  is this issue open? can you assign this to me?
