### ISSUE TITLE
[FrontendV2] Show submission details in 3 columns on All submissions page

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3335]
### Description

Current UI:
![Screen Shot 2021-03-24 at 11 42 45 AM](https://user-images.githubusercontent.com/16323427/112263963-2180bc00-8c96-11eb-88d6-43b5d09fc50f.png)

When a user selects the submission to see the submission details on All submissions page we should the content in 2 columns. We should show the submission details in 3 columns. Here's how the fields will be divided in columns:

1. Column 1: Team members, Team members email id (list should be wrapped when overflows), stdout file, stderr file
2. Column 2: Status, Submission Number, Submitted At, metadata file
3. Column 3: Show on leaderboard, Flagged, Re-run submission, Delete submission

**Comment by savish28** [comment]
@Ram81 Could I please work on this?

**Comment by Gahina** [comment]
@Ram81  Can I work on this issue?

**Comment by shikhar168** [comment]
@Ram81 can i work on this?
