### ISSUE TITLE
[Frontend V2] Remove filter by team name from My submissions tab 

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3336]
### Description

Currently, we have a filter to search results by team name on `My Submissions` tab. As one user can be a part of only 1 team in a challenge we don't need a filter results by team name option on `My submissions` tab. We should remove the filter.

**Comment by Alabhya268** [comment]
@Ram81, I want to work on this.

**Comment by Ram81** [comment]
@Alabhya268 sure, go ahead
