### ISSUE TITLE
[Frontend V2] Show execution time and submitted at for each entry on My submissions page

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3337]
### Description

Currently, we show `Execution time` and `Submitted at` for each submission on the `My submission` tab once use clicks on the submission entry.  Here's how it looks currently

![Screen Shot 2021-03-24 at 11 52 40 AM](https://user-images.githubusercontent.com/16323427/112264854-7cff7980-8c97-11eb-87da-f68fb56936b6.png)

For each entry in the `My submissions` table we should move `Execution time` and `Submitted at` out of collapsible div and show it for each row

**Comment by savish28** [comment]
@Ram81 Could I please work on this?

**Comment by Ram81** [comment]
@savish28 sure, go ahead
