### ISSUE TITLE
[Frontend V2] Modifications for Privacy policy page

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3344]
### Description

![Screen Shot 2021-03-24 at 12 28 41 PM](https://user-images.githubusercontent.com/16323427/112268208-9fe05c80-8c9c-11eb-93fd-8944b7da1ded.png)

Following are the modifications for Privacy policy page:

- [ ] Center the page content for large screens
- [ ] Start the sidebar from the top of the page, currently the sidebar is centered on the page it should start from the top
- [ ] Remove the rocket, cloud and birds animation from the page

**Comment by niharsalunke** [comment]
Hi @Ram81 may I work on this issue?
