### ISSUE TITLE
[Frontend V2] Add option to submit using evalai cli

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3348]
### Description

In frontend v1 we show the option to make a submission using EvalAI-cli. We should add the same feature in frontend v2. Here's how the option looks in frontend v1.

![Screen Shot 2021-03-24 at 12 42 02 PM](https://user-images.githubusercontent.com/16323427/112269563-893b0500-8c9e-11eb-8838-caa4049dbb5b.png)

**Comment by burnerlee** [comment]
@Ram81 made a small PR to add this feature. Please review
