### ISSUE TITLE
Add tests for testing urls in challenges app.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#337]
The tests file must be located at tests/unit/challenges/test_urls.py. Create one, if it doesn't exists.
For reference please use http://stackoverflow.com/questions/18987051/how-do-i-unit-test-django-urls

**Comment by anweshknayak** [comment]
@deshraj can I work on this ?

**Comment by parismita** [comment]
@deshraj  shall i try this too....its similar

**Comment by deshraj** [comment]
Sure. Assigning it to you. :-)

**Comment by parismita** [comment]
@deshraj I am not able to get what challenge_time is and where is it declared....can u please tell we what is to be done there
last url test which is commented in the pull request
