### ISSUE TITLE
Create an API endpoint for deleting a User from a Host Team

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#338]
API endpoint: `/api/hosts/<hosts_team_id>/`
Method: `DELETE`

A user can request this API to remove himself from the host team. You can get the user from `request.user`. 

Please comment here for more details. Also, check other APIs to delete.

**Comment by deshraj** [comment]
@RishabhJain2018 I have assigned this also since this is very similar to #336

**Comment by RishabhJain2018** [comment]
okk sure.
