### ISSUE TITLE
Does anybody know why need using docker-compose restart worker after created a challenge？

### ISSUE THREAD

**Issue by lg920810** [Cloud-CV/EvalAI#3383]
I use the dev environment to deploy locally. Now every time I create a challenge, I need to using `docker-compose restart woker `  to restart the container in the background. Does the restart worker button in the challenge page implement a restart operation? And can it be used only when deployed to AWS? I want to modify some code so that I can try it locally. I want to know the purpose of restarting the container, is it to restart some services?

Thanks!

**Comment by savish28** [comment]
@lg920810 Basically in local dev, all challenges evaluation scripts are stored "initially" to save runtime by again and again fetching them. So what docker restart does is basically rerun the script of the worker and eventually stores the updated evaluation script in the variables. AWS is not required to run worker docker for local dev testing. Hope you got the answer.

**Comment by AaqibAhamed** [comment]
Shall we close this issue??.. Answer has been given already..

**Comment by lg920810** [comment]
> @lg920810 Basically in local dev, all challenges evaluation scripts are stored "initially" to save runtime by again and again fetching them. So what docker restart does is basically rerun the script of the worker and eventually stores the updated evaluation script in the variables. AWS is not required to run worker docker for local dev testing. Hope you got the answer.

Thanks for your answer.
