### ISSUE TITLE
Notification not visible on challenge page

### ISSUE THREAD

**Issue by gautamjajoo** [Cloud-CV/EvalAI#3387]
### Observed Behaviour
Notifications are not visible as the star button is overlapping on the challenge page.

### Expected Behaviour
Increase `z-index` of the notification label so that it is visible.

![Screenshot from 2021-04-01 20-29-52](https://user-images.githubusercontent.com/24366008/113313994-702ef580-9329-11eb-87a6-d833a27d1cfc.png)

**Comment by Pratyush-Saxena** [comment]
@gautamjajoo may i work on this?

**Comment by ShauryaAg** [comment]
@Pratyush-Saxena This is already fixed by #3371

**Comment by AaqibAhamed** [comment]
already fixed

**Comment by AaqibAhamed** [comment]
Please Close this issue

**Comment by gautamjajoo** [comment]
Closing since fixed in https://github.com/Cloud-CV/EvalAI/pull/3517
