### ISSUE TITLE
Add tests for testing urls in hosts app.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#339]
The tests file must be located at tests/unit/hosts/test_urls.py. Create one, if it doesn't exists.
For reference please use http://stackoverflow.com/questions/18987051/how-do-i-unit-test-django-urls

**Comment by parismita** [comment]
Hey I am new here. Shall i try this? what exactly do i have to do ?

**Comment by deshraj** [comment]
Yeah @parismita, it will be a good start for you. Let me know if you need some help.

**Comment by parismita** [comment]
@deshraj  I am having a ImportError: Failed to import test module: for all tests. I have updated openssl, npm,node.js and curl still the problem persist.

**Comment by deshraj** [comment]
Can you please send the screenshot?

**Comment by parismita** [comment]
![screenshot from 2017-01-08 12 48 49](https://cloud.githubusercontent.com/assets/17319560/21748075/d3c79ec6-d5a0-11e6-8e0e-c004e845d5c9.png)
same error for all tests

**Comment by deshraj** [comment]
Can you try installing the python packages in a virtual environment. I think you are facing the error since you are not running tests in virtual environment. Please try and let me know if that doesn't work.

**Comment by parismita** [comment]
its working now

**Comment by deshraj** [comment]
Awesome :-)

**Comment by deshraj** [comment]
Fixed in #380
