### ISSUE TITLE
Add tests for testing urls in participants app.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#340]
The tests file must be located at tests/unit/participants/test_urls.py. Create one, if it doesn't exists.
For reference please use http://stackoverflow.com/questions/18987051/how-do-i-unit-test-django-urls.

**Comment by anweshknayak** [comment]
@deshraj as I have finished all of you assigned. can I work on this ?

**Comment by deshraj** [comment]
Sure, go ahead.
