### ISSUE TITLE
cannot submit result file today - argoverse motion forecasting competition

### ISSUE THREAD

**Issue by jnyuan** [Cloud-CV/EvalAI#3409]
![image](https://user-images.githubusercontent.com/20141371/116541215-c3db3180-a91d-11eb-93b2-1a96aaf57374.png)

The page remains gray during the upload process, and there is no file uploaded today in the upload history

**Comment by AaqibAhamed** [comment]
Is there anyone working on this issue??

**Comment by Ram81** [comment]
@jnyuan we have fixed the issue. You should be able to make submissions now.

**Comment by Ram81** [comment]
Closing this issue.


Please re-open the issue if it persists.
