### ISSUE TITLE
Add tests for testing urls in project directory.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#341]
The tests file must be located at tests/unit/evalai/test_urls.py. Create one, if it doesn't exists.
For reference please use http://stackoverflow.com/questions/18987051/how-do-i-unit-test-django-urls.

**Comment by deshraj** [comment]
Thanks @RishabhJain2018 for opening this issue. This is a really great step in setting TDD.

**Comment by anweshknayak** [comment]
@deshraj  can I work on this ?

**Comment by Ram81** [comment]
@deshraj  can you assign this to me?

**Comment by parismita** [comment]
Shall i try this after completion of test of challenge urls?
What exactly is to be done here ?

**Comment by deshraj** [comment]
I think this a duplicate issue. The issues are opened with respect to all the apps. Closing it now.

**Comment by RishabhJain2018** [comment]
@deshraj No, this issue is with respect to this [file](https://github.com/Cloud-CV/EvalAI/blob/master/evalai/urls.py). I think there are two-three urls for which tests are to be written, so we should reopen this issue. What do you say?

**Comment by deshraj** [comment]
Oh just realized that. Reopening it.

**Comment by parismita** [comment]
i'll do this

**Comment by TroJan** [comment]
Fixed in #419 .
