### ISSUE TITLE
Cloud Production script

### ISSUE THREAD

**Issue by rajatraj733** [Cloud-CV/EvalAI#3421]
Could you guys please provide the steps to deploy in cloud services as well?

In the readme.md file, there are steps to build and deploy the application locally. 
I tried to follow the same steps described in the documentation for the cloud as well. That created two UIs at port 8888  and 4200. On both UI, login api, it is invoking has the base url of localhost. I guess I can go to config.json and change that. But it seems like that particular docker-compose.yml file is focussed for local only. For production, I guess you have different steps. docker-compose-production.yml is also not revealing much as docker images are being downloaded from ecr services.

If there would have been script to launch app in cloud, it would have been easier for open source community looking for deploy evalai app.

Let me know if I'm missing something. Thanks!!

**Comment by yashdusing** [comment]
Hey @rajatraj733 ! 
Could you try these : 
Instructions / Readme for deployment : https://github.com/Cloud-CV/EvalAI/pull/3010
then you can go for either VM deployment & AWS services deployment : 
VM deployment PR : https://github.com/Cloud-CV/EvalAI/pull/2853
AWS deployment PR : https://github.com/Cloud-CV/EvalAI/pull/2978

**Comment by rajatraj733** [comment]
Thanks @yashdusing for the reply. Seems like your pr are open for more than 6 months. Any reasons, why has it not been reviewed yet.

@RishabhJain2018 @deshraj @Ram81 Hello guys, I understand there may be more priority tasks in the pipeline. Would appreciate, if these pr can be reviewed. I'm sure, if necessary @yashdusing will come up with the changes if any required to be merged into master.

**Comment by Ram81** [comment]
@rajatraj733 we don't have the cloud deployment setup in the scope of the project we have planned for next few months.
