### ISSUE TITLE
Create an API endpoint to get all the challenges participated by the user

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#346]
URL: `/api/challenges/get_all_challenges_participated_by_user/`
Method: GET

**Comment by RishabhJain2018** [comment]
@deshraj Can I work on this?

**Comment by deshraj** [comment]
Sure, let me know if you need some help.

**Comment by RishabhJain2018** [comment]
okk.

**Comment by RishabhJain2018** [comment]
@deshraj As discussed with **TroJan** in #349 , please asssign this to TroJan.

**Comment by deshraj** [comment]
FIxed in #503
