### ISSUE TITLE
Create an API endpoint to get all the challenges hosted by the user

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#347]
URL: /api/challenges/get_all_challenges_hosted_by_user/
Method: GET

**Comment by RishabhJain2018** [comment]
@deshraj Can I work on this ?

**Comment by deshraj** [comment]
Sure. Assigning it to you.

**Comment by RishabhJain2018** [comment]
@deshraj As discussed with **TroJan** in #350 , please assign this to TroJan.

**Comment by deshraj** [comment]
Fixed in #503
