### ISSUE TITLE
2 proposed feature requests for leaderboard

### ISSUE THREAD

**Issue by johnwlambert** [Cloud-CV/EvalAI#3485]
Hi EvalAI team, thanks for all your hard work on an excellent platform. I have two proposed feature requests:

1. When I click on an entry in a leaderboard (say the 5th entry), the leaderboard re-centers on the object, and hides the objects above, which is a bit counter-intuitive. I would prefer behavior where that entry is actually highlighted.

2. Could we have an option to show on the leaderboard which columns have "higher is better" or "lower is better"? (via arrows)

(e.g. as shown in Table 4 of [this paper](https://arxiv.org/pdf/2006.11275.pdf))
<img width="1130" alt="Screen Shot 2021-06-19 at 1 53 25 PM" src="https://user-images.githubusercontent.com/16724970/122651271-ba906900-d105-11eb-9825-53fdd69e5af8.png">

**Comment by RishabhJain2018** [comment]
Hi @johnwlambert, Thank you for the feature requests. We will try to release these ASAP.

**Comment by RishabhJain2018** [comment]
Closing as this is fixed!
