### ISSUE TITLE
Unable to paste passwords on signup form

### ISSUE THREAD

**Issue by michaelmior** [Cloud-CV/EvalAI#3499]
Since I use a password manage (as I would argue most if not everyone should), I prefer to be able to paste in passwords in sign up forms since they are randomly generated. There is a lot of debate around this issue, but the consensus seems to be that disallowing pasting passwords is bad for security since it encourages users to choose weak passwords among other reasons.

Some references below:

[The “Cobra Effect” that is disabling paste on password fields](https://www.troyhunt.com/the-cobra-effect-that-is-disabling/)
[Let them paste passwords](https://www.ncsc.gov.uk/blog-post/let-them-paste-passwords)
[Don’t Disable Copying / Pasting Passwords](https://medium.com/@EricJFisher/dont-disable-copying-pasting-passwords-a2198428f8f)
[Is there any reason to disable paste password on login?](https://security.stackexchange.com/questions/131106/is-there-any-reason-to-disable-paste-password-on-login)

**Comment by AvineshTripathi** [comment]
hey just wanted to know if this topic has come to conclusion or not ?

**Comment by vashuteotia123** [comment]
@michaelmior Is this issue still there? I would like to work on this.

**Comment by michaelmior** [comment]
I don't think this is an issue any more as I am able to paste in a password now.
