### ISSUE TITLE
Integrate Eslint with the frontend code

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#352]

**Comment by deshraj** [comment]
For reference, see this http://eslint.org/docs/user-guide/configuring

**Comment by RishabhJain2018** [comment]
@deshraj Can I work on this??

**Comment by RishabhJain2018** [comment]
@deshraj should I create the configuration file at `EvalAI/.eslintrc.json` this location?

**Comment by aka-jain** [comment]
@RishabhJain2018 : Do some research and find the best way to integrate Eslint by your own.

**Comment by RishabhJain2018** [comment]
@aka-jain okk sure.

**Comment by deshraj** [comment]
Assignin to @aka-jain now.

**Comment by dexter1691** [comment]
@RishabhJain2018: This resource might be very useful: https://github.com/airbnb/javascript
It's the gold standard guidelines used by a lot of javascript repositories.

**Comment by aka-jain** [comment]
@dexter1691 : Airbnb guidelines are really awesome but we are already using John Papa Guidelines for our Javascript (Angular1), also currently we are not working on ES6 version which is highly recommendable for production now a days so I think at this point this repo may not be useful for us as many guidlines are related to ES6. But to make code quality good, John Papa guidelines are also fair enough for JS and Angular. https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md

@RishabhJain2018 : You can go thorugh the Airbnb repo, it will be very helpful to understand the structure of Javascript :) And for our project, try to go through ES5 section.

**Comment by dexter1691** [comment]
@aka-jain : This is done? Should we close?

**Comment by aka-jain** [comment]
@dexter1691 : Need to do some improvements on this. I'm working on it.

**Comment by spyshiv** [comment]
@aka-jain : Assigning this to me since you have other tasks to do.

**Comment by aka-jain** [comment]
@spyshiv Sure.

**Comment by aka-jain** [comment]
@spyshiv Is it done with Gulp improvement?

**Comment by spyshiv** [comment]
@aka-jain : Almost done. There is seperate branch `js_linting` for this purpose. Need minor improvements in it.
However checkout to that branch and run `gulp lint` to see the errors and warnings.

**Comment by aka-jain** [comment]
Fixed with #650
