### ISSUE TITLE
settings/dev.sample.py changed but not updated in Readme.md

### ISSUE THREAD

**Issue by parismita** [Cloud-CV/EvalAI#357]
no USER and PASSWORD field in dev.sample.py as written in Readme

**Comment by gauthamzz** [comment]
just add 


'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'evalai',
        'USER': 'your username',
        'PASSWORD': 'your password',
        'HOST': 'localhost',
        'PORT': '5432',
    }

**Comment by deshraj** [comment]
Sorry, my bad. Thanks @parismita for opening this issue. Do you want to take lead on this and fix it?

**Comment by parismita** [comment]
yeah

**Comment by deshraj** [comment]
You should change the `dev.sample.py`

**Comment by deshraj** [comment]
Fixed.
