### ISSUE TITLE
Not able to see scores for LVIS challenge

### ISSUE THREAD

**Issue by sudz123** [Cloud-CV/EvalAI#3596]
Hi!

We have submitted our file and it has been over 24 hours but we are not able to see our scores for LVIS 2021 val phase. Is this normal? What is the expected delay? Also is there any way to know if something went wrong and if so, what went wrong?

**Comment by sudz123** [comment]
Now it shows cancelled. With execution time None.

**Comment by fuweifu-vtoo** [comment]
I also meet the same problem? have you solved it?

**Comment by sudz123** [comment]
Nope

**Comment by Ram81** [comment]
Hi @sudz123, there was a issue with our evaluation server due to which submissions were not processed. We have fixed the issue, your submissions should be done evaluating in couple of hours.

**Comment by RishabhJain2018** [comment]
Closing it as it is resolved. Please feel free to reopen in case it is still not resolved.
