### ISSUE TITLE
Cost for hosting challenges?

### ISSUE THREAD

**Issue by danielamassiceti** [Cloud-CV/EvalAI#3603]
Hi there

Is there any cost associated with hosting a challenge on EvalAI?

Thanks

**Comment by Ram81** [comment]
Hi @danielamassiceti, no there is no cost associated with hosting a challenge on EvalAI. You can go to [eval.ai](https://eval.ai/) and follow the instructions on our [starters template](https://github.com/Cloud-CV/EvalAI-starters) to get started.

Closing this, as this is not a issue
