### ISSUE TITLE
Add a timeout field in Submission model 

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#362]
Add a new field `timeout` in `Submission` model in jobs app. Set the default to `300 seconds`.

**Comment by anweshknayak** [comment]
@deshraj can I work on this?

**Comment by deshraj** [comment]
Sure, assigning it to you.

**Comment by anweshknayak** [comment]
any hint for this ?

**Comment by deshraj** [comment]
Anwesh, see this https://docs.djangoproject.com/en/1.10/ref/models/fields/#timefield

**Comment by anweshknayak** [comment]
@deshraj I have one doubt. You mentioned timeout? I couldn't actually get how to proceed with this. TimeField as it says in docs time( represented in Python by a datetime.time instance ) How about setting default to 300s ?

**Comment by deshraj** [comment]
See this https://docs.python.org/2/library/datetime.html#datetime.timedelta.total_seconds. This might help. 

For eg. you can create a 300 secs datetime object using following code: 
```
from datetime import timedelta
a = timedelta(seconds=300)
```

**Comment by TroJan** [comment]
@deshraj : what if we create this as a positive integer field with default value of 300 ? Also can we please keep the name as execution_time_limit. This is actually self explanatory.

**Comment by anweshknayak** [comment]
@deshraj it is done should be closed

**Comment by TroJan** [comment]
Merged in #391 . thanks @anweshknayak :)
