### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by gshippee** [Cloud-CV/EvalAI#3623]
Hello, 

Upon running the docker-compose command, I am receiving the following error:

 => CANCELED [evalai_django internal] load metadata for docker.io/library/python:3.7.5                             8.3s
 => CANCELED [evalai_nodejs_v2 internal] load metadata for docker.io/library/node:12.2.0                           8.2s
 => CANCELED [evalai_nodejs internal] load metadata for docker.io/library/node:8.11.2                              8.2s
 => ERROR [evalai_worker internal] load metadata for docker.io/library/evalai_django:latest                        8.1s
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

Any ideas why this might be happening/how to resolve? 

Thank you.

**Comment by Aditya-Gupta1** [comment]
Same Issue. Can't set up the project. Seems like the image `pakohan/elasticmq` is removed.

**Comment by RishabhJain2018** [comment]
Hey @gshippee @Aditya-Gupta1 , Thanks for bring this to our notice. We will look into this and get back to you.

**Comment by Ram81** [comment]
This issue was fixed. Closing this PR
