### ISSUE TITLE
Set django cache backend for the development environment

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#363]
Currently, we are using memcached for caching in the development environment also. We should change it to default django cache backend. 

Let me know if you have questions.

**Comment by RishabhJain2018** [comment]
@deshraj Can I work on this?

**Comment by deshraj** [comment]
Sure. Assigning it to you. :-)

**Comment by RishabhJain2018** [comment]
@deshraj For a suggestion, can we use [this](https://docs.djangoproject.com/en/1.10/topics/cache/#dummy-caching-for-development) cache backend for development ?

**Comment by deshraj** [comment]
Sounds good to me.

**Comment by deshraj** [comment]
Fixed.
