### ISSUE TITLE
Create is_public field in Phase model

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#364]
We would like to add a new field `is_public` in phase model to check if the particular phase is set active by the host team or not. Set the default value to `False`.

**Comment by gauthamzz** [comment]
Can you assign this to me , do we need a named migration after this ?

**Comment by deshraj** [comment]
@gauthamzz I am glad to see such enthusiasm but can you please finish other issues before I assign you any new ?

**Comment by Ram81** [comment]
@deshraj can you assign this one to me?

**Comment by deshraj** [comment]
Fixed in #373.
