### ISSUE TITLE
In Docs Change link in Host Challenge using Github in step 1.

### ISSUE THREAD

**Issue by haldendmello** [Cloud-CV/EvalAI#3665]
When we click on **EvalAI-Starters** it goes to different page.
<img width="1440" alt="ss2" src="https://user-images.githubusercontent.com/60038994/148992353-d80f0008-645a-4cf4-bdc1-9cc4fe5abadf.png">

**Comment by haldendmello** [comment]
I have send Pull Request.

**Comment by Ram81** [comment]
@haldendmello that is the expected behavior.

Closing this issue
