### ISSUE TITLE
Enable code upload challenges in development.

### ISSUE THREAD

**Issue by gustavofuhr** [Cloud-CV/EvalAI#3667]
Hello,

I'm setting up my own forked version of EvalAI and I'm having troubles setting code upload challenges. If I understand correctly the code (in the DEV environment), there is no worker that is able to receive a code upload submission, right?

So, for the worker `Dockerfile` instead of this:
```
CMD ["./docker/wait-for-it.sh", "django:8000", "--", "python", "-m", "scripts.workers.submission_worker"]
```
I'm doing this:
```
CMD ["./docker/wait-for-it.sh", "django:8000", "--", "python", "-m", "scripts.workers.code_upload_submission_worker"]
```

That raise a bunch of errors, that I'm trying to figure out. 
Is that the "correct" way to enable code upload on development?

p.s.: I'm only interested in code upload challenge, not remote evaluation.

Thanks!

**Comment by gustavofuhr** [comment]
Actually, I just found that there is a different worker Dockerfile in `EvalAI/docker/dev/code-upload-worker/Dockerfile`. Is that the one that should be used?

There is some documentation on all this?

**Comment by Ram81** [comment]
Hi @gustavofuhr,

We don't support running code upload challenges locally, the pipeline is tightly coupled with AWS infrastructure so setting up locally would be difficult. 

>Actually, I just found that there is a different worker Dockerfile in EvalAI/docker/dev/code-upload-worker/Dockerfile. Is that the one that should be used?

Yes, that's correct

>There is some documentation on all this?

No, currently we don't have any documentation on how to set it up locally. 

Closing the issue as I have addressed the queries.

**Comment by gustavofuhr** [comment]
Got it @Ram81, but there is any doc to set up code upload eval remotely then?

**Comment by Ram81** [comment]
@gustavofuhr unfortunately we don't have any documentation on how to set it up remotely but we do support spawning the required infrastructure in a remote AWS account on EvalAI. The way it works is, challenge hosts create a remote evaluation code upload challenge on EvalAI and share an IAM role with us that we use to spawn the required infrastructure in remote AWS account. In this flow, challenge hosts don't have to manage the infrastructure as everything is automated.
