### ISSUE TITLE
[Frontend] Fix the twitter feed loading when user navigates back to homepage

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3676]
### Description

The twitter feed homepage fails to load when a users visits some other page after visiting the homepage and then comes back to the homepage. Steps to reproduce:

1. Open EvalAI homepage on FrontendV2
2. Navigate to login/signup page
3. Navigate back to homepage and check the twitter feed

Screenshot for reference:

![Screenshot from 2022-01-17 18-02-21](https://user-images.githubusercontent.com/16323427/149845858-cf83d18a-07a2-44f2-b455-109189c32178.png)

Expected behavior:

![Screenshot from 2022-01-17 18-03-28](https://user-images.githubusercontent.com/16323427/149845934-4e5ea244-acc1-4731-b1cc-d280d44dae57.png)

**Comment by ayushvrma** [comment]
Hi, can I work on this? I'm a beginner though, would need some help if that's okay?

**Comment by haldendmello** [comment]
@Ram81 can I work on the issue. I know the basics of Angular.

**Comment by haldendmello** [comment]
> @Ram81 can I work on the issue. I know the basics of Angular.
I have send Pull request
Fix #3676 [Frontend] Fix the twitter feed loading when user navigates back to homepage

**Comment by Ram81** [comment]
Hi @ayushvrma, sure you work on this issue. You can post your doubts on our gitter channel if you are stuck.


>@Ram81 can I work on the issue. I know the basics of Angular.

Hi @haldendmello, thanks for your interest. We usually follow first come first serve approach to assign issues as @ayushvrma has already requested this issue you'll have to look for another issue. If he isn't able to make progress in a week then we can reassign this issue to you.

**Comment by haldendmello** [comment]
Hi @ayushvrma if you want any help you can contact me haldendmello19@gmail.com

**Comment by bridyash13** [comment]
Hey @Ram81 can I work on this issue as I don't think ayush has made any progress as there's no pull request linked to this issue

**Comment by ayushvrma** [comment]
@Ram81 @haldendmello I'm sorry to not being able to figure out how to fix the code yet. You can assign it to @bridyash13

**Comment by haldendmello** [comment]
@ayushvrma @bridyash13 This issue is fixed.

**Comment by Ram81** [comment]
Closing this as it is fixed
