### ISSUE TITLE
[Backend] Submission validation absent in challenges for unsupported files

### ISSUE THREAD

**Issue by GeekGawd** [Cloud-CV/EvalAI#3686]
I noticed that the user can upload non .txt files as a submission in the challenges. Resources can be saved on such a file by just adding a validation.

Ideal Behaviour:
Throw 400 Bad Request for unsupported files

Current Behaviour:
No validation written in views for this.

https://user-images.githubusercontent.com/89455838/151967012-aad876d9-604d-4742-a2ce-c12b0023eb6b.mp4

If this is a potential issue. I would like to be assigned to it and work on it. Thank You!

**Comment by Suryansh5545** [comment]
Hello @GeekGawd  it seems there is already a issue for this error. #3358

**Comment by Ram81** [comment]
Closing this issue as it is a duplicate
