### ISSUE TITLE
[FrontendV2] Disable submit button on submit page when a selected file is of incorrect type

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#3695]
### Description

Currently, in our Frontend V2 submit page on the challenge page user can submit a file even if it has a extension which is not allowed by challenge hosts in (i.e. not in `allowed_submission_file_types` for a challenge phase). If a user uploads a file on the frontend which has a invalid extension we should disable the submit button and show a message that selected file type is invalid.

Screenshot for reference:

![Screenshot from 2022-02-12 12-05-57](https://user-images.githubusercontent.com/16323427/153720823-2babbc7d-4e16-403d-8d61-b6525d74daf7.png)

Expected behavior: Disable the submit button when file uploaded using `Upload file` option has a invalid extension.

**Comment by haldendmello** [comment]
@Ram81 want to work on this issue.

**Comment by cypersii** [comment]
Is this issue still open?

**Comment by MUDITJAIN2** [comment]
@Ram81  Can you please assign me this issue? im intrested to work upon it .

**Comment by SumeelaMadusankha** [comment]
I am intrested in solving this issue. Can you please assign me on this.

**Comment by gchhablani** [comment]
@SumeelaMadusankha This issue is old. We are not building `frontend_v2` currently.
@Ram81 I am closing this one for now.
