### ISSUE TITLE
What is the stable working version with bug fixes?

### ISSUE THREAD

**Issue by surak** [Cloud-CV/EvalAI#3699]
The last released version is from 4 years ago (1.1) - is there a "stable" recent version with bug fixes? Should one use the master branch? It's not clear from here.

**Comment by Ram81** [comment]
Hi @surak, the current master is the latest release which is stable.

**Comment by surak** [comment]
It's hard for institutions to deploy things in production without a clear release schedule - is "master" from 2020 the same as 2022? Would it be possible to create a tag so packagers and people working with software installs can work with? Otherwise, we will simply lock into a commit. 

Thanks!
