### ISSUE TITLE
Expand team to show team members

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#371]
In team view, there is an option to show members of team. Need to implement it such that clicking on card expand with its team member also add toggle functionality to cards.

Let me know in case of any query .

**Comment by Ram81** [comment]
@aka-jain  can you assign this to me?

**Comment by deshraj** [comment]
@Ram81 please try to do one issue at a time. Otherwise it blocks the overall development. We have enugh number of issues for you to solve. :-)

**Comment by deshraj** [comment]
This issue will apply for both the participant team view and the challenge host team view.

**Comment by Ram81** [comment]
@deshraj  I will do this one now. 
any hints for this one?

**Comment by aka-jain** [comment]
@Ram81: I think you should do #372 first, it will be helpful for you to give an overview of whole system. 
If you still want to do this then let me know please. I'll make #372 free for others.

**Comment by Ram81** [comment]
@aka-jain Okay as you say I will try #372 first

**Comment by jayantsa** [comment]
@aka-jain can I work on this?

**Comment by RishabhJain2018** [comment]
@aka-jain @deshraj Is someone working on this issue ??

**Comment by aka-jain** [comment]
@rishab please work on any other issue, I'm assigning it to @jayantsa.
@jayantsa please go ahead, and let me know if you need any help

**Comment by RishabhJain2018** [comment]
@aka-jain okk sure :-)

**Comment by jayantsa** [comment]
@aka-jain Is there any API endpoint that returns participants based on team name

**Comment by aka-jain** [comment]
@deshraj : can you help @jayantsa  here?

**Comment by deshraj** [comment]
@jayantsa Please look at the http://localhost:8000/docs and you can find an API endpoint with url ` /api/participants/participant_team/<pk>` which gives you the details of a challenge based on the primary key of the team which is `<pk>` here. For eg. for a challenge with primary key `1`, the url will be ` /api/participants/participant_team/1`. 

Please let me know if you have more queries.

**Comment by jayantsa** [comment]
@deshraj  This API returns > **Object { id: 1, team_name: "team2", created_by: "jayant" }**  but inorder to show Team members in particular team we should return **Object { count: 3, next: null, previous: null, results: Array[3] }** where array contains all the Participants from participant db havind team_name="team2". Am i right ?

**Comment by aka-jain** [comment]
Sorry @jayantsa to catching you late. @deshraj any idea about API response?

**Comment by deshraj** [comment]
Dependent on #476

**Comment by jayantsa** [comment]
Also Dependent on #515

**Comment by jayantsa** [comment]
@aka-jain solved #476 and #515. Will work on this issue. Can we use bootstrap for making drop-down list??

**Comment by deshraj** [comment]
@jayantsa we are planning to use materializecss throughout. So, it would be good if you can use materializecss for drop down list.

**Comment by jayantsa** [comment]
@deshraj  ok sure.

**Comment by jayantsa** [comment]
@deshraj  Please reopen #515 .Need to make small changes.

**Comment by jayantsa** [comment]
@deshraj  **Please assign this issue to some one else** because due to some reason won't be able to contribute for some time. **Solved #476, #515, #527, #528** that were required for this. 
Now when call to **/api/participants/participant_team**  is made then within results we will have team details along with its members and same is the case when call to **/api/hosts/challenge_host_team/** is made

**Comment by deshraj** [comment]
Thanks for informing @jayantsa :-) 

@aka-jain Assigning it to you.

**Comment by spyshiv** [comment]
@aka-jain : I am on it.

**Comment by aka-jain** [comment]
Okay 👍

**Comment by deshraj** [comment]
Fixed in #896. Thanks @spyshiv :)

**Comment by spyshiv** [comment]
Cool :)
