### ISSUE TITLE
Show count in Dashbboard view cards

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#372]
Add count to all mentioned cards in Dashboard. 
Example: for card participated challenges show number of participated challenges of user just above the text written and over the image.

**Comment by Ram81** [comment]
@aka-jain can you assign this to me?

**Comment by aka-jain** [comment]
@Ram81 : Sure, go ahead.

**Comment by Ram81** [comment]
any hints?

**Comment by aka-jain** [comment]
Go thorugh the API doc first at /docs on your django server. From that, you can get the API's that will be needed here to call count of each card. If count field doesn't exist then you can use length to find count of an Object.
Got it? 
You can take help related to API calls from other controllers. In case you want to know more about API services in angular then let me know, happy to help you :)

@deshraj : Can you list all the API's here related to cards in Dashboard?

**Comment by deshraj** [comment]
@Ram81 if you have started working on this, then can you please check the /docs and let me know if you can find the relevant API endpoints.

**Comment by Ram81** [comment]
@deshraj  I'll see & let you know if any doubts!

**Comment by Ram81** [comment]
@deshraj  for create challenge card I have to use API Endpoint from challenges App,am I right?

**Comment by Ram81** [comment]
@deshraj @aka-jain for create challenge card I have to use API Endpoint from challenges App,am I right?

**Comment by Ram81** [comment]
@aka-jain  are the API's ready for this issue,so that I can start to work on it?

**Comment by deshraj** [comment]
@Ram81 we are not ready with this. Once we have the APIs ready for this, I will let you know.

**Comment by deshraj** [comment]
We are not planning to show the current cards on the dashboard. It will be replaced by a news feed. hence closing this issue.
