### ISSUE TITLE
Modify the distance of the footer from the top of the screen

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#374]
The footer on the dashboard should start from the height equal to the height of the screen. Please let us know if you have doubts.

**Comment by parismita** [comment]
yeah its working now

**Comment by RishabhJain2018** [comment]
@deshraj Can I work on this ?

**Comment by deshraj** [comment]
Sure. Assigning it to you.

**Comment by deshraj** [comment]
Fixed in #420
