### ISSUE TITLE
Blank screen is coming while running django server

### ISSUE THREAD

**Issue by jainarunarunjain** [Cloud-CV/EvalAI#375]
![image](https://cloud.githubusercontent.com/assets/16155501/21747806/a3188e16-d528-11e6-8071-170111bd8aca.png)

localhost:8000 is blank and django server is throwing warnings.

**Comment by anweshknayak** [comment]
update repo. and remember to pip install the requirement files too.

**Comment by jainarunarunjain** [comment]
@anweshknayak Still not working

**Comment by anweshknayak** [comment]
update the bower components too

**Comment by anweshknayak** [comment]
and there were some recent changes in README have a look

**Comment by deshraj** [comment]
@jainarunarunjain is the issue resolved or not?

**Comment by jainarunarunjain** [comment]
i had already done this but nothing happened

**Comment by deshraj** [comment]
Can you make request to any API endpoint?

**Comment by jainarunarunjain** [comment]
@deshraj yes, api request is working

**Comment by parismita** [comment]
@jainarunarunjain do gulp dev and gulp connect and runservser simultaniously and goto localhost/8888.....there is the actual website..... i think localhost/8000 is just the backend part and the views r not directly linked to html thts wht it is so......not so sure abt it.......but the site is at localhost/8888 not localhost/8000 thts for sure

**Comment by parismita** [comment]
@deshraj i dont think this is a bug, this is how it is i guess....(just guessing :-P )

**Comment by deshraj** [comment]
No, you are right. I have discussed with @jainarunarunjain the same on Gitter. Thanks for your input @parismita :-) Glad that you are trying to help others.

**Comment by aka-jain** [comment]
@deshraj : Making template path as frontend/dist is solving my problem. Is it a right way to solve this issue?

**Comment by anweshknayak** [comment]
error still persists? Please reopen @dexter1691

**Comment by aka-jain** [comment]
@deshraj : Please have a look to this issue.

**Comment by deshraj** [comment]
Sure, It's already on my todo list. Will fix it soon.

**Comment by deshraj** [comment]
Fixed in #615. Now, we have to make sure that the 500 and 404 page of django has its own static files and should not interfere with the angular files since both are independent.
