### ISSUE TITLE
`docker-compose up --build` throws an error

### ISSUE THREAD

**Issue by KDr2** [Cloud-CV/EvalAI#3768]
I am trying to follow the instructions on README.md to build up the docker images. But it seems that some Dockerfile uses an out-of-date system: https://github.com/Cloud-CV/EvalAI/blob/master/docker/dev/nodejs/Dockerfile this file tries to install google-chrome-stable on debian jessie, which can't be satisfied:

```
The following packages have unmet dependencies:
 google-chrome-stable : Depends: libdrm2 (>= 2.4.60) but 2.4.58-2 is to be installed
                        Recommends: libu2f-udev but it is not installable
                        Recommends: libvulkan1 but it is not installable
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'nodejs' failed to build: The command '/bin/sh -c apt-get update && apt-get install -yq google-chrome-stable' returned a non-zero code: 100
```

Is there anyone who knows how to fix this? Thank you.

**Comment by xmichele** [comment]
Hello, try replacing this Dockerfile step with apt-get update -qqy --no-install-recommends && apt-get install -qqy --no-install-recommends google-chrome-stable

**Comment by KarimElsayad247** [comment]
I'm having a similar issue but with a completely other project. Build succeeds on Ubuntu, but fails on WSL with this error 

```
The following packages have unmet dependencies:
 google-chrome-stable : Depends: libgbm1 (>= 17.1.0~rc2) but 13.0.6-1+b2 is to be installed
                        Recommends: libu2f-udev but it is not installable
                        Recommends: libvulkan1 but it is not going to be installed
```

**Comment by santoshkona** [comment]
Did you find any solution for this issue ? I am facing the same

**Comment by Mitzz** [comment]
I am facing similar issue but with python 3.7-stretch image. 
Docker version 20.10.17, build 100c70180f

Dockerfile as follows

`FROM library/python:3.7-stretch
RUN apt-get update

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt-get -y update
RUN apt-get install -y google-chrome-stable
`
