### ISSUE TITLE
How to build docker images on a machine and execute to another one

### ISSUE THREAD

**Issue by castorfou** [Cloud-CV/EvalAI#3777]
This is a question not an issue.

For a reason I cannot build evalai docker images on my host machine.
It is behind a corporate firewall. But I would like to run evalai on this host, and connect internally to our corporate gitlab.

I have successfully built docker images on a standard linux machine, out of this network. And I would like to 'move' these images on my final host and just start evalai. And I am not sure how to do it.

From my standard linux machine, I am able to list and extract all evalai images with commands like `sudo docker save -o /tmp/evalai_nodejs.tar evalai_nodejs` . Copy these images to my host machine.
And from this host machine, I can then load these images with `sudo docker load -i evalai_nodejs.tar` and they are visible from `docker images`
But I am not sure how to start evalai. If I try `docker-compose up --build` from evalai, it tries to rebuild them and it fails.

Sorry it is likely a very basic docker question. But any help would be appreciated.

**Comment by xmichele** [comment]
Hello, do a docker-compose up without --build

**Comment by castorfou** [comment]
Thank you, it works now with nodejs image. I am going to transfer all images, then start evalai. Will let you know the results.
