### ISSUE TITLE
Submission stuck at "Submitted" for TextCaps and NoCaps

### ISSUE THREAD

**Issue by xchen147** [Cloud-CV/EvalAI#3796]
Hello,

Looking over the previous issues, I believe this is a recurrent issue. This time this issue has been there for NoCaps and TextCaps at least 3-4 days ago.

Thanks for your attention,

**Comment by lorenmt** [comment]
I just met the same problem on VQA Benchmark. Wondering if is there any expected time to fix this? @gchhablani Really appreciate your time and help.
