### ISSUE TITLE
AttributeError: 'MultiOut' object has no attribute 'flush'

### ISSUE THREAD

**Issue by gchhablani** [Cloud-CV/EvalAI#3818]
Found an issue mentioned in one of the messages:
```AttributeError: 'MultiOut' object has no attribute 'flush'.``` The VizWiz 2022 challenge evaluation is failing apparently because of this.

This is probably due to the MultiOut class added recently.

**Comment by xinyu1205** [comment]
I have encountered the same problem. Is there any solution?

**Comment by xinyu1205** [comment]
> Found an issue mentioned in one of the messages: `AttributeError: 'MultiOut' object has no attribute 'flush'.` The VizWiz 2022 challenge evaluation is failing apparently because of this.
> 
> This is probably due to the MultiOut class added recently.


Hi, sorry to bother you. I have encountered the same problem. Is there any solution?

**Comment by gchhablani** [comment]
@xinyu1205 This issue has been fixed in staging and the fix will be moved to prod soon. Sorry for the delay.

CC @Ram81

**Comment by xinyu1205** [comment]
> @xinyu1205 This issue has been fixed in staging and the fix will be moved to prod soon. Sorry for the delay.
> 
> CC @Ram81

Really appreciate for your reply! I'm look forward to an early resolution of this issue.
