### ISSUE TITLE
BDD100K Object Detection on EvalAI submission status failed

### ISSUE THREAD

**Issue by Chung-Lucy** [Cloud-CV/EvalAI#3850]
I submit my validation and testing result of BDD100K Object Detection Challenge on EvalAI on Monday, and get the result of validation but the status of testing is "Failed" with the following error message:

"Traceback (most recent call last):
File "/code/scripts/workers/submission_worker.py", line 504, in run_submission
submission_output = EVALUATION_SCRIPTS[challenge_id].evaluate(
AttributeError: module 'challenge_data.challenge_1857' has no attribute 'evaluate' "

Please help me to resolve the problem and get the testing result, thanks!

**Comment by gchhablani** [comment]
Thanks for pointing out this issue. There is a problem with the challenge configuration. We have reached out to the hosts and are trying to get this issue resolved as quickly as possible.
 
Thanks,
Gunjan

**Comment by Chung-Lucy** [comment]
Thank you for your reply. If the issue is resolved, please inform me. Thank you very much!!

Best Regards,
Lucy
