### ISSUE TITLE
Remove test_annotation field from ChallengePhase serializer

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#388]
We should remove the field `test_annotation` from all the APIs related to Challenge Phase since this data has to be only accessed by the Challenge Organizer.

**Comment by Ram81** [comment]
@deshraj  can I try this one?

**Comment by parismita** [comment]
is anyone doing this??

**Comment by Ram81** [comment]
yeah I want to work on this one!

**Comment by parismita** [comment]
yooo...no issue...i was just asking

**Comment by Ram81** [comment]
yeah its fine

**Comment by deshraj** [comment]
Assigning to @Ram81 :-)

**Comment by Ram81** [comment]
@deshraj  I've removed ' test_annotation ' field from ChallengePhaseSerializer's meta class is there any other dependency I should look for?

**Comment by deshraj** [comment]
Can you please write test for the same and check if this field is returned or not in response from the APIs?

**Comment by Ram81** [comment]
Sure will do that :+1:

**Comment by Ram81** [comment]
@deshraj Do I have remove other tests from CreateChallengePhaseTest & UpdateChallengePhaseTest  as we removed field from Serializer?

**Comment by deshraj** [comment]
@Ram81 No, you don't need to remove the tests. Just make changes to the existing tests to check if the `test_annotation` field is present or not in all those APIs. Does that make sense?

**Comment by Ram81** [comment]
I've to just revert the tests i.e if field is not present  ok response will be there else a basd request,am I right?

**Comment by deshraj** [comment]
I think it would be a good idea to create a PR and then I can suggest the changes.

**Comment by Ram81** [comment]
@deshraj Okay will do & let you know

**Comment by Ram81** [comment]
@deshraj do I have to just add a test in GetChallengePhaseTest class in test_view.py or some other ones too or am I doing it totally wrong, please guide?

**Comment by deshraj** [comment]
Yeah, you are correct.

**Comment by Ram81** [comment]
@deshraj so there I've to remove test_annotations field from 'expected[]' ,right?

**Comment by deshraj** [comment]
Yup. You might also need to add one or more test cases. Can you open a PR once you are done with the changes and then we can see what other changes do we need to make?

**Comment by Ram81** [comment]
Okay for now I will remove the field & generate a PR & then you suggest changes !

**Comment by Ram81** [comment]
@deshraj  what about tests you wanted me to write?

**Comment by deshraj** [comment]
Fixed in #431
