### ISSUE TITLE
Fix manage tab visibility access on challenge page

### ISSUE THREAD

**Issue by gchhablani** [Cloud-CV/EvalAI#3894]
### Description
Currently, the challenge page manage tab for any challenge is visible to anyone if they try to directly access the link. This should not be the case. Ideally, it should be redirected to `404` page directly.

https://user-images.githubusercontent.com/29076344/226559437-d0c7fd99-f5d4-4cdb-84d2-7e0dcdd01b62.mov

I made an attempt in #3883 but it is slow as we use our Django API to fetch whether the user is challenge host or not. This leads to a 1 second delay in redirecting to the 404 page which is undesired. The hosts should be able to access this link but the participants should not.

Note that this is a **critical** issue.

### Pre-requisites/Learnings
This issue essentially requires background on a few things:
- An overview understanding of [EvalAI challenges](https://evalai.readthedocs.io/en/latest/host_challenge.html).
- An understanding of the [Challenge Model](https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/models.py) on EvalAI.
- An understanding of the [EvalAI frontend](https://github.com/Cloud-CV/EvalAI/tree/master/frontend).

### How to Approach
- You can start by setting up EvalAI locally. Set up the dev version locally (preferred) using the steps [here](https://github.com/Cloud-CV/EvalAI/tree/master#installation-instructions).
- Play around with the the frontend, and create a PR. Please add screenshots/GIFs of the changes.
- Reach out to us regarding any issues that you face or if you need any help with understanding any of the above.

**Comment by AyushR1** [comment]
@gchhablani I can also work on this one, If possible assign it to me! Thanks!

**Comment by CodeDetector** [comment]
@gchhablani  I understand this issue and would like to work on it .

**Comment by gchhablani** [comment]
@AyushR1 As I said, let's get your PR merged. I will provide review on that one asap and then you can take up some other issue.

**Comment by gchhablani** [comment]
@imperorrp I have assigned this issue to @CodeDetector. Please check if any other issues are open, I will assign you to them.

**Comment by CodeDetector** [comment]
Hi @gchhablani I am working on this issue . Was facing issues with docker setup that is resolved .

**Comment by gchhablani** [comment]
@CodeDetector Please ping me on the slack if you face any issues. Thanks!

**Comment by gchhablani** [comment]
@CodeDetector Are there any updates on this?
