### ISSUE TITLE
Create endpoint for creating a new Challenge

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#39]
Details about the endpoint:
- Url: /api/challenges/
- Header: Authorization: Token <token>
- Method: POST
- Response: 
  - status on success: HTTP_201_CREATED
  - status on exception:  HTTP_406_NOT_ACCEPTABLE
  - status on Unauthorized access: HTTP_203_NON_AUTHORITATIVE_INFORMATION

For more details, feel free to discuss on thread or gitter channel https://gitter.im/Cloud-CV/EvalAI

**Comment by TroJan** [comment]
Fixed in #123
