### ISSUE TITLE
Increase the code quality in landscape. 

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#390]
@deshraj I found the code quality is low in landscape.io . Please refer to this [link](https://landscape.io/github/Cloud-CV/EvalAI/547/messages/smell).

Can I work on this to fix this??

**Comment by deshraj** [comment]
Oh this looks like a good initiative. Do you want to work on this? I was going to open an issue for the same.

**Comment by RishabhJain2018** [comment]
@deshraj yeah sure.

**Comment by souravsingh** [comment]
@deshraj I am interested in working on the issue if no one else is working

**Comment by deshraj** [comment]
@souravsingh: Sorry, @RishabhJain2018 is already working on this.

**Comment by RishabhJain2018** [comment]
@deshraj I think we should close this?

**Comment by deshraj** [comment]
Thanks. :-)
