### ISSUE TITLE
Bug: Duplicate rows for a second on Leaderboard on selecting any dropdown option

### ISSUE THREAD

**Issue by rahul2240** [Cloud-CV/EvalAI#3902]
**Expected Behaviour**
- No duplicate entry should appear when applying a filter on the leaderboard

**Observed Behaviour**
- Duplicate rows appear for a second after changing filters on the leaderboard
![evaliai](https://user-images.githubusercontent.com/25618739/227228839-18aab82a-d4bd-4269-b9f8-8af32740054c.gif)

**Steps To Reproduce**
- Open any challenge
- Go to the leaderboard
- Select any dropdown option

**Comment by Adi9235** [comment]
Hi @rahul2240 can I work on this issue but I am beginner to this project so if it is good to start.

**Comment by gchhablani** [comment]
Thanks @rahul2240 for posting this issue. If you are looking to participate in GSoC with us, please feel free to work on this.

@Adi9235 This is currently not a GSoC issue but if @rahul2240 is not working on this, we can assign you this one.

**Comment by rahul2240** [comment]
@gchhablani, let @Adi9235 take this 😄

**Comment by Dedeepya-K** [comment]
Hey there, as a part of GSoC even I would like to contribute and if the issue is still open and no one is working on it, I would like to take this up.
