### ISSUE TITLE
Missing terms in challenge configuration docs

### ISSUE THREAD

**Issue by gchhablani** [Cloud-CV/EvalAI#3920]
The current [docs for challenge configuration] (https://evalai.readthedocs.io/en/latest/configuration.html) do not contain all the terms we allow in [challenge configuration](https://github.com/Cloud-CV/EvalAI-Starters/blob/master/challenge_config.yaml).

It should be fixed asap to help the hosts understand what the terms mean.

Additional next issue (probably slightly harder than this) would be explaning what all is required and what is optional (if anything) in the challenge configuration.

**Comment by Suryansh5545** [comment]
@gchhablani I will take this up
