### ISSUE TITLE
Show user timezone on submission worker logs

### ISSUE THREAD

**Issue by gchhablani** [Cloud-CV/EvalAI#3923]
Currently, the timezone used on submission worker logs is UTC.

![image](https://user-images.githubusercontent.com/29076344/230247599-7c8ad225-14cf-47a3-89b1-7d3489c5d05e.png)

We would like to show the user's timezone on frontend. This will require processing the logs to convert the time from UTC and taking the user timezone. Might also require changes on the backend.

**Comment by AyushR1** [comment]
@gchhablani I can take the issue! Please assign it

**Comment by gchhablani** [comment]
@AyushR1 Assigned!
