### ISSUE TITLE
insecure/Unsupported Django Version

### ISSUE THREAD

**Issue by Suryansh5545** [Cloud-CV/EvalAI#3928]
Present:-
We are currently on Django 2.2 LTS and the Extended support for this version has been ended in April 2022
![image](https://user-images.githubusercontent.com/34577232/230734776-bc6206b4-8802-4077-bc17-014ca7575bc5.png)
So, this version will no longer get any security patch.

Future:-
            We should consider upgrading to Django 3.2 or 4.2 LTS . 
![image](https://user-images.githubusercontent.com/34577232/230735240-a4c88d6a-04a6-4656-b320-edf0a77a10d8.png)

This will require a major change as in django 4.2 they have introduced many changes few of the major once are
Change in URL Routing since 2.2
Support for some databases dropped.
Several new settings and some removed in 4.2

**Comment by Jaishree2310** [comment]
@Suryansh5545  
I am at a beginner level right now and would love to take up this ticket. can you please assign it to me? thanks in advance!

**Comment by Suryansh5545** [comment]
@Jaishree2310 maintainers haven't commented on this yet so I am not sure about this. Also this will be a lot of work and I believe will require more than one PR.

**Comment by gchhablani** [comment]
@Suryansh5545 Thanks for pointing this out. What you are proposing will be an entire project of its own. Can you please shed some light on what will be the issues with continuing the current version for the time being?

**Comment by Suryansh5545** [comment]
@gchhablani The main issue currently will be that with the version 2.2 being deprecated , we will no longer receive security patchs for the vulnerabilities discovered after the april 2022 period. This isn't that big of a issue for now to justify to upgrade our django version immediately as it will be a major change and we can continue to use our current version for the time being. But perhaps should consider upgrading after the completion of current projects.
