### ISSUE TITLE
Add auto-collapse/expand for metrics on the leaderboard

### ISSUE THREAD

**Issue by gchhablani** [Cloud-CV/EvalAI#3934]
Add `...` for loading more metrics on the leaderboard.
The metrics should get shown when the users scroll down but not unless they have reached there.

**Comment by Suryansh5545** [comment]
@gchhablani can I work on it?

**Comment by chiragbiradar** [comment]
Hey @gchhablani can I work on this?

**Comment by Bhavay-2001** [comment]
Hi @gchhablani, can I contribute to this issue? If yes, please let me know how can I start. 
Thanks

**Comment by Jaishree2310** [comment]
Hi @gchhablani can I take this token? Please assign this to me.
