### ISSUE TITLE
Create endpoint to get list of all the challenges

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#40]
Details about the endpoint:
- Url: /api/challenges/
- Header: None
- Method: GET
- Response:
  - status on success: HTTP_200_OK
  - status on exception:  HTTP_406_NOT_ACCEPTABLE
  - status on Unauthorized access: HTTP_203_NON_AUTHORITATIVE_INFORMATION

For more details, feel free to discuss on thread or gitter channel https://gitter.im/Cloud-CV/EvalAI

**Comment by TroJan** [comment]
Fixed via #122
