### ISSUE TITLE
My file stuck at “Submitted” at BDD100k MOT

### ISSUE THREAD

**Issue by qwomeng** [Cloud-CV/EvalAI#4001]
Hello @Ram81 @David_Novotny @Rishabh_Jain @rishabh   @gchhablani,
I’m sorry to bother you. I found that the BDD100K Multiple Object Tracking Challenge,
fail to process my results and the status is always "Submitted"（test set）.
The team name is xiong.
Can you please have a look ?

I really need this result and would very much appreciate your help and reply. Thanks in advance!

**Comment by qwomeng** [comment]
Solved. I don't know who helped me, but thanks a lot !

**Comment by piggi999** [comment]
@qwomeng  楼主你好，请问你的MotionTrack论文中的github链接打不开，请问有开源打算吗？什么时候开源呀？
