### ISSUE TITLE
I can no longer participate in any challenges.

### ISSUE THREAD

**Issue by 18979705623** [Cloud-CV/EvalAI#4010]
Recently, I found that my EvalAI account can no longer participate in any challenges. At the bottom of the challenge result submission webpage, it shows: Sorry, the participant team is not approved by host yet. The same is true for the accounts of people around me (their accounts are registered and used by me). What's going on?

**Comment by Suryansh5545** [comment]
@18979705623 please clear the cookies of your browser . That should fix the issue.

**Comment by 18979705623** [comment]
> 

This method works! Amazing.

**Comment by RishabhJain2018** [comment]
Closing since it is resolved!
