### ISSUE TITLE
Add a new status option in Submission model

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#406]
For reference, see this https://github.com/Cloud-CV/EvalAI/blob/master/apps/jobs/models.py#L25

We want to add a new status option with name `SUBMITTING = "submitting"`

**Comment by Ram81** [comment]
@deshraj  as I am not working on any issue currently can I work on this?

**Comment by deshraj** [comment]
Sure, go ahead. Assigning it to you. :-)

**Comment by Ram81** [comment]
@deshraj  I just have to add the option name submitting & add it in status_Options in the Submission model ,am I right ? or do I have to change any other code?

**Comment by deshraj** [comment]
You would also need to add an entry similar to this https://github.com/Cloud-CV/EvalAI/blob/master/apps/jobs/models.py#L32

**Comment by Ram81** [comment]
Okay Understood @deshraj will do it & let you know?

**Comment by deshraj** [comment]
Sounds good.

**Comment by Ram81** [comment]
@deshraj  sorry for this I will just remove directive.js from it !

**Comment by TroJan** [comment]
@deshraj : please make sure that migrations(named please) are also there in the PR.

**Comment by deshraj** [comment]
Sure, will take of it.

**Comment by TroJan** [comment]
@Ram81 : thanks for the quick fix :)
