### ISSUE TITLE
Create endpoint for updating the challenge

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#41]
Details about the endpoint:
- Url: /api/challenges/<challenge_id>/
- Header: Authorization: Token <token>
- Method: PUT/PATCH
- Response: 
  - status on success: HTTP_200_OK
  - status on exception:  HTTP_406_NOT_ACCEPTABLE
  - status on Unauthorized access: HTTP_203_NON_AUTHORITATIVE_INFORMATION

For more details, feel free to discuss on thread or gitter channel https://gitter.im/Cloud-CV/EvalAI

**Comment by TroJan** [comment]
Fixed in #126
