### ISSUE TITLE
My file stuck at “Submitted” at Argoverse Motion Forecasting Competition

### ISSUE THREAD

**Issue by Porphy** [Cloud-CV/EvalAI#4126]
Hi, I participated in the Argoverse Motion Forecasting Competition and after submitting my prediction yesterday, the submission status was “Submitted”  without any evaluation results, normally it should show “running”  followed by “finished”  with the evaluation results. However, when I checked today I found that the status changed to “failed”  and there was an error outputting the following, which seems to be a problem with missing server files:
Traceback (most recent call last):
  File "/code/scripts/workers/submission_worker.py", line 504, in run_submission
    submission_metadata=submission_serializer.data,
  File "/tmp/tmptedjfcjd/compute/challenge_data/challenge_454/main.py", line 109, in evaluate
    outputs[k] = eval_forecasting.compute_forecasting_metrics(output,gt,city_dict,k,30,2,prob)
  File "/code/argoverse-api/argoverse/evaluation/eval_forecasting.py", line 217, in compute_forecasting_metrics
    metric_results["DAC"] = get_drivable_area_compliance(forecasted_trajectories, city_names, max_n_guesses)
  File "/code/argoverse-api/argoverse/evaluation/eval_forecasting.py", line 166, in get_drivable_area_compliance
    avm = ArgoverseMap()
  File "/code/argoverse-api/argoverse/map_representation/map_api.py", line 66, in __init__
    self.city_lane_centerlines_dict = self.build_centerline_index()
  File "/code/argoverse-api/argoverse/map_representation/map_api.py", line 172, in build_centerline_index
    city_lane_centerlines_dict[city_name] = load_lane_segments_from_xml(xml_fpath)
  File "/code/argoverse-api/argoverse/data_loading/vector_map_loader.py", line 310, in load_lane_segments_from_xml
    tree = ET.parse(os.fspath(map_fpath))
  File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/code/argoverse-api/map_files/pruned_argoverse_PIT_10314_vector_map.xml'

![image](https://github.com/Cloud-CV/EvalAI/assets/92923476/ded7906e-2ae3-48f7-a80a-2276328be6ea)

Thanks!

**Comment by gchhablani** [comment]
@Porphy Fixed now. Thanks for pointing this out.

**Comment by Porphy** [comment]
> Hi @gchhablani, I encountered the same situation, and it has been in "submitted" status for 2 days. Thank you in advance for your assistance. ![sub](https://private-user-images.githubusercontent.com/20128813/287578976-1cb11c26-efe5-4583-9417-2d3ba8b058a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTUxMDYsIm5iZiI6MTcwMzc1NDgwNiwicGF0aCI6Ii8yMDEyODgxMy8yODc1Nzg5NzYtMWNiMTFjMjYtZWZlNS00NTgzLTk0MTctMmQzYmE4YjA1OGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDA5MTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNWNiN2I0N2M1YzVkMTMzMTMxOTk0MjVmMWRiZWRmZDE0ZDZmNzIzYTNhNDhlOGMxYTk3ZTE1ODM0OGFhMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HFNi1lihadIdgxNkxCKjTJ-OUFxUbpijOkl1vOrF6iI)

Hi, @KexianShen , I encountered the same situation again, can you receive the evaluation results now?

**Comment by gchhablani** [comment]
@Porphy I don't see any pending submissions for this challenge. Please create a message or a separate issue for a different challenge.

**Comment by KexianShen** [comment]
@Porphy yes, it works well
