### ISSUE TITLE
Modify EC2 autoscaling to not check for end dates challenges

### ISSUE THREAD

**Issue by gchhablani** [Cloud-CV/EvalAI#4128]

**Comment by galanggg** [comment]
Hi @gchhablani, I want to clarify this issue. So I need to remove this line of code for not checking the end dates?
[https://github.com/Cloud-CV/EvalAI/blob/bacbf89c5fa7e6155183525ddfef0f7a2e953af6/scripts/monitoring/auto_scale_ec2_workers.py#L89](url)
