### ISSUE TITLE
My submission is stuck at 'Submitted'.

### ISSUE THREAD

**Issue by DonghaChoiGIST** [Cloud-CV/EvalAI#4132]
My submission for the VQAv2(https://eval.ai/web/challenges/challenge-page/830/overview) test-dev phase keeps getting stuck at 'submitted' status.
my team name is DC

![image](https://github.com/Cloud-CV/EvalAI/assets/101086211/fdb9268c-5f55-4cf4-93ca-4338e397f928)

**Comment by PengLongkun** [comment]
The same question with you.
My team name is happy623

**Comment by ziqipang** [comment]
Same here. I have waited for one day.

**Comment by ziqipang** [comment]
@gchhablani I saw that your magical hand addressed this issue for a lot of people. It would be great if you could help us look into this issue. Thank you so much!

**Comment by gchhablani** [comment]
@ziqipang @PengLongkun @DonghaChoiGIST I have resolved this issue. Hopefully all submisssions will get evaluated soon.

**Comment by ziqipang** [comment]
@gchhablani Thank you! It works now
