### ISSUE TITLE
My file stuck at “Submitted” at Nuscenes Detection challenge

### ISSUE THREAD

**Issue by DodgePark** [Cloud-CV/EvalAI#4163]
Sorry to bother, but my nuscenes test set submission stays at 'Submitted' status and it looks it won't change.
My team name is pak.
![1212](https://github.com/Cloud-CV/EvalAI/assets/113985787/8703f3ab-38bb-4681-976a-cead375e0aa9)

**Comment by rishabh** [comment]
Hi, I think you have the wrong rishabh ;)

**Comment by DodgePark** [comment]
Still doesn't work ;)

**Comment by DodgePark** [comment]
Now it works! thank you
