### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by QA-x** [Cloud-CV/EvalAI#4201]
In VQA Challenge 2021, submitting an answer file prompts Failed. is this due to an error in the assessment process or is it an error in my answer file?

**Comment by ssyze** [comment]
I have the same issue. Even if i use the result file evaluated in the past, it is failed now.
The stderr shows some errors on sql.

**Comment by QA-x** [comment]
@ssyze ，Is this the issue you are talking about that shows up on the assessment site? May I ask if you have resolved it now?

**Comment by Pefect96** [comment]
I also meet the same question. Have you solved the problem?

**Comment by FarinaMatteo** [comment]
Same here. Files that were valid submissions in the past lead to failures. However, it seems that the stdout file already contains the final evaluation results.

**Comment by FarinaMatteo** [comment]
Same again, I had files queueing for around 30hrs. I bet there isn't much we can't do unless some EvalAI contributor has some tricks up his sleeve @gchhablani

**Comment by LinB203** [comment]
same question for 3 days.

**Comment by QA-x** [comment]
@FarinaMatteo Thanks for the heads up.“it seems that the stdout file already contains the final evaluation results.”

**Comment by QA-x** [comment]
@LinB203 You can read FarinaMatteo's comments. Files that were valid submissions in the past lead to failures. However, it seems that the stdout file already contains the final evaluation results.

**Comment by WWW2323** [comment]
Same question on nuScenes challenge.  It is terrible because the deadline of CVPR is coming.

**Comment by gchhablani** [comment]
Hi all,
Thanks for pointing to this issue.
Due to a recent merge, for some challenges the evaluation was failing.
I have fixed this.
If you continue to see this for any challenge, please send us a contact message through the forum or send me an email.

Thanks,
Gunjan
