### ISSUE TITLE
Create API endpoint to get all the submissions made by user for a challenge phase

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#421]

**Comment by RishabhJain2018** [comment]
@deshraj Can I work on this?

**Comment by deshraj** [comment]
Yeah Sure. Assigning it to you.

**Comment by deshraj** [comment]
Let me know if you need some help.

**Comment by RishabhJain2018** [comment]
ok.

**Comment by RishabhJain2018** [comment]
@deshraj In **[this](https://github.com/Cloud-CV/EvalAI/blob/master/apps/jobs/views.py#L27)** function, shouldn't we check the flag value for `approved_by_admin` field [here](https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/models.py#L34) for submitting to a challenge ?

**Comment by deshraj** [comment]
Yeah, great thought. We will add a decorator for the same in another PR. I am keeping a note of the same.

**Comment by RishabhJain2018** [comment]
So, Can I submit the PR without adding this decorator?

**Comment by deshraj** [comment]
Sure, go ahead.

**Comment by deshraj** [comment]
Fixed in #427. Closing it.
