### ISSUE TITLE
My file stuck at “Submitted” at nocaps.

### ISSUE THREAD

**Issue by shufangxun** [Cloud-CV/EvalAI#4214]
Hello,

@gchhablani 
I’m sorry to bother you. My submissions on the [nocaps](https://eval.ai/web/challenges/challenge-page/355/leaderboard/1011) keep getting stuck at 'submitted' status for a long time (~10hours).  Can you help me to solve it ? 
<img width="1142" alt="image" src="https://github.com/Cloud-CV/EvalAI/assets/19266420/0b0b21c6-3e78-49ae-b15a-5f1f02129891">

**Comment by Pefect96** [comment]
I meet the same problem, and I have submitted my results two days.@gchhablani 
![image](https://github.com/Cloud-CV/EvalAI/assets/95663989/c1365bbb-280a-4658-b7e3-656b406b8270)

**Comment by gchhablani** [comment]
@Pefect96 Fixed.

**Comment by Pefect96** [comment]
@gchhablani I have not obtain my results after submitting my file six days. It is always runing. Can you help me?
![image](https://github.com/Cloud-CV/EvalAI/assets/95663989/d655b80c-32c0-43cd-a52c-d1c227a2c84a)
