### ISSUE TITLE
stuck at TextVQA Challenge 2021

### ISSUE THREAD

**Issue by mactavish91** [Cloud-CV/EvalAI#4215]
please help me.

**Comment by kftam1994** [comment]
I also encountered the same issue. Submission in Test-Standard and Test-Violation Standard are stuck at "Submitted" without evaluation

**Comment by kftam1994** [comment]
![Capture](https://github.com/Cloud-CV/EvalAI/assets/33834357/444c2ec9-8a99-45e7-b7bf-7ed67d792efd)
Please help fix the challenge. Thank you

**Comment by kftam1994** [comment]
@gchhablani Could you help fix this challenge. Many thanks for your help

**Comment by kftam1994** [comment]
@gchhablani Thanks for fixing it but it seems my new submission is stuck at the "Running" stage for few hours
![image](https://github.com/Cloud-CV/EvalAI/assets/33834357/c76acad4-337c-462c-9715-a7d2c9c5f7d8)
