### ISSUE TITLE
Clear input field after creating a Participant Team

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#424]
On the `My Participant Team` view, once the user creates a participant team, then the input field should become empty. 

Please see the screenshot below for more information. 
<img width="1439" alt="screen shot 2017-01-12 at 11 27 17 pm" src="https://cloud.githubusercontent.com/assets/2945708/21918384/b2cde00a-d91e-11e6-977e-942fb0d38886.png">

**Comment by parismita** [comment]
@deshraj  Shall i try this?

**Comment by deshraj** [comment]
Yup sure. Assigning it to you.

**Comment by parismita** [comment]
@deshraj after creating new team why does it automatically redirects to challenge-page.html??

**Comment by deshraj** [comment]
Actaully, the files are not refreshed since you last pulled the code from master branch. Please run `gulp dev` in the root directory of the project and it should work fine.

**Comment by parismita** [comment]
@deshraj if the PR is fine then i can try #425

**Comment by deshraj** [comment]
@parismita I would like to make @aka-jain call on this. @aka-jain can you please review the PR?

**Comment by deshraj** [comment]
Fixed in #429. Closing it.
