### ISSUE TITLE
Clear input field after creating a Host Team

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#425]
On the 'My Hosts Team' view, once the user creates a host team, then the input field should become empty.

Please see the screenshot below for more information.
<img width="1440" alt="screen shot 2017-01-12 at 11 29 55 pm" src="https://cloud.githubusercontent.com/assets/2945708/21918420/28f82b3c-d91f-11e6-9892-d5cd55a99714.png">

**Comment by anweshknayak** [comment]
@deshraj can I work on this ?

**Comment by deshraj** [comment]
@anweshknayak looks like you are already working on #300. Please try to finish that first.

**Comment by deshraj** [comment]
Fixed in #430
