### ISSUE TITLE
Remove the radio button from the My Participant Team View 

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#426]
See the line: https://github.com/Cloud-CV/EvalAI/blob/master/frontend/src/views/web/teams.html#L20

We need to remove the radio buttons and replace them by https://github.com/Cloud-CV/EvalAI/blob/master/frontend/src/views/web/challenge-host-teams.html#L19

Let me know if you have concerns.

**Comment by gauthamzz** [comment]
I would like to try this, but i get errors thrown when installing frontend :disappointed: 
`npm install
npm WARN evalai@1.0.0 No repository field.`

**Comment by aka-jain** [comment]
@gauthamzz : That's not the error, your client side should work fine. Moreover have you read Readme again, it has been updated. Also try to run gulp dev and see if errors are coming or not.

**Comment by Rishav09** [comment]
hi,I want to work on this issue,

**Comment by spyshiv** [comment]
@Rishav09 - Sure! Go ahead.

**Comment by deshraj** [comment]
@Rishav09 any update on this?

**Comment by Rishav09** [comment]
Hi,I just fixed this and it got merged too.Sorry ,I didn't mentioned it here

**Comment by deshraj** [comment]
Thanks for informing. :-)
