### ISSUE TITLE
Instance is None while saving the file in Submission Model

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#428]
In Submission model, when the model is saved then the path where the `input_file` is saved is `submission_files/submission_None/` but ideally the `None` should be replaced with the id of the submission.

**Comment by deshraj** [comment]
@TroJan can you please prioritize this over all other issues assigned to you? It seems like this the super critical thing for us for now.

**Comment by TroJan** [comment]
Fixed via #681
