### ISSUE TITLE
New Design Buttons Elements

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#432]
Please check attached file for new design button (host challenge button in design). Need to design a global component for button which can be use anywhere with common class name.
Points need to be focus:
1. Button color,
2. Button Border-radius,
3. Button back shadow and shadow color,
4. Button text color and font-weight.
5. Class name should be unique,
6. Write a sass in sepearate file. Don't put code in older files.

**Note: Please make PR to **new-ui** branch instead of **master** branch. The changes will be later merged into master.**

Let us know in case of query.
![relax](https://cloud.githubusercontent.com/assets/11537940/21943766/c36ef5ea-d9f8-11e6-895d-786adfb552f3.png)

**Comment by RishabhJain2018** [comment]
@aka-jain Can I work on this?

**Comment by aka-jain** [comment]
@RishabhJain2018 : Do #432 first, it will be helpful to set colors easily here.

**Comment by RishabhJain2018** [comment]
Okk sure.

**Comment by aka-jain** [comment]
@RishabhJain2018 : Now you can work on this.

**Comment by aka-jain** [comment]
Fixed with #437
