### ISSUE TITLE
Update variable.scss file for new UI

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#433]
Change the variables file of scss with new color codes as mentioned below:
1. Gradient : blue= #323d8a, purple= #af34d3
2. Dark blue (Primary color): dark blue = #382373
3. Light gray (secondary colors) : light gray = #9d9d9d
4. dark gray (secondary colors): dark gray = #4d4d4d

**Note: Please make PR to new-ui branch instead of master branch. The changes will be later merged into master.**
Please see attached design for reference.
![relax](https://cloud.githubusercontent.com/assets/11537940/21944741/bbbef318-d9fd-11e6-84fe-b4a59dfa54fa.png)

**Comment by deshraj** [comment]
Fixed in #435. Closing it.
