### ISSUE TITLE
Decorator to check that Challenges are approved by admin or not.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#436]
Add a decorator to check whether a challenge is being `approved_by_admin` or not. Also add the test cases regarding the same.

@deshraj Can I work on this ?

**Comment by deshraj** [comment]
Looks like you have a good insight about the APIs. Thanks for pointing this issue. 

You can surely work on this. Assigning it to you. :-)

**Comment by deshraj** [comment]
We are planning to include it in the near future after Version 1.0

Closing it for now.
