### ISSUE TITLE
Profile Section is not fixed when page is scrolled

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#439]
When we open My Profile link from dashboard & try to scroll the position of profile section isn't fixed.

**Comment by Ram81** [comment]
@aka-jain I will work on this for now.

**Comment by aka-jain** [comment]
@Ram81 : Sure.

**Comment by Ram81** [comment]
@aka-jain  should I make the profile section fixed like dashboard-sidebar when opened or some other change if you want?

**Comment by aka-jain** [comment]
Yes, give it a fixed position for now, and integrate it with inner scroll in Porfile section.

**Comment by Ram81** [comment]
"integrate it with inner scroll in Porfile section." didn't quite get that?

**Comment by aka-jain** [comment]
@Ram81 : Make profile section scrollable in case when screen's height becomes less then the height of the content in Profile Bar.

**Comment by Ram81** [comment]
@aka-jain  should I Integrate inner scroll to profile section in this issue or do you want me to close this issue & wait for next version of the issue?
