### ISSUE TITLE
The evaluation stuck on "Submitted" status

### ISSUE THREAD

**Issue by notoookay** [Cloud-CV/EvalAI#4390]
@gchhablani HI, my evaluation stuck on the status of "Submitted", I see you helped lots of guys, can you help me with that? It's been 2 days after I submitted.

I evaluate on subtask of [KILT](https://eval.ai/web/challenges/challenge-page/689), Open Domain QA - Natural Questions & TriviaQA & HotpotQA.

Team: wenyang

Thank you!

**Comment by caiyuxuan1120** [comment]
Hi, have you solved the problem?

**Comment by notoookay** [comment]
Yes. I remember that I waited for 1 week, and suddenly it executed the running. There's nothing I can do but wait.
