### ISSUE TITLE
Frontend(Auth): Prevent unnecessary api calls 

### ISSUE THREAD

**Issue by spyshiv** [Cloud-CV/EvalAI#442]
- [x] Handle form's required field error on client side
- [x] check length of password (min. 8 characters) field before api call in login, signup etc.
- [x] in signup prevent api call if both passwords aren't same 

Verify form's parameters as much as possible on the client side.  No need to send bad request on server.

**Comment by RishabhJain2018** [comment]
@spyshiv @aka-jain Can I work on this?

**Comment by spyshiv** [comment]
Yeah sure. Go ahead. 
assigning you

**Comment by RishabhJain2018** [comment]
@spyshiv I think we should this?

**Comment by spyshiv** [comment]
Can't close this now. Need to add this feature to reset password and change password too.

**Comment by RishabhJain2018** [comment]
@spyshiv okk. So, can I work on that ?

**Comment by spyshiv** [comment]
As for now i am continuing this. Let me set some features then I will let you when you have to work on this

**Comment by RishabhJain2018** [comment]
okk sure. no problem. :-)

**Comment by spyshiv** [comment]
refer to #483 
Closing this issue
