### ISSUE TITLE
Correct pagination count in team page.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#461]
Initially when we have less than 10 results on existing teams then its page count is shown as 0 but it should be 1.

**Comment by jainarunarunjain** [comment]
@aka-jain Can i work on this

**Comment by aka-jain** [comment]
Refer to #462

**Comment by Ram81** [comment]
@aka-jain  can you assign this one to me?

**Comment by aka-jain** [comment]
Sure, go ahead. Assinging this to you.

**Comment by Ram81** [comment]
any details?

**Comment by aka-jain** [comment]
Check existing teams card in team view, you can see the current page number 0 but it should be 1 if we have atleast 1 team in existing team. It gets 1 when you crossed limit of 10 teams.

**Comment by Ram81** [comment]
Okay will do that & let you know.

**Comment by deshraj** [comment]
Closing it since now it is a part of #488
