### ISSUE TITLE
Pagination not working in teams view.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#462]
Need to solve it for both participant and host team view.

**Comment by parismita** [comment]
shall i try this??

**Comment by aka-jain** [comment]
Sure, in team view there are buttons for next and previous which are not working. Logic is already there. You only have to check and make it correct.

**Comment by aka-jain** [comment]
One update, this is working fine when you reload the page. Basically when we create a team it appends to existing team at run time but it is not affecting pagination login, which works on every page reload. 
Please correct this logic so that without reloading if we exceed limit of 10 then pagination buttons should get activated.

**Comment by parismita** [comment]
@aka-jain vm.existTeam is not updating with click, thts why this is hapenning, nothing is updating in the js file....what is to be done now?

**Comment by aka-jain** [comment]
@parismita : I think it gets updated with success function of create team not with click. Isn't it?

**Comment by parismita** [comment]
@aka-jain but i did console.log() of response....it was not updating...if team is created then it should

**Comment by anweshknayak** [comment]
@aka-jain same as #488 right ?

**Comment by aka-jain** [comment]
@anweshknayak : you can work on this. I think there is some error with this issue. Just try  and let me know if you find any error?

**Comment by aka-jain** [comment]
@parismita : Thanks for the efforts, I'm assigning this to @anweshknayak for now.

**Comment by anweshknayak** [comment]
sure @aka-jain

**Comment by anweshknayak** [comment]
@aka-jain by any chance this maybe cache related issue is it ? and $state.reload() would this even help in the controller. I don't think just asking.

**Comment by aka-jain** [comment]
@anweshknayak  Yes, there is nothing like cache thing issue. And don't use reload too. Let me know where you are exactly stucked?

**Comment by anweshknayak** [comment]
@aka-jain pagination logic is all fine. can you give some hints?

**Comment by parismita** [comment]
@aka-jain the updating is done after sucess function right?....then the sucess function not called after submit...possibly....even when i console logged only once i got 200 response

**Comment by anweshknayak** [comment]
@parismita I think the pagination part is not being updated while creating new team. You pointed out the real issue I guess. Did you try using the loader func of pagination in create new team ?

**Comment by aka-jain** [comment]
Thanks guys for helping. 
I think there is some confusion related to this task. Let us handle this.

**Comment by anweshknayak** [comment]
@aka-jain I have fixed this issue. Shall I put up a PR ?

**Comment by aka-jain** [comment]
Sure @anweshknayak, please go ahead. I will check it :)

**Comment by deshraj** [comment]
@aka-jain @anweshknayak is this issue resolved?

**Comment by anweshknayak** [comment]
fixed via #549

**Comment by aka-jain** [comment]
@deshraj Only challenge participation team pagination is left. Let me complete that too then we can close this issue.

**Comment by deshraj** [comment]
@aka-jain all the paginations done?

**Comment by deshraj** [comment]
@aka-jain @anweshknayak Is this resolved? If yes, please add a reference to the PR.
