### ISSUE TITLE
Team name should be unique

### ISSUE THREAD

**Issue by dexter1691** [Cloud-CV/EvalAI#470]
The participant team name should be unique ( or a primary key)! Right now two different users can create a team with the same name!! 

We need to fix this in both participant teams and challenge teams.

**Comment by Rishav09** [comment]
I want to work on this,could you assign me

**Comment by dexter1691** [comment]
Thanks! This is a super critical issue so expecting rapid response on this. 
You can work on this.

**Comment by deshraj** [comment]
@Rishav09 Let me know if you are stuck somewhere with this issue.

**Comment by deshraj** [comment]
@Rishav09 are you still working on this?

**Comment by Rishav09** [comment]
Yes ,I had some issues with my database.I tried to add primary key to the team-name of <models.py-host> and <models.py-participants> but it is throwing an error <Unable to create or select a team.
{{perm.emailError}}>

**Comment by deshraj** [comment]
you can just make it `unique=True` and remain the `id` attribute as the primary key.

**Comment by deshraj** [comment]
Fixed in #543 and #544
