### ISSUE TITLE
Logout sometime fails due to invalid token

### ISSUE THREAD

**Issue by dexter1691** [Cloud-CV/EvalAI#473]
Likely an issue with the authorization token expiring.

**Comment by RishabhJain2018** [comment]
@dexter1691 @deshraj Can I work on this issue?

**Comment by deshraj** [comment]
@RishabhJain2018, @spyshiv is already working on it. Can you pick any other issue?

**Comment by RishabhJain2018** [comment]
@deshraj yeah sure.

**Comment by spyshiv** [comment]
This issue has been resolved. PR #519. 
@dexter1691 please check once and close this.

**Comment by deshraj** [comment]
Working properly on staging. Closing it.
