### ISSUE TITLE
Adding same participant multiple times sends a 200 response

### ISSUE THREAD

**Issue by dexter1691** [Cloud-CV/EvalAI#474]
Sending same participant multiple times should not send a response. Instead it should send an error response saying that the participant has already been added.

**Comment by TroJan** [comment]
@dexter1691 : inviting a user to a team involves sending an email, this is the reason why it is giving 202 status code (if email is not delivered). But on the db part only one row will be created.

**Comment by dexter1691** [comment]
Interesting. But the status of the participant is set as accepted. It should probably be set as pending, no?

**Comment by TroJan** [comment]
@dexter1691 : yeah , I and @deshraj decided that for v1, status will be `accepted` only.

**Comment by deshraj** [comment]
Closing this since according to version 1, this is handled correctly.
