### ISSUE TITLE
Add functionality of inviting users to Host Team

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#477]
A Host Team member can invite others in the same host team. A similar implementation can be found in the participant team view and the controller will be almost the same as of Participant Team View. 

Let me know if you have doubts/concerns.

**Comment by Ram81** [comment]
@deshraj  can you assign this to me?

**Comment by deshraj** [comment]
Sure.

**Comment by deshraj** [comment]
@Ram81 if you need help, then you can refer to https://github.com/Cloud-CV/EvalAI/pull/351/commits/786edf14afa092341c52ac5b46ff409c978699cd

**Comment by Ram81** [comment]
Okay @deshraj :+1:

**Comment by Ram81** [comment]
@deshraj  is the api for inviting user to host team ready?

**Comment by deshraj** [comment]
@Ram81 Sorry for replying late. I missed this thread somehow. Yes, the API is ready. Please check `/docs` again.

**Comment by Ram81** [comment]
@deshraj I've already added the URL for the API you are mentioning, in PR #512.

**Comment by deshraj** [comment]
@Ram81 Yeah there is no need to change the URL. Again, sorry I missed this thread. :) Please ping me on gitter if I miss something.

**Comment by Ram81** [comment]
@deshraj You can close this one too.
