### ISSUE TITLE
Add functionality to remove yourself from the Host Team

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#478]
The view and controller will be almost similar to that of Participant Team View. 
Please see #348 for code.

**Comment by anweshknayak** [comment]
@deshraj as Im not working on any other issue right now. Can I pick this up ?

**Comment by deshraj** [comment]
Sure. :-)

**Comment by anweshknayak** [comment]
fixed by #574 ?

**Comment by deshraj** [comment]
@anweshknayak I don't think so. Since you are already working on other issue, so I am assigning @daas-ankur-shukla on this.

**Comment by anweshknayak** [comment]
@deshraj no actually there is a confusion. I already had a PR ready. But close that since some PR has already been merged.

**Comment by deshraj** [comment]
@anweshknayak I get what you are saying. But looks like there is some issue at the backend. That's why @aka-jain removed the API support from the frontend. Can you please cross check the API on your own machine?

**Comment by daas-ankur-shukla** [comment]
@deshraj i have got the environment ready on my machine but i am not able to recreate the issue. i am getting the following error while signing up

OPTIONS http://localhost:8000/api/auth/registration/ net::ERR_CONNECTION_REFUSED
(anonymous) @ vendor.js:112
p @ vendor.js:107
(anonymous) @ vendor.js:105
(anonymous) @ vendor.js:138
$eval @ vendor.js:152
$digest @ vendor.js:149
$apply @ vendor.js:153
(anonymous) @ vendor.js:287
dispatch @ vendor.js:3
q.handle @ vendor.js:3

Some guidance on recreating the issue will be helpful

**Comment by daas-ankur-shukla** [comment]
sorry for the trivia. got it sorted

**Comment by anweshknayak** [comment]
@aka-jain close this fixed by #574

**Comment by daas-ankur-shukla** [comment]
so is it closed or still open?

**Comment by aka-jain** [comment]
No @anweshknayak, this hasn't solved yet. Code is there for client side but there is some error from backened side. Are you working on any other issue?

**Comment by anweshknayak** [comment]
@aka-jain related to #607 ? @gauthamzz is working on it.

**Comment by aka-jain** [comment]
Yep, let solve him first. Then we will integrate the Client side code.

**Comment by aka-jain** [comment]
@anweshknayak Are you working on any issue?

**Comment by anweshknayak** [comment]
@aka-jain No. Are there any new issues to work ?

**Comment by aka-jain** [comment]
What about #575 ?

**Comment by aka-jain** [comment]
@daas-ankur-shukla Please check other issue to work on :)

**Comment by daas-ankur-shukla** [comment]
@aka-jain sure, but i am curious, weather #478 has been solved or not? and if yes, how? :)

**Comment by anweshknayak** [comment]
@aka-jain @deshraj close this ?

**Comment by deshraj** [comment]
@anweshknayak Sorry, I missed this one. closing it now.
