### ISSUE TITLE
Add number of concurrent request metric in metrics middleware

### ISSUE THREAD

**Issue by dexter1691** [Cloud-CV/EvalAI#480]
We will need to use "Gauge" metric type: http://docs.datadoghq.com/guides/dogstatsd/#metrics

This will require increasing a shared counter "atomically". Check this for reference: http://stackoverflow.com/questions/2080660/python-multiprocessing-and-a-shared-counter

**Comment by RishabhJain2018** [comment]
@dexter1691 @deshraj can I work on this issue?

**Comment by dexter1691** [comment]
@RishabhJain2018 : Sorry, but this will require access to Datadog credentials which only the core team members have for now. Please choose a different issue.

**Comment by RishabhJain2018** [comment]
@dexter1691 ok sure.

**Comment by TroJan** [comment]
@dexter1691 @deshraj : is this done ?

**Comment by deshraj** [comment]
No, not yet. But this is not the priority as of now.

**Comment by deshraj** [comment]
Closing this since not a priority as of now.
