### ISSUE TITLE
Create notification system for EvalAI

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#482]
Notificatins for all warnings, alert and messages.

**Comment by parismita** [comment]
@aka-jain shall i try this?......notification as pop up or just error message is to be shown?

**Comment by aka-jain** [comment]
@parismita This one is critical task, let us make the global module for the notification first then will break this system into smaller chunks. Then you can work on it.

**Comment by parismita** [comment]
yooo....pl notify me when done

**Comment by spyshiv** [comment]
@aka-jain : What is the current status of this issue?
Are you using any kind of lib. for showing notification?? or will it be done from scratch?

**Comment by aka-jain** [comment]
We are going to build this from Scratch. Just make a directive for this which take messages as a value and return notification. Thoughts?
Any other suggestions from your side?

**Comment by spyshiv** [comment]
@aka-jain: Doing from scratch will be very comfortable for everyone.  :+1: 
and I think directive is the best solution. I am creating one for this purpose.

**Comment by aka-jain** [comment]
Awesome @spyshiv  :)

**Comment by deshraj** [comment]
@spyshiv lets get this done ASAP since most of the features are dependent on this.

**Comment by spyshiv** [comment]
Work is in progress...will do it ASAP.

**Comment by deshraj** [comment]
@spyshiv can you please complete is ASAP since we are really close to the deadline. :)

**Comment by spyshiv** [comment]
@deshraj : Sorry for the delay. I was busy in other works.
It's almost done.(branch `ui_notification`) 
Just brief a list of events when these notification will be shown.

**Comment by aka-jain** [comment]
Closing this issue, fixed with #684
