### ISSUE TITLE
Add a check in Endpoint to check if challenge is active or not

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#485]
See this endpoint: https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/views.py#L197
We need to add a check that is the challenge is active or not otherwise return a 404 response.

**Comment by RishabhJain2018** [comment]
@deshraj Can I work on this?

**Comment by deshraj** [comment]
Sure.

**Comment by deshraj** [comment]
Fixed in #486
