### ISSUE TITLE
Convert start_date and end_date of Challenge model to human readable format

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#491]

**Comment by manu-chroma** [comment]
hey @virajprabhu, are you working on this issue ?
if not, I'd like to take this one up. :smile:

**Comment by virajprabhu** [comment]
@manu-chroma I'm nearly done with this. Can you pick up another one?

**Comment by manu-chroma** [comment]
sure thanks!

**Comment by deshraj** [comment]
Fixed in #499
