### ISSUE TITLE
Add is_active field to ChallengePhase serializer

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#494]
Please see #484 for reference.

**Comment by RishabhJain2018** [comment]
@deshraj Can I work on this issue?

**Comment by deshraj** [comment]
Sure.

**Comment by RishabhJain2018** [comment]
@deshraj I think we should also check [here](https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/views.py#L247) , if the challenge phase `is_active` or not ?

**Comment by deshraj** [comment]
No, I don't think so. `is_active` in ChallengePhaseSerializer is just to give data to the client side so that it becomes easy to figure out if the challenge phase is active or not.

**Comment by RishabhJain2018** [comment]
@deshraj I think we should also check [here](https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/views.py#L271) , if the challenge phase `is_active` or not ?

**Comment by RishabhJain2018** [comment]
@deshraj Please help with [this](https://travis-ci.org/Cloud-CV/EvalAI/builds/192783985#L953) error in tests.

**Comment by deshraj** [comment]
It looks like your forgot to set the value of start_date or end_date.

**Comment by RishabhJain2018** [comment]
@deshraj  The value of `start_date` and `end_date` has already been set in the base class. Please refer to this [link](https://github.com/Cloud-CV/EvalAI/blob/master/tests/unit/challenges/test_views.py#L850).

**Comment by deshraj** [comment]
Fixed in #502
