### ISSUE TITLE
Problem with Auth messages

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#501]
Clicking on login button without filling any field is not showing any messages. 
I think a message like "All fields are required" should also be shown there.

**Comment by aka-jain** [comment]
@spyshiv @RishabhJain2018 : Can you look into this?

**Comment by RishabhJain2018** [comment]
@aka-jain yeah sure.

**Comment by aka-jain** [comment]
@RishabhJain2018 : assigning this to you.

**Comment by deshraj** [comment]
Fixed in #510
