### ISSUE TITLE
Change Job Submission API

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#509]
Currently while posting the data to create a submission, the `challenge_id` and `challenge_phase_id` is in URL but we want to make it part of the request body instead of being in the URL.

**Comment by RishabhJain2018** [comment]
@deshraj Can I work on this issue?

**Comment by deshraj** [comment]
So Quick! Assigning it to you. :-)

**Comment by deshraj** [comment]
@RishabhJain2018 please don't work on this. We need to do some more brainstorming.

**Comment by RishabhJain2018** [comment]
@deshraj okk sure.

**Comment by deshraj** [comment]
It comes out that we have to make other endpoints for getting details of Job Submissions. So, closing it for now.
