### ISSUE TITLE
Add HostTeamDetail serializer to show host details

### ISSUE THREAD

**Issue by jayantsa** [Cloud-CV/EvalAI#515]
@deshraj Can I work on this?

**Comment by deshraj** [comment]
Sure go ahead. Sounds like a good initiative. I was going to open an issue for the same. :-)

**Comment by deshraj** [comment]
Fixed in #518

**Comment by jayantsa** [comment]
@deshraj  Can you reopen this issue as I think we should also change the serializer in view that is returning the response in **hosts/challenge_host_team** so that we dont have to make api calls again and again as **hosts/challenge_host_team/<pk>** to show the details of host team on client side. Just have to change the Serializer from **ChallengeHostTeamSerializer** to **HostTeamDetailSerializer** in 
**challenge_host_team_list** view and same in participant app

**Comment by deshraj** [comment]
Yeah, Agree. Can you please open two different issues for hosts and participants app and make sure when you open a PR then these are two different Pull Requests?

**Comment by deshraj** [comment]
Closing it again since this is going to be a new issue now.

**Comment by jayantsa** [comment]
@deshraj ok will do that
