### ISSUE TITLE
Change name of memcached location environment Variable

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#522]

**Comment by deshraj** [comment]
We want to change the name of the environment variable from `LOCATION` to `MEMCACHED_LOCATION`

**Comment by RishabhJain2018** [comment]
@deshraj Can I work on this issue?

**Comment by deshraj** [comment]
Sure, if you want to work on this, then please do it quickly. You need to make changes in `settings/common.py` and `settings/prod.py`

**Comment by deshraj** [comment]
Fixed in #523
