### ISSUE TITLE
Improve gulp dev task.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#536]
Currently when we run gulp dev then it compresses all the files, but while using dev server it shouldn't do that. Have to write unique tasks for dev so that no compression occurs.
Task will be very simple, just redirect all the files from src to dist without any merging and compression.

@spyshiv thoughts?

**Comment by spyshiv** [comment]
That's great idea. It'll save many seconds on development side. And then we can also use livereload (browser refresh) feature of `gulp-connect` on change in static files. 
:+1:

**Comment by aka-jain** [comment]
Yayy! Way to go :)

**Comment by deshraj** [comment]
@spyshiv @aka-jain is this one fixed?

**Comment by spyshiv** [comment]
@deshraj : This is done. Closing this
