### ISSUE TITLE
Frontend: Add validation before sending invite to other team members

### ISSUE THREAD

**Issue by spyshiv** [Cloud-CV/EvalAI#552]
- [ ] Handle errors (email required & email valid ) with ng-messages as it is done in auth pages.
- [x] Show notification on invitation success after closing the modal of email invite (depend on issue #482 )

**Comment by anweshknayak** [comment]
@spyshiv shall I try the first one ? I just made a PR which used ng-messages.

**Comment by spyshiv** [comment]
I have reviewed your PR #593 . First complete the changes then ask for this.
Till then this is issue is open for all.

**Comment by anweshknayak** [comment]
@spyshiv this is to be done for verify-email view right ?

**Comment by RishabhJain2018** [comment]
@spyshiv  @aka-jain  Can I work on this?

**Comment by spyshiv** [comment]
sure @RishabhJain2018, Assigning it to you.

**Comment by spyshiv** [comment]
@anweshknayak : it is regarding email invitation on dashboard.

**Comment by deshraj** [comment]
@RishabhJain2018 any update on this. This one is easier and should have been fixed by now.

**Comment by RishabhJain2018** [comment]
@deshraj Actually last week, I was busy with some of my college work.I am really sorry for the delay. I will fix this asap.

**Comment by spyshiv** [comment]
@RishabhJain2018 : What is the current status regarding this issue?

**Comment by RishabhJain2018** [comment]
@spyshiv As discussed with you, I will fix this asap.

**Comment by anweshknayak** [comment]
@spyshiv @RishabhJain2018 can I try ?

**Comment by deshraj** [comment]
Sure @anweshknayak.

**Comment by anweshknayak** [comment]
@spyshiv let me know when the notification thing is ready :)

**Comment by spyshiv** [comment]
@anweshknayak : Have you done first task which is not dependent on notification things ?
and Notification feature has been added in PR #684. 
You can start working on first task. I will let you know when the PR #684 will be merged

**Comment by anweshknayak** [comment]
sure @spyshiv. And yes I will complete the first task.

**Comment by spyshiv** [comment]
@anweshknayak: I have already completed 2nd task. 3rd task is not required now so i have removed that. So finally you have  to do only first task. Ask me for code review when you are done

**Comment by anweshknayak** [comment]
@spyshiv need some help. How do I get to this view? I need to test.

**Comment by spyshiv** [comment]
@anweshknayak: Sorry I was busy.
![screenshot from 2017-02-24 14 10 29](https://cloud.githubusercontent.com/assets/7015220/23296437/0f55ce26-fa9b-11e6-8019-a3c52f064622.png)

The issue is related to make this email input required. Let me know if you can/can't get this view.

**Comment by anweshknayak** [comment]
@spyshiv do I need to create separate template for mdDialog to integrate ng-messages with it ?

**Comment by aka-jain** [comment]
@anweshknayak Are you working on any other issue too?

**Comment by spyshiv** [comment]
@anweshknayak : what is the status of this issue. If you are too busy in doing other issues then let me know so that I can assign this to someone else

**Comment by anweshknayak** [comment]
@spyshiv I won't be able to work on issues for a few days. Please assign to someone else. :)

**Comment by TroJan** [comment]
@RishabhJain2018 : can you take this up ?

**Comment by RishabhJain2018** [comment]
@TroJan Yeah sure. Currently I am on #850 . I will take this up asap.

**Comment by Obtin** [comment]
@RishabhJain2018 @aka-jain @deshraj Can I work on this. Thank you.

**Comment by deshraj** [comment]
I think you have few issues on your plate. You can work on this once you complete the other issues assigned to you. :)

**Comment by Obtin** [comment]
@deshraj, I am done with my other issues. I have started working on this too. Thank you.

**Comment by Obtin** [comment]
@deshraj@aka-jain can we also add the check for entering correct email-address before it checks for the existence of a user with this username?
![email](https://user-images.githubusercontent.com/25207205/35477312-242ffb64-03e6-11e8-940c-89823c907004.png). In order to prevent such mistakes.

**Comment by deshraj** [comment]
FYI: This issue is still open. Please feel free to pick it up. Also,  tagged it as a good first issue. :)

**Comment by gautamjajoo** [comment]
@deshraj Can I work on this issue?

**Comment by deshraj** [comment]
Sure, go ahead.

**Comment by gautamjajoo** [comment]
@deshraj Hey! I have done with email required. How should I proceed for checking if email is valid?

**Comment by gautamjajoo** [comment]
@deshraj I think you missed it.
