### ISSUE TITLE
Navigation Link Changes

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#558]
We need to do following changes in the client side: 

- [ ] Change password on Sidebar of Dashboard

- [ ] Add "Participate in Challenges" button next to the "Host Competition" button on main page

- [ ] Replace "Host Competition" with "Host Challenge" on Home Page

- [ ] Show © CloudCV 2016-2017  on footer

**Comment by gauthamzz** [comment]
i would like to work on this

**Comment by deshraj** [comment]
Sure @gauthamzz :)

**Comment by aka-jain** [comment]
@gauthamzz sure, assigning it you.

**Comment by deshraj** [comment]
@gauthamzz I think I cannot assign this issue to you since you haven't accepted the invite for a Collaborator to EvalAI.

**Comment by deshraj** [comment]
Let me know when you have accepted the invite.

**Comment by gauthamzz** [comment]
i haven't gotten an invitation yet :confused:

**Comment by gauthamzz** [comment]
@deshraj do you want update password like this ?
![screenshot from 2017-01-27 04-24-06](https://cloud.githubusercontent.com/assets/12110844/22353865/8eea4f72-e448-11e6-8bf0-48922cef9f05.png)
