### ISSUE TITLE
Show a default logo when there is no logo for a challenge

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#559]
When there is no logo for a particular challenge, then we need to show a default logo of EvalAI there. 
@aka-jain can you give a sample logo that needs to be shown if the original logo is not ready yet?

**Comment by Ram81** [comment]
@deshraj as I am done with my previous work can I do this too ?

**Comment by gauthamzz** [comment]
I would like to try this

**Comment by Ram81** [comment]
@deshraj anyone doing this issue?

**Comment by deshraj** [comment]
Sure, go ahead. You can use the CloudCV logo to display when there in no logo for a particular challenge.

**Comment by Ram81** [comment]
@deshraj  you can close this one fixed in #611

**Comment by aka-jain** [comment]
Fixed with #611
