### ISSUE TITLE
Show a modal on clicking "Host Challenge" on the main page

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#560]
On the home page, when user clicks on "Host Challenge", then we need to show a modal saying the following content:

`Thanks for your interest in hosting a Challenge on EvalAI. We will release this feature soon!`

**Comment by Ram81** [comment]
@deshraj  can you assign this to me?

**Comment by anweshknayak** [comment]
https://www.bennadel.com/blog/2806-creating-a-simple-modal-system-in-angularjs.htm

**Comment by aka-jain** [comment]
@anweshknayak : Modal is already included in our Project. Please check invite team member feature, you can get an idea of it's working. Also for reference check angular material modals.
Thanks.

**Comment by aka-jain** [comment]
BTW who is working on this issue?

**Comment by Ram81** [comment]
@aka-jain  I will do this one

**Comment by anweshknayak** [comment]
@aka-jain I already have some pending issue to work on. I will finish that before I pick up anything new.

**Comment by aka-jain** [comment]
Sure @Ram81 Please do it :)

**Comment by aka-jain** [comment]
Merged with #573
