### ISSUE TITLE
Create an API Endpoint for Submitting a Contact Message 

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#562]
Dependent on #561 

Details:

Method: `POST`
Data to post: `name`, `email`, `message`
URL: `/api/web/contact`
Returns 201 HTTP Response

**Comment by RishabhJain2018** [comment]
@deshraj Can I work on this?

**Comment by deshraj** [comment]
Sure.

**Comment by RishabhJain2018** [comment]
@deshraj What message it should return on successful submission of form ? I have a suggestion for this like `Your message has been successfully recorded. We will contact you shortly.`

**Comment by RishabhJain2018** [comment]
@deshraj I think we should use `AllowAny` permission class for the contact view.

**Comment by deshraj** [comment]
Yeah Sure. All sounds good to me.

**Comment by RishabhJain2018** [comment]
@deshraj I think we should close this?

**Comment by RishabhJain2018** [comment]
@deshraj I think we should close this?
