### ISSUE TITLE
Create a View for Contact Us Page

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#563]
Dependent on #561 #562 

The view should enable the users to submit their queries with the following field names: 

- Name
- Email Address
- Message

**Comment by parismita** [comment]
shall i try this too?? we have to use serializer for submiting the form?

**Comment by deshraj** [comment]
Sure @parismita. Yup, you have to create a new serializer. :-)

**Comment by parismita** [comment]
completed with #562

**Comment by RishabhJain2018** [comment]
@deshraj I think we should close this?

**Comment by deshraj** [comment]
View on the client side is still not done for this particular issue. Reopening it now.

**Comment by Ram81** [comment]
@deshraj can you assign this to me?

**Comment by deshraj** [comment]
Sure.

**Comment by Ram81** [comment]
any details for view?

**Comment by deshraj** [comment]
Please see the description of this issue. :)

**Comment by Ram81** [comment]
@deshraj  I meant about the design of the view. should I design temporary one for now or is there some design for it?

**Comment by deshraj** [comment]
@Ram81 you are welcome to create the view that matches with the current design that we are following. We would be happy to see your creativity with the existing design. :)

**Comment by Ram81** [comment]
@deshraj @aka-jain  you can close this. Fixed in #741

**Comment by spyshiv** [comment]
Closing this
