### ISSUE TITLE
Create a route and View for "Our Team" Page

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#565]
@aka-jain Can you please take lead and describe the details for this issue?

**Comment by gauthamzz** [comment]
Could I try this

**Comment by deshraj** [comment]
Sure

**Comment by gauthamzz** [comment]
Details?

**Comment by deshraj** [comment]
@aka-jain can you explain what all fields should we show on the page and how exactly?

**Comment by aka-jain** [comment]
@gauthamzz : For now just make a route which directs to team page of EvalAI. Give it a name /team and make a  new html file for it. Will share the design with you soon.

**Comment by Ram81** [comment]
@aka-jain  sorry for this I mistakenly named commit the issue of this number!

**Comment by gauthamzz** [comment]
@aka-jain i did as much as you asked , could you share the design or will that be another issue ?

**Comment by aka-jain** [comment]
Done with #601
