### ISSUE TITLE
Create route and view for "Terms and Conditions" Page

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#566]
Add a dummy content for now that we can modify later.

**Comment by Ram81** [comment]
@deshraj : can you assign this to me?

**Comment by deshraj** [comment]
Sure

**Comment by Ram81** [comment]
@deshraj any details?

**Comment by deshraj** [comment]
@Ram81 You can put dummy details in the Page and we will modify it later soon.

**Comment by aka-jain** [comment]
Done with #597. Closing it.
