### ISSUE TITLE
Create a view for "Join our Team" Page

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#567]
In this view, the user will see the details about the project and links to our Github Page, Gitter Link and Mailing list link so that if he is interested in contributing, then he can navigate to these pages from EvalAI. 

Let me know if you need more details. :-)

**Comment by gauthamzz** [comment]
i would like to work on this

**Comment by deshraj** [comment]
Sure, go ahead.

**Comment by aka-jain** [comment]
@gauthamzz this is a sepearate issue for our team page. Will share the details soon with you. Till then you can work on other issues :)

**Comment by gauthamzz** [comment]
@aka-jain what about this ?

**Comment by aka-jain** [comment]
Assigning this to me.

**Comment by jainarunarunjain** [comment]
@deshraj @aka-jain Is anyone working on this or shall i try.

**Comment by aka-jain** [comment]
@jainarunarunjain you can take this up. Will share the details soon with you.

**Comment by jainarunarunjain** [comment]
@aka-jain Sure.

**Comment by jainarunarunjain** [comment]
@aka-jain done with route

**Comment by aka-jain** [comment]
Thanks @jainarunarunjain . Fixed with #739.
