### ISSUE TITLE
Show Github Stars and Forks on the footer

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#568]
We need to show the number of forks and stars on EvalAI on the footer. 
Please contact @aka-jain for design details. 

Please see https://developer.github.com/v3/repos/#get for reference.

**Comment by missionary0** [comment]
I would like to work on this

**Comment by deshraj** [comment]
Sure. Let me know if you need some help. :-)

**Comment by missionary0** [comment]
Where can we chat privately?

**Comment by deshraj** [comment]
@missionary0 It would be great if we can chat publicly on Gitter https://gitter.im/Cloud-CV/EvalAI

**Comment by aka-jain** [comment]
@missionary0 Any update regarding this issue?

**Comment by itaditya** [comment]
@aka-jain if @missionary0 is not doing it , am I allowed to work on this issue ?

**Comment by aka-jain** [comment]
I don't think that @missionary0  is active, so assigning this to you @itaditya. Please go ahead.

**Comment by itaditya** [comment]
Ok Sir

**Comment by aka-jain** [comment]
@itaditya: dude don't call me sir 😛 😃

**Comment by itaditya** [comment]
Ok :+1:

**Comment by itaditya** [comment]
As we have to get the data from the github api , I need a controller for making that request, but currently , the footer.html is loaded directly via ng-include , should I make a directive instead and attach a controller there ?
