### ISSUE TITLE
Create a dropdown to user name on Landing Page.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#571]
When user is logged in then show a down arrow button aside to user's name clicking on which display dropdown having 3 options:
1. Change Password (redirect to change password route)
2. Update Profile (redirect to update profile route)
3. Logout

Let us know in case of any query.

**Comment by deshraj** [comment]
@aka-jain I think I have mentioned these changes in #558. May be you can just go ahead and make changes in that issue. Feel free to close this. :-)

**Comment by aka-jain** [comment]
@deshraj I think sepearate issue will be good for this feature as it is a combination of 3 features. Can we edit #558 so that it doesn't contain any task related to this issue.

**Comment by deshraj** [comment]
Sure. Sounds good to me. Please feel free to edit that issue.

**Comment by RishabhJain2018** [comment]
@aka-jain @deshraj Can I work on this?

**Comment by deshraj** [comment]
Sure

**Comment by deshraj** [comment]
@RishabhJain2018 any updates on this?

**Comment by RishabhJain2018** [comment]
@deshraj Yeah, the PR is almost ready. I will push it asap.

**Comment by RishabhJain2018** [comment]
@aka-jain @deshraj there is no route for update profile in `route.js`. I think we will need it in future. Should I open a issue for the same, what are your views about it?
