### ISSUE TITLE
Remove ContactUs django App

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#579]
We don't want ContactUs App for storing the Contact. Just use the `web` django app. This will revert the #569. 

#569 was merged by mistake.

**Comment by manu-chroma** [comment]
hey, I'd like to work on this one for my first PR on EvalAI

**Comment by deshraj** [comment]
Hey Manu, I think Rishabh has already solved this issue. You can work on any other unassigned issue.

**Comment by RishabhJain2018** [comment]
@deshraj I think we should close this?

**Comment by deshraj** [comment]
Fixed in #578
