### ISSUE TITLE
Frontend(change password): Integrate ng-messages in change password view

### ISSUE THREAD

**Issue by spyshiv** [Cloud-CV/EvalAI#582]
It should be done as it is done in auth views(login, signup, reset password).

**Comment by anweshknayak** [comment]
@spyshiv can I do this ?

**Comment by spyshiv** [comment]
yes. `ng-message="required"` should be here since all three fields(old password, new_password1, new password2) are required. 

content to write in required field respectively.
`"Old password is required".`
`"New password is required."`
`"Confirm new password is required."`

And don't forget to use password comparison feature as it is already done in `signup` and `reset password confirm` .

**Comment by spyshiv** [comment]
@anweshknayak : Can't assign you right now since other issues are already assigned to you. please complete those issue first.

**Comment by anweshknayak** [comment]
I can't . Im getting blank page after running gulp dep:runserver .

**Comment by deshraj** [comment]
@anweshknayak can you paste the browser's console error?

**Comment by anweshknayak** [comment]
http://pastebin.com/vMd9PfC7

**Comment by deshraj** [comment]
Can you please share the screenshot of browser's console?

**Comment by anweshknayak** [comment]
![screenshot from 2017-01-23 22 14 39](https://cloud.githubusercontent.com/assets/8139783/22213262/7cb18082-e1b9-11e6-98a3-198bf3f0f57c.png)

**Comment by deshraj** [comment]
I can see that the url is `http://127.0.0.1:8000` which is the backend server. FYI, I didn't get time to fix #375. Will do that today. 

Is this error is blocking you in some way?

**Comment by spyshiv** [comment]
@deshraj : that should not block the frontend serve and rest apis. Same issue was with me but things were working fine.
@anweshknayak : you have to open `127.0.0.1:8888`. (remember port 8888 for frontend not 8000)

**Comment by anweshknayak** [comment]
@deshraj @spyshiv actually both for the frontend(127.0.0.1:8888) and 127.0.0.1:8000 I am getting blank pages. Sorry for the confusion

**Comment by In-vincible** [comment]
@spyshiv @deshraj @anweshknayak is this issue open to work on?

**Comment by anweshknayak** [comment]
@In-vincible please choose some other issue. I have already put up a PR. as you see above.
