### ISSUE TITLE
Add Inertia Scroll for rich UX

### ISSUE THREAD

**Issue by itaditya** [Cloud-CV/EvalAI#600]
@aka-jain , I think inertia scrolling [Demo](https://www.yourwebtech.info/demo/mobile-like-smooth-scrolling-for-website-using-jquery/) , can be a good enhancement for the project's UX. Can I make a contribution regarding this

**Comment by aka-jain** [comment]
@itaditya Thanks for the suggestion, but soon we will start working on the New UI then we can implement inertia scroll but for now it isn't a great thing to add to project.

**Comment by itaditya** [comment]
Ok Sir
