### ISSUE TITLE
Update readme for proxy setup

### ISSUE THREAD

**Issue by gauthamzz** [Cloud-CV/EvalAI#602]
for ones under proxy, we need to set up
1.  npm proxy so that npm install does't break [link](http://stackoverflow.com/questions/7559648/is-there-a-way-to-make-npm-install-the-command-to-work-behind-proxy/18346387#18346387).
2. for bower install we need to create .bowerrc with proxy inside it . This file should be added in .gitignore as well

**Comment by deshraj** [comment]
Sorry @gauthamzz, we don't want to add a section for proxy setup in README. It would be good if you can add details here in the issue and then if anyone faces the same issue then he/she can see this issue. Closing it for now.
