### ISSUE TITLE
Cannot remove teams from existing host team view

### ISSUE THREAD

**Issue by anweshknayak** [Cloud-CV/EvalAI#607]

**Comment by aka-jain** [comment]
Thanks @anweshknayak for pointing this out, actually we have some API problem. @deshraj please take care of it :P

**Comment by deshraj** [comment]
Sure. I am working on another issue as of now so might take time to fix this. Anyone wants to take this issue, then go ahead. :-)

**Comment by gauthamzz** [comment]
@deshraj could i try ?

**Comment by deshraj** [comment]
Sure.

**Comment by aka-jain** [comment]
@gauthamzz Progress?

**Comment by gauthamzz** [comment]
@aka-jain i'm not sure where the bug is . still finding out . i dont think its frontend . I need some more time

**Comment by aka-jain** [comment]
Yes @gauthamzz it is not from frontendside, actually API is not working properly. Please check accordingly.

**Comment by yadavankit** [comment]
#633 @deshraj please review this PR for this issue too

**Comment by yadavankit** [comment]
@deshraj the code already works fine as it removes the user from `ChallengeHost` but the team shows up because the User is still the owner of the team. One more thing, in Host Challenge page, user should be able to view all teams he is a part of (as of now, one can only view teams created by him). What do you say?

**Comment by deshraj** [comment]
> @deshraj the code already works fine as it removes the user from ChallengeHost but the team shows up because the User is still the owner of the team.
@yadavankit I think you should add a check where you check if the user is the owner of the Team and if he is the part of the team then delete the whole team since he is the owner of the team. 

> One more thing, in Host Challenge page, user should be able to view all teams he is a part of (as of now, one can only view teams created by him). What do you say?
Good catch. Can you please open a issue for the same?

**Comment by yadavankit** [comment]
@deshraj yeah sure 👍

**Comment by deshraj** [comment]
@yadavankit are you working on this or @gauthamzz is working?

**Comment by yadavankit** [comment]
@deshraj I did not start on this issue as it is assigned to @gauthamzz. Should I?

**Comment by gauthamzz** [comment]
@deshraj told me someone else is working on this , so i stopped working on this

**Comment by anweshknayak** [comment]
I just tested this. It is working fine. Still anyone can confirm tho

**Comment by gauthamzz** [comment]
yeah its working fine now

**Comment by yadavankit** [comment]
@deshraj @anweshknayak if fine, then lets close it for now?

**Comment by deshraj** [comment]
Thanks everyone for confirming. :)
