### ISSUE TITLE
"undefined" shown with error message displayed on password reset view

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#613]
Please see the error message in the screenshot. The response from the backend is correct. 
<img width="1438" alt="screen shot 2017-01-31 at 2 01 16 am" src="https://cloud.githubusercontent.com/assets/2945708/22455255/4b44b1ea-e759-11e6-9a18-fcde3e5ffbd3.png">

**Comment by anweshknayak** [comment]
just curious. how to get to this view ?

**Comment by deshraj** [comment]
If you are on dev environment,
1. then go to forgot password link
2. enter the email address associated to your account
3. See the email content on your terminal
4. Copy the link and paste it on browser
5. Change the port in the link from `8000` -> `8888` 
6. Type the new password very similar to the email address and then submit

This way, you can reproduce the error.

**Comment by anweshknayak** [comment]
@deshraj can I try ?

**Comment by deshraj** [comment]
Sure.

**Comment by daas-ankur-shukla** [comment]
hi @deshraj can i take up this issue?

**Comment by deshraj** [comment]
@daas-ankur-shukla, Sorry @anweshknayak is already working on this issue. Can you please pick up any unassigned issue :)

**Comment by aka-jain** [comment]
@anweshknayak progress?

**Comment by anweshknayak** [comment]
@aka-jain I have one doubt regarding this. What is to be placed there in place of undefined? EMAIL?

**Comment by aka-jain** [comment]
Is that message coming from controller?

**Comment by anweshknayak** [comment]
@aka-jain Yes.

**Comment by aka-jain** [comment]
@anweshknayak Just remove it. No need to replace it with some other text.
