### ISSUE TITLE
Fix toggle problem between Login and Forgot Account.

### ISSUE THREAD

**Issue by anweshknayak** [Cloud-CV/EvalAI#616]
![errorpic](https://cloud.githubusercontent.com/assets/8139783/22465091/065f8d0c-e7e0-11e6-8f88-301ebb0ec456.png)

Steps to reproduce:

1. Go to Login Page
2. Enter some details 
3. Click on the Forgotten account button below the form
4. Enter details in the Forgotten account page
5. Switch back to the login page

You will get to see that the username and password field label should go up as I switch but it does not behave like that. 

Refer : https://github.com/Cloud-CV/EvalAI/issues/260

**Comment by aka-jain** [comment]
Thanks @anweshknayak for pointing this out. 

Anyone interested to solve this?

**Comment by Ram81** [comment]
@aka-jain  can you assign this to me?

**Comment by deshraj** [comment]
Sure.

**Comment by anweshknayak** [comment]
@Ram81 you on this ?

**Comment by aka-jain** [comment]
@anweshknayak When you titled an issue then don't write Frontend to the heading. Just add label tag of frontend or backened to the particular issue.

**Comment by anweshknayak** [comment]
@aka-jain I don't think I got privileges to add labels yet.

**Comment by Ram81** [comment]
Sorry for the delay was busy with some college stuff.

**Comment by Ram81** [comment]
@deshraj please review!

**Comment by deshraj** [comment]
@Ram81 Any updates on this?

**Comment by Ram81** [comment]
@deshraj  this one is done you can close this.

**Comment by deshraj** [comment]
@Ram81 Thanks for informing. :)
