### ISSUE TITLE
Auth: Need email verification mail resend feature.

### ISSUE THREAD

**Issue by spyshiv** [Cloud-CV/EvalAI#630]
Why??
Suppose user loses verification email without verifying the link. Then neither user will verify his account nor create a new account with same email address. 

# Requirements
## Backend 
- [ ] API endpoint to resend verification email (User token based)
@deshraj : Please take care of it.

## Frontend 
I think there should be button/Link ("Resend Verification Email" ) inside rounded (dark red) portion of following screenshot. 
![screenshot from 2017-02-05 11 39 21](https://cloud.githubusercontent.com/assets/7015220/22624135/31d25094-eb98-11e6-882d-26bf2c090d00.png)

@aka-jain : Need your thoughts about it.

**Comment by gauthamzz** [comment]
can i try this ?

**Comment by yadavankit** [comment]
@gauthamzz are you on #607 ?

**Comment by utkbansal** [comment]
I'd like to work on this.

**Comment by deshraj** [comment]
Sure, @utkbansal. You can work on this issue. :)

**Comment by deshraj** [comment]
@utkbansal I am assuming you are still working on this. Please let us know if you are stuck somewhere. We would be happy to unblock you. :)

**Comment by daas-ankur-shukla** [comment]
@deshraj can i work on this?

**Comment by Curious72** [comment]
@spyshiv is this issue unassigned? If so , can i work on this one?

**Comment by deshraj** [comment]
@Curious72 since @jiayibupt showed interest first, so I would like to assign this issue to him. Please look for other available issues.

**Comment by Curious72** [comment]
@deshraj  Sure !

**Comment by spyshiv** [comment]
@jiayibupt : Are you working on this? Please let me know so that i can assign this to you.

**Comment by divyanshu1302** [comment]
Can I try for this issue, if it is free now ?

**Comment by aka-jain** [comment]
@RishabhJain2018 have a look at this issue. Let me know whenever you get started working on it.

**Comment by RishabhJain2018** [comment]
@aka-jain yeah sure. Currently, I am working on the feature of creating challenge using zip. I will put it in my to do list.

**Comment by isht3** [comment]
@RishabhJain2018 Can I take over?

**Comment by RishabhJain2018** [comment]
Yes sure! Assigning this to you!

**Comment by isht3** [comment]
Hi, I looked into this, and we can use two methods. 

- Setting `ACCOUNT_EMAIL_VERIFICATION = 'mandatory'` will send a Email every time they log in and if the user is not verified, where we can set a cool-down time for sending email and can be done in two lines of code. The downside to this is that, the user won't have a control over when the email will come the second time.

-  The second is the above mentioned one, where we declare a new resend endpoint, and write a custom view and use `allauth` API's to resend the E-mail, where the user has control over when the email is send. 

I like the second one, @deshraj @RishabhJain2018 your inputs on this much appreciated. :)

**Comment by deshraj** [comment]
@isht3 thanks for the suggesting the two methods. The second method definitely sounds like a good way to proceed with. Please let me know if you are interested in working on this.

**Comment by RishabhJain2018** [comment]
Yes, the second method is a good way. :+1:

**Comment by isht3** [comment]
@deshraj I already started on the issue! :smile:

**Comment by isht3** [comment]
Hi @Obtin I worked on this issue and my PR is currently under review but there is an issue with the request throttling, if you're interested you could work on that. :smile:
