### ISSUE TITLE
Create Team model in `web` django app

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#635]
The `Team` model will contain the following fields:

- name 
- email
- headshot (ImageField)
- visible (BooleanField)
- github_url (URL)
- linkedIn_url (URL)
- personal_website (URL)
- type (CharField with choices (core_team, contributor))

Ping me for more details.

**Comment by yadavankit** [comment]
@deshraj on it

**Comment by deshraj** [comment]
@yadavankit I am assigning this issue to you. But, please ask beforehand if you want to work on any issue since it could lead to duplicate effort.

**Comment by yadavankit** [comment]
@deshraj yeah sure 😊 . Can you help me with the defaults for `Team` member variables?

**Comment by deshraj** [comment]
Add default to `visible` field and set it as `True`. Rest all the fields are required by default. No need to put default for those fields.

**Comment by yadavankit** [comment]
#638 please review :)

**Comment by deshraj** [comment]
Fixed in #638
