### ISSUE TITLE
Host: Status field of ChallengeHost model is initialized by Accepted 

### ISSUE THREAD

**Issue by daas-ankur-shukla** [Cloud-CV/EvalAI#640]
**CURRENT STATE -**

The status field is initialized as ACCEPTED by the `invite_host_to_team` view in the host app.

**ISSUE -**

This should be PENDING by default and the invited user should have the option to accept or deny the invitation.

**Comment by deshraj** [comment]
@daas-ankur-shukla I am glad that you have been playing well with the codebase. 

I will share the details about this issue soon. It's not on the priority list as of now and hence you can focus on other issues.

**Comment by daas-ankur-shukla** [comment]
:+1:

**Comment by Ram81** [comment]
@deshraj  should I do this?

**Comment by deshraj** [comment]
@Ram81 It is not the part of Version 1 of project. Please pick any other issue for now.

**Comment by isht3** [comment]
@deshraj I think #1347 solves this.

**Comment by deshraj** [comment]
Thanks @isht3. Closing this since it is a duplicate issue as #1347
