### ISSUE TITLE
Modify all the Filefields/Imagefields in the serializers to be hyperlinked

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#644]
Currently, when the serializers that return the imagefield/filefield links, then it is something like `/media/blah/blah.png` but ideally it should be the full URL with something like this  `http://localhost:8000/media/blah/blah.png`. 

We want to modify the serializers returning the Image URLs or File URLs. 

Please see http://stackoverflow.com/questions/23918619/django-rest-framework-and-filefield-absolute-url for more details.

**Comment by yadavankit** [comment]
Okay. Am taking it up then @deshraj 
Just to make it sure, all serializers are to be altered?

**Comment by deshraj** [comment]
@yadavankit Sure, you can go ahead. Yep, all the serializers need to be altered which includes the imagefield/filefield. Also, please make sure that things don't break on the client side after making changes.

**Comment by yadavankit** [comment]
@deshraj while working on this issue, I was testing the `POST` request **creating a submission** and that gave me `No exception method supplied` due to `ConnectionClosed` at the endpoint and hence, no response. So, for now, should I leave it as it is ?

**Comment by deshraj** [comment]
@yadavankit the API is working properly. Its just that you have to start rabbitmq worker for that. I haven't added the instructions in README. I will update it soon. Please leave it as it is for now.

**Comment by yadavankit** [comment]
@deshraj yeah, I got to know it should be running on port 5672 and I haven't set it yet.

**Comment by yadavankit** [comment]
@deshraj should we mention this as an issue to Update README for starting rabbitmq worker at 5672?

**Comment by deshraj** [comment]
Sure. I can do that and will assign it to myself.

**Comment by deshraj** [comment]
Fixed in #662
