### ISSUE TITLE
Integrate the Update Profile API Endpoint with Client Side

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#649]
The `update profile` option in the left menu doesn't work. I think there is no API for fetching and updating the profile data.

@TroJan @deshraj What are your views about it?

**Comment by deshraj** [comment]
@RishabhJain2018 I think we already have the API to get and update the user profile at this endpoint ` /api/auth/user/` with `GET` and `PUT` request respectively. We just need to integrate the endpoint to update the user profile with the client side.

**Comment by RishabhJain2018** [comment]
@deshraj Can I work on this?

**Comment by RishabhJain2018** [comment]
@aka-jain Please add a To-Do's, so that I can add this feature.

**Comment by deshraj** [comment]
TODOs:

- [ ] Create a form in the update profile view

- [ ] Use the update user API in the backend and integrate it with the client side

- [ ] Show notification on successful profile updation

- [ ] Add the Update Profile Option in the sidebar
