### ISSUE TITLE
Enforce unique random file name for files being uploaded

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#652]
Currently, the files being uploaded are having simple name and we don't want them to serve to anyone who knows the pattern. Hence, we should store the files with name as uuid that will to secure it to some extent. 

For reference, see this http://stackoverflow.com/questions/2673647/enforce-unique-upload-file-names-using-django?answertab=active#tab-top

**Comment by RishabhJain2018** [comment]
@deshraj Can I work on this?

**Comment by RishabhJain2018** [comment]
@deshraj Can I also change the file name for [these](https://github.com/Cloud-CV/EvalAI/blob/master/apps/jobs/models.py#L69) models also.

**Comment by deshraj** [comment]
Yes @RishabhJain2018, that is also a part of the issue.

**Comment by deshraj** [comment]
@RishabhJain2018 Any updates on this?

**Comment by RishabhJain2018** [comment]
@deshraj I had discussed this with @TroJan & I will fix this asap.

**Comment by deshraj** [comment]
Sounds good.

**Comment by deshraj** [comment]
Reopening this issues since a fix has to be added in this as discussed with @RishabhJain2018 .

**Comment by RishabhJain2018** [comment]
@deshraj yeah sure. I will fix this asap.

**Comment by TroJan** [comment]
@deshraj @RishabhJain2018 : can you please explain here what fix ?

**Comment by RishabhJain2018** [comment]
@TroJan Please refer [this](https://github.com/Cloud-CV/EvalAI/commit/d01d29fa54367e0b8fc55e141672e23dc1539e56#commitcomment-20969490) link.

**Comment by TroJan** [comment]
@RishabhJain2018 : Can we close this if everything is complete?

**Comment by RishabhJain2018** [comment]
@TroJan Yeah, this is complete . Please merge the PR.
