### ISSUE TITLE
Add setInterval to API calls to get realtime data

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#653]
Currently on leaderboard and my-submissions view, the user has to refresh the page again and again to check the progress of his submission. We want to use $setInterval (https://docs.angularjs.org/api/ng/service/$interval) so that after a delay of lets say `5 seconds`, it makes an API call to get the data and update the view accordingly. 

Changes to be done in the following controllers:
- My Submission View
- Leaderboard View

**Comment by anweshknayak** [comment]
@deshraj can I take this up ?

**Comment by anweshknayak** [comment]
anyone working on this ?

**Comment by spyshiv** [comment]
yes. I am working on this.

**Comment by aka-jain** [comment]
@spyshiv let me handle this, you continue work on notification System :)

**Comment by spyshiv** [comment]
sure... @aka-jain

**Comment by deshraj** [comment]
Fixed.
