### ISSUE TITLE
Add a button of 'Create Participant Team' on Challenge Participation View

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#654]
On Challenge Participate View, 

**Use-case 1**: when no participant team exists for a particular user, then we should show him a button `Create Participate Team` instead of `Participate` which will redirect the user to Participant Team view.  

**Use-case 2**: When some participant team exists for a user, then show him both the buttons `Create Participate Team` and `Participate`. 

Let me know if you have doubts reagarding this issue. 

Just for reference, see the image attached below. 

<img width="1440" alt="screen shot 2017-02-08 at 7 50 46 pm" src="https://cloud.githubusercontent.com/assets/2945708/22764322/f9c34724-ee37-11e6-98d2-f092d3435f71.png">

**Comment by Ram81** [comment]
@deshraj can you assign this to me?

**Comment by aka-jain** [comment]
@deshraj Isn't it participate will also create a team? I mean do we have different API's for this feature?

**Comment by deshraj** [comment]
@aka-jain no, the Participate button won't create a team. 
So, we have two options:
1. Lets add a button named `Create Participant Team` next to it and then redirect it to the `My Participant Team` view where the user can create a Team. 
2. Add the create team view here where the user can create a team in this view only. 

Let me know which approach sounds better according to UX point of view?

**Comment by deshraj** [comment]
@Ram81 Lets wait for a while till we finalize the UX for this.

**Comment by Ram81** [comment]
@deshraj  Sure

**Comment by Ram81** [comment]
is the UX ready @deshraj ?

**Comment by deshraj** [comment]
@Ram81 Can you add a view similar to the 'My Participant Team View' here so that user can select or create a team on the challenge view only. Also, it would be great if you can integrate with the API of creation. This should be simple since it has already been implemented in the 'My Participant Team View'. Do ask @aka-jain or me for more details.

**Comment by Ram81** [comment]
@deshraj  sure

**Comment by deshraj** [comment]
Fixed in #688
