### ISSUE TITLE
Remove gulp lint warnings and errors. 

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#655]

**Comment by aka-jain** [comment]
Steps to follow:
Run gulp dev:runserver or gulp lint 
Errors will come up in Blue color, need to solve those errors as soon as possible. 
p.s: errors are too simple like add missing semicolon, IIFE wrong definition etc.

**Comment by RishabhJain2018** [comment]
@aka-jain @spyshiv Can I work on this?

**Comment by deshraj** [comment]
Sure @RishabhJain2018.

**Comment by aka-jain** [comment]
@RishabhJain2018 Let us know as soon as you finished recovering all the errors, we have to make a restrict entry for these errors in near future.

**Comment by RishabhJain2018** [comment]
@aka-jain I will fix these asap.

**Comment by aka-jain** [comment]
@RishabhJain2018 Are you working on any other issue?

**Comment by RishabhJain2018** [comment]
Actually I was working on issue that is dependent on notification system. So, Currently I am working on this one.

**Comment by aka-jain** [comment]
Okay.

**Comment by aka-jain** [comment]
Fixed with #665
