### ISSUE TITLE
New Home Page for EvalAI

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#656]
New Design.
![bigger5](https://cloud.githubusercontent.com/assets/11537940/22772732/67d8b816-eec4-11e6-9274-414031b54ff8.png)

**Comment by aka-jain** [comment]
Working on it.

**Comment by daas-ankur-shukla** [comment]
looks nice :+1:

**Comment by deshraj** [comment]
Fixed in #691
