### ISSUE TITLE
Add News Feed in Dashboard

### ISSUE THREAD

**Issue by Arun-Jain** [Cloud-CV/EvalAI#664]
This news feed will contain all the recent activities and questions regarding all challenges.
This helps user to get more information regarding various challenges.
@deshraj @aka-jain @spyshiv thoughts?

**Comment by aka-jain** [comment]
Hmmm... nice idea @jainarunarunjain. @deshraj we can do this for v2, what say?

**Comment by dexter1691** [comment]
This is already part of v2 plan. We were thinking of having a permanent news feed in a column on the right hand side. Very similar to how facebook has it I guess. 

Potential items to show on the newsfeed:
- If somebody sets state-of-the-art on a challenge the user has participated in
- A simple timer if the challenge is about to end
- If somebody other than you in your team submitted an entry to a challenge
- etc
We should may be use this issue to brainstorm and design some mocks for this! 

@jainarunarunjain : Thanks for opening this issue!

**Comment by jainarunarunjain** [comment]
Okay

**Comment by PratikDhanave** [comment]
I want to work on it

**Comment by prasadwajekar** [comment]
i would like to work on it...

**Comment by deshraj** [comment]
Closing this since this feature is not in priority for this quarter.
