### ISSUE TITLE
Solve blinking of data in my submission view.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#668]
Problem is mainly due to digest cycle of Angular. Need to apply and watch for the changes in scope of the challenge controller.

**Comment by anweshknayak** [comment]
@aka-jain can I try ?

**Comment by aka-jain** [comment]
Have you done with the Pagination of submission view?

**Comment by anweshknayak** [comment]
@aka-jain Yes check the PR.

**Comment by anweshknayak** [comment]
@aka-jain any hint on how to solve the problem ? I understand the need of apply and watch. But to which scope variables to attach to ? Can you give me some pointers to go ahead with.

**Comment by aka-jain** [comment]
I have to figure it out. So please do it by yourself. Let see if you can find something.

**Comment by aka-jain** [comment]
Assigning this to myself.

**Comment by deshraj** [comment]
@aka-jain did we find a solution for this problem?

**Comment by RishabhJain2018** [comment]
@deshraj @aka-jain Does this issue still exists in `My Submissions` view ?

**Comment by deshraj** [comment]
Yeah, it still exists.
