### ISSUE TITLE
Polling not working as expected in My-Submissions View

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#676]
Cases that are not covered in Polling:

## Problem 1: 
Problem occurs when the data is updated and the user is on some page except the 1st page of Pagination. 

## How to replicate?
1. Open My-submissions in one tab and goto page 2 or 3 using pagination
2. Open submission view in another tab
3. Create a submission
4. Go back to the previous tab of my-submissions
5. When you click on "Page is outdated. Click here to refresh", then you are still on the 3rd page with the updated data but you should be redirected to the first page of pagination with the updated data.

## Problem 2:
When the submission status changes, then the data is not updated on the client side since we are checking the length of the response and not the content of the response. Please see line https://github.com/Cloud-CV/EvalAI/blob/master/frontend/src/js/controllers/challengeCtrl.js#L614

**Comment by gauthamzz** [comment]
Is. Anyone doing this?

**Comment by deshraj** [comment]
No. @gauthamzz if you are interested in solving this one, I can assign it to you.

**Comment by gauthamzz** [comment]
Yeah that would be great

**Comment by deshraj** [comment]
Sure. Please be quick in solving this issue since this is one the critical issue and we want it to get done ASAP. :) 

Let us know if you need any help.

**Comment by deshraj** [comment]
@gauthamzz any updates on this?

**Comment by gauthamzz** [comment]
can i get some hints on the first part

**Comment by deshraj** [comment]
@gauthamzz, please don't worry about this issue anymore. I have fixed this issue in #708 since this was super urgent. :) You can pick some other issue.

**Comment by gauthamzz** [comment]
close this ?

**Comment by deshraj** [comment]
Sure, will do this after merging the PR.
