### ISSUE TITLE
Create a ModelAdmin class in base app to exclude created and modified fields

### ISSUE THREAD

**Issue by TroJan** [Cloud-CV/EvalAI#68]
The admin class should live in base apps. It will be derived from ModelAdmin class and will use [exclude](https://docs.djangoproject.com/en/1.10/ref/contrib/admin/#django.contrib.admin.ModelAdmin.exclude) to exclude `created` and `modified` fields.

This is so that anyone adding an object from the admin panel should not be shown in these fields as these are handled internally by Django before saving an object.

Name of the class should be `TimeStampedAdmin` and it should live in `base/admin.py`

**Comment by RishabhJain2018** [comment]
@deshraj @TroJan Can I work on this?

**Comment by deshraj** [comment]
Fixed in #132
