### ISSUE TITLE
Frontend: Remove comparison operator in case of 'true' and 'false'.

### ISSUE THREAD

**Issue by spyshiv** [Cloud-CV/EvalAI#683]
- [ ] Case1: if somewhere code is written like this
`if(variable_name === 'true') { //code }` or `if(variable_name == 'true') { //code }`
then change this to 
`if(variable_name){
//code
}`

- [ ] Case2: if somewhere code is written like this
`if(variable_name === 'false') {
       //code
}`
then change this to 
`if(!variable_name){
//code
}`

PS: It's not only for `if` but also same for `else`, `else if`, `whether` etc.

**Comment by jainarunarunjain** [comment]
@spyshiv Can I work on this?

**Comment by deshraj** [comment]
@jainarunarunjain I don't think anyone has picked up this issue. So, you can work on it. :-)

**Comment by aka-jain** [comment]
Fixed with #686
