### ISSUE TITLE
Setup ModelAdmin class for each model in Team app

### ISSUE THREAD

**Issue by TroJan** [Cloud-CV/EvalAI#69]
This class should be derived from TimeStampedAdmin of base app. 

Notable attributes should be
* list_display
* search_fields
* list_filter

Note that this issue depends on [#68](https://github.com/Cloud-CV/EvalAI/issues/68) which involves the creation of `TimeStampedAdmin` class.

**Comment by RishabhJain2018** [comment]
@deshraj @TroJan Can I work on this??

**Comment by deshraj** [comment]
Fixed in #170
