### ISSUE TITLE
Frontend: Merge 'gulp lint' task with 'gulp watch'.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#690]
@spyshiv assigning it to you.

**Comment by spyshiv** [comment]
Cool..

**Comment by anweshknayak** [comment]
@spyshiv you working on this ?

**Comment by spyshiv** [comment]
Yes. I am working on this. Will update it soon.
Thank you for reminding me.

**Comment by spyshiv** [comment]
@RishabhJain2018 : Do you want to work on this issue? Let me know if you are interested.

**Comment by RishabhJain2018** [comment]
@spyshiv yeah sure.

**Comment by spyshiv** [comment]
I am assuming that you are familiar with the tasks `lint` and `watch`. So what you have to do is whenever any js file is changed you have to make run `gulp lint`.
Let me know if you stuck somewhere.

**Comment by RishabhJain2018** [comment]
@spyshiv What we want to achieve after merging these two tasks ? What should be the outcome?

**Comment by aka-jain** [comment]
@RishabhJain2018 Just going through your PR, yes the code is right but we have to do some additional changes too. Like server should not run until you solve all the errors of lint. So integrate lint with watch such that if we get any error than server should stop. Getting?
@spyshiv want to add something else?

**Comment by RishabhJain2018** [comment]
@aka-jain Yeah I got this point. :+1:  @spyshiv Please tell anything else that should be added ? I will update the PR accordingly.

**Comment by RishabhJain2018** [comment]
@aka-jain @spyshiv Reopen this issue as some task is still left on this issue . Please refer to above conversation.

**Comment by spyshiv** [comment]
I didn't close this issue intentionally it is done automatically. :smile: 
Reopening again.
@aka-jain @RishabhJain2018 : For the reference please have a look at comment in `gulpfile.js` line 233. 
PS: Since it should not be a blocker so once the linting errors and warnings are fixed (issue #805) then start doing work on this.

**Comment by RishabhJain2018** [comment]
@aka-jain @spyshiv  By this ` So integrate lint with watch such that if we get any error than server should stop`, you want to say that gulp watch task should break when any lint error is present ??

**Comment by spyshiv** [comment]
@RishabhJain2018 
Keep 'gulp watch' always active.
Order of running tasks
1. Watch 2. Lint 3. Connect
- `Watch` should always be running
- If `Lint` gives an error then break the `connect` (should stop the server)
- If `Lint` is fine then run `connect`
Getting??
Let me know if you have any doubt.

**Comment by RishabhJain2018** [comment]
@spyshiv Okay sure.

**Comment by spyshiv** [comment]
@RishabhJain2018 : `lint` errors are removed. Now you can start work on this issue with additional feature as discussed above.

**Comment by RishabhJain2018** [comment]
@spyshiv okay sure.
