### ISSUE TITLE
Sidebar menu is not working on New UI mobile version.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#693]

**Comment by Ram81** [comment]
@aka-jain can you assign this to me?

**Comment by aka-jain** [comment]
Sure @Ram81 , go ahead.

**Comment by Ram81** [comment]
@aka-jain any hints?

**Comment by aka-jain** [comment]
@Ram81 hints regarding what... have you understood the issue? Or you need help to solve it.

**Comment by Ram81** [comment]
@aka-jain when I see the page in mobile I am unable to use any link! why is it so I don't get it?

**Comment by aka-jain** [comment]
So for that there is a hamburger icon, clicking on which opens a sidebar like we do in mobile apps and that's an issue.

**Comment by Ram81** [comment]
@aka-jain that's not what I was saying when I use it in mobile view I am unable to use any link other than the icon used to open sidebar & not even any link from footer is working!

**Comment by aka-jain** [comment]
Hmmm... I think there is an overlay of a transparent image which stops clicking event on these links. So that is the issue... Find that overlay and customize it so that everything will work fine.

**Comment by Ram81** [comment]
sure will do that

**Comment by aka-jain** [comment]
@Ram81 what about this one? I think this one is working now. Can you check once again please by updating your master? 
Also try to do one task at a time. Let's make issues free for other contributors too.

**Comment by aka-jain** [comment]
Fixed with #751. Closing this.
