### ISSUE TITLE
Integrate Team API with frontend

### ISSUE THREAD

**Issue by yadavankit** [Cloud-CV/EvalAI#695]
API endpoint for `our-team` view is to be integrated

**Comment by deshraj** [comment]
Thanks @yadavankit for re-opening it again. I closed the #677  issue accidently.

**Comment by deshraj** [comment]
@yadavankit are you working on this issue or is it open?

**Comment by yadavankit** [comment]
@deshraj I don't have good experience with frontend, so I guess I won't be working on this issue, please assign this to team members well versed with frontend :) Meanwhile, will be working on the issue we talked about

**Comment by deshraj** [comment]
@yadavankit: Sounds good. :)

**Comment by deshraj** [comment]
Assigning this to myself.

**Comment by deshraj** [comment]
Unassigning myself since i am occupied with some other work. Feel free to comment if you are interested in working on this task.

**Comment by aka-jain** [comment]
@deshraj I think this is done, isn't it?

**Comment by deshraj** [comment]
No, not yet. I was to work on this but didn't get time to complete it.

**Comment by RishabhJain2018** [comment]
@deshraj @aka-jain Can I work on this?

**Comment by aka-jain** [comment]
But then on Prod how lists are coming, it that hard coded?

**Comment by deshraj** [comment]
Yeah, currently I have hard coded the details for the staging server just to check how it looks.

**Comment by aka-jain** [comment]
Okay, cool.

**Comment by RishabhJain2018** [comment]
@deshraj @aka-jain Can I work on this?

**Comment by deshraj** [comment]
Yep Sure.
