### ISSUE TITLE
Optimization of Images.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#698]
Use this APP to optimize all the images https://compressor.io/

**Comment by anweshknayak** [comment]
@aka-jain can I take this up ?

**Comment by aka-jain** [comment]
Sure @anweshknayak.

**Comment by daas-ankur-shukla** [comment]
@aka-jain  can you please provide some details regarding this issue

**Comment by aka-jain** [comment]
@daas-ankur-shukla I think @anweshknayak is already working on it. 
@anweshknayak are you?

**Comment by anweshknayak** [comment]
No not yet. @daas-ankur-shukla go ahead you can do this. Just go that site mentioned above and upload those images there and compress them and replace the original images with the compressed ones.

**Comment by daas-ankur-shukla** [comment]
@anweshknayak ok i am on it. but one silly question. which images?

**Comment by anweshknayak** [comment]
@daas-ankur-shukla https://github.com/Cloud-CV/EvalAI/tree/master/frontend/src/images 
find more if there

**Comment by anweshknayak** [comment]
@daas-ankur-shukla you doin this ?

**Comment by daas-ankur-shukla** [comment]
@anweshknayak yup

**Comment by daas-ankur-shukla** [comment]
dint find any more than those at the link

**Comment by anweshknayak** [comment]
put up a PR and ask the mentors to review.

**Comment by daas-ankur-shukla** [comment]
which branch should i commit to? should i make my own branch?

**Comment by anweshknayak** [comment]
Yeah from your fork create a branch and push to master in evalai.

**Comment by daas-ankur-shukla** [comment]
it says i dont have permissions to push to master

**Comment by anweshknayak** [comment]
http://stackoverflow.com/a/3476453/4037592 . Remove it and set your fork repo's link as origin.

**Comment by daas-ankur-shukla** [comment]
created PR #727. I Hope I have done it correctly :P

**Comment by aka-jain** [comment]
Yep. Fixed with #727
