### ISSUE TITLE
Setup ModelAdmin class for each model in Host app

### ISSUE THREAD

**Issue by TroJan** [Cloud-CV/EvalAI#70]
This class should be derived from a TimeStampedAdmin of base app.

Notable attributes should be
* list_display
* search_fields
* list_filter

Note that this issue depends on [Issue 68](https://github.com/Cloud-CV/EvalAI/issues/68) which involves the creation of `TimeStampedAdmin` class.

**Comment by deshraj** [comment]
Fixed in #150
