### ISSUE TITLE
Change style/design of Notification system.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#700]
Do following changes:
1. Make top-right and bottom-right border-radius 0,
2. Position should be 20px from top and 0 from right,
3. Make opacity of div to 1 from .8

**Comment by jainarunarunjain** [comment]
@aka-jain Can i work on this.

**Comment by aka-jain** [comment]
Sure @jainarunarunjain. Please see the updated description for this issue.

**Comment by deshraj** [comment]
@jainarunarunjain: please add one more fix. The toast should go away after 4 seconds. Please add a timeout for the toasts.

**Comment by jainarunarunjain** [comment]
@deshraj Sure

**Comment by aka-jain** [comment]
Thanks @jainarunarunjain. Fixed with #712
