### ISSUE TITLE
Footer in About Us page is not aligned 

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#714]
![footer](https://cloud.githubusercontent.com/assets/16323427/23216486/214f297a-f93c-11e6-893f-4d5f5fd6ab03.png)

**Comment by Ram81** [comment]
@aka-jain I must be fixed at bottom!

**Comment by deshraj** [comment]
Thanks for opening this @Ram81 :) Feel free to fix this.

**Comment by deshraj** [comment]
Fixed in #715
