### ISSUE TITLE
Setup ModelAdmin class for each model in Challenge app

### ISSUE THREAD

**Issue by TroJan** [Cloud-CV/EvalAI#72]
This class should be derived from a TimeStampedAdmin of base app.

Notable attributes should be
* list_display
* search_fields
* list_filter

Note that this issue depends on [Issue 68](https://github.com/Cloud-CV/EvalAI/issues/68) which involves the creation of `TimeStampedAdmin` class.

**Comment by gauthamzz** [comment]
can i try this ?

**Comment by TroJan** [comment]
@gauthamzz : yeah sure, but if you dont mind can you give #68 a try. This is because TimeStampedAdmin class does not exist as of now and we need it here.

**Comment by gauthamzz** [comment]
Can you give me an idea how to do #68 i haven't made any model admin till now.

**Comment by gauthamzz** [comment]
Can you give me an idea how to solve #68

**Comment by TroJan** [comment]
@gauthamzz : as of now you can start by just writing a [modelAdmin](https://docs.djangoproject.com/en/1.10/ref/contrib/admin/#django.contrib.admin.ModelAdmin) class.  This class will register the model on django admin site. 

There are certain attributes for this class, which defines how can you search on this model, what filters will be available and so on. We are only concerned with three attributes 

* [list_display](https://docs.djangoproject.com/en/1.10/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_display)
* [list_filter](https://docs.djangoproject.com/en/1.10/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_filter)
* [search_fields](https://docs.djangoproject.com/en/1.10/ref/contrib/admin/#django.contrib.admin.ModelAdmin.search_fields)

**Comment by jainarunarunjain** [comment]
can i try this?

**Comment by gauthamzz** [comment]
i am almost done with this , try other part

**Comment by jainarunarunjain** [comment]
Sure

**Comment by deshraj** [comment]
Fixed in #149
