### ISSUE TITLE
Change Password not working properly

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#720]
As of now, Change password view has following issues:
- Change Password actually doesn't change the password
- `undefined` shown after message that user gets to see on the interface

**Comment by anweshknayak** [comment]
@deshraj can I work on this ?

**Comment by deshraj** [comment]
Sure. Assigning it to you. :)

**Comment by anweshknayak** [comment]
@deshraj Changing password actually works. What more to be done about it ?
