### ISSUE TITLE
Frontend: Prevent 404 page on adding trailing slash('/') in the urls

### ISSUE THREAD

**Issue by spyshiv** [Cloud-CV/EvalAI#728]
This code was deleted accidentally. 
[See the help](https://github.com/Cloud-CV/EvalAI/commit/998e2e7ffa9435f30dd448430b1387eba7ca50a7#commitcomment-21032649)

**Comment by Ram81** [comment]
@spyshiv can you assign this to me?

**Comment by spyshiv** [comment]
Sure..Go ahead.

**Comment by spyshiv** [comment]
@Ram81 What is the status of this. Please fix that asap. You have to just copy and paste .

**Comment by spyshiv** [comment]
Sorry my bad. you already did.

**Comment by Ram81** [comment]
@spyshiv :+1:

**Comment by spyshiv** [comment]
@Ram81 : It's fine. It wasn't much delay.
Closing this issue as it is fixed in PR #732.
