### ISSUE TITLE
Integrate Django REST Swagger for API docs

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#73]
For reference, see this: https://django-rest-swagger.readthedocs.io/en/latest/

**Comment by RishabhJain2018** [comment]
@deshraj Can I fix this??

**Comment by deshraj** [comment]
Sure, go ahead. :-)

**Comment by RishabhJain2018** [comment]
@deshraj Which version are we going to use ?

**Comment by deshraj** [comment]
Since we are using django 1.10 so the latest version that is compatible with it will work.

**Comment by RishabhJain2018** [comment]
okk.
