### ISSUE TITLE
No response on file submission without selecting the Phase

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#731]
In the challenge submission view, if I just upload a file without selecting the phase, then the loader doesn't go away and there is no error on the page. For reference, see the below screenshots. 
<img width="1440" alt="screen shot 2017-02-24 at 9 26 42 am" src="https://cloud.githubusercontent.com/assets/2945708/23306941/9c0c18a2-fa73-11e6-8815-40cfcd17be77.png">
<img width="1440" alt="screen shot 2017-02-24 at 9 26 55 am" src="https://cloud.githubusercontent.com/assets/2945708/23306940/9c02e804-fa73-11e6-8c72-27322acd2111.png">

**Comment by anweshknayak** [comment]
@deshraj I would like to work on this ?

**Comment by deshraj** [comment]
Sure

**Comment by anweshknayak** [comment]
![screenshot from 2017-02-25 00 17 39](https://cloud.githubusercontent.com/assets/8139783/23316328/fc1df2b6-faef-11e6-9965-453984b45518.png)

@deshraj error in page is showing up. Can you elaborate more in the issue ?

**Comment by anweshknayak** [comment]
![screenshot from 2017-02-25 16 49 16](https://cloud.githubusercontent.com/assets/8139783/23330700/951f7900-fb7a-11e6-8ee6-6f3d2f558dc3.png)

**Comment by deshraj** [comment]
@anweshknayak I think the case of uploading file without selecting the phase is working properly. 
Please check the console response coming from the backend. It seems like there are some other unhandled cases that needs to be covered.

**Comment by anweshknayak** [comment]
![screenshot from 2017-02-25 16 59 50](https://cloud.githubusercontent.com/assets/8139783/23330738/f626fc72-fb7b-11e6-94fb-d8044dee32d4.png)

**Comment by deshraj** [comment]
I see. @anweshknayak can you please add a check where if the phase is not selected, then there is no API call made to the backend.

**Comment by anweshknayak** [comment]
sure @deshraj

**Comment by anweshknayak** [comment]
@aka-jain Im working on this one too. Need some help. How shall I make use of promises to cancel http request here ? found something here (http://odetocode.com/blogs/scott/archive/2014/04/24/canceling-http-requests-in-angularjs.aspx)

**Comment by aka-jain** [comment]
There is no need to cancel http request @anweshknayak. Try to do as @deshraj mention above. You just need to check the value of phase with if else statements. It's easy, actually I have done this before but due to some reason some code has been changed. So try to do with if else statements. Thanks.

**Comment by aka-jain** [comment]
@anweshknayak status?

**Comment by anweshknayak** [comment]
@aka-jain will do it today. Had exams.

**Comment by deshraj** [comment]
@anweshknayak any updates on this?

**Comment by anweshknayak** [comment]
@deshraj I didn't get time to fix this yet. Meanwhile please make this feel for others to solve.

**Comment by deshraj** [comment]
Thanks for informing Anwesh. :)

**Comment by varunagrawal** [comment]
@deshraj I'd like to get more experience with the frontend of EvalAI. Can you please assign this bug to me?

**Comment by deshraj** [comment]
Already fixed. Closing it.
