### ISSUE TITLE
Reset password page doesn’t reset when moved from one view to another

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#733]
## How to replicate this issue?

1. Click on Forgot password
2. Submit email
3. Click `Back to Log In`
4. Click again on `Forgot Password`

**Comment by Ram81** [comment]
@deshraj  can I take this up?

**Comment by deshraj** [comment]
Yep, sure.

**Comment by Ram81** [comment]
@deshraj fixed in #735 you can close this

**Comment by spyshiv** [comment]
Closing this.
