### ISSUE TITLE
Frontend: Remove jslint errors, and clean the code

### ISSUE THREAD

**Issue by spyshiv** [Cloud-CV/EvalAI#734]
Steps to follow
1. Fine the line `/* jshint shadow:true */` in the js files of directory `frontend/src/js/`
2. Remove the line `/* jshint shadow:true */` 
3. Run `gulp lint` and see the linting warnings and errors in the terminal
4. Fix the warnings and errors.
   - [ ] if there is variable duplication, please use your senses and rename them smartly.
   - [ ] Remove unnessary variables that are defined inside a block and never used
   - [ ] Remove `console.log();` [if there is nothing in the block except `console.log()` then don't remove it ] 
5. Test the view in your local and see that everything is fine.

5. Do not use `/* jshint shadow:true */` anywhere. If you can't fix the errors or stuck somewhere, report to @spyshiv or @aka-jain .

**Comment by jainarunarunjain** [comment]
@spyshiv Can i work on this?

**Comment by aka-jain** [comment]
@jainarunarunjain sure go ahead.

**Comment by RishabhJain2018** [comment]
@spyshiv @deshraj I think this is completed in #736 .So should we close this?

**Comment by aka-jain** [comment]
Closing it. Fixed with #736 .
