### ISSUE TITLE
Improve Gulp Watch task to handle remove, delete, and errors in files.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#74]
Need to update watch task of gulp  so that it can easily get files update like delete and add.

**Comment by anweshknayak** [comment]
update task like what ? can you give me a headstart.

**Comment by aka-jain** [comment]
If you add a new file or delete any existing file or if your JavaScript throws error then gulp watch task breaks. Need to fix it, there is a gulp dependency available which handle all JS errors, addition and deletion. You have to rewrite the gulp watch task so that it can easily handle all these changes. I hope you got my point.

**Comment by anweshknayak** [comment]
https://www.npmjs.com/package/gulp-watch This should help I think ?

**Comment by anweshknayak** [comment]
http://stackoverflow.com/a/34346524 this solves the issue I guess ?

**Comment by aka-jain** [comment]
@anweshknayak addition and deletion are working now. It was an older version problem. 
But watch task is not handling JS errors. It breaks down when JS file throws error. Can you plesae verify and try to solve this only.
Take reference form this link and you can use Plumber plugin for this too. https://cameronspear.com/blog/how-to-handle-gulp-watch-errors-with-plumber/
