### ISSUE TITLE
Reuse the code of rocket container in views folder by making  a separate file of it.

### ISSUE THREAD

**Issue by jainarunarunjain** [Cloud-CV/EvalAI#742]
@deshraj @aka-jain @spyshiv will it be possible. 
Thoughts?

**Comment by aka-jain** [comment]
@jainarunarunjain yup, we can do this. I'm assigning it to you. Let me know if you need any help.

**Comment by jainarunarunjain** [comment]
@aka-jain Sure, will do this :)

**Comment by jainarunarunjain** [comment]
@deshraj @spyshiv @aka-jain we should close this. Fixed in #753

**Comment by spyshiv** [comment]
cool. :+1: 
Closing this
