### ISSUE TITLE
Frontend: Changing route doesn't scroll to top in the new page

### ISSUE THREAD

**Issue by spyshiv** [Cloud-CV/EvalAI#744]
Example:
1. Open home page and go to footer
2. In footer click on the `about us` link

You can see the page doesn't scroll to top. See the screenshot
![screenshot from 2017-03-02 02 04 20](https://cloud.githubusercontent.com/assets/7015220/23480065/94a3367c-feec-11e6-8a55-7129a7c69e3d.png)

**Comment by aka-jain** [comment]
@spyshiv I'm on it.

**Comment by spyshiv** [comment]
cool :+1:

**Comment by aka-jain** [comment]
Task is open, I'm working on some other issue.

**Comment by spyshiv** [comment]
@aka-jain : Cool :+1:

**Comment by gauthamzz** [comment]
I would like to try this

**Comment by spyshiv** [comment]
@gauthamzz Sure assigning to you

**Comment by aka-jain** [comment]
@gauthamzz are you still on it?

**Comment by gauthamzz** [comment]
@aka-jain  i am i need one more day , i have an exam tmmrw.then im free .Is that fine ?

**Comment by aka-jain** [comment]
Let's free this issue till then. Let me know whenever you get free. Will assign it to you again if no one shows interest in it.

**Comment by spyshiv** [comment]
@anweshknayak : can you fix this ?? Let me know if you are interested.

**Comment by anweshknayak** [comment]
@spyshiv Sure. I am interested.

**Comment by spyshiv** [comment]
@anweshknayak: Let see how quick you are.... Assigning this to you.
