### ISSUE TITLE
Hide toaster container in mobile view <993px

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#745]
There is a problem regarding links in mobile view. For that we have to remove the toaster container for mobile view.

**Comment by gauthamzz** [comment]
Can i try this ?

**Comment by spyshiv** [comment]
You are already assigned issue #744 . Please complete that first

**Comment by gauthamzz** [comment]
I didnt see that. i deleted the comment . ill do #774 first

**Comment by anweshknayak** [comment]
@aka-jain can I put a PR ?

**Comment by aka-jain** [comment]
Sure @anweshknayak .
