### ISSUE TITLE
Add content to home page

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#75]
Need to complete the Homepage:

Main content that will come:
1. Top 5 challenges
2. Intro to EvalAI
3. How it works

**Comment by Ram81** [comment]
I want to take this one @aka-jain, when done with design let me know?

**Comment by shivanXI** [comment]
I am also interested in this one @aka-jain , if the design is ready can you assign it to me to do it ?

**Comment by aka-jain** [comment]
@shivanXI : Sure, will do it.

**Comment by aka-jain** [comment]
@spyshiv : assigning this to you.

**Comment by spyshiv** [comment]
@aka-jain: As we will work on new ui so we will get back to this issue later.

**Comment by deshraj** [comment]
Sounds good. Closing it for now.
