### ISSUE TITLE
Missing Error Catch In Team API

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#754]
We should also catch error while returning the Team List([here](https://github.com/Cloud-CV/EvalAI/blob/master/apps/web/views.py#L65)) from the database.
@deshraj @TroJan What are your views about it ?

**Comment by TroJan** [comment]
@RishabhJain2018 : Thanks for pointing this out. But it is actually not required.

Reason being that `all` does not throws an exception. It simply returns an empty list if no objects are found. However, `get` throws an exception, so when ever we are using `get` we need to catch it in a proper try-catch block.

**Comment by RishabhJain2018** [comment]
@TroJan okay sure. Thanks for guiding.
