### ISSUE TITLE
Notification should disappear after certain time interval.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#758]
For Now, we have to wait for long and then it disappears. The time period for its disappearing must be small.
@deshraj @aka-jain @spyshiv Can I work on this?

**Comment by spyshiv** [comment]
sure. Assigning this to you. Let me know if any query.

**Comment by RishabhJain2018** [comment]
@spyshiv The default timeout is 5 sec. What if we reduce it to 2 sec? What are your views about it?

**Comment by deshraj** [comment]
Ummm....I think we should make it to 3 seconds.

**Comment by RishabhJain2018** [comment]
@deshraj Okay sure.
