### ISSUE TITLE
Webhook Integration with slack Api 

### ISSUE THREAD

**Issue by divyanshu1302** [Cloud-CV/EvalAI#761]
Incoming/Outcoming  Webhooks are a simple way to post/get messages from external sources into Slack, or vice-versa.I think it may be helpful for registered teams to send and receive data from Slack to  our project or vice-versa using Webhooks. 
@deshraj @spyshiv @aka-jain @TroJan  Can you please allow me to work on it ?

**Comment by deshraj** [comment]
@divyanshu1302 the time is so early for this feature. We will work on this feature in the near future but not now. :) 

Closing for now.
