### ISSUE TITLE
Validation in profile update section required 

### ISSUE THREAD

**Issue by Curious72** [Cloud-CV/EvalAI#762]
There is a need for validation in profile update section ! If the user updates his/her username to be short for example a single letter 'a' , the update is performed , but when the user tries to log in with the updated username , he/she is unable to log in because of short username and the message 'username is short' is displayed !

The error can be reproduced , by logging in and updating the username with a single letter and then logging in again !

@deshraj @spyshiv  @aka-jain  Can i work on this issue ?

**Comment by aka-jain** [comment]
@Curious72 sure, assigning it to you.

**Comment by RishabhJain2018** [comment]
@aka-jain I think we should close this?

**Comment by spyshiv** [comment]
Closing this.
