### ISSUE TITLE
Integrating OAuth with EvalAI

### ISSUE THREAD

**Issue by anweshknayak** [Cloud-CV/EvalAI#766]
Logging in using OAuth/OAuth2(Github, facebook)

**Comment by Curious72** [comment]
@deshraj @spyshiv @aka-jain Is this issue open ? Can i work on this ?

**Comment by anweshknayak** [comment]
@Curious72 I just added this if it's good enough for an idea. @deshraj is this the right place to add ideas ?

**Comment by TroJan** [comment]
@anweshknayak : thanks for sharing this. 

@anweshknayak , @Curious72 : this is good to have feature. But as of now we are on a strict timeline, so we will take this when v2 is planned.

Closing this for now, Will open in v2(if required)

**Comment by WinnersGoHome** [comment]
Is there any chance you can reopen this issue now?  Oauth support would be great.
