### ISSUE TITLE
Adding button to scroll-up(top) in "Show All Challenges" view

### ISSUE THREAD

**Issue by anweshknayak** [Cloud-CV/EvalAI#770]
Ref : https://material.angularjs.org/latest/ .
A button at the right-bottom corner which will smooth scroll up.

**Comment by aka-jain** [comment]
Good One. We can work on this.

**Comment by aka-jain** [comment]
This issue is open. let me know if anyone interested.

**Comment by RishabhJain2018** [comment]
@aka-jain Can I work on this?

**Comment by aka-jain** [comment]
@RishabhJain2018 Are you working on some other issue I think, isn't it?

**Comment by RishabhJain2018** [comment]
@aka-jain Yeah , I was working on this #690 issue but the PR is under discussion with @spyshiv . So, currently I am free. So, I thought to pick it up.

**Comment by aka-jain** [comment]
Start working on #690. I have already discussed that with @spyshiv.

**Comment by RishabhJain2018** [comment]
@aka-jain okay sure. :+1:

**Comment by anweshknayak** [comment]
@RishabhJain2018 we already got one plugin for scroll https://github.com/Cloud-CV/EvalAI/blob/master/bower.json#L26. You can use this one for the issue.

**Comment by anweshknayak** [comment]
@aka-jain is anyone doing this ? @RishabhJain2018 are you? I can do this one.

**Comment by ishapotnis1** [comment]
Hi.. @anweshknayak are you done with this issue?

**Comment by anweshknayak** [comment]
@ishapotnis1 No I haven't done. Feel free to take this up. @aka-jain

**Comment by aka-jain** [comment]
Anyone up on this issue?

**Comment by anirudhvenu** [comment]
@aka-jain Is this issue done? I'd like to take it up if it hasn't been already.

**Comment by RishabhJain2018** [comment]
@anirudhvenu Please complete #886 first, then you can try this one. :)

**Comment by vishu160196** [comment]
Has this issue been solved? I would like to work on this @anweshknayak

**Comment by aka-jain** [comment]
@vishu160196 assigning this to you. Please go ahead and let me know if you face any problem.

**Comment by vishu160196** [comment]
@aka-jain I uilt the dockerfile given in the repository. The containers are running but only one of the ports (0.0.0.0:8000) is sending response (EvalAI- Home Page) with only Hello WOrld printed in <h1></h1> tags. Where exactly do i have to add the button and where is the (dummy) content to be scrolled up?

**Comment by aka-jain** [comment]
Check port 8888.

**Comment by vishu160196** [comment]
@aka-jain This site can’t be reached. The web page at http://0.0.0.0:8888/ might be temporarily down or it may have moved permanently to a new web address.

**Comment by Obtin** [comment]
@aka-jain If nobody is working on it. I would like to take this. Thank you.

**Comment by deshraj** [comment]
@Obtin Sure. :)
