### ISSUE TITLE
Redesign Login page.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#772]
Redesign login page same as we did for the about us page. Try to reuse the code.

**Comment by Ram81** [comment]
@aka-jain can you assign this to me?

**Comment by aka-jain** [comment]
Do you have any pending tasks?

**Comment by chan24** [comment]
@aka-jain Hey akash! I think I can fix this. Can u assign this task to me?

**Comment by aka-jain** [comment]
@Ram81 need to know your status.

**Comment by Ram81** [comment]
@aka-jain you can assign this to @chan24 as I have exams this week I will not be able to do it quickly!

**Comment by aka-jain** [comment]
@chan24 You can pick this up. Let me know if you are ready.

**Comment by chan24** [comment]
@aka-jain Thanks! I will work on it. Any hints?

**Comment by aka-jain** [comment]
Sure, please try to finish it ASAP. For design just take reference from about us page. Left column should contain form and at right we have the rocket container. Getting?

**Comment by chan24** [comment]
Yeah cool..On it!

**Comment by aka-jain** [comment]
@chan24 Let #815 be completed first. Then we assign this task to you.

**Comment by deshraj** [comment]
Part of #996. Closing this one.
