### ISSUE TITLE
Redesign Signup Page.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#773]
Depends on #772.

**Comment by Ram81** [comment]
@aka-jain can I take this up?

**Comment by aka-jain** [comment]
@Ram81 why you said no to login page design? This issue is based on that so lets that be completed first.

**Comment by Ram81** [comment]
@aka-jain sorry my bad

**Comment by Ram81** [comment]
@aka-jain I can do this quickly if you allow me as you said the description of design of login page in #772? so should I do it?

**Comment by aka-jain** [comment]
@Ram81 Try this first #815

**Comment by Ram81** [comment]
@aka-jain sure

**Comment by deshraj** [comment]
Part of #996. Closing this one.
