### ISSUE TITLE
Readme errors for setting up evalAi on system.

### ISSUE THREAD

**Issue by AnshulBasia** [Cloud-CV/EvalAI#774]
4th point -> Use your linux system username and password for fields USER and PASSWORD in dev.py file.
It created a lot of misunderstanding.

**Comment by RishabhJain2018** [comment]
@AnshulBasia I think @TroJan have updated the setup guidelines. Please see [this](https://github.com/Cloud-CV/EvalAI/blob/master/docs/setup.md) link. :-)

**Comment by AnshulBasia** [comment]
@RishabhJain2018 Thanks  a lot. It'd be better if readme is also up to date. :)
