### ISSUE TITLE
Display Initial data in update profile card.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#779]
For now, when a user opens the update profile view, then he sees blank fields.
What I was thinking that he must see the previous `username`, `first_name`, `last_name` in the card & it must be editable, so that the user can change it.
@deshraj @spyshiv @aka-jain what are your thoughts about it?

**Comment by aka-jain** [comment]
Yes, fields should be present there.

**Comment by RishabhJain2018** [comment]
@aka-jain Can I work on this?

**Comment by spyshiv** [comment]
Sure... Assigning this to you.
