### ISSUE TITLE
Integrate testing to client side.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#781]
@spyshiv let's start working on it.

**Comment by spyshiv** [comment]
Sure... 👍

**Comment by spyshiv** [comment]
@aka-jain : So first of all i am targeting unit test for these components.
- [ ] controllers,
- [ ] directives
- [ ] filters

I am integrating this with `gulp` so that in future we can also prevent git task (i.e `git commit` , `git push`) until the unit test return success.
Any other thoughts?

**Comment by aka-jain** [comment]
Cool 👍

**Comment by RishabhJain2018** [comment]
@deshraj @aka-jain @spyshiv I have done a bit of research on the packages to be used for testing in angular. [Here](https://goo.gl/RUkiCh) is a list of them. I think it will be helpful to select the package for unit testing.

**Comment by spyshiv** [comment]
@RishabhJain2018: Thanks for analytical support. It's really helpful. :+1:

**Comment by aka-jain** [comment]
That's great @RishabJain2018. We are going with Mocha. @spyshiv any thoughts?

**Comment by spyshiv** [comment]
Let me compare the features between these tools/frameworks. Will let you know soon.

**Comment by RishabhJain2018** [comment]
@spyshiv If there is a need of any assistance of mine, then I would love to help. :-)

**Comment by spyshiv** [comment]
great. I will let you know.

**Comment by aka-jain** [comment]
@spyshiv I think testing integration has been done, so lets make a seperate issue for writing different tests cases. Thoughts?

**Comment by RishabhJain2018** [comment]
@deshraj @spyshiv We should have different issues for different test cases for controllers. What do you say?

**Comment by deshraj** [comment]
Karma is already set. Closing this one.
