### ISSUE TITLE
Make fetching pull request locally easy

### ISSUE THREAD

**Issue by TroJan** [Cloud-CV/EvalAI#782]
This involves writing a bash script which will help reviewer to locally fetch a pull request and test it thoroughly on its local machine.

For reference you can consider github [checking out pull request](https://help.github.com/articles/checking-out-pull-requests-locally/#modifying-an-inactive-pull-request-locally) documentation

Details about the script:

**Path**: scripts/tools (create this folder if it does not exist)
Script will take 2 command line arguments 
* Id of pull request
* remote(default value is upstream)

So script will be run like

```
./scripts/tools/fetch-pull-request <pull_request_id> <remote>
```

The checkout branch for review should have name something like `review-<pull_request_id>`.

**Comment by gauthamzz** [comment]
can i try this ?

**Comment by TroJan** [comment]
@gauthamzz : sure assigning this to you :)

**Comment by TroJan** [comment]
@gauthamzz : thanks for the fix. :)
