### ISSUE TITLE
Move connection params out of worker to settings

### ISSUE THREAD

**Issue by TroJan** [Cloud-CV/EvalAI#783]
We are using RabbitMQ to publish messages for submission and execute them. RabbitMQ needs some connection parameters like host name, exchange name, queue name, etc.

To consume message from the queue, a worker is written. This workers lives at `scripts/workers/submission_worker.py`.  

Presently the connection as well as exchange parameters are hardcoded in that file. Ideally they should be present in environment variables. But as of now we can avoid keeping them in environment variables and instead leverage Django settings.

So this task involves moving the connection parameters to settings. Concerned parameters are 
* host
* exchange name
* exchange type
* submission queue name
* submission queue parameters

As of now all the parameters can live in base settings. Also please make sure that you define a dict something like `RABBITMQ_PARAMETERS` and within it multiple keys for host, exchange and all.
So final value of variable should look like

```
RABBITMQ_PARAMETERS = {
    'HOST': 'value',
    'EXCHANGE_NAME': 'value'
    'SUBMISSION_QUEUE': {
        'NAME': 'value',
        ....
    }
}
```

**Comment by mayank-agarwal-96** [comment]
Can I work on this issue?

**Comment by TroJan** [comment]
@mayank-agarwal-96 : sure. assigning it to you.

**Comment by mayank-agarwal-96** [comment]
Should I make the changes in 'settings.dev' or 'settings.common'? The default settings in submission_worker.py is 'settings.dev'.
