### ISSUE TITLE
Dropdown for emails of other users in team invite popup .

### ISSUE THREAD

**Issue by Curious72** [Cloud-CV/EvalAI#788]
Currently the invite for team involves a popup with an input field for email address . If the user is not sure about the email address of the person he/she wants to invite , they will not be able to send the invite . To solve this issue , there should be a dropdown to show the email ids along with username , of users with emails matching with the user's query.

@deshraj @aka-jain @spyshiv What do you think about this ? Can i work on this ?

**Comment by aka-jain** [comment]
@deshraj I think that should be come in our V2, however it will be a critical task. Thoughts?

**Comment by deshraj** [comment]
I don't think we would want to show the email ids of other participants. So, we would rather show their usernames and their First and Last name in that place. Accordingly, the backend API will change. 
Let me know @Curious72 if you are interested in working on this issue. :)

**Comment by Curious72** [comment]
@deshraj Sure i would really like to work on this :)

**Comment by deshraj** [comment]
@Curious72 any update on this? Please let us know if you are busy with something else. Anyone else can handle this in that case.

**Comment by chan24** [comment]
@deshraj can you assign me this issue?

**Comment by Curious72** [comment]
@deshraj I am working on it !

**Comment by deshraj** [comment]
@Curious72 please keep me posted with this issue.

**Comment by deshraj** [comment]
Update: we don't want to expose the email id of the users and hence this feature is not a valid feature to have. Closing this one.
