### ISSUE TITLE
Correct the toaster message.

### ISSUE THREAD

**Issue by jainarunarunjain** [Cloud-CV/EvalAI#789]
Add space in send invite toaster message in My Host Team.
@aka-jain @spyshiv Can i work on this.

**Comment by aka-jain** [comment]
@jainarunarunjain Please attach a screenshot of the bug.

**Comment by jainarunarunjain** [comment]
![screenshot from 2017-03-04 20-04-42](https://cloud.githubusercontent.com/assets/16155501/23579562/1b6d769c-0116-11e7-9811-4be933dde159.png)
There should be a space.

**Comment by singhpratyush** [comment]
![screenshot from 2017-03-04 20-19-53](https://cloud.githubusercontent.com/assets/10860278/23579678/0c57c2e6-0118-11e7-87d0-c0ac21d03b93.png)
Well I don't see the issue. That `c` in lowercase looks weird though.

**Comment by jainarunarunjain** [comment]
@singhpratyush Please check it once because i think you are in My Participant Team and the bug is in My Host Team

**Comment by singhpratyush** [comment]
Oops, my fault. It is there in the `My Host Team` view.

**Comment by aka-jain** [comment]
@jainarunarunjain Make this message "Invitation failed. Please try again"

**Comment by jainarunarunjain** [comment]
@aka-jain Sure.

**Comment by aka-jain** [comment]
Oh my bad, just give a space there. I misunderstood something.

**Comment by spyshiv** [comment]
this is fixed in #794 
Closing this...
