### ISSUE TITLE
Give user rating based on his performance in contests

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#792]
@aka-jain @deshraj @spyshiv does it sound good?

**Comment by spyshiv** [comment]
@Ram81 : Can you elaborate it ?? How will you approach to implement this feature?

**Comment by Ram81** [comment]
For each contest user participated in we will give user rating based on his rank in the particular contest(it will be relative & will involve some math) then add this rating to his current rating to obtain his average rating & thus we can show his progress by change in his rating. does it sound good? @spyshiv

**Comment by aka-jain** [comment]
@Ram81 but rank is enough to show the capability of a user. Why we need rating or what will be the plus point for adding rating? Yes we can show that in how many challenges he has participated with average rank. But I don't think that user rating will be useful in any way. 
Let's take other thoughts too.

**Comment by Ram81** [comment]
@aka-jain when I do competitive programming after each contest when I see change in rating then I get encouraged about doing it more in order to improve that's why I thought this feature would help us to get more user try using our platform so that they can test there skills.

**Comment by aka-jain** [comment]
@spyshiv @deshraj Need your thoughts here.

**Comment by Ram81** [comment]
@deshraj @aka-jain @spyshiv we can use such a formula for calculating the rating of a user
https://www.codechef.com/ratings

**Comment by aka-jain** [comment]
@deshraj what do you think about this feature. Shall we close this or move with it?

**Comment by deshraj** [comment]
This feature is something that we should definitely keep but this is not in the current roadmap. I will look into this and add it in the roadmap for the near future. 

@Ram81 Thanks for suggesting this feature. :)

**Comment by Ram81** [comment]
Thanks @deshraj and @aka-jain
