### ISSUE TITLE
Show the users skill in his profile

### ISSUE THREAD

**Issue by Ram81** [Cloud-CV/EvalAI#793]
based on the contests submission a user has made in particular language we should show the skill level of user in the language in profile as we can see on hackerearth. @aka-jain @deshraj @spyshiv  what about this feature?

**Comment by aka-jain** [comment]
We have this feature in our mind already but will start implementing in V2. Closing it for now.
@deshraj I think we should start discussing about additional features on Gitter, issue page is not looking a good option. Thoughts?
