### ISSUE TITLE
Facebook icon present only on dashboard and not on other pages.

### ISSUE THREAD

**Issue by mayank-agarwal-96** [Cloud-CV/EvalAI#798]
Facebook icon is present on Dashboard but missing on Home, About us and Team.

**Comment by mayank-agarwal-96** [comment]
@TroJan This is just a minor thing I noticed. Can I fix this?

**Comment by deshraj** [comment]
It would be great if you can create a single view for this and use it in all the other views. :)

**Comment by mayank-agarwal-96** [comment]
@deshraj Sure I will give it a shot :) Thanks

**Comment by aka-jain** [comment]
I think you just need to remove Facebook icon from dashboard view. As we don't have Facebook links for now. @deshraj thoughts?

**Comment by mayank-agarwal-96** [comment]
@aka-jain I think any of them will work as the goal is to create a single view and use it.

**Comment by aka-jain** [comment]
Are you talking about Facebook in footer?

**Comment by mayank-agarwal-96** [comment]
@aka-jain Yes, I mean we can choose to keep it or not to keep it as the primary objective is to use a single view and use it everywhere.

**Comment by aka-jain** [comment]
Agree with you @mayank-agarwal-96 , but dashboard and other pages footers are little different in styles. Basically we are using flex to dashoard footer and not in other pages that's why we have two different footer. 
So just remove that facebook icon from the dashboard footer.

**Comment by mayank-agarwal-96** [comment]
@aka-jain Oh , I didn't know about it! Then I will just remove the icon from the Dashboard footer.
