### ISSUE TITLE
Django Profiling

### ISSUE THREAD

**Issue by yadavankit** [Cloud-CV/EvalAI#799]
There isn't any provision for reviewing the following -

- [ ] Intercept and store `Requests`

- [ ] How many `Queries` are used per page

- [ ] How much time is spent by a `Request` on `Django`, `Queries` etc.

- [ ] How heavy our pages are

**Comment by yadavankit** [comment]
@deshraj @TroJan your thoughts?

**Comment by TroJan** [comment]
@yadavankit : I appreciate your thought for this. Just that I and @deshraj are a little busy with many other things, So if possible you can take a lead and lets us know what APIS, pages are causing bottleneck. This will involve you doing a detailed analysis of things. Analysis as you pointed out will include queries run, time taken for a request and many other paramteres.

You can use [django-debug-toolbar](https://github.com/jazzband/django-debug-toolbar).

**Comment by yadavankit** [comment]
@TroJan sounds good :)

**Comment by yadavankit** [comment]
@TroJan I researched a bit about the approach I am gonna take and IMHO, we should use [opbeat](https://opbeat.com/) for the aforesaid tasks. Thoughts?

**Comment by deshraj** [comment]
@yadavankit closing this for now since this is not on roadmap for now. Will reopen it once we start working on this. Thanks for suggesting this feature. :)
