### ISSUE TITLE
Fix footer alignment in T&C page.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#804]

**Comment by jainarunarunjain** [comment]
@aka-jain Can i work on this.

**Comment by spyshiv** [comment]
@jainarunarunjain : Assigning this to you.

**Comment by jainarunarunjain** [comment]
@aka-jain @spyshiv There is nothing to fix, Everything is ok.
![screenshot from 2017-03-06 20-19-05](https://cloud.githubusercontent.com/assets/16155501/23615018/0cdba68a-02ab-11e7-916c-93137a04054b.png)

**Comment by aka-jain** [comment]
Sorry, my bad.
