### ISSUE TITLE
Frontend: Remove lint errors and clean the code

### ISSUE THREAD

**Issue by spyshiv** [Cloud-CV/EvalAI#805]
Steps to follow:

1. Run `gulp lint` and see the errors in the terminal
2. Remove all the warnings and errors.
3. `jshint` has been removed from linting purpose so if you see any comment named `jshint` then remove it.
4. if you see warning `Unexpected console statement` then remove the console from the js file. And if console is important to be written then refer this [link](http://eslint.org/docs/rules/no-console) and it's your call that how you gonna fix that.

PS: It's and important task and need to be done ASAP.

**Comment by AnshulBasia** [comment]
#806 

gulp lint is not throwing any errors. All comments containing jshint have been removed.
![qw](https://cloud.githubusercontent.com/assets/12856392/23610905/9d1d3d00-029a-11e7-88cb-2dbf63ca9d65.png)

**Comment by spyshiv** [comment]
@AnshulBasia : Before doing anything regarding this issue, You should have asked any mentors (including me) to assign this issue to you. But now I can't assign this to you since it's critical and might be a blocker for frontend development. Please look for another issues. 
Thanks.

**Comment by AnshulBasia** [comment]
@spyshiv  It's alright. Although, I am willing to do the same changes to updated master, if you suggest so. Thanks for your time.

**Comment by jainarunarunjain** [comment]
@spyshiv Is anyone working on this or shall i try.

**Comment by spyshiv** [comment]
Sure @jainarunarunjain . Please try to finish it ASAP....
Assigning to you...
