### ISSUE TITLE
Improved password change feature view.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#810]
Steps to do:
1. After successfully password change, show a modal which will asks user to "stay" or "login again".
2. If user selects "Stay" then do nothing if user clicks "Login again" then make user log out and open login page view.

@spyshiv any thoughts?

**Comment by mayank-agarwal-96** [comment]
I want to work on this.

**Comment by spyshiv** [comment]
@aka-jain : nice idea. 👍

**Comment by aka-jain** [comment]
Great. @mayank-agarwal-96 assigning it to you. Please do it ASAP :)

**Comment by mayank-agarwal-96** [comment]
@aka-jain I am facing problems while I am trying to change password. When I tried changing password, it said "something went wrong" and there were warnings in Django server. 
Also a new issue I faced was, suppose my old password is "12345678" and I enter "123456789" in both old password and new password field, it says "Old password cannot be same as New Password" while my old password was never "123456789".

**Comment by aka-jain** [comment]
What are the errors?
Yes, I know that old password field is not matching correctly. Will open a separate issue for that.

**Comment by mayank-agarwal-96** [comment]
Now the feature worked fine. I think the errors are because of some response from the API. When I tried a password which was similar to my old password (only one char different) , it showed "Something went wrong" but when I chose an entirely fresh password, it worked fine.

**Comment by deshraj** [comment]
Sorry, I didn't keep track of this issue. We should control this at the backend side and not at the client side. Closing this issue and the respective Pull Request.
