### ISSUE TITLE
Write a sass mixin to provide crossbrowser support to keyframes. 

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#811]
Currently we are using animation with only default keyframes. Need to make a mixin for these keyframes such that it covers atleast four browsers namely Chrome, Firefox, Opera, Safari. 
For any help check out sass mixins for keyframes http://sass-lang.com/guide.

p.s example out rocket animation in landing page.

**Comment by anweshknayak** [comment]
> You need to include the browser-specific keyframe animations with their browser-specific transforms within them

This we need to do? Just curious.

Ref : http://stackoverflow.com/a/20617786/4037592

**Comment by aka-jain** [comment]
@anweshknayak yes but with mixin.

**Comment by anweshknayak** [comment]
@aka-jain can I try this? I will try to do it asap.

**Comment by aka-jain** [comment]
Sure @anweshknayak, go ahead.

**Comment by aka-jain** [comment]
@anweshknayak status? Let me know if you are busy with some other issue.

**Comment by anweshknayak** [comment]
@aka-jain I will not be able to work on issues till tomorrow.  Busy with college stuff.

**Comment by aka-jain** [comment]
Okay, please inform us in case if you are unable to do any task. 
I'm making this issue free till then.

**Comment by anweshknayak** [comment]
@aka-jain sure :)

**Comment by aka-jain** [comment]
@Ram81 Can you do this?

**Comment by spyshiv** [comment]
@aka-jain : I am assigning this to myself.

**Comment by aka-jain** [comment]
Sure @spyshiv

**Comment by NSDCars5** [comment]
@aka-jain Is this still needed? The latest versions of all four mentioned browsers support keyframes unprefixed.

https://caniuse.com/#feat=css-animation

**Comment by aka-jain** [comment]
Yes @NSDCars5, you can work on this.

**Comment by spyshiv** [comment]
FYI @NSDCars5 It's not about modern browsers. We are using `autoprefixer` in gulp file that does that. 
Check that out https://github.com/Cloud-CV/EvalAI/blob/e6f8065b63a604fd842c5c48f644c86556f26604/gulpfile.js#L101

**Comment by NSDCars5** [comment]
@spyshiv Oh, okay, makes sense. 

Again, in that case, autoprefixer is already supporting the last two versions of major browsers, so the mixin shouldn't be needed?

**Comment by spyshiv** [comment]
@NSDCars5 I agree mixins shouldn't be used since we are using autoprefixer.
Closing this issue since this is not needed anymore.
