### ISSUE TITLE
Redesign auth view like we have other pages.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#815]
Redesign auth views, namely:
Reset Password
Email Confirmation

@deshraj add other auth views too if I left any.

**Comment by Ram81** [comment]
@aka-jain can I take this one?

**Comment by aka-jain** [comment]
Sure @Ram81.

**Comment by deshraj** [comment]
@aka-jain is it different from #996?

**Comment by aka-jain** [comment]
@deshraj description updated!

**Comment by deshraj** [comment]
Fixed in #999. Closing it.
