### ISSUE TITLE
Footer not fixed in Join-Us Page

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#824]
Please see the screenshot below for reference: 
<img width="1440" alt="screen shot 2017-03-10 at 7 27 34 pm" src="https://cloud.githubusercontent.com/assets/2945708/23818264/a90f7bf2-05c7-11e7-93c5-13b4a31f1399.png">

**Comment by Ram81** [comment]
@deshraj can I take this one?

**Comment by deshraj** [comment]
Sure. :)

**Comment by Ram81** [comment]
@deshraj  you can close this.

**Comment by aka-jain** [comment]
Fixed with #830
