### ISSUE TITLE
Add field named method_name in Submission model

### ISSUE THREAD

**Issue by TroJan** [Cloud-CV/EvalAI#826]
_What ?_

Add a field named `method_name` in `Submission` model of `jobs` app. The field should be a CharField with maximum length as 1000. The field will be nullable.

_Why ?_

So that a user or challenge host can track which method(like KNN, etc) is being used to make a submission.
It is optional because many a times no such definite name of function need not be present.

_How ?_

This issue will involve updating `Submission` model of `jobs` app. A CharField with a maximum length of 1000 which can be null will be added. Corresponding to this change, a named migration will also be added.

_Impact/Learning ?_

Learning about various types of [Django model fields](https://docs.djangoproject.com/en/1.10/ref/models/fields/). Also a bit about what are [Django migration](https://docs.djangoproject.com/en/1.10/topics/migrations/) and how they work.

**Comment by RishabhJain2018** [comment]
@TroJan Can I work on this?

**Comment by TroJan** [comment]
@RishabhJain2018 : sure :)
