### ISSUE TITLE
Change binding key for submission worker

### ISSUE THREAD

**Issue by TroJan** [Cloud-CV/EvalAI#835]
__Problem__

Presently submission worker creates an exclusive queue and binds on that queue with a key of `challenge.add.*`.

__Why__ ?

The key needs to be changed because we need to add support for editing of challenge file also. In the future we will bind on key `challenge.*.*` and then add a check in the code to take action accordingly

__Impact__ ?

It will extend submission worker to add support for scenarios where challenge related files are being edited.

__How__ ?

The relevant code is in file `scripts/workers/submission_worker.py`. Ideally the key should now be `challenge.*.*`

__TakeAways__

About RabbitMq, Exlcusive Queue and binding keys

**Comment by RishabhJain2018** [comment]
@TroJan Can I work on this?

**Comment by TroJan** [comment]
@RishabhJain2018 : thanks for the fix. :)

**Comment by RishabhJain2018** [comment]
@TroJan Welcome ! :)
