### ISSUE TITLE
"New password can't be same as old password" displayed in password change view even when old password inserted is wrong.

### ISSUE THREAD

**Issue by mayank-agarwal-96** [Cloud-CV/EvalAI#837]
@deshraj @aka-jain @TroJan What do you think about this?
This should not be a front end validation. Rather such errors and warnings should be part of API responses.

**Comment by xamfy** [comment]
@deshraj I think this issue should be closed.

**Comment by deshraj** [comment]
Thanks for noticing @xamfy. Closing this.
