### ISSUE TITLE
Scroll to details section on home page.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#84]
There is an option to scroll up to second section in  Landing page by clicking on "Get Insight". Need to implement smooth scroll which will scroll the page with in limit of atmax 2ms.

In case of query, leave your comment here.

**Comment by anweshknayak** [comment]
Where shall I add the script ? Shall I create a separate script file under /src/controllers or create a custom separate function in any of the scripts present in  /src/controllers ?

**Comment by aka-jain** [comment]
Can you make a directive for this?

**Comment by anweshknayak** [comment]
https://github.com/oblador/angular-scroll/ Can I add these instead in the dependecies file of bower ? and use it.

**Comment by aka-jain** [comment]
Sure, you can use it.

**Comment by anweshknayak** [comment]
/frontend/bower_components. The script files here , can you tell where this are imported so that they are being used in the actual code ?

**Comment by aka-jain** [comment]
For your information, to add external files, add their file path in app.script.json in case of JS and app.styles.json in case of CSS. And run gulp dev which will build vendor.js and vendor.css. Then you don't need to add their paths in index file externally.
Let me know in case of query.

**Comment by anweshknayak** [comment]
after installing the library and setting the path. do I need to manually import the directive in the landing.html file by adding ng-model and ng-app or it directly imports the function from the path provided ?

**Comment by aka-jain** [comment]
For adding any dependency use **app.js** file, and in case you want to write a directive then write it in **directive.js** file. No need to add paths manually.
