### ISSUE TITLE
Publish message whenever file field of Challenge and Challenge Phase changes

### ISSUE THREAD

**Issue by taranjeet** [Cloud-CV/EvalAI#841]
__Problem__

We need to propagate changes related to `test_annotation` and `evaluation_script` to the submission worker. The support for handling the change already in the worker is being taken care of in [Issue 840](https://github.com/Cloud-CV/EvalAI/issues/840). We need to add support for publishing message when ever any such change happens.

__Please be more clear__ ?

When ever `evaluation_script` or `test_annotation` file of Challenge or ChallengePhase changes, we need a way to tell this to submission worker that the files have changed and you need to update the files.

The best way can be by using a Queue based architecture and publishing a message to the exchange.

__Why__ ?

Submission worker when starts loads all `evaluation_script` and `test_annotation` file in advance. In case if the Challenge Host updates any of the file, there is no way to communicate this to the worker.

If the worker is not communicated about the changes, then submissions may be evaluated with the wrong set of parameters.

__Impact__ ?

It actually guarantees that whenever any submission is evaluated, it is evaluated against the write set of parameters.

__How__ ?

It can be done by capturing the update of concerned models(here _Challenge_ and _ChallengePhase_).
[Issue 839](https://github.com/Cloud-CV/EvalAI/issues/839) deals with this. The print statement in that issue can now be modified and there a new message can be published.

The __content__ of the message still needs to be figured out by the __contributor__. I will prefer that you publish only primary keys in the message but this is still open to discussion.

Regarding how to publish message, you can take help from function `publish_submission_message` of `jobs/sender.py`. The published message will have a routing key of `challenge.edit.*`.

__TakeAways__

How Exchanges work in RabbitMQ, how message are routed to the exchange ?

Also I will prefer that before coding, its better to discuss the approach over here only, so that we can get an idea and update if something is not right.

**Comment by gauthamzz** [comment]
can i try ?

**Comment by TroJan** [comment]
@gauthamzz : sure :)

**Comment by TroJan** [comment]
@gauthamzz : Let me know if you are struck somewhere. We can discuss it over here. :)

**Comment by gauthamzz** [comment]
I'm still reading, new to this, will get this done fast .I hope it's fine. 😊

**Comment by TroJan** [comment]
@gauthamzz : Any update on this, You can actually ask here if you are struck somewhere.

**Comment by TroJan** [comment]
@gauthamzz : any progress on this?

**Comment by gauthamzz** [comment]
@TroJan i been trying, but this is kinda very new . Could you help out?

**Comment by TroJan** [comment]
@gauthamzz : yeah tell me where are you struck?

**Comment by TroJan** [comment]
@gauthamzz : any update on this?

**Comment by gauthamzz** [comment]
sorry ,i kind of got busy in exams and stuff ,hope it was okay

**Comment by isht3** [comment]
@taranjeet Can I take over?

**Comment by taranjeet** [comment]
@isht3 : yeah please. :)

**Comment by isht3** [comment]
@taranjeet Where should I start to get a deeper insight to the problem?

**Comment by isht3** [comment]
@taranjeet I've started working on this. I will soon let you know about the progress.

**Comment by isht3** [comment]
@taranjeet how do I confirm my email in development? I was trying to mimic the process of submitting a task to produce the issue. Do I have to do it through the API's?

**Comment by RishabhJain2018** [comment]
@isht3 You can confirm it using django admin.

**Comment by isht3** [comment]
@RishabhJain2018 Okay, cool!

**Comment by isht3** [comment]
Hi, @taranjeet and @RishabhJain2018 I've looked into this issue and gone through how submissions and challenges work. I have gotten a good idea of how everything fits together now.
Now, from my understanding only two things need to be done,

* Change the content of print statement in Challenge model.
* Publish a message to the RabbitMQ exchange through `jobs/sender.py` whenever there is an update to `test_annotation` and `evaluation_script`.

I will post the contents of the message here soon, so you could review it.

**Comment by isht3** [comment]
@RishabhJain2018 

```
It can be done by capturing the update of concerned models(here Challenge and ChallengePhase).
Issue 839 deals with this. The print statement in that issue can now be modified and there a new message can be published.
```
This talks about an print statement in the Issue 839 that I should change, but I can't find any such statement. Is it referring to the logger statement?

**Comment by isht3** [comment]
@deshraj This issue and #842 seems to be related, can I work on this? :smile:

**Comment by isht3** [comment]
@RishabhJain2018 The print statement mentioned in this issue is the model field logger you wrote in https://github.com/Cloud-CV/EvalAI/blob/57e5fb3d2fcdc8e6a7699638a320bdaade817101/apps/base/models.py#L40 Yes?

**Comment by taranjeet** [comment]
@deshraj @RishabhJain2018 : Is this issue still required? If not can we please close it?

**Comment by deshraj** [comment]
Similar to #842. Closing it. Thanks for pointing out @taranjeet :)
