### ISSUE TITLE
Fade Effects on route change

### ISSUE THREAD

**Issue by anweshknayak** [Cloud-CV/EvalAI#847]
@aka-jain @spyshiv is it good ?

**Comment by aka-jain** [comment]
Not getting. Please elaborate!

**Comment by anweshknayak** [comment]
@aka-jain Like this one (https://tympanus.net/Tutorials/CSS3ContentTabs/)

**Comment by aka-jain** [comment]
Yes we can, but these are not tabs basically these are routes. So I'm giving upon you to find the solution for this.

**Comment by anweshknayak** [comment]
Ohh sure @aka-jain  :smiley:

**Comment by anweshknayak** [comment]
@aka-jain found something here http://jasonwatmore.com/post/2016/01/20/angular-nganimate-tutorial-with-ui-router

**Comment by aka-jain** [comment]
@anweshknayak go ahead and do this task!

**Comment by aka-jain** [comment]
@anweshknayak progress?

**Comment by anweshknayak** [comment]
@aka-jain you can make this issue free for others. :) I haven't started working on this yet

**Comment by aka-jain** [comment]
This feature isn't much needed, so closing it for now.
