### ISSUE TITLE
Add nullable attribute to the Team Model

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#848]
Following changes are required in the Team model: 

- [ ] Convert the URLFields to CharField with URL

- [ ] Change the fields `email`, `github_url`, `linkedin_url`, `personal_website` to nullable fields

**Comment by RishabhJain2018** [comment]
@deshraj Can I work on this?

**Comment by deshraj** [comment]
Yeah sure. Go ahead. :)

**Comment by RishabhJain2018** [comment]
@deshraj Can we use `[slugfield](https://docs.djangoproject.com/en/1.8/ref/models/fields/#slugfield)` for this?

**Comment by deshraj** [comment]
No, can you please change them with `CharField` ?

**Comment by RishabhJain2018** [comment]
@deshraj okay sure.
