### ISSUE TITLE
Create an API Endpoint to show all the submissions to Challenge Host for a particular Challenge

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#850]
### Objective

The aim is to create an API endpoint which fetches all the submissions of a Challenge and and returns as a JSON Response. 

### Constraints:
- URL: `/api/challenges/<challenge_pk>/submissions/`
- Only the Challenge Host of that particular challenge can access this information. 
- Request Method: `GET`
- Response on success: `200`
- Response on not allowed: `406`
- Pagination: `YES`

### Stretch Goal
After we have the API ready, we would like to add support for filtering the submissions according to the `date of submission`, `challenge phase`, `status of submissions`.

**Comment by yadavankit** [comment]
@deshraj can I work on this one?

**Comment by AliRaza3997** [comment]
@deshraj can I work on this?

**Comment by deshraj** [comment]
@yadavankit Yeah, you can work on this. :)

**Comment by deshraj** [comment]
@yadavankit Please don't start working on this if you haven't started yet. I would like to do it myself since we need this feature ASAP. Sorry for the last minute information.

**Comment by yadavankit** [comment]
@deshraj I saw this just now, had to run some errands. No issues :)

**Comment by deshraj** [comment]
Cool, thanks for coordinating. :)
