### ISSUE TITLE
Create view to show all the submissions of a Challenge to Challenge Hosts

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#851]
### Objective

Create a view that will show all the submissions to a Challenge. The link should be shown as a different tab in the Challenge View to Challenge Hosts of that Challenge. 
*Note:* This can be only seen by the Challenge Host of a Particular challenge. 

### Reference

It would be very similar to the `My Submissions` view of a challenge. Please let us know if you need help with this. 

### Depends On

#850

**Comment by Ram81** [comment]
@deshraj  can you share the design of this page or should I try one that will match our current design?

**Comment by RishabhJain2018** [comment]
@deshraj Since we have this feature. We should close this now.
