### ISSUE TITLE
Contact Us form not working properly

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#853]
The Contact Form is not working properly. Please check the console logs and fix it accordingly.

**Comment by RishabhJain2018** [comment]
@deshraj Can I work on this?

**Comment by RishabhJain2018** [comment]
@deshraj I think we should also modify this api to also return the `name` and `email` of the user on the `GET` request as it will be handy for the user not to fill the name & email in the contact form once he is logged in.
Moreover, we are also taking the `name` and `email` of the user from the database only , if he is logged in. Please refer [here](https://github.com/Cloud-CV/EvalAI/blob/master/apps/web/views.py#L37).
What do you say?

**Comment by deshraj** [comment]
I think we should just fill the name and email address already in the contact form if the user is already logged in.

**Comment by RishabhJain2018** [comment]
@deshraj Yeah. For that we need to modify the api. I think a separate issue will be good for this. What do you say?

**Comment by deshraj** [comment]
Sounds good to me.

**Comment by RishabhJain2018** [comment]
@deshraj Please check it once , I think it is not fixed.

**Comment by deshraj** [comment]
@RishabhJain2018 Thanks for pointing out. Reopening it now.

**Comment by aka-jain** [comment]
@RishabhJain2018 Is it done?

**Comment by RishabhJain2018** [comment]
@aka-jain No, Actually I need to change the API accordingly, I will fix it asap.

**Comment by aka-jain** [comment]
Sure 👍
