### ISSUE TITLE
Setup Sphinx Documentation

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#854]
All the documentation of EvalAI resides in `/docs` folder in the project repository. We would like to setup sphinx documentation at `/docs` for this project. Since we use the `.md` extension file format, so it would be easy to set it up. 

For more details, please see https://daler.github.io/sphinxdoc-test/includeme.html

**Comment by AnshulBasia** [comment]
Any clue with the error:
'''
make html
make: *** No rule to make target 'html'.  Stop.
'''

**Comment by AnshulBasia** [comment]
![make_latex](https://cloud.githubusercontent.com/assets/12856392/24202908/3ddae5de-0f3a-11e7-8ac3-a971208e4472.png)
@deshraj  make HTML was successful but please check this error in make  latexpdf.

**Comment by deshraj** [comment]
@AnshulBasia we dont need the `make latexpdf`. We just need to build the html files.

**Comment by AnshulBasia** [comment]
@deshraj Please let me know if there's any issue..?

**Comment by RishabhJain2018** [comment]
@deshraj I think we should close this.

**Comment by RishabhJain2018** [comment]
@deshraj Since we have docs setup from PR #1090. So, I closing this one.
