### ISSUE TITLE
Create a template view to show after successful email verification during Signup

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#857]
### Description

When a user registers on EvalAI, he receives an email that contains a unique link to confirm his email id. Whenever he clicks on the link, he should be shown a static page similar to this http://api.evalai.cloudcv.org/api/auth/registration/account-confirm-email/MTc:1cpmQ6:0_PqK9K-JJuKYxC3aSY2Bjt3OLU/

### Todo 

1. Override the URL Patterns for the URL  `/api/auth/registration/account-confirm-email/<token>/` to convert it to django TemplateView
2. Create a template at the backend that is served to the user whenever he clicks on the unique link.

**Comment by mayank-agarwal-96** [comment]
Can I work on this?

**Comment by deshraj** [comment]
@mayank-agarwal-96 sure.

**Comment by mayank-agarwal-96** [comment]
@deshraj Right now ConfirmEmailView ( which is an APIView ) is called on this url. So do I need to change this with a TemplateView?

**Comment by deshraj** [comment]
Yeah, please do that and delete the APIView in the views file.

**Comment by mayank-agarwal-96** [comment]
@deshraj Ok, thank you :)

**Comment by mayank-agarwal-96** [comment]
@deshraj I am stuck on finding a good way to reuse css and images in the frontend directory for the email confirmation template. Will adding it to static help?

**Comment by deshraj** [comment]
@mayank-agarwal-96 Since both the frontend and backend are independent of each other, so it would be a good idea to not reuse the static files. Can you please create different static files for the backend?

**Comment by mayank-agarwal-96** [comment]
@deshraj Ok sure, it would also be easier to create new static files.
