### ISSUE TITLE
Update Privacy and Terms Page

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#858]
Currently the Privacy and Terms page contains fake data. We would want to update it with the information at this link: https://github.com/Cloud-CV/EvalAI/wiki/Privacy-and-Terms

**Comment by Ram81** [comment]
@deshraj can I take this one?

**Comment by deshraj** [comment]
Yeah sure.

**Comment by AliRaza3997** [comment]
I have done this. Kindly check the pull request.

**Comment by AliRaza3997** [comment]
@deshraj I have done this. Kindly check the pull request.

**Comment by deshraj** [comment]
@AliRaza3997 Thanks for submitting the Pull request. I would suggest that please donot work on any issue on which someone else is working on. I am accepting this since you are new. Please keep this in mind in future. :) 

@Ram81 Please don't start working on this feature. Sorry for the inconvenience.

**Comment by AliRaza3997** [comment]
Sorry for the inconvenience. Didn't see any assignment when I started working on it. I would keep this in mind the next time and ask first. Thanks.
