### ISSUE TITLE
Disable change of 'username' on client side on Update Profile View

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#863]
A user should not be able to change his username once he has created his account. 

### TODO

Disable the username field in the `Update Profile` view to make sure a user cannot modify his username.

**Comment by mayank-agarwal-96** [comment]
Can I work on this?

**Comment by deshraj** [comment]
Sure.

**Comment by ishapotnis1** [comment]
@deshraj If this issue is still open I would like to try it.

**Comment by deshraj** [comment]
@ishapotnis1 I think @mayank-agarwal-96 is already working on this. Feel free to look for other issues.

**Comment by mayank-agarwal-96** [comment]
@deshraj Shall I make the input field disabled or completely remove the username field? When I am disabling the field, the animation for "Username" also stops working leading to something like this:
![screenshot from 2017-03-26 18-28-14](https://cloud.githubusercontent.com/assets/11095642/24331450/690c7cf2-1252-11e7-8981-f89e9171942f.png)

**Comment by deshraj** [comment]
I think you can convert the username `field` from a form-field to a `<p>` tag or something similar depending on which will look good.

**Comment by Shashi456** [comment]
Instead of disabling the field i made it readonly , so now the issue of the animation not working would not arise , does that sound good enough
?

**Comment by spyshiv** [comment]
@mayank-agarwal-96  @Shashi456 : FYI, Add `class="active"` to `label` to see focus effect on `username`.

**Comment by spyshiv** [comment]
Fixed in #894. 
Closing this.
