### ISSUE TITLE
Restrict the update profile API Endpoint from updating username 

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#864]
Currently, django-rest-auth provides the functionality to update the username with the update profile API Endpoint. We want to restrict this since we don't want a user to update his username once he has created his account. 

For more details about the API endpoint, look at http://django-rest-auth.readthedocs.io/en/latest/api_endpoints.html#basic

**Comment by deshraj** [comment]
Related to #863

**Comment by yadavankit** [comment]
@deshraj can I take it up?

**Comment by deshraj** [comment]
@yadavankit Sure. :)

**Comment by mayank-agarwal-96** [comment]
@deshraj @yadavankit Is anyone still working on this or can I take this one?

**Comment by deshraj** [comment]
@mayank-agarwal-96 Yeah, you can work on it. :)

**Comment by yadavankit** [comment]
@deshraj ohh, I just forgot this issue... my bad 😅  @mayank-agarwal-96 yeah go on bro...you can take this up :)

**Comment by isht3** [comment]
Hi, I'm a bit new to restful services using django, and I guess that with a bit of learning I could solve this issue, where would be the best place to start using rest for evalai?

**Comment by yadavankit** [comment]
Hey @isht3 [Djnago REST Documentation](http://www.django-rest-framework.org/) would be a good place to start learning about how REST is implemented in EvalAI.

**Comment by isht3** [comment]
@taranjeet @yadavankit I'm currently in the process of learning django REST, I'd like to inform that I'll be back for bigger contributions to CloudCV after I'm done with a personal project of mine.

**Comment by deshraj** [comment]
@isht3 Sounds good. Thanks for informing. :)

**Comment by isht3** [comment]
@deshraj Can I start working on this? :)

**Comment by RishabhJain2018** [comment]
yes sure. Assigning this to you.

**Comment by isht3** [comment]
Hi, @deshraj @RishabhJain2018 To update the username after creation of account we should do a PUT request to `/api/auth/user/`, right? I'd like to test this for a bit, would it be best to do it through cURL or drf-docs?

**Comment by RishabhJain2018** [comment]
@isht3 Please refer here for the command https://pvcarrera.github.io/general/2015/03/18/curl.html. Moreover , you can use Postman client for the same. Let me know if you still have doubts.

**Comment by isht3** [comment]
@RishabhJain2018 I'll look into it! :smile:

**Comment by isht3** [comment]
@RishabhJain2018 Hi, I have analysed the issue. Since only the `PUT` request to the `/auth/user/` which contains `username` should be restricted, it would require writing a view to check the parameters passed, if it passes then pass it onto `rest_auth`, right?
