### ISSUE TITLE
Add Installation Guide for different Platforms

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#866]
We would like to add different markdown files for setting up IDE on different Platforms such as

- [x] Ubuntu
- [x] Fedora
- [ ] OS X
- [ ] Windows

**Comment by TroJan** [comment]
Concerned file for this is [setup.md](https://github.com/Cloud-CV/EvalAI/blob/master/docs/setup.md). For ubuntu the instructions are present, but one can actually update them if something is missing.

Also please update the markdown error in the same file(generally headings). Like

###Step 1: Install prerequisites  ---> ### Step 1: Install prerequisites

(A space needs to added after the hash series, ###)

**Comment by kakshay21** [comment]
@deshraj @TroJan  On it

**Comment by deshraj** [comment]
Closing this since installation works on all platforms now.
