### ISSUE TITLE
Use IsChallengeCreator decorator in Challenge Phase detail API Endpoint

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#879]
Currently, the check for if the requesting user is Creator of Challenge or not is missing from the `challenge_phase_detail` API View. We would like to add the `IsChallengeCreator` decorator (https://github.com/Cloud-CV/EvalAI/blob/master/apps/challenges/permissions.py#L6) to this endpoint. 

Also, please add test cases after making the above changes.

**Comment by AnshulBasia** [comment]
Can I work on this..?

**Comment by deshraj** [comment]
@AnshulBasia Sure. :)

**Comment by Shashi456** [comment]
@deshraj  can you tell me what exactly do we do after the check?

**Comment by deshraj** [comment]
@Shashi456 I think @AnshulBasia is already working on this. Feel free to pick any other unassigned issue. :)

**Comment by Shashi456** [comment]
@deshraj what about #863

**Comment by varunagrawal** [comment]
@AnshulBasia any updates on this? If you're busy, I can take it forward.

**Comment by AnshulBasia** [comment]
@varunagrawal Sorry,I am done but testing is yet to be done. I got stuck with my assignments. Please take it forward. Thanks.

**Comment by varunagrawal** [comment]
Sure thing mate @AnshulBasia. Thanks for letting us know. :)

**Comment by varunagrawal** [comment]
@deshraj please assign this to me.

**Comment by deshraj** [comment]
Sure.

**Comment by modestlearner** [comment]
@deshraj Can you please tell me what we need to do exactly.

**Comment by deshraj** [comment]
@modestlearner: This is quite critical and I would like to fix it myself. Can you please pick some other issue?

**Comment by modestlearner** [comment]
@deshraj Sure

**Comment by isht3** [comment]
@deshraj Is this solved?

**Comment by varunagrawal** [comment]
Hi @isht3, @deshraj has been on vacation the past few weeks and should be back today. Expect this to be solved sometime this week. :)

**Comment by isht3** [comment]
@varunagrawal Hope he had a good time, I'm going on vacation today! lol.

**Comment by deshraj** [comment]
@isht3: no, this issue is not solved yet. Please feel free to take this up.

**Comment by Obtin** [comment]
@isht3 are you working on this too. If not I would like to take this up Thank you.

**Comment by varunagrawal** [comment]
@isht3 Deshraj has given you the go ahead. If you don't have the time to work on this, we understand, and we can assign this to @Obtin

**Comment by isht3** [comment]
@varunagrawal, @Obtin Yes, I already started working on this. I was going through how to work on decorators, that's why this was taking time. I'll finish this by sometime next week. :smile:

**Comment by isht3** [comment]
@deshraj The `IsChallengeCreator` class and its use-cases should be completely replaced with the `IsChallengeCreator` decorator, yes?

**Comment by varunagrawal** [comment]
@isht3 no that class is required in the permissions since other API endpoints depend on it. You should just be able to add that permission class to the `@permission_classes` decorator and have it work. The crucial aspect of this issue are the test cases which need to ensure all corner cases are handled.

I know this seems like very little work technically, but then again, this is an easy issue to get people started with CloudCV contribution. :)

**Comment by isht3** [comment]
@varunagrawal I think the changes are already added to the `permission_classes`, I'll get started with writing the tests. Thank you for clearing it up!
