### ISSUE TITLE
Add Affiliation in Update Profile View

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#886]
Currently the user cannot set his affiliation to any organization. We would like to add the Affiliation to Update Profile view.

**Comment by DaivikDave** [comment]
i want to work on it.

**Comment by deshraj** [comment]
Sure, go ahead. :)

**Comment by DaivikDave** [comment]
@deshraj  is there a file or an issue that explains the code structure of the site. I'm having touble  in figuring out  which file to look at .

**Comment by deshraj** [comment]
@DaivikDave you have to make changes in the file https://github.com/Cloud-CV/EvalAI/blob/master/frontend/src/views/web/update-profile.html and to its controller that is here https://github.com/Cloud-CV/EvalAI/blob/master/frontend/src/js/controllers/updateProfileCtrl.js

**Comment by deshraj** [comment]
You will become familiar with the codebase as you start play around with it on your local machine.

**Comment by DaivikDave** [comment]
Yeah i viewed some python scripts and will work university affiliation and
some more issues. Can i mail you if i have some doubts?

**Comment by deshraj** [comment]
It would be great if you can comment here on the respective issues/PRs. We can also talk on gitter. There other contributors can also help you in making contribution to the project. You can also mail me. :)

**Comment by DaivikDave** [comment]
i have added university affiliation in html ,updateprofile.js, profile.html  but its not getting  updated.Also the university data is not fetched when i refresh the updateprofile.html.Is there a controller for profile.html? @deshraj @TroJan  @spyshiv

**Comment by varunagrawal** [comment]
@DaivikDave I would recommend opening a PR on your current work. That way we can take a look at your code and help direct you better. :)

**Comment by anirudhvenu** [comment]
@deshraj is this still open? I would like to work on it if it is.

**Comment by RishabhJain2018** [comment]
@anirudhvenu yes it is open. go ahead!

**Comment by RishabhJain2018** [comment]
@anirudhvenu Any update on this ?

**Comment by anirudhvenu** [comment]
@RishabhJain2018 Sorry for the delayed response. I changed update-profile.html, profile.html and updateProfileCtrl.js, however the affiliation is still not getting updated in the back-end. I have submitted a PR, would you be able to take a look at it?

**Comment by RishabhJain2018** [comment]
@anirudehdev Yes sure. I will review it :)

**Comment by anuj-rathore** [comment]
@RishabhJain2018  If nobody is working on it, can I take this?

**Comment by varunagrawal** [comment]
I guess we have to wait for the resolution of the previous PR. @anuj-rathore you should see what needs to be added on top of that in order to close this issue.
