### ISSUE TITLE
Change 'visible' field in Team model

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#889]
Currently the `visible` field is set to `True` as default in the Team model. We would like to set it to False. 

The line to be changed is https://github.com/Cloud-CV/EvalAI/blob/master/apps/web/models.py#L38

**Comment by Ram81** [comment]
@deshraj can I do this?

**Comment by deshraj** [comment]
Yep Sure.

**Comment by deshraj** [comment]
Fixed with #892
