### ISSUE TITLE
Add API Endpoint to add contributors in Team list

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#890]
### Objective

Build API Endpoint for adding new contributors to the Team Page

Method: `POST`
Endpoint: `/api/web/team`
Fields to accept: `Name`, `Email`, `Headshot`, `github_url`, `linkedin_url`, `personal_website`, `background_image`, `team_type='Contributor'`

Dependent on #889

**Comment by artkorenev** [comment]
I want to take this one.

Could you please share permissions that are needed for this method?

Thanks

**Comment by deshraj** [comment]
There are no permissions associated with this API Endpoint. Anyone can access this.

**Comment by deshraj** [comment]
Fixed with #899
