### ISSUE TITLE
Create a View to add contributors to Team Page

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#891]
Dependent on #889 and #890

**Comment by artkorenev** [comment]
@deshraj  I would take this one if you don't mind

**Comment by deshraj** [comment]
Sure. :)

**Comment by artkorenev** [comment]
Could you please clarify, you want to have a view on the page **SERVER/team**?
Thanks

**Comment by deshraj** [comment]
@artkorenev I didn't get your question here. Could you please elaborate more here?

**Comment by artkorenev** [comment]
Sorry, I wanted to clarify whether I should provide a view to this page https://evalai.cloudcv.org/team?

**Comment by varunagrawal** [comment]
@artkorenev I may be incorrect and @deshraj could provide more details, but having this view in the Admin panel makes more sense since this is primarily for the maintainers to update.

**Comment by deshraj** [comment]
@varunagrawal we wanted to keep it client side so that the contributors can fill the form themselves and then we can approve it at the backend. Please let me know if you have a better idea in mind. Welcome for new suggestions. :)

**Comment by varunagrawal** [comment]
Wouldn't it be cool if we could just use the Github API? 
[This](https://developer.github.com/v3/repos/#list-contributors) page tells us how to retrieve the list of contributors directly from the repo.

**Comment by deshraj** [comment]
@varunagrawal this sounds like a good idea but then we won't be able to update the personal website URL, LinkedIn URL, background headshot for the contributors.

**Comment by varunagrawal** [comment]
So here's an idea:
1. Set up Github webhook to fire whenever a PR is merged.
2. The webhook triggers an endpoint to query Github API for new contributors.
3. New contributors are added to the DB using their email from Github. If they have an account already, then continue, else send an email to the user saying they have been added as a contributor and they need to click a link to confirm their account creation.
4. The user can now sign in and update their details as required, adding the various URLs and images.

**Comment by deshraj** [comment]
This solution sounds perfect but might be an overkill to write code for this particular feature and not worth it. We could look for other Open Source Projects and see how they do it. 

One way is to create `CONTRIBUTORS.md` (most popular way of doing this). We might just parse it using a python script and add new contributors to the database accordingly. 

@TroJan do you have thoughts for this?

**Comment by varunagrawal** [comment]
@deshraj yeah it may be overkill for the simplicity of this feature. I was gunning for a fully automated process that required no work from us in the future. :blush:

**Comment by TroJan** [comment]
@deshraj : i think github approach would be an overkill right now. However I really appreciate your efforts @varunagrawal

**Comment by deshraj** [comment]
Cool. @artkorenev so can you please create a view similar to the `contact us` view?

**Comment by artkorenev** [comment]
@deshraj sure

**Comment by deshraj** [comment]
@artkorenev are you still working on this? Please let me know so that I can assign it to someone else if you are not working on this issue.

**Comment by artkorenev** [comment]
@deshraj sorry for the delay. Yeah, I am working on it. I have been a little bit overwhelmed with side activities for a couple of days.

**Comment by deshraj** [comment]
No issues. Please keep me posted if something comes up. :)

**Comment by deshraj** [comment]
Not needed anymore.
