### ISSUE TITLE
Add unique property to DatasetSplit codename

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#917]
Currently, there can be multiple dataset splits with the same codename and it leads to the exception of `MultiplObjectsReturned` in submission worker. 

### TODO
Add the unique property to `codename`  field in DatasetSplit model.

**Comment by mayank-agarwal-96** [comment]
@deshraj I want to take this up.

**Comment by deshraj** [comment]
Yeah sure. Assigning it to you. :)

**Comment by deshraj** [comment]
Fixed in #927
