### ISSUE TITLE
Blog link not working in footer.

### ISSUE THREAD

**Issue by RishabhJain2018** [Cloud-CV/EvalAI#920]
In the footer `Blog` is not hyperlinked.

**Comment by varunagrawal** [comment]
@RishabhJain2018 can you please provide detail about what the blog link should be? I don't see any URL setup for the blog in the code so I am guessing the blog will be hosted separately?

**Comment by RishabhJain2018** [comment]
@varunagrawal I think @deshraj or @dexter1691  can better answer this query. Actually I found it not working, so I opened up a issue so that we should not forget it in future. Let's wait for their answer.

**Comment by deshraj** [comment]
Thanks @RishabhJain2018 for opening this issue. We will host the blog separately using Github Pages. We haven't started working on the theme selection for the blog. We will start working on this soon.

**Comment by deshraj** [comment]
Closing this one since currently we have removed the blog link from the webapp.
