### ISSUE TITLE
Permission Denied - Unable to create or select a team

### ISSUE THREAD

**Issue by yogeshdarji99** [Cloud-CV/EvalAI#931]
I signed up and also verified my email twice, but when I click on Show all challenges --> View Details, i get this error everytime
<img width="1412" alt="screen shot 2017-04-12 at 10 48 11 am" src="https://cloud.githubusercontent.com/assets/11489650/24967031/5e32e41e-1f6e-11e7-9bfb-39a0eb5ba8e1.png">

Is it a known issue?

**Comment by deshraj** [comment]
@yogeshdarji99 this is not an issue. Can you please check `Email Address` model on django admin and see if the email is verified actually or not?

**Comment by varunagrawal** [comment]
@yogeshdarji99 when you created your account using the `dev.py` settings, the email verification link is output to your terminal. You need to copy and paste that link in your browser to allow EvalAI to confirm your account.

**Comment by deshraj** [comment]
Fixed in #940
