### ISSUE TITLE
Server is not running on gulp:dev runserver

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#937]
Due to breaking lint injection, lint is not working properly on calling gulp:devrunserver.

Call lint on starting of watch task too. It is working when it detects any file change so make it for first call too.

**Comment by aka-jain** [comment]
@RishabhJain2018 Next time try to check all the possible cases please!

**Comment by RishabhJain2018** [comment]
@aka-jain yeah sure. I apologise for it.

**Comment by varunagrawal** [comment]
@aka-jain did you identify the problem? If yes, can you please share? This is blocking testing for #913.

**Comment by deshraj** [comment]
This is resolved in #938. Closing this now.
