### ISSUE TITLE
Allow console statements in development enviornment

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/EvalAI#956]
### Current Behaviour

The `lint` task throws an error if we add console statements in the developement environment but it should be ideally allowed. See screenshot below for more details. 

![screen shot 2017-04-23 at 5 37 31 am](https://cloud.githubusercontent.com/assets/2945708/25312446/fce36c0c-27e6-11e7-8e7a-78187b6ff02a.png)

### Expected Behaviour

Allow the console statements in the development enviornment.

**Comment by spyshiv** [comment]
Fixed in #983.
