### ISSUE TITLE
Unnecessary Information on First Load 

### ISSUE THREAD

**Issue by aayusharora** [Cloud-CV/EvalAI#982]
### Steps to reproduce
- Go to https://evalai.cloudcv.org/
- Refresh the page and see the top right corner.
OS : `Ubuntu 14.04`
Browser: `Chrome Version 57.0.2987.133 (64-bit)`
### `Bug`
![45](https://cloud.githubusercontent.com/assets/12194719/25576554/c14ec57c-2e7d-11e7-9762-d5febde602e8.png)

### ` Expected `

![correct](https://cloud.githubusercontent.com/assets/12194719/25576731/b879330a-2e7e-11e7-8b4d-10c7ad01c157.png)

Thanks!

**Comment by deshraj** [comment]
@aayusharora welcome!!!! Thanks for opening the issue. It would be really great if you can suggest a fix for the same. :)

**Comment by aka-jain** [comment]
Yeap, we have to replace ng-hide/ng-show with ng-if here. Forgot to make it correct. Thanks @aayusharora  for pointing this out. Would you like to work on this?

**Comment by aayusharora** [comment]
Sure @aka-jain Will it be fine to send a PR in 2-3 days. I am stuck in exams.
Thanks :)

**Comment by aka-jain** [comment]
Yeah, sure @aayusharora. Do it whenever you get time.

**Comment by aayusharora** [comment]
Solves the issue here https://github.com/Cloud-CV/EvalAI/pull/988 @aka-jain @deshraj.
