### ISSUE TITLE
Protect submission URL for non participated user.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#986]
Go to http://localhost:8888/web/challenges/challenge-page/2/submission without having any participated team, the page redirects to submission page with blank view.

**What to do?**
Show message and participation button to participate first on blank area.

@deshraj any suggestion for this?

**Comment by deshraj** [comment]
Agree. This sounds like a good solution.

**Comment by anweshknayak** [comment]
@aka-jain can I do this one ?

**Comment by aka-jain** [comment]
Sure @anweshknayak, go ahead. Assigning it to you.

**Comment by deshraj** [comment]
This is already fixed and hence closing it.
