### ISSUE TITLE
UX Improvements for Mobiles

### ISSUE THREAD

**Issue by aayusharora** [Cloud-CV/EvalAI#989]
- [ ]  No way to logout on small screens.
- [x]  Animations on small screens create UX problems as they are not responsive [ Suggestion needed ]
- [ ]  Absence of Information => No Participate button in Mobile View
- [x]  Breaked Layout on Mobiles
## Observed Behaviour 
![galaxys5](https://cloud.githubusercontent.com/assets/12194719/25721719/25646842-312f-11e7-971e-d2e64d30fd88.png)
![67](https://cloud.githubusercontent.com/assets/12194719/25722806/1506ee30-3133-11e7-863d-d6cf1ee907c3.png)
![breakedlayout](https://cloud.githubusercontent.com/assets/12194719/25723001/e060486a-3133-11e7-950c-bcb29a49d69f.png)

## Expected Behaviour
- There should be a logout button on small screens.
- There should be a Participate button on small screens.
- Animations can be replaced by fixed images that take less load for mobiles.

@aka-jain @deshraj 
What are your views regarding this ?

**Comment by aka-jain** [comment]
Yes @aayusharora, the app is not responsive at this time. I will start working on mobile design soon. Will let you know when I finish up with the design.

Also, I agree with your points and will keep in mind. Thanks.

**Comment by anweshknayak** [comment]
Something like this looks good 
![mobile](https://user-images.githubusercontent.com/8139783/35912713-619189c4-0c23-11e8-9033-f4ec6838f5be.gif)

**Comment by anweshknayak** [comment]
Also if we could bring in those group of birds falling from the top and the clouds in the background for responsive view?

**Comment by aka-jain** [comment]
@anweshknayak how you want this to apply, I'm not getting. 
Also, responsiveness has been solved so we're closing this issue. If you want to suggest something then please try to open new issue.
Thanks.
