### ISSUE TITLE
Removing Redundancy Using Custom Services 

### ISSUE THREAD

**Issue by aayusharora** [Cloud-CV/EvalAI#990]
There are some places in the Frontend Structure where the controllers and a single service are handling the Requests/Response, Loaders etc.
- Custom Services can be the best approach as any controller can use it, making the code cleaner and 
   usable.
## Redundancy in the code can be removed:
[File1](https://github.com/Cloud-CV/EvalAI/blob/master/frontend/src/js/controllers/featuredChallengeCtrl.js)
and
[File2](https://github.com/CloudCV/EvalAI/blob/master/frontend/src/js/controllers/challengeHostTeamsCtrl.js#L3)
`vm.startExistLoader = function(msg) { vm.isExistLoader = true; vm.loaderTitle = msg; vm.loginContainer.addClass('low-screen'); };
    // stop loader
vm.stopExistLoader = function() { vm.isExistLoader = false; vm.loaderTitle = ''; vm.loginContainer.removeClass('low-screen'); };`

Thanks.

**Comment by aka-jain** [comment]
@aayusharora We are alredy using services for requests and responses, have a look again please.
Also try to open seperate issue for removing particular redundancy.

Would you like to work on loader redundancy?

**Comment by aayusharora** [comment]
@aka-jain IMHO, Generally a service in Angular service defined the purpose for which it is used. Here, the utility service contains all the functions, though it will work but will not be maintainable when codebase becomes large.
I would like to suggest breaking them into multiple services. I will create a separate issue to track this in detail.
Yes, I will be working for loader redundancy. :)
Thanks.

**Comment by aka-jain** [comment]
I agree and got your point, let's open a separate issue for that.
Assigning loader task to you for now.

**Comment by aka-jain** [comment]
@aayusharora any progress on this?

**Comment by aayusharora** [comment]
Hey, @aka-jain I was stuck in the exams. I am on this.

**Comment by aayusharora** [comment]
@aka-jain Solved here #1003
