### ISSUE TITLE
 Proper commenting in codebase.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#991]
@spyshiv we have to set standard comments in each file so that it will be easy for others to understand the codebase. Thoughts?

Let me know, so that we can start it with code refactor.

**Comment by spyshiv** [comment]
@aka-jain : it's great initiative. 👍 
Let's do discussion somewhere else (I.e. share a Google doc) after then we'll update the wiki as well.

**Comment by aka-jain** [comment]
Great 👍

**Comment by isht3** [comment]
@aka-jain Is this issue available for people not doing GSoC? As I think that this would be a great opportunity for me to get familiar with the codebase.

**Comment by aka-jain** [comment]
Thanks for showing interest @isht3, and yes you are free to work on any issue. Will let you now once we decide the proper rules for commenting.

**Comment by isht3** [comment]
Thanks, @aka-jain .

**Comment by isht3** [comment]
@aka-jain Any updates?

**Comment by deshraj** [comment]
Ummm....I think this cannot be an issue. Instead, we all should keep in mind that we should add comments in the code base whenever we are writing any piece of code.
