### ISSUE TITLE
Implement promises for code enhancement.

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#992]
@spyshiv let's do this ASAP.

**Comment by aayusharora** [comment]
@aka-jain Can you please describe this more? Where are we going to replace callbacks with promises?
Well, I can also provide some inputs. 
Thanks.

**Comment by aka-jain** [comment]
@aayusharora wherever possible.
Basically @spyshiv and I is discussing first for the usage of promises. Will let you know once we start it.

**Comment by rishabhja** [comment]
Can I help in this?

**Comment by aka-jain** [comment]
@rishabhja thanks for showing your interest but we haven't decided the code structure for promises yet, so can't start right now.
Will let you know once we finalize the structure for the same.

**Comment by deshraj** [comment]
Closing this.
