### ISSUE TITLE
Remove Unused CSS 

### ISSUE THREAD

**Issue by aka-jain** [Cloud-CV/EvalAI#993]
Implementing this with a gulp plugin will be a good option. @spyshiv let me know if you would like to suggest any plugin which can help us to set the proper CSS styles.

**Comment by aayusharora** [comment]
Hi, @aka-jain 
We can use this https://www.npmjs.com/package/css-purge to detect redundant CSS. Thanks :)

**Comment by aka-jain** [comment]
@aayusharora do you know any gulp module for CSS refactoring?

**Comment by spyshiv** [comment]
@aayusharora : css-purge is only for removing css duplications so we are not gonna use that.
We are using `purifycss`. It's quite interesting.
Source: [purifycss](https://github.com/purifycss/purifycss)

**Comment by aayusharora** [comment]
Hi there @spyshiv @aka-jain Please correct the issue title to "Removing Unused CSS". I suggest purging because the issue talks about the redundancy.

**Comment by deshraj** [comment]
Agree @aayusharora. Updated the title. :)

**Comment by aka-jain** [comment]
Closing this.
Fixed with #994 ,
